import { createHash, createHmac, timingSafeEqual } from "node:crypto";
import type { ArtifactRecord } from "./index";

export class ObjectStorageError extends Error{constructor(public readonly code:string,message:string,public readonly status=400){super(message);}}
export type StoredObject={key:string;sha256:string;sizeBytes:number;mimeType:string};
export interface ObjectStorageProvider{putImmutable(input:{key:string;body:Uint8Array;sha256:string;mimeType:string}):Promise<StoredObject>;read(key:string):Promise<Uint8Array>;remove(key:string):Promise<void>;health():Promise<{ok:boolean;detail:string}>;}
export interface ArtifactCatalog{artifact(organizationId:string,artifactId:string):ArtifactRecord|null;artifactStorageBytes(organizationId:string,now:number):number;}
export interface ArtifactScanner{scan(input:{body:Uint8Array;mimeType:string;sha256:string}):Promise<{state:"clean"|"blocked"|"failed";reason:string|null}>;}
export type ArtifactWriteInput={organizationId:string;projectId:string;taskId:string;attemptId:string|null;artifactId:string;kind:string;filename:string;mimeType:string;body:Uint8Array;provenance:Record<string,unknown>;idempotencyKey:string;correlationId:string;storageLimitBytes:number;retentionDays:number};
export type ArtifactAccessInput={activeOrganizationId:string;organizationId:string;activeProjectId:string;artifactId:string;ttlSeconds?:number};

const allowedMime=new Set(["application/json","application/pdf","text/plain","text/markdown","text/csv","text/html","image/png","image/jpeg","image/webp"]);
const segment=/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/;
const sha256=(body:Uint8Array)=>createHash("sha256").update(body).digest("hex");
const encode=(value:string)=>Buffer.from(value).toString("base64url");
const decode=(value:string)=>Buffer.from(value,"base64url").toString("utf8");
export function assertStoredArtifact(value:ArtifactRecord){const prefix=`oneshowseo/${value.organizationId}/${value.projectId}/${value.taskId}/${value.id}/`;if(!value.objectKey.startsWith(prefix)||value.objectKey.length<=prefix.length||!/^[a-f0-9]{64}$/.test(value.sha256)||!allowedMime.has(value.mimeType)||!Number.isInteger(value.sizeBytes)||value.sizeBytes<1||value.sizeBytes>25*1024*1024||value.scanState!=="clean"||!/^days:[1-9][0-9]{0,3}$/.test(value.retentionClass)||value.expiresAt===null)throw new ObjectStorageError("INVALID_STORED_ARTIFACT","产物存储记录未通过安全策略",409);}
function safeMetadata(value:unknown,path="provenance"):unknown{if(value===null||typeof value==="string"||typeof value==="boolean")return value;if(typeof value==="number"&&Number.isFinite(value))return value;if(Array.isArray(value))return value.map((item,index)=>safeMetadata(item,`${path}[${index}]`));if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value as Record<string,unknown>).map(([key,item])=>{if(/password|secret|token|credential|api[_-]?key/i.test(key))throw new ObjectStorageError("SENSITIVE_ARTIFACT_METADATA",`产物元数据不能包含敏感字段：${path}.${key}`);return[key,safeMetadata(item,`${path}.${key}`)];}));throw new ObjectStorageError("INVALID_ARTIFACT_METADATA","产物元数据无效");}
function safeFilename(value:string){const name=value.trim();if(!segment.test(name)||name==="."||name==="..")throw new ObjectStorageError("INVALID_ARTIFACT_FILENAME","产物文件名无效");return name;}
function validateContent(body:Uint8Array,mimeType:string){if(!allowedMime.has(mimeType))throw new ObjectStorageError("MIME_NOT_ALLOWED","不支持此产物类型",415);if(body.byteLength<1||body.byteLength>25*1024*1024)throw new ObjectStorageError("ARTIFACT_SIZE_INVALID","单个产物必须在 1B 到 25MB 之间",413);const head=Buffer.from(body.subarray(0,16));if(mimeType==="application/pdf"&&!head.toString("ascii").startsWith("%PDF-"))throw new ObjectStorageError("MIME_MISMATCH","文件内容与声明类型不一致",415);if(mimeType==="image/png"&&!head.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))throw new ObjectStorageError("MIME_MISMATCH","文件内容与声明类型不一致",415);if(mimeType==="image/jpeg"&&!(head[0]===0xff&&head[1]===0xd8&&head[2]===0xff))throw new ObjectStorageError("MIME_MISMATCH","文件内容与声明类型不一致",415);if(mimeType==="image/webp"&&!(head.toString("ascii",0,4)==="RIFF"&&head.toString("ascii",8,12)==="WEBP"))throw new ObjectStorageError("MIME_MISMATCH","文件内容与声明类型不一致",415);if(mimeType==="application/json"){try{JSON.parse(Buffer.from(body).toString("utf8"));}catch{throw new ObjectStorageError("INVALID_JSON_ARTIFACT","JSON 产物无效",415);}}}

export class SignatureArtifactScanner implements ArtifactScanner{async scan(input:{body:Uint8Array}){const text=Buffer.from(input.body).toString("utf8");return/EICAR-STANDARD-ANTIVIRUS-TEST-FILE|<script[^>]*>\s*fetch\([^)]*(?:token|cookie)/i.test(text)?{state:"blocked" as const,reason:"SIGNATURE_MATCH"}:{state:"clean" as const,reason:null};}}

export class ArtifactObjectService{
  constructor(private readonly provider:ObjectStorageProvider,private readonly catalog:ArtifactCatalog,private readonly scanner:ArtifactScanner,private readonly signingSecret:string,private readonly publicBasePath="/api/artifacts/download",private readonly now:()=>number=()=>Math.floor(Date.now()/1000)){if(Buffer.byteLength(signingSecret)<32)throw new ObjectStorageError("SIGNING_SECRET_INVALID","对象访问签名密钥至少需要 32 字节",500);}
  async store(input:ArtifactWriteInput):Promise<ArtifactRecord>{for(const value of [input.organizationId,input.projectId,input.taskId,input.artifactId,input.kind,input.idempotencyKey,input.correlationId])if(!segment.test(value))throw new ObjectStorageError("INVALID_ARTIFACT_SCOPE","产物范围标识无效");const filename=safeFilename(input.filename);validateContent(input.body,input.mimeType);if(!Number.isInteger(input.storageLimitBytes)||input.storageLimitBytes<0||this.catalog.artifactStorageBytes(input.organizationId,this.now())+input.body.byteLength>input.storageLimitBytes)throw new ObjectStorageError("STORAGE_LIMIT_REACHED","当前套餐存储空间不足",403);if(!Number.isInteger(input.retentionDays)||input.retentionDays<1||input.retentionDays>3650)throw new ObjectStorageError("RETENTION_POLICY_INVALID","产物保留策略无效");const digest=sha256(input.body),scan=await this.scanner.scan({body:input.body,mimeType:input.mimeType,sha256:digest});if(scan.state!=="clean")throw new ObjectStorageError(scan.state==="blocked"?"ARTIFACT_BLOCKED":"SCAN_UNAVAILABLE",scan.state==="blocked"?"产物未通过安全扫描":"产物扫描服务不可用",scan.state==="blocked"?422:503);const key=`oneshowseo/${input.organizationId}/${input.projectId}/${input.taskId}/${input.artifactId}/${filename}`,stored=await this.provider.putImmutable({key,body:input.body,sha256:digest,mimeType:input.mimeType});return{id:input.artifactId,organizationId:input.organizationId,projectId:input.projectId,taskId:input.taskId,attemptId:input.attemptId,kind:input.kind,objectKey:stored.key,sha256:stored.sha256,mimeType:stored.mimeType,sizeBytes:stored.sizeBytes,scanState:"clean",retentionClass:`days:${input.retentionDays}`,expiresAt:this.now()+input.retentionDays*86400,provenance:safeMetadata(input.provenance) as Record<string,unknown>,idempotencyKey:input.idempotencyKey,createdAt:this.now()};}
  authorizeAccess(input:ArtifactAccessInput){if(input.activeOrganizationId!==input.organizationId)throw new ObjectStorageError("TENANT_MISMATCH","无权访问此产物",403);const artifact=this.catalog.artifact(input.organizationId,input.artifactId);if(!artifact||artifact.projectId!==input.activeProjectId)throw new ObjectStorageError("ARTIFACT_NOT_FOUND","产物不存在",404);if(artifact.scanState!=="clean")throw new ObjectStorageError("ARTIFACT_NOT_AVAILABLE","产物尚未通过安全扫描",409);if(artifact.expiresAt!==null&&artifact.expiresAt<=this.now())throw new ObjectStorageError("ARTIFACT_EXPIRED","产物已过期",410);const ttl=Math.max(30,Math.min(300,input.ttlSeconds??120)),payload=encode(JSON.stringify({v:1,o:artifact.organizationId,p:artifact.projectId,a:artifact.id,h:artifact.sha256,e:this.now()+ttl,n:crypto.randomUUID()})),signature=createHmac("sha256",this.signingSecret).update(payload).digest("base64url");return{url:`${this.publicBasePath}?token=${payload}.${signature}`,expiresAt:this.now()+ttl};}
  async resolveAccess(token:string){const [payload,provided,...extra]=token.split(".");if(!payload||!provided||extra.length)throw new ObjectStorageError("INVALID_ARTIFACT_TOKEN","产物访问链接无效",401);const expected=createHmac("sha256",this.signingSecret).update(payload).digest(),actual=Buffer.from(provided,"base64url");if(actual.length!==expected.length||!timingSafeEqual(actual,expected))throw new ObjectStorageError("INVALID_ARTIFACT_TOKEN","产物访问链接无效",401);let claim:{v:number;o:string;p:string;a:string;h:string;e:number};try{claim=JSON.parse(decode(payload));}catch{throw new ObjectStorageError("INVALID_ARTIFACT_TOKEN","产物访问链接无效",401);}if(claim.v!==1||!Number.isInteger(claim.e)||claim.e<=this.now())throw new ObjectStorageError("ARTIFACT_TOKEN_EXPIRED","产物访问链接已过期",401);const artifact=this.catalog.artifact(claim.o,claim.a);if(!artifact||artifact.projectId!==claim.p||artifact.sha256!==claim.h||artifact.scanState!=="clean"||(artifact.expiresAt!==null&&artifact.expiresAt<=this.now()))throw new ObjectStorageError("ARTIFACT_NOT_FOUND","产物不存在",404);const body=await this.provider.read(artifact.objectKey);if(body.byteLength!==artifact.sizeBytes||sha256(body)!==artifact.sha256)throw new ObjectStorageError("ARTIFACT_INTEGRITY_FAILED","产物完整性校验失败",500);return{artifact,body};}
}
