import { createHash } from "node:crypto";
import type { CommercialSubject, CreditLedgerEntry } from "../commerce";
import type { ArtifactRecord, ExecutionSettlementRepository, ExternalEffectRecord, NotificationRecord } from "./index";
import { assertStoredArtifact } from "./object-storage";

export class TaskSettlementError extends Error{constructor(public readonly code:string,message:string,public readonly status=400){super(message);}}
export interface TaskCommerceSettlementGate{commitCredits(subject:CommercialSubject,input:{reservationId:string;idempotencyKey:string;correlationId:string}):CreditLedgerEntry;releaseCredits(subject:CommercialSubject,input:{reservationId:string;idempotencyKey:string;correlationId:string}):CreditLedgerEntry;}
export type TaskTerminalState="completed"|"failed"|"cancelled"|"quarantined";
export type AtomicTaskSettlementInput={organizationId:string;projectId:string;taskId:string;jobId:string;attemptId:string|null;state:TaskTerminalState;subject:CommercialSubject;reservationId:string|null;artifacts:ArtifactRecord[];notifications:NotificationRecord[];externalEffects:ExternalEffectRecord[];idempotencyKey:string;correlationId:string};
export type AtomicTaskSettlementResult={taskId:string;jobId:string;state:TaskTerminalState;creditEntryId:string|null;artifactIds:string[];notificationIds:string[];externalEffectIds:string[];duplicate:boolean};

function normalized(value:unknown,path="metadata"):unknown{if(value===null||typeof value==="string"||typeof value==="boolean")return value;if(typeof value==="number"&&Number.isFinite(value))return value;if(Array.isArray(value))return value.map((item,index)=>normalized(item,`${path}[${index}]`));if(value&&typeof value==="object")return Object.fromEntries(Object.keys(value as Record<string,unknown>).sort().map(key=>{if(/password|secret|token|credential|api[_-]?key/i.test(key))throw new TaskSettlementError("SENSITIVE_SETTLEMENT_DATA",`结算数据不能包含敏感字段：${path}.${key}`);return[key,normalized((value as Record<string,unknown>)[key],`${path}.${key}`)];}));throw new TaskSettlementError("INVALID_SETTLEMENT_DATA",`结算数据包含不支持的值：${path}`);}
function payload(input:AtomicTaskSettlementInput){return{organizationId:input.organizationId,projectId:input.projectId,taskId:input.taskId,jobId:input.jobId,attemptId:input.attemptId,state:input.state,reservationId:input.reservationId,artifacts:input.artifacts.map(value=>({...value,provenance:normalized(value.provenance,"artifact.provenance")})).sort((a,b)=>a.id.localeCompare(b.id)),notifications:input.notifications.map(value=>({...value,arguments:normalized(value.arguments,"notification.arguments")})).sort((a,b)=>a.id.localeCompare(b.id)),externalEffects:input.externalEffects.map(value=>({...value,evidence:normalized(value.evidence,"effect.evidence")})).sort((a,b)=>a.id.localeCompare(b.id))};}
function validate(input:AtomicTaskSettlementInput){for(const value of [input.organizationId,input.projectId,input.taskId,input.jobId,input.idempotencyKey,input.correlationId])if(!value.trim())throw new TaskSettlementError("INVALID_SETTLEMENT_REQUEST","任务结算参数不完整");if(input.subject.organizationId!==input.organizationId)throw new TaskSettlementError("TENANT_MISMATCH","结算组织不匹配",403);const scoped=[...input.artifacts,...input.notifications,...input.externalEffects];for(const value of scoped)if(value.organizationId!==input.organizationId||value.projectId!==input.projectId||value.taskId!==input.taskId)throw new TaskSettlementError("SETTLEMENT_SCOPE_MISMATCH","结算记录不属于当前任务",403);for(const artifact of input.artifacts)assertStoredArtifact(artifact);for(const effect of input.externalEffects){if(!effect.provider.trim()||!effect.operation.trim()||!/^[a-f0-9]{64}$/.test(effect.requestHash)||effect.state==="pending")throw new TaskSettlementError("INVALID_EXTERNAL_EFFECT","外部操作结算记录无效");}if(input.state==="completed"&&input.externalEffects.some(effect=>effect.state!=="succeeded"))throw new TaskSettlementError("UNRESOLVED_EXTERNAL_EFFECT","存在未确认成功的外部操作，任务不能结算为完成",409);const body=payload(input),json=JSON.stringify(body);if(Buffer.byteLength(json)>262144)throw new TaskSettlementError("SETTLEMENT_TOO_LARGE","单次结算数据不能超过 256KB",413);return{body,hash:createHash("sha256").update(json).digest("hex")};}

export class AtomicTaskSettlementService{
  constructor(private readonly repository:ExecutionSettlementRepository,private readonly commerce:TaskCommerceSettlementGate,private readonly now:()=>number=()=>Math.floor(Date.now()/1000)){}
  settle(input:AtomicTaskSettlementInput):AtomicTaskSettlementResult{const{body,hash}=validate(input),scope="task.settle",now=this.now();return this.repository.transaction(()=>{const existing=this.repository.idempotency(input.organizationId,scope,input.idempotencyKey);if(existing){if(existing.requestHash!==hash)throw new TaskSettlementError("IDEMPOTENCY_CONFLICT","幂等键已用于不同的结算请求",409);return this.duplicate(existing.response);}
    const task=this.repository.task(input.organizationId,input.taskId),job=this.repository.job(input.organizationId,input.jobId);if(!task||task.projectId!==input.projectId)throw new TaskSettlementError("TASK_NOT_FOUND","任务不存在",404);if(!job||job.taskId!==task.id||job.projectId!==input.projectId)throw new TaskSettlementError("JOB_NOT_FOUND","作业不存在",404);if(job.state!==input.state)throw new TaskSettlementError("JOB_NOT_TERMINAL",`作业状态 ${job.state} 不能结算为 ${input.state}`,409);
    for(const effect of body.externalEffects as ExternalEffectRecord[]){const duplicate=this.repository.externalEffect(input.organizationId,effect.provider,effect.idempotencyKey);if(duplicate){if(duplicate.requestHash!==effect.requestHash||duplicate.taskId!==input.taskId||duplicate.operation!==effect.operation)throw new TaskSettlementError("EXTERNAL_EFFECT_CONFLICT","外部操作幂等记录冲突",409);if(duplicate.state!==effect.state){if(!this.repository.settleExternalEffect(effect))throw new TaskSettlementError("EXTERNAL_EFFECT_CONFLICT","外部操作状态不能被覆盖",409);}else if(duplicate.externalReference!==effect.externalReference||duplicate.errorCode!==effect.errorCode||JSON.stringify(normalized(duplicate.evidence))!==JSON.stringify(effect.evidence))throw new TaskSettlementError("EXTERNAL_EFFECT_CONFLICT","外部操作结果记录冲突",409);}else this.repository.appendExternalEffect(effect);}
    for(const artifact of body.artifacts as ArtifactRecord[])this.repository.appendArtifact(artifact);for(const notification of body.notifications as NotificationRecord[])this.repository.appendNotification(notification);
    const credit=input.reservationId?(input.state==="completed"?this.commerce.commitCredits(input.subject,{reservationId:input.reservationId,idempotencyKey:`task:${input.taskId}`,correlationId:input.correlationId}):this.commerce.releaseCredits(input.subject,{reservationId:input.reservationId,idempotencyKey:`task:${input.taskId}`,correlationId:input.correlationId})):null;
    if(!this.repository.settleTask({organizationId:input.organizationId,taskId:input.taskId,state:input.state,progress:input.state==="completed"?100:task.progress,now}))throw new TaskSettlementError("TASK_STATE_CONFLICT","任务已被其他结算操作更新",409);
    const result:AtomicTaskSettlementResult={taskId:input.taskId,jobId:input.jobId,state:input.state,creditEntryId:credit?.id??null,artifactIds:input.artifacts.map(value=>value.id),notificationIds:input.notifications.map(value=>value.id),externalEffectIds:input.externalEffects.map(value=>value.id),duplicate:false};this.repository.appendOutbox({id:crypto.randomUUID(),organizationId:input.organizationId,projectId:input.projectId,aggregateType:"task",aggregateId:input.taskId,eventType:"execution.task.settled",payload:result,state:"pending",attempts:0,availableAt:now,publishedAt:null,lastError:null,idempotencyKey:`task-settled:${input.taskId}`,correlationId:input.correlationId,createdAt:now});this.repository.appendAudit({id:crypto.randomUUID(),organizationId:input.organizationId,projectId:input.projectId,actorType:"system",actorId:null,action:"execution.task.settle",targetType:"task",targetId:input.taskId,outcome:input.state==="completed"?"success":"failed",reason:input.state,policyVersion:"execution-settlement-v1",correlationId:input.correlationId,metadata:{jobId:input.jobId,attemptId:input.attemptId,creditEntryId:credit?.id??null,artifactCount:input.artifacts.length,notificationCount:input.notifications.length,externalEffectCount:input.externalEffects.length},occurredAt:now});this.repository.putIdempotency({id:crypto.randomUUID(),organizationId:input.organizationId,scope,idempotencyKey:input.idempotencyKey,requestHash:hash,resourceType:"task",resourceId:input.taskId,responseStatus:200,response:result,expiresAt:null,createdAt:now,updatedAt:now});return result;});}
  private duplicate(response:Record<string,unknown>|null):AtomicTaskSettlementResult{if(!response)throw new TaskSettlementError("IDEMPOTENCY_RECORD_INCOMPLETE","结算幂等记录不完整",500);return{taskId:String(response.taskId),jobId:String(response.jobId),state:String(response.state) as TaskTerminalState,creditEntryId:response.creditEntryId?String(response.creditEntryId):null,artifactIds:Array.isArray(response.artifactIds)?response.artifactIds.map(String):[],notificationIds:Array.isArray(response.notificationIds)?response.notificationIds.map(String):[],externalEffectIds:Array.isArray(response.externalEffectIds)?response.externalEffectIds.map(String):[],duplicate:true};}
}
