import type { ArtifactRecord, ExecutionTask } from "./index";

export type WorkspaceTaskItem={id:string;title:string;description:string;priority:number;status:string;type:string;createdAt:number;url?:string;evidence?:string;category?:string;severity?:string;source:"execution"|"legacy";correlationId:string|null;artifactCount:number};
export type WorkspaceArtifactItem={id:string;taskId:string;kind:string;title:string;mimeType:string;sizeBytes:number;createdAt:number;expiresAt:number|null;source:"execution";accessPath:string};
export type LegacyTaskItem=Omit<WorkspaceTaskItem,"source"|"correlationId"|"artifactCount">;
export interface WorkspaceCatalogRepository{executionTasks(organizationId:string,projectId:string):Array<ExecutionTask&{priority:number;artifactCount:number}>;legacyTasks(organizationId:string,projectId:string):LegacyTaskItem[];artifacts(organizationId:string,projectId:string,now:number):ArtifactRecord[];}

const state=(value:ExecutionTask["state"])=>value==="waiting_approval"?"proposed":value==="queued"?"approved":value==="running"||value==="retrying"?"in_progress":value==="completed"?"completed":value==="cancelled"?"dismissed":"failed";
const text=(value:unknown,fallback:string)=>typeof value==="string"&&value.trim()?value.trim().slice(0,1000):fallback;
export class WorkspaceCatalogService{
  constructor(private readonly repository:WorkspaceCatalogRepository,private readonly now=()=>Math.floor(Date.now()/1000)){}
  read(organizationId:string,projectId:string){const canonical=this.repository.executionTasks(organizationId,projectId),linked=new Set(canonical.map(task=>typeof task.input.legacyTaskId==="string"?task.input.legacyTaskId:null).filter(Boolean)),execution=canonical.map(task=>({id:task.id,title:text(task.input.title,task.taskType),description:text(task.input.description,task.locale==="en"?"Durable platform task":"平台持久任务"),priority:task.priority,status:state(task.state),type:task.taskType,createdAt:task.createdAt,url:typeof task.input.url==="string"?task.input.url:undefined,evidence:typeof task.input.evidence==="string"?task.input.evidence:undefined,category:typeof task.input.category==="string"?task.input.category:undefined,severity:typeof task.input.severity==="string"?task.input.severity:undefined,source:"execution" as const,correlationId:task.correlationId,artifactCount:task.artifactCount})),legacy=this.repository.legacyTasks(organizationId,projectId).filter(task=>!linked.has(task.id)).map(task=>({...task,source:"legacy" as const,correlationId:null,artifactCount:0}));const artifacts=this.repository.artifacts(organizationId,projectId,this.now()).map(artifact=>({id:artifact.id,taskId:artifact.taskId,kind:artifact.kind,title:text(artifact.provenance.title??artifact.provenance.filename,artifact.kind),mimeType:artifact.mimeType,sizeBytes:artifact.sizeBytes,createdAt:artifact.createdAt,expiresAt:artifact.expiresAt,source:"execution" as const,accessPath:`/api/artifacts/${encodeURIComponent(artifact.id)}/access?projectId=${encodeURIComponent(projectId)}`}));return{tasks:[...execution,...legacy].sort((a,b)=>b.priority-a.priority||b.createdAt-a.createdAt),artifacts,content:artifacts.filter(item=>/content|draft|article|brief|publish/i.test(item.kind)),knowledge:artifacts.filter(item=>/knowledge|document|dataset|reference|evidence/i.test(item.kind)),reports:artifacts.filter(item=>/report|audit|analysis|export/i.test(item.kind))};}
}
