import { NextResponse } from "next/server";
import { authenticateApiRequest, recordApiRequest } from "../../../lib/api-access";
import { getDatabase, writeAudit } from "../../../lib/auth";
import { commercialSubject } from "../../../lib/billing";
import { atomicTaskCreationService } from "../../../lib/execution";
import { enforceDeveloperRateLimit } from "../../../lib/developer-rate-limit";
import { permissions, type OrganizationRoleKey } from "../../../platform/modules/identity/authorization";
import { MCP_PROTOCOL_VERSION, dispatchMcp, mcpTools, validateMcpRouting } from "../../../platform/modules/developer/mcp";

const json=(value:unknown,status=200)=>NextResponse.json(value,{status,headers:{"cache-control":"private, no-store","mcp-protocol-version":MCP_PROTOCOL_VERSION}});
export async function GET(){return json({name:"OneShowSEO",endpoint:"/api/mcp",protocolVersion:MCP_PROTOCOL_VERSION,transport:"stateless-streamable-http",authorization:"Bearer organization API key",methods:["server/discover","tools/list","tools/call"]});}
export async function POST(request:Request){
 const text=await request.text();if(Buffer.byteLength(text)>65536)return json({jsonrpc:"2.0",id:null,error:{code:-32600,message:"Request too large"}},413);let body:Record<string,unknown>;try{body=JSON.parse(text) as Record<string,unknown>;}catch{return json({jsonrpc:"2.0",id:null,error:{code:-32700,message:"Parse error"}},400);}const routing=validateMcpRouting(request.headers,body);if(routing)return json({jsonrpc:"2.0",id:body.id??null,error:{code:-32020,message:routing}},400);
 const params=body.params&&typeof body.params==="object"&&!Array.isArray(body.params)?body.params as Record<string,unknown>:{},args=params.arguments&&typeof params.arguments==="object"&&!Array.isArray(params.arguments)?params.arguments as Record<string,unknown>:{},name=typeof params.name==="string"?params.name:"",tool=mcpTools.find(value=>value.name===name),projectId=typeof args.projectId==="string"?args.projectId:undefined,requiredScopes=tool?[tool.requiredScope]:undefined,auth=await authenticateApiRequest(request,{requiredScopes,projectId});if(!auth)return json({jsonrpc:"2.0",id:body.id??null,error:{code:-32001,message:"Unauthorized",data:{code:"UNAUTHENTICATED"}}},401);
 try{const rate=await enforceDeveloperRateLimit(auth.key,{projectId,endpoint:`MCP ${String(body.method)} ${name}`.trim(),cost:name==="start_agent_task"?10:1});if(!rate.allowed)return NextResponse.json({jsonrpc:"2.0",id:body.id??null,error:{code:-32029,message:"Rate limited",data:{code:"RATE_LIMITED",retryAfterSeconds:rate.retryAfterSeconds,resetsAt:rate.resetsAt,limitedBy:rate.limitedBy}}},{status:429,headers:{"mcp-protocol-version":MCP_PROTOCOL_VERSION,"retry-after":String(rate.retryAfterSeconds??1),"x-rate-limit-policy":rate.policyVersion}});}catch{return json({jsonrpc:"2.0",id:body.id??null,error:{code:-32003,message:"Rate-limit service unavailable",data:{code:"DEPENDENCY_UNAVAILABLE",retryAfterSeconds:5}}},503);}
 const organizationId=auth.user.organization.organizationId,allowed=(id:string)=>auth.key.projectIds==="*"||auth.key.projectIds.includes(id),select="SELECT id,name,site_url siteUrl,host,market,language,status,version,created_at createdAt,updated_at updatedAt FROM projects WHERE organization_id=? AND status!='pending_deletion'";
 const response=await dispatchMcp(body,{scopes:new Set(auth.key.scopes),projectAllowed:allowed,listProjects:async limit=>{const rows=getDatabase().prepare(`${select} ORDER BY updated_at DESC,id LIMIT ?`).bind(organizationId,Math.min(limit,100)).all().results;return auth.key.projectIds==="*"?rows:rows.filter(row=>allowed(String((row as{ id:unknown}).id)));},getProject:async id=>getDatabase().prepare(`${select} AND id=?`).bind(organizationId,id).first(),startTask:async input=>{const created=(await atomicTaskCreationService()).create({activeOrganizationId:organizationId,organizationId,projectId:input.projectId,requestedByAccountId:auth.user.id,role:auth.user.organization.roleKey as OrganizationRoleKey,permission:permissions.projectsUpdate,subject:commercialSubject(auth.user),triggerType:"mcp",taskType:"agent_run",capability:input.capability,input:input.input,locale:"zh-CN",idempotencyKey:input.idempotencyKey,correlationId:request.headers.get("traceparent")||`mcp:${crypto.randomUUID()}`,entitlements:[{key:"agents",quantity:1,currentUsage:0}],creditCost:1,queue:"agents",jobType:input.capability,priority:50,maxAttempts:3,timeoutSeconds:300});return{taskId:created.task.id,jobId:created.job.id,state:created.task.state,duplicate:created.duplicate,correlationId:created.task.correlationId};}});
 recordApiRequest(auth.user.id,auth.key.id,request,"error"in response?400:200);await writeAudit("mcp_request",auth.user.id,request,JSON.stringify({method:body.method,tool:name||null,projectId:projectId||null,outcome:"error"in response?"failed":"success"}));return json(response,"error"in response?400:200);
}
