import type { DeveloperScope } from "./rest-contract";

export const MCP_PROTOCOL_VERSION="2026-07-28" as const;
export const mcpTools=[
 {name:"list_projects",title:"List OneShowSEO projects",description:"Lists projects visible to this credential.",requiredScope:"projects:read"as DeveloperScope,inputSchema:{type:"object",properties:{limit:{type:"integer",minimum:1,maximum:100}},additionalProperties:false},annotations:{readOnlyHint:true,idempotentHint:true}},
 {name:"get_project",title:"Get a OneShowSEO project",description:"Gets one project without revealing resources outside credential scope.",requiredScope:"projects:read"as DeveloperScope,inputSchema:{type:"object",properties:{projectId:{type:"string",minLength:1,maxLength:128}},required:["projectId"],additionalProperties:false},annotations:{readOnlyHint:true,idempotentHint:true}},
 {name:"start_agent_task",title:"Start a governed agent task",description:"Creates the same durable, entitled, audited and idempotent task used by OneShowSEO.",requiredScope:"tasks:write"as DeveloperScope,inputSchema:{type:"object",properties:{projectId:{type:"string",minLength:1,maxLength:128,"x-mcp-header":true},capability:{type:"string",enum:["platform.synthetic"]},idempotencyKey:{type:"string",minLength:16,maxLength:128,"x-mcp-header":true},input:{type:"object",additionalProperties:true}},required:["projectId","capability","idempotencyKey","input"],additionalProperties:false},annotations:{readOnlyHint:false,idempotentHint:true,destructiveHint:false}},
] as const;
export type McpToolName=(typeof mcpTools)[number]["name"];
export type McpContext={scopes:ReadonlySet<DeveloperScope>;projectAllowed:(projectId:string)=>boolean;listProjects:(limit:number)=>unknown[]|Promise<unknown[]>;getProject:(projectId:string)=>unknown|null|Promise<unknown|null>;startTask:(input:{projectId:string;capability:string;idempotencyKey:string;input:Record<string,unknown>})=>unknown|Promise<unknown>};
type Rpc={jsonrpc?:unknown;id?:unknown;method?:unknown;params?:unknown};
const error=(id:unknown,code:number,message:string,data?:Record<string,unknown>)=>({jsonrpc:"2.0",id:id??null,error:{code,message,...(data?{data}: {})}});
const result=(id:unknown,value:unknown)=>({jsonrpc:"2.0",id:id??null,result:value});
const object=(value:unknown):value is Record<string,unknown>=>Boolean(value)&&typeof value==="object"&&!Array.isArray(value);
export function validateMcpRouting(headers:Headers,body:Rpc){const protocol=headers.get("mcp-protocol-version");if(protocol!==MCP_PROTOCOL_VERSION)return"Unsupported MCP-Protocol-Version";if(headers.get("mcp-method")!==body.method)return"Mcp-Method header does not match request";const bodyName=object(body.params)&&typeof body.params.name==="string"?body.params.name:null,headerName=headers.get("mcp-name");if(body.method==="tools/call"&&headerName!==bodyName)return"Mcp-Name header does not match request";return null;}
export async function dispatchMcp(body:Rpc,context:McpContext){
 if(body.jsonrpc!=="2.0"||!(typeof body.id==="string"||typeof body.id==="number"))return error(body.id,-32600,"Invalid Request");
 if(body.method==="server/discover")return result(body.id,{protocolVersion:MCP_PROTOCOL_VERSION,serverInfo:{name:"oneshowseo",title:"OneShowSEO",version:"1.0.0"},capabilities:{tools:{listChanged:false}},instructions:"Tools enforce organization, project, entitlement, idempotency, usage and audit policies."});
 if(body.method==="tools/list")return result(body.id,{tools:mcpTools.filter(tool=>context.scopes.has(tool.requiredScope)).map(tool=>({name:tool.name,title:tool.title,description:tool.description,inputSchema:tool.inputSchema,annotations:tool.annotations})),nextCursor:null,ttlMs:300000,cacheScope:"private"});
 if(body.method!=="tools/call")return error(body.id,-32601,"Method not found");
 const params=object(body.params)?body.params:{},name=typeof params.name==="string"?params.name:"",args=object(params.arguments)?params.arguments:{};const tool=mcpTools.find(value=>value.name===name);if(!tool)return error(body.id,-32602,"Unknown tool");if(!context.scopes.has(tool.requiredScope))return error(body.id,-32003,"Forbidden",{code:"FORBIDDEN"});
 try{
  if(name==="list_projects"){const limit=Number(args.limit??25);if(!Number.isInteger(limit)||limit<1||limit>100)return error(body.id,-32602,"Invalid arguments",{fields:{limit:"must be an integer from 1 to 100"}});const projects=await context.listProjects(limit);return result(body.id,{content:[{type:"text",text:JSON.stringify(projects)}],structuredContent:{projects},isError:false});}
  const projectId=typeof args.projectId==="string"?args.projectId:"";if(!projectId||!context.projectAllowed(projectId))return error(body.id,-32004,"Project not found",{code:"NOT_FOUND"});
  if(name==="get_project"){const project=await context.getProject(projectId);return project?result(body.id,{content:[{type:"text",text:JSON.stringify(project)}],structuredContent:{project},isError:false}):error(body.id,-32004,"Project not found",{code:"NOT_FOUND"});}
  const capability=args.capability,idempotencyKey=args.idempotencyKey,input=args.input;if(capability!=="platform.synthetic"||typeof idempotencyKey!=="string"||!/^[A-Za-z0-9][A-Za-z0-9._:-]{15,127}$/.test(idempotencyKey)||!object(input))return error(body.id,-32602,"Invalid arguments",{code:"VALIDATION_FAILED"});const task=await context.startTask({projectId,capability,idempotencyKey,input});return result(body.id,{content:[{type:"text",text:JSON.stringify(task)}],structuredContent:{task},isError:false});
 }catch(cause){const value=cause as{code?:string;message?:string};return error(body.id,value.code==="IDEMPOTENCY_CONFLICT"?-32009:-32603,value.code==="IDEMPOTENCY_CONFLICT"?"Idempotency conflict":"Tool execution failed",{code:value.code||"INTERNAL_ERROR"});}
}
