import {NextResponse} from "next/server";
import {agentRegistry,ensureBuiltInProjectAgents} from "../../../lib/agents";
import {getCurrentUser,writeAudit} from "../../../lib/auth";
import {ownedProject} from "../../../lib/product";
import {AuthorizationError,authorizePlatformAccount,can,permissions,type OrganizationRoleKey} from "../../../platform/modules/identity/authorization";
import {AgentRegistryError} from "../../../platform/modules/agents/registry";
import {AgentManifestError} from "../../../platform/modules/agents/manifest";
const failure=(error:unknown)=>error instanceof AgentRegistryError?NextResponse.json({error:error.message,code:error.code},{status:error.status}):error instanceof AgentManifestError?NextResponse.json({error:"Agent 清单无效",code:error.message,issues:error.issues},{status:400}):null;
export async function GET(request:Request){const user=await getCurrentUser();if(!user)return NextResponse.json({error:"请先登录"},{status:401});if(!can(user.organization.roleKey as OrganizationRoleKey,permissions.projectsRead))return NextResponse.json({error:"没有查看 Agent 的权限"},{status:403});const projectId=new URL(request.url).searchParams.get("projectId")||"";if(!await ownedProject(user.organization.organizationId,projectId))return NextResponse.json({error:"项目不存在"},{status:404});try{await ensureBuiltInProjectAgents(user.organization.organizationId,projectId);return NextResponse.json({agents:(await agentRegistry()).list(user.organization.organizationId,projectId)},{headers:{"cache-control":"private, no-store"}});}catch(error){const response=failure(error);if(response)return response;throw error;}}
export async function PUT(request:Request){const user=await getCurrentUser();if(!user)return NextResponse.json({error:"请先登录"},{status:401});if(!can(user.organization.roleKey as OrganizationRoleKey,permissions.projectsUpdate))return NextResponse.json({error:"没有配置 Agent 的权限"},{status:403});const body=await request.json().catch(()=>null) as Record<string,unknown>|null,projectId=typeof body?.projectId==="string"?body.projectId:"";if(!await ownedProject(user.organization.organizationId,projectId))return NextResponse.json({error:"项目不存在"},{status:404});try{const record=(await agentRegistry()).configure({organizationId:user.organization.organizationId,projectId,agentKey:String(body?.agentKey||""),agentVersion:String(body?.agentVersion||""),enabled:body?.enabled===true,configuration:body?.configuration??{},expectedRevision:Number(body?.revision)});await writeAudit("project_agent_configured",user.id,request,JSON.stringify({organizationId:user.organization.organizationId,projectId,agentKey:record.agentKey,agentVersion:record.agentVersion,enabled:record.enabled,revision:record.revision}));return NextResponse.json({agent:record});}catch(error){const response=failure(error);if(response)return response;throw error;}}
export async function POST(request:Request){const user=await getCurrentUser();if(!user)return NextResponse.json({error:"请先登录"},{status:401});try{authorizePlatformAccount(user.role);const manifest=await request.json().catch(()=>null),result=(await agentRegistry()).publish(manifest);await writeAudit("agent_version_published",user.id,request,JSON.stringify({agentKey:result.record.agentKey,agentVersion:result.record.version,digest:result.record.digest,duplicate:result.duplicate}));return NextResponse.json({version:result.record,duplicate:result.duplicate},{status:result.duplicate?200:201});}catch(error){const response=failure(error);if(response)return response;if(error instanceof AuthorizationError)return NextResponse.json({error:"没有发布 Agent 的权限"},{status:403});throw error;}}
