import type { AppDatabase } from "../../../lib/database";
import type { ArtifactRecord, CancellationRequest, ExecutionAuditEvent, ExecutionIdempotencyRecord, ExecutionJob, ExecutionRepository, ExecutionSettlementRepository, ExecutionTask, ExecutionWorkerRepository, ExternalEffectRecord, InboxMessage, JobAttempt, JobLease, NotificationRecord, OutboxMessage, TaskProgressEvent, WorkerClaim, WorkerFailureState, WorkerHeartbeat, WorkerMaintenance } from "../../modules/execution";

type JsonRow=Record<string,unknown>;
const parse=<T>(value:unknown)=>JSON.parse(String(value)) as T;
const boolean=(value:unknown)=>Boolean(Number(value));

export class SqliteExecutionRepository implements ExecutionRepository,ExecutionWorkerRepository,ExecutionSettlementRepository{
  constructor(private readonly database:AppDatabase){}
  ensureSchema(){this.database.exec(`
    CREATE UNIQUE INDEX IF NOT EXISTS projects_organization_id_execution_uq ON projects(organization_id,id);
    CREATE TABLE IF NOT EXISTS execution_tasks (
      id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES identity_organizations(id) ON DELETE RESTRICT,project_id TEXT NOT NULL,
      requested_by_account_id TEXT REFERENCES users(id) ON DELETE SET NULL,trigger_type TEXT NOT NULL CHECK(trigger_type IN ('manual','scheduled','api','mcp','approval','agent','system')),
      task_type TEXT NOT NULL,capability TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('queued','running','retrying','waiting_approval','completed','failed','cancelled','quarantined')),
      progress INTEGER NOT NULL DEFAULT 0 CHECK(progress BETWEEN 0 AND 100),cancellable INTEGER NOT NULL DEFAULT 1 CHECK(cancellable IN (0,1)),input_json TEXT NOT NULL CHECK(json_valid(input_json)),locale TEXT NOT NULL CHECK(locale IN ('zh-CN','en')),
      idempotency_key TEXT NOT NULL,correlation_id TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 1 CHECK(version>0),created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,started_at INTEGER,completed_at INTEGER,
      UNIQUE(organization_id,id),UNIQUE(organization_id,project_id,id),UNIQUE(organization_id,idempotency_key),CHECK(completed_at IS NULL OR state IN ('completed','failed','cancelled','quarantined')),FOREIGN KEY(organization_id,project_id) REFERENCES projects(organization_id,id) ON DELETE RESTRICT
    );
    CREATE INDEX IF NOT EXISTS execution_tasks_org_project_state_idx ON execution_tasks(organization_id,project_id,state,updated_at DESC,id DESC);
    CREATE INDEX IF NOT EXISTS execution_tasks_correlation_idx ON execution_tasks(correlation_id);
    CREATE TABLE IF NOT EXISTS execution_jobs (
      id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES identity_organizations(id) ON DELETE RESTRICT,project_id TEXT NOT NULL,task_id TEXT NOT NULL,
      queue TEXT NOT NULL,job_type TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('queued','running','retrying','completed','failed','cancelled','quarantined')),priority INTEGER NOT NULL DEFAULT 50 CHECK(priority BETWEEN 0 AND 100),
      available_at INTEGER NOT NULL,max_attempts INTEGER NOT NULL CHECK(max_attempts BETWEEN 1 AND 100),timeout_seconds INTEGER NOT NULL CHECK(timeout_seconds BETWEEN 1 AND 86400),attempt_count INTEGER NOT NULL DEFAULT 0 CHECK(attempt_count>=0),
      idempotency_key TEXT NOT NULL,correlation_id TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,completed_at INTEGER,UNIQUE(organization_id,id),UNIQUE(organization_id,idempotency_key),FOREIGN KEY(organization_id,project_id) REFERENCES projects(organization_id,id) ON DELETE RESTRICT,FOREIGN KEY(organization_id,project_id,task_id) REFERENCES execution_tasks(organization_id,project_id,id) ON DELETE RESTRICT
    );
    CREATE INDEX IF NOT EXISTS execution_jobs_claim_idx ON execution_jobs(queue,state,available_at,priority DESC,created_at,id);
    CREATE INDEX IF NOT EXISTS execution_jobs_org_task_idx ON execution_jobs(organization_id,task_id,created_at,id);
    CREATE TABLE IF NOT EXISTS execution_job_attempts (
      id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES identity_organizations(id) ON DELETE RESTRICT,job_id TEXT NOT NULL,task_id TEXT NOT NULL,
      attempt_number INTEGER NOT NULL CHECK(attempt_number>0),worker_id TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('running','succeeded','failed','cancelled','timed_out')),started_at INTEGER NOT NULL,finished_at INTEGER,error_code TEXT,error_message TEXT,retry_at INTEGER,correlation_id TEXT NOT NULL,
      UNIQUE(organization_id,id),UNIQUE(job_id,attempt_number),CHECK((state='running')=(finished_at IS NULL)),FOREIGN KEY(organization_id,job_id) REFERENCES execution_jobs(organization_id,id) ON DELETE RESTRICT,FOREIGN KEY(organization_id,task_id) REFERENCES execution_tasks(organization_id,id) ON DELETE RESTRICT
    );
    CREATE INDEX IF NOT EXISTS execution_attempts_org_job_idx ON execution_job_attempts(organization_id,job_id,attempt_number DESC);
    CREATE TABLE IF NOT EXISTS execution_job_leases (
      id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES identity_organizations(id) ON DELETE RESTRICT,job_id TEXT NOT NULL,attempt_id TEXT NOT NULL,
      worker_id TEXT NOT NULL,token_hash TEXT NOT NULL CHECK(length(token_hash)=64),state TEXT NOT NULL CHECK(state IN ('active','released','expired')),acquired_at INTEGER NOT NULL,heartbeat_at INTEGER NOT NULL,expires_at INTEGER NOT NULL,released_at INTEGER,version INTEGER NOT NULL DEFAULT 1 CHECK(version>0),
      CHECK(expires_at>acquired_at),CHECK((state='active' AND released_at IS NULL) OR (state='released' AND released_at IS NOT NULL) OR state='expired'),FOREIGN KEY(organization_id,job_id) REFERENCES execution_jobs(organization_id,id) ON DELETE RESTRICT,FOREIGN KEY(organization_id,attempt_id) REFERENCES execution_job_attempts(organization_id,id) ON DELETE RESTRICT
    );
    CREATE UNIQUE INDEX IF NOT EXISTS execution_leases_active_job_idx ON execution_job_leases(job_id) WHERE state='active';
    CREATE INDEX IF NOT EXISTS execution_leases_expiry_idx ON execution_job_leases(state,expires_at,job_id);
    CREATE TABLE IF NOT EXISTS execution_progress_events (
      id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES identity_organizations(id) ON DELETE RESTRICT,project_id TEXT NOT NULL,task_id TEXT NOT NULL,attempt_id TEXT,
      sequence INTEGER NOT NULL CHECK(sequence>0),progress INTEGER NOT NULL CHECK(progress BETWEEN 0 AND 100),stage TEXT NOT NULL,message_key TEXT,metadata_json TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(metadata_json)),correlation_id TEXT NOT NULL,created_at INTEGER NOT NULL,UNIQUE(task_id,sequence),FOREIGN KEY(organization_id,project_id) REFERENCES projects(organization_id,id) ON DELETE RESTRICT,FOREIGN KEY(organization_id,project_id,task_id) REFERENCES execution_tasks(organization_id,project_id,id) ON DELETE RESTRICT,FOREIGN KEY(organization_id,attempt_id) REFERENCES execution_job_attempts(organization_id,id) ON DELETE RESTRICT
    );
    CREATE INDEX IF NOT EXISTS execution_progress_org_task_idx ON execution_progress_events(organization_id,task_id,sequence DESC);
    CREATE TABLE IF NOT EXISTS execution_cancellations (
      id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES identity_organizations(id) ON DELETE RESTRICT,project_id TEXT NOT NULL,task_id TEXT NOT NULL,requested_by_account_id TEXT REFERENCES users(id) ON DELETE SET NULL,
      state TEXT NOT NULL CHECK(state IN ('requested','acknowledged','completed','rejected')),reason TEXT NOT NULL,idempotency_key TEXT NOT NULL,correlation_id TEXT NOT NULL,requested_at INTEGER NOT NULL,acknowledged_at INTEGER,completed_at INTEGER,
      UNIQUE(task_id),UNIQUE(organization_id,idempotency_key),FOREIGN KEY(organization_id,project_id) REFERENCES projects(organization_id,id) ON DELETE RESTRICT,FOREIGN KEY(organization_id,project_id,task_id) REFERENCES execution_tasks(organization_id,project_id,id) ON DELETE RESTRICT
    );
    CREATE INDEX IF NOT EXISTS execution_cancellations_pending_idx ON execution_cancellations(organization_id,state,requested_at,task_id);
    CREATE TABLE IF NOT EXISTS execution_idempotency_keys (
      id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES identity_organizations(id) ON DELETE CASCADE,scope TEXT NOT NULL,idempotency_key TEXT NOT NULL,request_hash TEXT NOT NULL CHECK(length(request_hash)=64),resource_type TEXT NOT NULL,resource_id TEXT NOT NULL,
      response_status INTEGER,response_json TEXT CHECK(response_json IS NULL OR json_valid(response_json)),expires_at INTEGER,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,UNIQUE(organization_id,scope,idempotency_key)
    );
    CREATE INDEX IF NOT EXISTS execution_idempotency_expiry_idx ON execution_idempotency_keys(expires_at) WHERE expires_at IS NOT NULL;
    CREATE TABLE IF NOT EXISTS execution_outbox (
      id TEXT PRIMARY KEY,organization_id TEXT REFERENCES identity_organizations(id) ON DELETE RESTRICT,project_id TEXT REFERENCES projects(id) ON DELETE RESTRICT,aggregate_type TEXT NOT NULL,aggregate_id TEXT NOT NULL,event_type TEXT NOT NULL,payload_json TEXT NOT NULL CHECK(json_valid(payload_json)),
      state TEXT NOT NULL CHECK(state IN ('pending','published','failed')),attempts INTEGER NOT NULL DEFAULT 0 CHECK(attempts>=0),available_at INTEGER NOT NULL,published_at INTEGER,last_error TEXT,idempotency_key TEXT NOT NULL,correlation_id TEXT NOT NULL,created_at INTEGER NOT NULL,CHECK((state='published')=(published_at IS NOT NULL))
    );
    CREATE UNIQUE INDEX IF NOT EXISTS execution_outbox_dedupe_idx ON execution_outbox(COALESCE(organization_id,''),idempotency_key);
    CREATE INDEX IF NOT EXISTS execution_outbox_delivery_idx ON execution_outbox(state,available_at,created_at,id);
    CREATE TABLE IF NOT EXISTS execution_inbox (
      id TEXT PRIMARY KEY,organization_id TEXT REFERENCES identity_organizations(id) ON DELETE RESTRICT,source TEXT NOT NULL,message_id TEXT NOT NULL,message_type TEXT NOT NULL,payload_hash TEXT NOT NULL CHECK(length(payload_hash)=64),payload_json TEXT NOT NULL CHECK(json_valid(payload_json)),
      state TEXT NOT NULL CHECK(state IN ('received','processed','failed')),received_at INTEGER NOT NULL,processed_at INTEGER,last_error TEXT,correlation_id TEXT NOT NULL,UNIQUE(source,message_id),CHECK((state='processed')=(processed_at IS NOT NULL))
    );
    CREATE INDEX IF NOT EXISTS execution_inbox_state_idx ON execution_inbox(state,received_at,id);
    CREATE TABLE IF NOT EXISTS execution_artifacts (
      id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES identity_organizations(id) ON DELETE RESTRICT,project_id TEXT NOT NULL,task_id TEXT NOT NULL,attempt_id TEXT,
      kind TEXT NOT NULL,object_key TEXT NOT NULL,sha256 TEXT NOT NULL CHECK(length(sha256)=64),mime_type TEXT NOT NULL,size_bytes INTEGER NOT NULL CHECK(size_bytes>=0),scan_state TEXT NOT NULL CHECK(scan_state IN ('pending','clean','blocked','failed')),retention_class TEXT NOT NULL,expires_at INTEGER,
      provenance_json TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(provenance_json)),idempotency_key TEXT NOT NULL,created_at INTEGER NOT NULL,UNIQUE(object_key),UNIQUE(organization_id,idempotency_key),FOREIGN KEY(organization_id,project_id) REFERENCES projects(organization_id,id) ON DELETE RESTRICT,FOREIGN KEY(organization_id,project_id,task_id) REFERENCES execution_tasks(organization_id,project_id,id) ON DELETE RESTRICT,FOREIGN KEY(organization_id,attempt_id) REFERENCES execution_job_attempts(organization_id,id) ON DELETE RESTRICT
    );
    CREATE INDEX IF NOT EXISTS execution_artifacts_org_project_task_idx ON execution_artifacts(organization_id,project_id,task_id,created_at DESC,id);
    CREATE INDEX IF NOT EXISTS execution_artifacts_expiry_idx ON execution_artifacts(expires_at) WHERE expires_at IS NOT NULL;
    CREATE TABLE IF NOT EXISTS execution_external_effects (
      id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES identity_organizations(id) ON DELETE RESTRICT,project_id TEXT NOT NULL,task_id TEXT NOT NULL,attempt_id TEXT,
      provider TEXT NOT NULL,operation TEXT NOT NULL,external_reference TEXT,request_hash TEXT NOT NULL CHECK(length(request_hash)=64),state TEXT NOT NULL CHECK(state IN ('pending','succeeded','failed','unknown')),
      evidence_json TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(evidence_json)),error_code TEXT,idempotency_key TEXT NOT NULL,correlation_id TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,
      UNIQUE(organization_id,provider,idempotency_key),FOREIGN KEY(organization_id,project_id) REFERENCES projects(organization_id,id) ON DELETE RESTRICT,FOREIGN KEY(organization_id,project_id,task_id) REFERENCES execution_tasks(organization_id,project_id,id) ON DELETE RESTRICT,FOREIGN KEY(organization_id,attempt_id) REFERENCES execution_job_attempts(organization_id,id) ON DELETE RESTRICT
    );
    CREATE INDEX IF NOT EXISTS execution_external_effects_task_idx ON execution_external_effects(organization_id,project_id,task_id,created_at,id);
    CREATE INDEX IF NOT EXISTS execution_external_effects_unknown_idx ON execution_external_effects(state,updated_at,id) WHERE state IN ('pending','unknown');
    CREATE TABLE IF NOT EXISTS operations_notifications (
      id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES identity_organizations(id) ON DELETE CASCADE,account_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,project_id TEXT,task_id TEXT,
      channel TEXT NOT NULL CHECK(channel IN ('in_app','email')),notification_type TEXT NOT NULL,locale TEXT NOT NULL CHECK(locale IN ('zh-CN','en')),title_key TEXT NOT NULL,body_key TEXT NOT NULL,arguments_json TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(arguments_json)),
      state TEXT NOT NULL CHECK(state IN ('pending','sent','failed','read','cancelled')),idempotency_key TEXT NOT NULL,available_at INTEGER NOT NULL,sent_at INTEGER,read_at INTEGER,last_error TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,UNIQUE(organization_id,channel,idempotency_key),CHECK(task_id IS NULL OR project_id IS NOT NULL),FOREIGN KEY(organization_id,project_id) REFERENCES projects(organization_id,id) ON DELETE CASCADE,FOREIGN KEY(organization_id,project_id,task_id) REFERENCES execution_tasks(organization_id,project_id,id) ON DELETE RESTRICT
    );
    CREATE INDEX IF NOT EXISTS operations_notifications_account_state_idx ON operations_notifications(organization_id,account_id,state,created_at DESC,id);
    CREATE TABLE IF NOT EXISTS operations_audit_events (
      id TEXT PRIMARY KEY,organization_id TEXT REFERENCES identity_organizations(id) ON DELETE RESTRICT,project_id TEXT,actor_type TEXT NOT NULL CHECK(actor_type IN ('user','api','mcp','agent','worker','system','support')),actor_id TEXT,action TEXT NOT NULL,target_type TEXT NOT NULL,target_id TEXT,
      outcome TEXT NOT NULL CHECK(outcome IN ('success','denied','failed','pending')),reason TEXT,policy_version TEXT,correlation_id TEXT NOT NULL,metadata_json TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(metadata_json)),occurred_at INTEGER NOT NULL,CHECK(project_id IS NULL OR organization_id IS NOT NULL),FOREIGN KEY(organization_id,project_id) REFERENCES projects(organization_id,id) ON DELETE RESTRICT
    );
    CREATE INDEX IF NOT EXISTS operations_audit_org_time_idx ON operations_audit_events(organization_id,occurred_at DESC,id);
    CREATE INDEX IF NOT EXISTS operations_audit_correlation_idx ON operations_audit_events(correlation_id,occurred_at,id);
    CREATE TRIGGER IF NOT EXISTS operations_audit_no_update BEFORE UPDATE ON operations_audit_events BEGIN SELECT RAISE(ABORT,'AUDIT_EVENTS_APPEND_ONLY'); END;
    CREATE TRIGGER IF NOT EXISTS operations_audit_no_delete BEFORE DELETE ON operations_audit_events BEGIN SELECT RAISE(ABORT,'AUDIT_EVENTS_APPEND_ONLY'); END;
  `);}
  transaction<T>(operation:()=>T){return this.database.transaction(operation);}
  createTask(value:ExecutionTask){this.database.prepare(`INSERT INTO execution_tasks(id,organization_id,project_id,requested_by_account_id,trigger_type,task_type,capability,state,progress,cancellable,input_json,locale,idempotency_key,correlation_id,version,created_at,updated_at,started_at,completed_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(value.id,value.organizationId,value.projectId,value.requestedByAccountId,value.triggerType,value.taskType,value.capability,value.state,value.progress,value.cancellable?1:0,JSON.stringify(value.input),value.locale,value.idempotencyKey,value.correlationId,value.version,value.createdAt,value.updatedAt,value.startedAt,value.completedAt).run();}
  task(organizationId:string,taskId:string){const row=this.database.prepare("SELECT * FROM execution_tasks WHERE organization_id=? AND id=?").bind(organizationId,taskId).first<JsonRow>();return row?this.mapTask(row):null;}
  taskByIdempotency(organizationId:string,key:string){const row=this.database.prepare("SELECT * FROM execution_tasks WHERE organization_id=? AND idempotency_key=?").bind(organizationId,key).first<JsonRow>();return row?this.mapTask(row):null;}
  createJob(value:ExecutionJob){this.database.prepare(`INSERT INTO execution_jobs(id,organization_id,project_id,task_id,queue,job_type,state,priority,available_at,max_attempts,timeout_seconds,attempt_count,idempotency_key,correlation_id,created_at,updated_at,completed_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(value.id,value.organizationId,value.projectId,value.taskId,value.queue,value.jobType,value.state,value.priority,value.availableAt,value.maxAttempts,value.timeoutSeconds,value.attemptCount,value.idempotencyKey,value.correlationId,value.createdAt,value.updatedAt,value.completedAt).run();}
  job(organizationId:string,jobId:string){const row=this.database.prepare("SELECT * FROM execution_jobs WHERE organization_id=? AND id=?").bind(organizationId,jobId).first<JsonRow>();return row?this.mapJob(row):null;}
  appendAttempt(value:JobAttempt){this.database.prepare(`INSERT INTO execution_job_attempts(id,organization_id,job_id,task_id,attempt_number,worker_id,state,started_at,finished_at,error_code,error_message,retry_at,correlation_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(value.id,value.organizationId,value.jobId,value.taskId,value.attemptNumber,value.workerId,value.state,value.startedAt,value.finishedAt,value.errorCode,value.errorMessage,value.retryAt,value.correlationId).run();}
  attempts(organizationId:string,jobId:string){return this.database.prepare("SELECT * FROM execution_job_attempts WHERE organization_id=? AND job_id=? ORDER BY attempt_number").bind(organizationId,jobId).all<JsonRow>().results.map(row=>this.mapAttempt(row));}
  putLease(value:JobLease){this.database.prepare(`INSERT INTO execution_job_leases(id,organization_id,job_id,attempt_id,worker_id,token_hash,state,acquired_at,heartbeat_at,expires_at,released_at,version) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`).bind(value.id,value.organizationId,value.jobId,value.attemptId,value.workerId,value.tokenHash,value.state,value.acquiredAt,value.heartbeatAt,value.expiresAt,value.releasedAt,value.version).run();}
  lease(organizationId:string,jobId:string){const row=this.database.prepare("SELECT * FROM execution_job_leases WHERE organization_id=? AND job_id=? ORDER BY acquired_at DESC,rowid DESC LIMIT 1").bind(organizationId,jobId).first<JsonRow>();return row?this.mapLease(row):null;}
  appendProgress(value:TaskProgressEvent){this.database.prepare(`INSERT INTO execution_progress_events(id,organization_id,project_id,task_id,attempt_id,sequence,progress,stage,message_key,metadata_json,correlation_id,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`).bind(value.id,value.organizationId,value.projectId,value.taskId,value.attemptId,value.sequence,value.progress,value.stage,value.messageKey,JSON.stringify(value.metadata),value.correlationId,value.createdAt).run();}
  progress(organizationId:string,taskId:string,limit:number){return this.database.prepare("SELECT * FROM execution_progress_events WHERE organization_id=? AND task_id=? ORDER BY sequence DESC LIMIT ?").bind(organizationId,taskId,Math.max(1,Math.min(500,limit))).all<JsonRow>().results.map(row=>this.mapProgress(row));}
  requestCancellation(value:CancellationRequest){this.database.prepare(`INSERT INTO execution_cancellations(id,organization_id,project_id,task_id,requested_by_account_id,state,reason,idempotency_key,correlation_id,requested_at,acknowledged_at,completed_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`).bind(value.id,value.organizationId,value.projectId,value.taskId,value.requestedByAccountId,value.state,value.reason,value.idempotencyKey,value.correlationId,value.requestedAt,value.acknowledgedAt,value.completedAt).run();}
  cancellation(organizationId:string,taskId:string){const row=this.database.prepare("SELECT * FROM execution_cancellations WHERE organization_id=? AND task_id=?").bind(organizationId,taskId).first<JsonRow>();return row?this.mapCancellation(row):null;}
  putIdempotency(value:ExecutionIdempotencyRecord){this.database.prepare(`INSERT INTO execution_idempotency_keys(id,organization_id,scope,idempotency_key,request_hash,resource_type,resource_id,response_status,response_json,expires_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`).bind(value.id,value.organizationId,value.scope,value.idempotencyKey,value.requestHash,value.resourceType,value.resourceId,value.responseStatus,value.response===null?null:JSON.stringify(value.response),value.expiresAt,value.createdAt,value.updatedAt).run();}
  idempotency(organizationId:string,scope:string,key:string){const row=this.database.prepare("SELECT * FROM execution_idempotency_keys WHERE organization_id=? AND scope=? AND idempotency_key=?").bind(organizationId,scope,key).first<JsonRow>();return row?this.mapIdempotency(row):null;}
  appendOutbox(value:OutboxMessage){this.database.prepare(`INSERT INTO execution_outbox(id,organization_id,project_id,aggregate_type,aggregate_id,event_type,payload_json,state,attempts,available_at,published_at,last_error,idempotency_key,correlation_id,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(value.id,value.organizationId,value.projectId,value.aggregateType,value.aggregateId,value.eventType,JSON.stringify(value.payload),value.state,value.attempts,value.availableAt,value.publishedAt,value.lastError,value.idempotencyKey,value.correlationId,value.createdAt).run();}
  outbox(organizationId:string|null,id:string){const row=organizationId===null?this.database.prepare("SELECT * FROM execution_outbox WHERE organization_id IS NULL AND id=?").bind(id).first<JsonRow>():this.database.prepare("SELECT * FROM execution_outbox WHERE organization_id=? AND id=?").bind(organizationId,id).first<JsonRow>();return row?this.mapOutbox(row):null;}
  pendingOutbox(limit:number,now:number){return this.database.prepare("SELECT * FROM execution_outbox WHERE state IN ('pending','failed') AND available_at<=? ORDER BY available_at,created_at,id LIMIT ?").bind(now,Math.max(1,Math.min(500,limit))).all<JsonRow>().results.map(row=>this.mapOutbox(row));}
  recordInbox(value:InboxMessage){try{this.database.prepare(`INSERT INTO execution_inbox(id,organization_id,source,message_id,message_type,payload_hash,payload_json,state,received_at,processed_at,last_error,correlation_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`).bind(value.id,value.organizationId,value.source,value.messageId,value.messageType,value.payloadHash,JSON.stringify(value.payload),value.state,value.receivedAt,value.processedAt,value.lastError,value.correlationId).run();return true;}catch(error){if(error instanceof Error&&/UNIQUE constraint failed: execution_inbox\.source, execution_inbox\.message_id/.test(error.message))return false;throw error;}}
  inbox(source:string,messageId:string){const row=this.database.prepare("SELECT * FROM execution_inbox WHERE source=? AND message_id=?").bind(source,messageId).first<JsonRow>();return row?this.mapInbox(row):null;}
  appendArtifact(value:ArtifactRecord){this.database.prepare(`INSERT INTO execution_artifacts(id,organization_id,project_id,task_id,attempt_id,kind,object_key,sha256,mime_type,size_bytes,scan_state,retention_class,expires_at,provenance_json,idempotency_key,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(value.id,value.organizationId,value.projectId,value.taskId,value.attemptId,value.kind,value.objectKey,value.sha256,value.mimeType,value.sizeBytes,value.scanState,value.retentionClass,value.expiresAt,JSON.stringify(value.provenance),value.idempotencyKey,value.createdAt).run();}
  artifact(organizationId:string,artifactId:string){const row=this.database.prepare("SELECT * FROM execution_artifacts WHERE organization_id=? AND id=?").bind(organizationId,artifactId).first<JsonRow>();return row?this.mapArtifact(row):null;}
  externalEffect(organizationId:string,provider:string,idempotencyKey:string){const row=this.database.prepare("SELECT * FROM execution_external_effects WHERE organization_id=? AND provider=? AND idempotency_key=?").bind(organizationId,provider,idempotencyKey).first<JsonRow>();return row?this.mapExternalEffect(row):null;}
  appendExternalEffect(value:ExternalEffectRecord){this.database.prepare(`INSERT INTO execution_external_effects(id,organization_id,project_id,task_id,attempt_id,provider,operation,external_reference,request_hash,state,evidence_json,error_code,idempotency_key,correlation_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(value.id,value.organizationId,value.projectId,value.taskId,value.attemptId,value.provider,value.operation,value.externalReference,value.requestHash,value.state,JSON.stringify(value.evidence),value.errorCode,value.idempotencyKey,value.correlationId,value.createdAt,value.updatedAt).run();}
  settleExternalEffect(value:ExternalEffectRecord){return this.database.prepare("UPDATE execution_external_effects SET external_reference=?,state=?,evidence_json=?,error_code=?,updated_at=? WHERE organization_id=? AND provider=? AND idempotency_key=? AND request_hash=? AND operation=? AND task_id=? AND state IN ('pending','unknown')").bind(value.externalReference,value.state,JSON.stringify(value.evidence),value.errorCode,value.updatedAt,value.organizationId,value.provider,value.idempotencyKey,value.requestHash,value.operation,value.taskId).run().meta.changes===1;}
  appendNotification(value:NotificationRecord){this.database.prepare(`INSERT INTO operations_notifications(id,organization_id,account_id,project_id,task_id,channel,notification_type,locale,title_key,body_key,arguments_json,state,idempotency_key,available_at,sent_at,read_at,last_error,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(value.id,value.organizationId,value.accountId,value.projectId,value.taskId,value.channel,value.notificationType,value.locale,value.titleKey,value.bodyKey,JSON.stringify(value.arguments),value.state,value.idempotencyKey,value.availableAt,value.sentAt,value.readAt,value.lastError,value.createdAt,value.updatedAt).run();}
  notifications(organizationId:string,accountId:string,limit:number){return this.database.prepare("SELECT * FROM operations_notifications WHERE organization_id=? AND account_id=? ORDER BY created_at DESC,id DESC LIMIT ?").bind(organizationId,accountId,Math.max(1,Math.min(200,limit))).all<JsonRow>().results.map(row=>this.mapNotification(row));}
  appendAudit(value:ExecutionAuditEvent){this.database.prepare(`INSERT INTO operations_audit_events(id,organization_id,project_id,actor_type,actor_id,action,target_type,target_id,outcome,reason,policy_version,correlation_id,metadata_json,occurred_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(value.id,value.organizationId,value.projectId,value.actorType,value.actorId,value.action,value.targetType,value.targetId,value.outcome,value.reason,value.policyVersion,value.correlationId,JSON.stringify(value.metadata),value.occurredAt).run();}
  auditEvents(organizationId:string,limit:number){return this.database.prepare("SELECT * FROM operations_audit_events WHERE organization_id=? ORDER BY occurred_at DESC,rowid DESC LIMIT ?").bind(organizationId,Math.max(1,Math.min(500,limit))).all<JsonRow>().results.map(row=>this.mapAudit(row));}
  settleTask(input:{organizationId:string;taskId:string;state:"completed"|"failed"|"cancelled"|"quarantined";progress:number;now:number}){return this.database.prepare("UPDATE execution_tasks SET state=?,progress=?,cancellable=0,updated_at=?,completed_at=?,version=version+1 WHERE organization_id=? AND id=? AND state IN ('running','retrying')").bind(input.state,input.progress,input.now,input.now,input.organizationId,input.taskId).run().meta.changes===1;}

  claimJob(input:{queue:string;jobTypes:string[];workerId:string;tokenHash:string;now:number;leaseSeconds:number}):WorkerClaim|null{return this.transaction(()=>{
    const jobTypes=[...new Set(input.jobTypes)].filter(Boolean);if(!jobTypes.length)return null;const placeholders=jobTypes.map(()=>"?").join(",");
    const row=this.database.prepare(`SELECT j.* FROM execution_jobs j JOIN execution_tasks t ON t.organization_id=j.organization_id AND t.id=j.task_id WHERE j.queue=? AND j.job_type IN (${placeholders}) AND j.state IN ('queued','retrying') AND j.available_at<=? AND t.state IN ('queued','retrying') AND NOT EXISTS (SELECT 1 FROM execution_cancellations c WHERE c.organization_id=j.organization_id AND c.task_id=j.task_id AND c.state IN ('requested','acknowledged')) ORDER BY j.priority DESC,j.available_at,j.created_at,j.id LIMIT 1`).bind(input.queue,...jobTypes,input.now).first<JsonRow>();if(!row)return null;
    const job=this.mapJob(row),task=this.task(job.organizationId,job.taskId);if(!task)throw new Error("WORKER_TASK_NOT_FOUND");const attemptNumber=job.attemptCount+1;
    const attempt:JobAttempt={id:crypto.randomUUID(),organizationId:job.organizationId,jobId:job.id,taskId:job.taskId,attemptNumber,workerId:input.workerId,state:"running",startedAt:input.now,finishedAt:null,errorCode:null,errorMessage:null,retryAt:null,correlationId:job.correlationId};
    const lease:JobLease={id:crypto.randomUUID(),organizationId:job.organizationId,jobId:job.id,attemptId:attempt.id,workerId:input.workerId,tokenHash:input.tokenHash,state:"active",acquiredAt:input.now,heartbeatAt:input.now,expiresAt:input.now+input.leaseSeconds,releasedAt:null,version:1};
    this.appendAttempt(attempt);this.putLease(lease);this.database.prepare("UPDATE execution_jobs SET state='running',attempt_count=?,updated_at=? WHERE organization_id=? AND id=? AND state IN ('queued','retrying')").bind(attemptNumber,input.now,job.organizationId,job.id).run();this.database.prepare("UPDATE execution_tasks SET state='running',started_at=COALESCE(started_at,?),updated_at=?,version=version+1 WHERE organization_id=? AND id=? AND state IN ('queued','retrying')").bind(input.now,input.now,task.organizationId,task.id).run();
    this.appendAudit({id:crypto.randomUUID(),organizationId:job.organizationId,projectId:job.projectId,actorType:"worker",actorId:input.workerId,action:"execution.job.claim",targetType:"job",targetId:job.id,outcome:"pending",reason:null,policyVersion:"execution-worker-v1",correlationId:job.correlationId,metadata:{attemptId:attempt.id,attemptNumber,leaseSeconds:input.leaseSeconds},occurredAt:input.now});
    return{task:{...task,state:"running",startedAt:task.startedAt??input.now,updatedAt:input.now,version:task.version+1},job:{...job,state:"running",attemptCount:attemptNumber,updatedAt:input.now},attempt,lease};
  });}

  heartbeatLease(input:{organizationId:string;jobId:string;attemptId:string;workerId:string;tokenHash:string;now:number;leaseSeconds:number}):WorkerHeartbeat|null{return this.transaction(()=>{
    const lease=this.lease(input.organizationId,input.jobId);if(!this.ownsActiveLease(lease,input)||lease.expiresAt<=input.now)return null;const next={...lease,heartbeatAt:input.now,expiresAt:input.now+input.leaseSeconds,version:lease.version+1};
    const changed=this.database.prepare("UPDATE execution_job_leases SET heartbeat_at=?,expires_at=?,version=? WHERE id=? AND state='active' AND version=? AND expires_at>?").bind(next.heartbeatAt,next.expiresAt,next.version,lease.id,lease.version,input.now).run().meta.changes;if(changed!==1)return null;
    const cancellation=this.database.prepare("SELECT id,state FROM execution_cancellations WHERE organization_id=? AND task_id=(SELECT task_id FROM execution_jobs WHERE organization_id=? AND id=?) AND state IN ('requested','acknowledged')").bind(input.organizationId,input.organizationId,input.jobId).first<{id:string;state:string}>();if(cancellation?.state==="requested")this.database.prepare("UPDATE execution_cancellations SET state='acknowledged',acknowledged_at=? WHERE id=? AND state='requested'").bind(input.now,cancellation.id).run();
    return{lease:next,cancellationRequested:Boolean(cancellation)};
  });}

  succeedAttempt(input:{claim:WorkerClaim;workerId:string;tokenHash:string;now:number}):boolean{return this.transaction(()=>{
    const{job,attempt}=input.claim,lease=this.lease(job.organizationId,job.id);if(!this.ownsActiveLease(lease,{...input,attemptId:attempt.id})||lease.expiresAt<=input.now)return false;
    this.database.prepare("UPDATE execution_job_attempts SET state='succeeded',finished_at=? WHERE organization_id=? AND id=? AND state='running'").bind(input.now,job.organizationId,attempt.id).run();this.releaseLease(lease,input.now);const changed=this.database.prepare("UPDATE execution_jobs SET state='completed',updated_at=?,completed_at=? WHERE organization_id=? AND id=? AND state='running'").bind(input.now,input.now,job.organizationId,job.id).run().meta.changes;if(changed!==1)throw new Error("WORKER_JOB_STATE_CONFLICT");this.workerEvent(job,input.workerId,input.now,"completed",attempt.attemptNumber,null);return true;
  });}

  failAttempt(input:{claim:WorkerClaim;workerId:string;tokenHash:string;now:number;state:WorkerFailureState;retryAt:number|null;errorCode:string;errorMessage:string}):boolean{return this.transaction(()=>{
    const{job,attempt}=input.claim,lease=this.lease(job.organizationId,job.id);if(!this.ownsActiveLease(lease,{...input,attemptId:attempt.id})||lease.expiresAt<=input.now)return false;if((input.state==="retrying")!==(input.retryAt!==null))throw new Error("WORKER_RETRY_POLICY_INVALID");
    this.database.prepare("UPDATE execution_job_attempts SET state='failed',finished_at=?,error_code=?,error_message=?,retry_at=? WHERE organization_id=? AND id=? AND state='running'").bind(input.now,input.errorCode,input.errorMessage,input.retryAt,job.organizationId,attempt.id).run();this.releaseLease(lease,input.now);this.database.prepare("UPDATE execution_jobs SET state=?,available_at=COALESCE(?,available_at),updated_at=?,completed_at=? WHERE organization_id=? AND id=? AND state='running'").bind(input.state,input.retryAt,input.now,input.state==="retrying"?null:input.now,job.organizationId,job.id).run();if(input.state==="retrying")this.database.prepare("UPDATE execution_tasks SET state='retrying',updated_at=?,version=version+1 WHERE organization_id=? AND id=? AND state='running'").bind(input.now,job.organizationId,job.taskId).run();this.workerEvent(job,input.workerId,input.now,input.state,attempt.attemptNumber,input.errorCode);return true;
  });}

  cancelAttempt(input:{claim:WorkerClaim;workerId:string;tokenHash:string;now:number;reason:string}):boolean{return this.transaction(()=>{
    const{job,attempt}=input.claim,lease=this.lease(job.organizationId,job.id);if(!this.ownsActiveLease(lease,{...input,attemptId:attempt.id})||lease.expiresAt<=input.now)return false;
    this.database.prepare("UPDATE execution_job_attempts SET state='cancelled',finished_at=?,error_code='JOB_CANCELLED',error_message=? WHERE organization_id=? AND id=? AND state='running'").bind(input.now,input.reason,job.organizationId,attempt.id).run();this.releaseLease(lease,input.now);this.database.prepare("UPDATE execution_jobs SET state='cancelled',updated_at=?,completed_at=? WHERE organization_id=? AND id=? AND state='running'").bind(input.now,input.now,job.organizationId,job.id).run();this.database.prepare("UPDATE execution_cancellations SET state='completed',acknowledged_at=COALESCE(acknowledged_at,?),completed_at=? WHERE organization_id=? AND task_id=? AND state IN ('requested','acknowledged')").bind(input.now,input.now,job.organizationId,job.taskId).run();this.workerEvent(job,input.workerId,input.now,"cancelled",attempt.attemptNumber,"JOB_CANCELLED");return true;
  });}

  maintainJobs(input:{queue:string;jobTypes:string[];workerId:string;now:number;limit:number;baseBackoffSeconds:number;maxBackoffSeconds:number}):WorkerMaintenance{return this.transaction(()=>{
    const jobTypes=[...new Set(input.jobTypes)].filter(Boolean),result:WorkerMaintenance={cancelled:0,recovered:[]};if(!jobTypes.length)return result;const limit=Math.max(1,Math.min(500,input.limit)),placeholders=jobTypes.map(()=>"?").join(",");
    const cancelled=this.database.prepare(`SELECT j.* FROM execution_jobs j JOIN execution_cancellations c ON c.organization_id=j.organization_id AND c.task_id=j.task_id WHERE j.queue=? AND j.job_type IN (${placeholders}) AND j.state IN ('queued','retrying') AND c.state IN ('requested','acknowledged') ORDER BY c.requested_at,j.id LIMIT ?`).bind(input.queue,...jobTypes,limit).all<JsonRow>().results;
    for(const row of cancelled){const job=this.mapJob(row);this.database.prepare("UPDATE execution_jobs SET state='cancelled',updated_at=?,completed_at=? WHERE organization_id=? AND id=? AND state IN ('queued','retrying')").bind(input.now,input.now,job.organizationId,job.id).run();this.database.prepare("UPDATE execution_cancellations SET state='completed',acknowledged_at=COALESCE(acknowledged_at,?),completed_at=? WHERE organization_id=? AND task_id=? AND state IN ('requested','acknowledged')").bind(input.now,input.now,job.organizationId,job.taskId).run();this.workerEvent(job,input.workerId,input.now,"cancelled",job.attemptCount,"JOB_CANCELLED_BEFORE_CLAIM");result.cancelled++;}
    const remaining=limit-result.cancelled;if(remaining<=0)return result;const expired=this.database.prepare(`SELECT l.*,j.project_id,j.task_id,j.attempt_count,j.max_attempts,j.timeout_seconds,j.correlation_id,j.idempotency_key,j.queue,j.job_type,j.priority,j.available_at,j.created_at,j.updated_at,j.completed_at,j.state AS job_state FROM execution_job_leases l JOIN execution_jobs j ON j.organization_id=l.organization_id AND j.id=l.job_id WHERE j.queue=? AND j.job_type IN (${placeholders}) AND j.state='running' AND l.state='active' AND l.expires_at<=? ORDER BY l.expires_at,l.id LIMIT ?`).bind(input.queue,...jobTypes,input.now,remaining).all<JsonRow>().results;
    for(const row of expired){const lease=this.mapLease(row),job=this.mapJoinedJob(row),cancellation=this.database.prepare("SELECT id FROM execution_cancellations WHERE organization_id=? AND task_id=? AND state IN ('requested','acknowledged')").bind(job.organizationId,job.taskId).first<{id:string}>();this.database.prepare("UPDATE execution_job_leases SET state='expired',version=version+1 WHERE id=? AND state='active'").bind(lease.id).run();const retrying=!cancellation&&job.attemptCount<job.maxAttempts,state= cancellation?"cancelled":retrying?"retrying":"quarantined";const retryAt=retrying?input.now+this.backoff(job.attemptCount,input.baseBackoffSeconds,input.maxBackoffSeconds):null;this.database.prepare("UPDATE execution_job_attempts SET state='timed_out',finished_at=?,error_code='LEASE_EXPIRED',error_message='Worker lease expired',retry_at=? WHERE organization_id=? AND id=? AND state='running'").bind(input.now,retryAt,job.organizationId,lease.attemptId).run();this.database.prepare("UPDATE execution_jobs SET state=?,available_at=COALESCE(?,available_at),updated_at=?,completed_at=? WHERE organization_id=? AND id=? AND state='running'").bind(state,retryAt,input.now,retrying?null:input.now,job.organizationId,job.id).run();if(retrying)this.database.prepare("UPDATE execution_tasks SET state='retrying',updated_at=?,version=version+1 WHERE organization_id=? AND id=? AND state='running'").bind(input.now,job.organizationId,job.taskId).run();if(cancellation)this.database.prepare("UPDATE execution_cancellations SET state='completed',acknowledged_at=COALESCE(acknowledged_at,?),completed_at=? WHERE id=?").bind(input.now,input.now,cancellation.id).run();this.workerEvent(job,input.workerId,input.now,state,job.attemptCount,cancellation?"JOB_CANCELLED_AFTER_LEASE_EXPIRY":"LEASE_EXPIRED");result.recovered.push({jobId:job.id,taskId:job.taskId,state,attemptNumber:job.attemptCount});}
    return result;
  });}

  private ownsActiveLease(lease:JobLease|null,input:{attemptId:string;workerId:string;tokenHash:string}):lease is JobLease{return Boolean(lease&&lease.state==="active"&&lease.attemptId===input.attemptId&&lease.workerId===input.workerId&&lease.tokenHash===input.tokenHash);}
  private releaseLease(lease:JobLease,now:number){this.database.prepare("UPDATE execution_job_leases SET state='released',released_at=?,version=version+1 WHERE id=? AND state='active'").bind(now,lease.id).run();}
  private backoff(attempt:number,base:number,max:number){return Math.min(max,base*2**Math.max(0,attempt-1));}
  private workerEvent(job:ExecutionJob,workerId:string,now:number,state:string,attemptNumber:number,reason:string|null){this.appendOutbox({id:crypto.randomUUID(),organizationId:job.organizationId,projectId:job.projectId,aggregateType:"job",aggregateId:job.id,eventType:`execution.job.${state}`,payload:{jobId:job.id,taskId:job.taskId,state,attemptNumber,reason},state:"pending",attempts:0,availableAt:now,publishedAt:null,lastError:null,idempotencyKey:`worker:${job.id}:${attemptNumber}:${state}`,correlationId:job.correlationId,createdAt:now});this.appendAudit({id:crypto.randomUUID(),organizationId:job.organizationId,projectId:job.projectId,actorType:"worker",actorId:workerId,action:`execution.job.${state}`,targetType:"job",targetId:job.id,outcome:state==="completed"||state==="cancelled"?"success":state==="retrying"?"pending":"failed",reason,policyVersion:"execution-worker-v1",correlationId:job.correlationId,metadata:{taskId:job.taskId,attemptNumber},occurredAt:now});}
  private mapJoinedJob(row:JsonRow):ExecutionJob{return{id:String(row.job_id),organizationId:String(row.organization_id),projectId:String(row.project_id),taskId:String(row.task_id),queue:String(row.queue),jobType:String(row.job_type),state:row.job_state as ExecutionJob["state"],priority:Number(row.priority),availableAt:Number(row.available_at),maxAttempts:Number(row.max_attempts),timeoutSeconds:Number(row.timeout_seconds),attemptCount:Number(row.attempt_count),idempotencyKey:String(row.idempotency_key),correlationId:String(row.correlation_id),createdAt:Number(row.created_at),updatedAt:Number(row.updated_at),completedAt:row.completed_at===null?null:Number(row.completed_at)};}

  private mapTask(row:JsonRow):ExecutionTask{return{id:String(row.id),organizationId:String(row.organization_id),projectId:String(row.project_id),requestedByAccountId:row.requested_by_account_id===null?null:String(row.requested_by_account_id),triggerType:row.trigger_type as ExecutionTask["triggerType"],taskType:String(row.task_type),capability:String(row.capability),state:row.state as ExecutionTask["state"],progress:Number(row.progress),cancellable:boolean(row.cancellable),input:parse(row.input_json),locale:row.locale as ExecutionTask["locale"],idempotencyKey:String(row.idempotency_key),correlationId:String(row.correlation_id),version:Number(row.version),createdAt:Number(row.created_at),updatedAt:Number(row.updated_at),startedAt:row.started_at===null?null:Number(row.started_at),completedAt:row.completed_at===null?null:Number(row.completed_at)};}
  private mapJob(row:JsonRow):ExecutionJob{return{id:String(row.id),organizationId:String(row.organization_id),projectId:String(row.project_id),taskId:String(row.task_id),queue:String(row.queue),jobType:String(row.job_type),state:row.state as ExecutionJob["state"],priority:Number(row.priority),availableAt:Number(row.available_at),maxAttempts:Number(row.max_attempts),timeoutSeconds:Number(row.timeout_seconds),attemptCount:Number(row.attempt_count),idempotencyKey:String(row.idempotency_key),correlationId:String(row.correlation_id),createdAt:Number(row.created_at),updatedAt:Number(row.updated_at),completedAt:row.completed_at===null?null:Number(row.completed_at)};}
  private mapAttempt(row:JsonRow):JobAttempt{return{id:String(row.id),organizationId:String(row.organization_id),jobId:String(row.job_id),taskId:String(row.task_id),attemptNumber:Number(row.attempt_number),workerId:String(row.worker_id),state:row.state as JobAttempt["state"],startedAt:Number(row.started_at),finishedAt:row.finished_at===null?null:Number(row.finished_at),errorCode:row.error_code===null?null:String(row.error_code),errorMessage:row.error_message===null?null:String(row.error_message),retryAt:row.retry_at===null?null:Number(row.retry_at),correlationId:String(row.correlation_id)};}
  private mapLease(row:JsonRow):JobLease{return{id:String(row.id),organizationId:String(row.organization_id),jobId:String(row.job_id),attemptId:String(row.attempt_id),workerId:String(row.worker_id),tokenHash:String(row.token_hash),state:row.state as JobLease["state"],acquiredAt:Number(row.acquired_at),heartbeatAt:Number(row.heartbeat_at),expiresAt:Number(row.expires_at),releasedAt:row.released_at===null?null:Number(row.released_at),version:Number(row.version)};}
  private mapProgress(row:JsonRow):TaskProgressEvent{return{id:String(row.id),organizationId:String(row.organization_id),projectId:String(row.project_id),taskId:String(row.task_id),attemptId:row.attempt_id===null?null:String(row.attempt_id),sequence:Number(row.sequence),progress:Number(row.progress),stage:String(row.stage),messageKey:row.message_key===null?null:String(row.message_key),metadata:parse(row.metadata_json),correlationId:String(row.correlation_id),createdAt:Number(row.created_at)};}
  private mapCancellation(row:JsonRow):CancellationRequest{return{id:String(row.id),organizationId:String(row.organization_id),projectId:String(row.project_id),taskId:String(row.task_id),requestedByAccountId:row.requested_by_account_id===null?null:String(row.requested_by_account_id),state:row.state as CancellationRequest["state"],reason:String(row.reason),idempotencyKey:String(row.idempotency_key),correlationId:String(row.correlation_id),requestedAt:Number(row.requested_at),acknowledgedAt:row.acknowledged_at===null?null:Number(row.acknowledged_at),completedAt:row.completed_at===null?null:Number(row.completed_at)};}
  private mapIdempotency(row:JsonRow):ExecutionIdempotencyRecord{return{id:String(row.id),organizationId:String(row.organization_id),scope:String(row.scope),idempotencyKey:String(row.idempotency_key),requestHash:String(row.request_hash),resourceType:String(row.resource_type),resourceId:String(row.resource_id),responseStatus:row.response_status===null?null:Number(row.response_status),response:row.response_json===null?null:parse(row.response_json),expiresAt:row.expires_at===null?null:Number(row.expires_at),createdAt:Number(row.created_at),updatedAt:Number(row.updated_at)};}
  private mapOutbox(row:JsonRow):OutboxMessage{return{id:String(row.id),organizationId:row.organization_id===null?null:String(row.organization_id),projectId:row.project_id===null?null:String(row.project_id),aggregateType:String(row.aggregate_type),aggregateId:String(row.aggregate_id),eventType:String(row.event_type),payload:parse(row.payload_json),state:row.state as OutboxMessage["state"],attempts:Number(row.attempts),availableAt:Number(row.available_at),publishedAt:row.published_at===null?null:Number(row.published_at),lastError:row.last_error===null?null:String(row.last_error),idempotencyKey:String(row.idempotency_key),correlationId:String(row.correlation_id),createdAt:Number(row.created_at)};}
  private mapInbox(row:JsonRow):InboxMessage{return{id:String(row.id),organizationId:row.organization_id===null?null:String(row.organization_id),source:String(row.source),messageId:String(row.message_id),messageType:String(row.message_type),payloadHash:String(row.payload_hash),payload:parse(row.payload_json),state:row.state as InboxMessage["state"],receivedAt:Number(row.received_at),processedAt:row.processed_at===null?null:Number(row.processed_at),lastError:row.last_error===null?null:String(row.last_error),correlationId:String(row.correlation_id)};}
  private mapArtifact(row:JsonRow):ArtifactRecord{return{id:String(row.id),organizationId:String(row.organization_id),projectId:String(row.project_id),taskId:String(row.task_id),attemptId:row.attempt_id===null?null:String(row.attempt_id),kind:String(row.kind),objectKey:String(row.object_key),sha256:String(row.sha256),mimeType:String(row.mime_type),sizeBytes:Number(row.size_bytes),scanState:row.scan_state as ArtifactRecord["scanState"],retentionClass:String(row.retention_class),expiresAt:row.expires_at===null?null:Number(row.expires_at),provenance:parse(row.provenance_json),idempotencyKey:String(row.idempotency_key),createdAt:Number(row.created_at)};}
  private mapExternalEffect(row:JsonRow):ExternalEffectRecord{return{id:String(row.id),organizationId:String(row.organization_id),projectId:String(row.project_id),taskId:String(row.task_id),attemptId:row.attempt_id===null?null:String(row.attempt_id),provider:String(row.provider),operation:String(row.operation),externalReference:row.external_reference===null?null:String(row.external_reference),requestHash:String(row.request_hash),state:row.state as ExternalEffectRecord["state"],evidence:parse(row.evidence_json),errorCode:row.error_code===null?null:String(row.error_code),idempotencyKey:String(row.idempotency_key),correlationId:String(row.correlation_id),createdAt:Number(row.created_at),updatedAt:Number(row.updated_at)};}
  private mapNotification(row:JsonRow):NotificationRecord{return{id:String(row.id),organizationId:String(row.organization_id),accountId:String(row.account_id),projectId:row.project_id===null?null:String(row.project_id),taskId:row.task_id===null?null:String(row.task_id),channel:row.channel as NotificationRecord["channel"],notificationType:String(row.notification_type),locale:row.locale as NotificationRecord["locale"],titleKey:String(row.title_key),bodyKey:String(row.body_key),arguments:parse(row.arguments_json),state:row.state as NotificationRecord["state"],idempotencyKey:String(row.idempotency_key),availableAt:Number(row.available_at),sentAt:row.sent_at===null?null:Number(row.sent_at),readAt:row.read_at===null?null:Number(row.read_at),lastError:row.last_error===null?null:String(row.last_error),createdAt:Number(row.created_at),updatedAt:Number(row.updated_at)};}
  private mapAudit(row:JsonRow):ExecutionAuditEvent{return{id:String(row.id),organizationId:row.organization_id===null?null:String(row.organization_id),projectId:row.project_id===null?null:String(row.project_id),actorType:row.actor_type as ExecutionAuditEvent["actorType"],actorId:row.actor_id===null?null:String(row.actor_id),action:String(row.action),targetType:String(row.target_type),targetId:row.target_id===null?null:String(row.target_id),outcome:row.outcome as ExecutionAuditEvent["outcome"],reason:row.reason===null?null:String(row.reason),policyVersion:row.policy_version===null?null:String(row.policy_version),correlationId:String(row.correlation_id),metadata:parse(row.metadata_json),occurredAt:Number(row.occurred_at)};}
}
