import type { AppDatabase } from "../../../lib/database";
import type { ProviderHealth } from "../../modules/integrations";
import type { IntegrationAudit, IntegrationConnection, IntegrationConnectionRepository, IntegrationCredentialRecord } from "../../modules/integrations/connections";

type Row = Record<string, unknown>;
export class SqliteIntegrationConnectionRepository implements IntegrationConnectionRepository {
  constructor(private readonly db: AppDatabase) {}
  ensureSchema() { this.db.exec(`
    CREATE TABLE IF NOT EXISTS integration_connections(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,project_id TEXT NOT NULL,provider_id TEXT NOT NULL,auth_method TEXT NOT NULL CHECK(auth_method IN('oauth2','api_key')),environment TEXT NOT NULL CHECK(environment IN('production','staging')),state TEXT NOT NULL CHECK(state IN('disconnected','connecting','connected','syncing','degraded','expired','permission_required','rate_limited','error')),granted_scopes_json TEXT NOT NULL CHECK(json_valid(granted_scopes_json)),owner_account_id TEXT NOT NULL,masked_hint TEXT NOT NULL,health_json TEXT CHECK(health_json IS NULL OR json_valid(health_json)),last_synced_at INTEGER,revision INTEGER NOT NULL CHECK(revision>0),created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,disconnected_at INTEGER,deleted_at INTEGER,UNIQUE(organization_id,project_id,id),FOREIGN KEY(organization_id,project_id)REFERENCES projects(organization_id,id));
    CREATE TABLE IF NOT EXISTS integration_credentials(id TEXT PRIMARY KEY,connection_id TEXT NOT NULL REFERENCES integration_connections(id),record_version INTEGER NOT NULL CHECK(record_version>0),encrypted_envelope TEXT NOT NULL,key_version TEXT NOT NULL,created_at INTEGER NOT NULL,revoked_at INTEGER,UNIQUE(connection_id,record_version));
    CREATE TABLE IF NOT EXISTS integration_audit_events(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,project_id TEXT NOT NULL,actor_id TEXT NOT NULL,action TEXT NOT NULL,connection_id TEXT NOT NULL,reason TEXT NOT NULL,correlation_id TEXT NOT NULL,metadata_json TEXT NOT NULL CHECK(json_valid(metadata_json)),occurred_at INTEGER NOT NULL,FOREIGN KEY(organization_id,project_id,connection_id)REFERENCES integration_connections(organization_id,project_id,id));
    CREATE INDEX IF NOT EXISTS integration_connection_scope_idx ON integration_connections(organization_id,project_id,state,provider_id);
    CREATE TRIGGER IF NOT EXISTS integration_audit_no_update BEFORE UPDATE ON integration_audit_events BEGIN SELECT RAISE(ABORT,'INTEGRATION_AUDIT_APPEND_ONLY');END;
    CREATE TRIGGER IF NOT EXISTS integration_audit_no_delete BEFORE DELETE ON integration_audit_events BEGIN SELECT RAISE(ABORT,'INTEGRATION_AUDIT_APPEND_ONLY');END;
  `); }
  transaction<T>(operation: () => T) { return this.db.transaction(operation); }
  projectExists(organizationId: string, projectId: string) { return Boolean(this.db.prepare("SELECT 1 ok FROM projects WHERE organization_id=? AND id=? AND status='active'").bind(organizationId, projectId).first()); }
  activeConnectionCount(organizationId: string) { return this.db.prepare("SELECT COUNT(*) count FROM integration_connections WHERE organization_id=? AND deleted_at IS NULL AND state!='disconnected'").bind(organizationId).first<{count:number}>()?.count || 0; }
  connection(organizationId: string, projectId: string, connectionId: string) { const row=this.db.prepare("SELECT * FROM integration_connections WHERE organization_id=? AND project_id=? AND id=?").bind(organizationId,projectId,connectionId).first<Row>();return row?this.mapConnection(row):null; }
  credential(connectionId: string) { const row=this.db.prepare("SELECT * FROM integration_credentials WHERE connection_id=? ORDER BY record_version DESC LIMIT 1").bind(connectionId).first<Row>();return row?this.mapCredential(row):null; }
  appendConnection(v: IntegrationConnection) { this.db.prepare("INSERT INTO integration_connections VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(v.id,v.organizationId,v.projectId,v.providerId,v.authMethod,v.environment,v.state,JSON.stringify(v.grantedScopes),v.ownerAccountId,v.maskedHint,v.health?JSON.stringify(v.health):null,v.lastSyncedAt,v.revision,v.createdAt,v.updatedAt,v.disconnectedAt,v.deletedAt).run(); }
  appendCredential(v: IntegrationCredentialRecord) { this.db.prepare("INSERT INTO integration_credentials VALUES(?,?,?,?,?,?,?)").bind(v.id,v.connectionId,v.recordVersion,v.encryptedEnvelope,v.keyVersion,v.createdAt,v.revokedAt).run(); }
  updateHealth(id:string,revision:number,state:IntegrationConnection["state"],health:ProviderHealth,now:number){return this.db.prepare("UPDATE integration_connections SET state=?,health_json=?,revision=revision+1,updated_at=? WHERE id=? AND revision=? AND deleted_at IS NULL").bind(state,JSON.stringify(health),now,id,revision).run().meta.changes===1;}
  disconnect(id:string,revision:number,now:number){return this.db.prepare("UPDATE integration_connections SET state='disconnected',revision=revision+1,disconnected_at=?,updated_at=? WHERE id=? AND revision=? AND deleted_at IS NULL").bind(now,now,id,revision).run().meta.changes===1;}
  revokeCredential(id:string,now:number){this.db.prepare("UPDATE integration_credentials SET revoked_at=COALESCE(revoked_at,?) WHERE id=?").bind(now,id).run();}
  deleteConnection(id:string,revision:number,now:number){return this.db.prepare("UPDATE integration_connections SET state='disconnected',revision=revision+1,disconnected_at=COALESCE(disconnected_at,?),deleted_at=?,updated_at=? WHERE id=? AND revision=? AND deleted_at IS NULL").bind(now,now,now,id,revision).run().meta.changes===1;}
  appendAudit(v:IntegrationAudit){this.db.prepare("INSERT INTO integration_audit_events VALUES(?,?,?,?,?,?,?,?,?,?)").bind(v.id,v.organizationId,v.projectId,v.actorId,v.action,v.connectionId,v.reason,v.correlationId,JSON.stringify(v.metadata),v.occurredAt).run();}
  private mapCredential(r:Row):IntegrationCredentialRecord{return{id:String(r.id),connectionId:String(r.connection_id),recordVersion:Number(r.record_version),encryptedEnvelope:String(r.encrypted_envelope),keyVersion:String(r.key_version),createdAt:Number(r.created_at),revokedAt:r.revoked_at===null?null:Number(r.revoked_at)};}
  private mapConnection(r:Row):IntegrationConnection{return{id:String(r.id),organizationId:String(r.organization_id),projectId:String(r.project_id),providerId:String(r.provider_id),authMethod:r.auth_method as IntegrationConnection["authMethod"],environment:r.environment as IntegrationConnection["environment"],state:r.state as IntegrationConnection["state"],grantedScopes:JSON.parse(String(r.granted_scopes_json)) as string[],ownerAccountId:String(r.owner_account_id),maskedHint:String(r.masked_hint),health:r.health_json===null?null:JSON.parse(String(r.health_json)) as ProviderHealth,lastSyncedAt:r.last_synced_at===null?null:Number(r.last_synced_at),revision:Number(r.revision),createdAt:Number(r.created_at),updatedAt:Number(r.updated_at),disconnectedAt:r.disconnected_at===null?null:Number(r.disconnected_at),deletedAt:r.deleted_at===null?null:Number(r.deleted_at)};}
}
