import type { AppDatabase } from "../../../lib/database";
import type { NotificationDelivery, NotificationPreference, NotificationRepository, StoredNotification } from "../../modules/notifications";

type Row=Record<string,unknown>;const bool=(v:unknown)=>Boolean(Number(v));const json=(v:unknown)=>JSON.parse(String(v)) as Record<string,unknown>;
export class SqliteNotificationRepository implements NotificationRepository{
  constructor(private readonly database:AppDatabase){}
  ensureSchema(){this.database.exec(`
    CREATE TABLE IF NOT EXISTS operations_notification_preferences(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES identity_organizations(id) ON DELETE CASCADE,account_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,notification_type TEXT NOT NULL,in_app_enabled INTEGER NOT NULL DEFAULT 1 CHECK(in_app_enabled IN (0,1)),email_enabled INTEGER NOT NULL DEFAULT 1 CHECK(email_enabled IN (0,1)),locale TEXT NOT NULL CHECK(locale IN ('zh-CN','en')),version INTEGER NOT NULL DEFAULT 1 CHECK(version>0),created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,UNIQUE(organization_id,account_id,notification_type));
    CREATE INDEX IF NOT EXISTS operations_notification_preferences_account_idx ON operations_notification_preferences(organization_id,account_id,notification_type);
    CREATE TABLE IF NOT EXISTS operations_notification_deliveries(id TEXT PRIMARY KEY,notification_id TEXT NOT NULL REFERENCES operations_notifications(id) ON DELETE CASCADE,organization_id TEXT NOT NULL,account_id TEXT NOT NULL,channel TEXT NOT NULL CHECK(channel IN ('in_app','email')),attempt_number INTEGER NOT NULL CHECK(attempt_number>0),state TEXT NOT NULL CHECK(state IN ('delivering','sent','retrying','failed','quarantined')),provider_reference TEXT,error_code TEXT,error_message TEXT,next_attempt_at INTEGER,started_at INTEGER NOT NULL,finished_at INTEGER,correlation_id TEXT NOT NULL,UNIQUE(notification_id,attempt_number));
    CREATE INDEX IF NOT EXISTS operations_notification_deliveries_retry_idx ON operations_notification_deliveries(state,next_attempt_at,notification_id);
  `);}
  transaction<T>(operation:()=>T){return this.database.transaction(operation);}
  preference(org:string,account:string,type:string){const row=this.database.prepare("SELECT * FROM operations_notification_preferences WHERE organization_id=? AND account_id=? AND notification_type=?").bind(org,account,type).first<Row>();return row?this.mapPreference(row):null;}
  preferences(org:string,account:string){return this.database.prepare("SELECT * FROM operations_notification_preferences WHERE organization_id=? AND account_id=? ORDER BY notification_type").bind(org,account).all<Row>().results.map(row=>this.mapPreference(row));}
  putPreference(v:NotificationPreference,expected:number|null){if(expected===0)return this.database.prepare("INSERT OR IGNORE INTO operations_notification_preferences(id,organization_id,account_id,notification_type,in_app_enabled,email_enabled,locale,version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),v.organizationId,v.accountId,v.notificationType,v.inAppEnabled?1:0,v.emailEnabled?1:0,v.locale,v.version,v.createdAt,v.updatedAt).run().meta.changes===1;return this.database.prepare("UPDATE operations_notification_preferences SET in_app_enabled=?,email_enabled=?,locale=?,version=?,updated_at=? WHERE organization_id=? AND account_id=? AND notification_type=? AND version=?").bind(v.inAppEnabled?1:0,v.emailEnabled?1:0,v.locale,v.version,v.updatedAt,v.organizationId,v.accountId,v.notificationType,expected).run().meta.changes===1;}
  notification(org:string,account:string,id:string){const row=this.database.prepare("SELECT * FROM operations_notifications WHERE organization_id=? AND account_id=? AND id=?").bind(org,account,id).first<Row>();return row?this.mapNotification(row):null;}
  putNotification(v:StoredNotification){return this.database.prepare(`INSERT OR IGNORE INTO operations_notifications(id,organization_id,account_id,project_id,task_id,channel,notification_type,locale,title_key,body_key,arguments_json,state,idempotency_key,available_at,sent_at,read_at,last_error,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(v.id,v.organizationId,v.accountId,v.projectId,v.taskId,v.channel,v.notificationType,v.locale,v.titleKey,v.bodyKey,JSON.stringify(v.arguments),v.state,v.idempotencyKey,v.availableAt,v.sentAt,v.readAt,v.lastError,v.createdAt,v.updatedAt).run().meta.changes===1;}
  list(org:string,account:string,limit:number){return this.database.prepare("SELECT * FROM operations_notifications WHERE organization_id=? AND account_id=? ORDER BY created_at DESC,id DESC LIMIT ?").bind(org,account,Math.max(1,Math.min(200,limit))).all<Row>().results.map(row=>this.mapNotification(row));}
  claim(now:number,limit:number){return this.database.prepare("SELECT * FROM operations_notifications WHERE channel='email' AND state='pending' AND available_at<=? ORDER BY available_at,id LIMIT ?").bind(now,Math.max(1,Math.min(100,limit))).all<Row>().results.map(row=>this.mapNotification(row));}
  beginDelivery(v:NotificationDelivery){return this.transaction(()=>{const count=this.database.prepare("SELECT COALESCE(MAX(attempt_number),0)+1 n FROM operations_notification_deliveries WHERE notification_id=?").bind(v.notificationId).first<{n:number}>()?.n??1;return this.database.prepare(`INSERT OR IGNORE INTO operations_notification_deliveries(id,notification_id,organization_id,account_id,channel,attempt_number,state,started_at,correlation_id)
    SELECT ?,?,?,?,?,?,?,?,? WHERE EXISTS (SELECT 1 FROM operations_notifications WHERE id=? AND organization_id=? AND account_id=? AND channel='email' AND state='pending') AND NOT EXISTS (SELECT 1 FROM operations_notification_deliveries WHERE notification_id=? AND state='delivering')`).bind(v.id,v.notificationId,v.organizationId,v.accountId,v.channel,count,v.state,v.startedAt,v.correlationId,v.notificationId,v.organizationId,v.accountId,v.notificationId).run().meta.changes===1;});}
  finishDelivery(v:{deliveryId:string;notificationId:string;state:NotificationDelivery["state"];providerReference:string|null;errorCode:string|null;errorMessage:string|null;nextAttemptAt:number|null;now:number}){this.transaction(()=>{this.database.prepare("UPDATE operations_notification_deliveries SET state=?,provider_reference=?,error_code=?,error_message=?,next_attempt_at=?,finished_at=? WHERE id=? AND state='delivering'").bind(v.state,v.providerReference,v.errorCode,v.errorMessage,v.nextAttemptAt,v.now,v.deliveryId).run();const notificationState=v.state==="sent"?"sent":v.state==="retrying"?"pending":"failed";this.database.prepare("UPDATE operations_notifications SET state=?,available_at=COALESCE(?,available_at),sent_at=CASE WHEN ?='sent' THEN ? ELSE sent_at END,last_error=?,updated_at=? WHERE id=?").bind(notificationState,v.nextAttemptAt,notificationState,v.now,v.errorMessage,v.now,v.notificationId).run();});}
  markRead(org:string,account:string,id:string,now:number){return this.database.prepare("UPDATE operations_notifications SET state='read',read_at=?,updated_at=? WHERE organization_id=? AND account_id=? AND id=? AND state IN ('pending','sent','read')").bind(now,now,org,account,id).run().meta.changes===1;}
  private mapPreference(r:Row):NotificationPreference{return{organizationId:String(r.organization_id),accountId:String(r.account_id),notificationType:String(r.notification_type),inAppEnabled:bool(r.in_app_enabled),emailEnabled:bool(r.email_enabled),locale:r.locale as NotificationPreference["locale"],version:Number(r.version),createdAt:Number(r.created_at),updatedAt:Number(r.updated_at)};}
  private mapNotification(r:Row):StoredNotification{return{id:String(r.id),organizationId:String(r.organization_id),accountId:String(r.account_id),projectId:r.project_id===null?null:String(r.project_id),taskId:r.task_id===null?null:String(r.task_id),channel:r.channel as StoredNotification["channel"],notificationType:String(r.notification_type),locale:r.locale as StoredNotification["locale"],titleKey:String(r.title_key),bodyKey:String(r.body_key),arguments:json(r.arguments_json),state:r.state as StoredNotification["state"],idempotencyKey:String(r.idempotency_key),availableAt:Number(r.available_at),sentAt:r.sent_at===null?null:Number(r.sent_at),readAt:r.read_at===null?null:Number(r.read_at),lastError:r.last_error===null?null:String(r.last_error),createdAt:Number(r.created_at),updatedAt:Number(r.updated_at)};}
}
