import type{AppDatabase}from"../../../lib/database";
import type{ElevatedAction,OperatorAdministrationRepository,OperatorAssignment}from"../../modules/operations/administration";
type Row=Record<string,unknown>;
export class SqliteOperatorAdministrationRepository implements OperatorAdministrationRepository{
 constructor(private readonly db:AppDatabase){}
 ensureSchema(){this.db.exec(`CREATE TABLE IF NOT EXISTS operations_operator_assignments(id TEXT PRIMARY KEY,account_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,role TEXT NOT NULL CHECK(role IN('platform_admin','support','finance','operations','security')),organization_scopes TEXT NOT NULL CHECK(json_valid(organization_scopes)),project_scopes TEXT NOT NULL CHECK(json_valid(project_scopes)),active INTEGER NOT NULL CHECK(active IN(0,1)),granted_by_account_id TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,granted_at INTEGER NOT NULL,revoked_at INTEGER);CREATE INDEX IF NOT EXISTS operator_assignment_account_idx ON operations_operator_assignments(account_id,active,role);CREATE TABLE IF NOT EXISTS operations_elevated_actions(id TEXT PRIMARY KEY,actor_account_id TEXT NOT NULL,actor_role TEXT NOT NULL,permission TEXT NOT NULL,organization_id TEXT,project_id TEXT,target_type TEXT NOT NULL,target_id TEXT,reason TEXT,outcome TEXT NOT NULL CHECK(outcome IN('success','denied','failed')),correlation_id TEXT NOT NULL,metadata_json TEXT NOT NULL CHECK(json_valid(metadata_json)),occurred_at INTEGER NOT NULL);CREATE INDEX IF NOT EXISTS elevated_action_scope_idx ON operations_elevated_actions(organization_id,occurred_at DESC,id);CREATE INDEX IF NOT EXISTS elevated_action_correlation_idx ON operations_elevated_actions(correlation_id,occurred_at,id);CREATE TRIGGER IF NOT EXISTS elevated_actions_no_update BEFORE UPDATE ON operations_elevated_actions BEGIN SELECT RAISE(ABORT,'ELEVATED_ACTIONS_APPEND_ONLY');END;CREATE TRIGGER IF NOT EXISTS elevated_actions_no_delete BEFORE DELETE ON operations_elevated_actions BEGIN SELECT RAISE(ABORT,'ELEVATED_ACTIONS_APPEND_ONLY');END;`);}
 assignments(accountId:string){return this.db.prepare("SELECT * FROM operations_operator_assignments WHERE account_id=? AND active=1 AND revoked_at IS NULL ORDER BY granted_at DESC").bind(accountId).all<Row>().results.map(row=>({id:String(row.id),accountId:String(row.account_id),role:row.role as OperatorAssignment["role"],organizationScopes:JSON.parse(String(row.organization_scopes)),projectScopes:JSON.parse(String(row.project_scopes)),active:Boolean(row.active),grantedByAccountId:String(row.granted_by_account_id),grantedAt:Number(row.granted_at),revokedAt:row.revoked_at===null?null:Number(row.revoked_at)}));}
 appendAction(value:ElevatedAction){this.db.prepare("INSERT INTO operations_elevated_actions VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(value.id,value.actorAccountId,value.actorRole,value.permission,value.organizationId,value.projectId,value.targetType,value.targetId,value.reason,value.outcome,value.correlationId,JSON.stringify(value.metadata),value.occurredAt).run();}
}
