import type{AppDatabase}from"../../../lib/database";
import type{PrivacyRepository,PrivacyRequest,RetentionPolicy}from"../../modules/operations/privacy";
type Row=Record<string,unknown>;
export class SqlitePrivacyRepository implements PrivacyRepository{
 constructor(private readonly db:AppDatabase){this.ensureSchema();}
 private ensureSchema(){this.db.exec(`
 CREATE TABLE IF NOT EXISTS operations_retention_policies(organization_id TEXT PRIMARY KEY,default_days INTEGER NOT NULL,artifact_days INTEGER NOT NULL,audit_days INTEGER NOT NULL,legal_hold INTEGER NOT NULL CHECK(legal_hold IN(0,1)),legal_hold_reason TEXT,updated_by_account_id TEXT NOT NULL,updated_at INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS operations_privacy_requests(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,account_id TEXT NOT NULL,project_id TEXT,type TEXT NOT NULL,state TEXT NOT NULL,reason TEXT NOT NULL,approval_reference TEXT,artifact_id TEXT,correlation_id TEXT NOT NULL,requested_at INTEGER NOT NULL,completed_at INTEGER);
 CREATE INDEX IF NOT EXISTS privacy_request_scope_idx ON operations_privacy_requests(organization_id,state,requested_at DESC);
 CREATE TABLE IF NOT EXISTS operations_privacy_exports(id TEXT PRIMARY KEY,request_id TEXT NOT NULL UNIQUE REFERENCES operations_privacy_requests(id),organization_id TEXT NOT NULL,object_key TEXT NOT NULL UNIQUE,sha256 TEXT NOT NULL,size_bytes INTEGER NOT NULL,expires_at INTEGER NOT NULL,created_at INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS operations_artifact_expirations(artifact_id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,expired_at INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS operations_privacy_audit(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,action TEXT NOT NULL,target_id TEXT,correlation_id TEXT NOT NULL,occurred_at INTEGER NOT NULL);
 CREATE TRIGGER IF NOT EXISTS privacy_audit_no_update BEFORE UPDATE ON operations_privacy_audit BEGIN SELECT RAISE(ABORT,'PRIVACY_AUDIT_APPEND_ONLY');END;
 CREATE TRIGGER IF NOT EXISTS privacy_audit_no_delete BEFORE DELETE ON operations_privacy_audit BEGIN SELECT RAISE(ABORT,'PRIVACY_AUDIT_APPEND_ONLY');END;`);}
 private audit(org:string,action:string,target:string|null,correlation:string,at:number){this.db.prepare("INSERT INTO operations_privacy_audit VALUES(?,?,?,?,?,?)").bind(crypto.randomUUID(),org,action,target,correlation,at).run();}
 policy(org:string){const r=this.db.prepare("SELECT * FROM operations_retention_policies WHERE organization_id=?").bind(org).first<Row>();return r?{organizationId:String(r.organization_id),defaultDays:Number(r.default_days),artifactDays:Number(r.artifact_days),auditDays:Number(r.audit_days),legalHold:Boolean(r.legal_hold),legalHoldReason:r.legal_hold_reason===null?null:String(r.legal_hold_reason),updatedByAccountId:String(r.updated_by_account_id),updatedAt:Number(r.updated_at)}:null;}
 putPolicy(v:RetentionPolicy){this.db.prepare("INSERT INTO operations_retention_policies VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(organization_id) DO UPDATE SET default_days=excluded.default_days,artifact_days=excluded.artifact_days,audit_days=excluded.audit_days,legal_hold=excluded.legal_hold,legal_hold_reason=excluded.legal_hold_reason,updated_by_account_id=excluded.updated_by_account_id,updated_at=excluded.updated_at").bind(v.organizationId,v.defaultDays,v.artifactDays,v.auditDays,v.legalHold?1:0,v.legalHoldReason,v.updatedByAccountId,v.updatedAt).run();this.audit(v.organizationId,"retention.updated",v.organizationId,`retention:${v.organizationId}:${v.updatedAt}`,v.updatedAt);}
 request(v:PrivacyRequest){this.db.prepare("INSERT INTO operations_privacy_requests VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").bind(v.id,v.organizationId,v.accountId,v.projectId,v.type,v.state,v.reason,v.approvalReference,v.artifactId,v.correlationId,v.requestedAt,v.completedAt).run();this.audit(v.organizationId,`privacy.${v.type}.requested`,v.id,v.correlationId,v.requestedAt);}
 requestById(org:string,id:string){const r=this.db.prepare("SELECT * FROM operations_privacy_requests WHERE organization_id=? AND id=?").bind(org,id).first<Row>();return r?this.map(r):null;}
 updateRequest(v:PrivacyRequest){this.db.prepare("UPDATE operations_privacy_requests SET state=?,approval_reference=?,artifact_id=?,completed_at=? WHERE organization_id=? AND id=?").bind(v.state,v.approvalReference,v.artifactId,v.completedAt,v.organizationId,v.id).run();this.audit(v.organizationId,`privacy.${v.type}.${v.state}`,v.id,v.correlationId,v.completedAt??v.requestedAt);}
 exportBundle(org:string){const organization=this.db.prepare("SELECT id,name,slug,status,created_at createdAt FROM identity_organizations WHERE id=?").bind(org).first()??{},members=this.db.prepare("SELECT m.user_id userId,u.email,u.name,u.status,r.role_key role,m.joined_at joinedAt FROM identity_memberships m JOIN users u ON u.id=m.user_id JOIN identity_roles r ON r.id=m.role_id WHERE m.organization_id=? ORDER BY m.created_at").bind(org).all().results,projects=this.db.prepare("SELECT id,name,site_url siteUrl,host,market,language,timezone,status,created_at createdAt FROM projects WHERE organization_id=? ORDER BY created_at").bind(org).all().results,ledger=this.db.prepare("SELECT id,project_id projectId,entry_type entryType,unit,amount,task_id taskId,correlation_id correlationId,created_at createdAt FROM commerce_credit_ledger WHERE organization_id=? ORDER BY created_at").bind(org).all().results,tasks=this.db.prepare("SELECT id,project_id projectId,task_type taskType,capability,state,progress,correlation_id correlationId,created_at createdAt,completed_at completedAt FROM execution_tasks WHERE organization_id=? ORDER BY created_at").bind(org).all().results;return{organization,members,projects,ledger,tasks};}
 putExport(v:{id:string;requestId:string;organizationId:string;objectKey:string;sha256:string;sizeBytes:number;expiresAt:number;createdAt:number}){this.db.prepare("INSERT INTO operations_privacy_exports VALUES(?,?,?,?,?,?,?,?)").bind(v.id,v.requestId,v.organizationId,v.objectKey,v.sha256,v.sizeBytes,v.expiresAt,v.createdAt).run();}
 eraseCredentials(org:string,at:number){const changed=this.db.prepare("UPDATE integration_credentials SET encrypted_envelope='erased:v1',key_version='erased',revoked_at=COALESCE(revoked_at,?) WHERE connection_id IN(SELECT id FROM integration_connections WHERE organization_id=?)").bind(at,org).run().meta.changes;this.db.prepare("UPDATE integration_connections SET state='disconnected',disconnected_at=COALESCE(disconnected_at,?),updated_at=? WHERE organization_id=? AND deleted_at IS NULL").bind(at,at,org).run();return changed;}
 tombstoneProject(org:string,id:string,at:number){return this.db.prepare("UPDATE projects SET status='pending_deletion',deletion_requested_at=?,updated_at=?,version=version+1 WHERE organization_id=? AND id=? AND status!='pending_deletion'").bind(at,at,org,id).run().meta.changes===1;}
 tombstoneAccount(org:string,id:string,at:number){const changed=this.db.prepare("UPDATE users SET status='suspended',updated_at=? WHERE id=? AND EXISTS(SELECT 1 FROM identity_memberships WHERE organization_id=? AND user_id=users.id)").bind(at,id,org).run().meta.changes===1;if(changed)this.db.prepare("DELETE FROM sessions WHERE user_id=?").bind(id).run();return changed;}
 expiredArtifacts(at:number,limit:number){return this.db.prepare("SELECT a.id,a.organization_id organizationId,a.object_key objectKey FROM execution_artifacts a WHERE a.expires_at IS NOT NULL AND a.expires_at<=? AND NOT EXISTS(SELECT 1 FROM operations_artifact_expirations e WHERE e.artifact_id=a.id) ORDER BY a.expires_at,a.id LIMIT ?").bind(at,Math.max(1,Math.min(500,limit))).all<{id:string;organizationId:string;objectKey:string}>().results;}
 recordArtifactExpiry(id:string,org:string,at:number){this.db.prepare("INSERT OR IGNORE INTO operations_artifact_expirations VALUES(?,?,?)").bind(id,org,at).run();this.audit(org,"artifact.expired",id,`artifact:expiry:${id}`,at);}
 private map(r:Row):PrivacyRequest{return{id:String(r.id),organizationId:String(r.organization_id),accountId:String(r.account_id),projectId:r.project_id===null?null:String(r.project_id),type:r.type as PrivacyRequest["type"],state:r.state as PrivacyRequest["state"],reason:String(r.reason),approvalReference:r.approval_reference===null?null:String(r.approval_reference),artifactId:r.artifact_id===null?null:String(r.artifact_id),correlationId:String(r.correlation_id),requestedAt:Number(r.requested_at),completedAt:r.completed_at===null?null:Number(r.completed_at)}}
}
