import type { AppDatabase } from "../../../lib/database";
import type { ArtifactRecord, ExecutionTask } from "../../modules/execution";
import type { LegacyTaskItem, WorkspaceCatalogRepository } from "../../modules/execution/workspace-catalog";

type Row=Record<string,unknown>;const parse=(value:unknown)=>JSON.parse(String(value)) as Record<string,unknown>;
export class SqliteWorkspaceCatalogRepository implements WorkspaceCatalogRepository{
  constructor(private readonly database:AppDatabase){}
  executionTasks(org:string,project:string){return this.database.prepare(`SELECT t.*,COALESCE((SELECT MAX(priority) FROM execution_jobs j WHERE j.organization_id=t.organization_id AND j.task_id=t.id),50) priority,(SELECT COUNT(*) FROM execution_artifacts a WHERE a.organization_id=t.organization_id AND a.task_id=t.id) artifact_count FROM execution_tasks t WHERE t.organization_id=? AND t.project_id=? ORDER BY t.created_at DESC,t.id`).bind(org,project).all<Row>().results.map(row=>({...this.task(row),priority:Number(row.priority),artifactCount:Number(row.artifact_count)}));}
  legacyTasks(org:string,project:string){return this.database.prepare(`SELECT t.id,t.type,t.title,t.description,t.priority,t.status,t.created_at,f.url,f.evidence,f.category,f.severity FROM seo_tasks t JOIN projects p ON p.id=t.project_id LEFT JOIN findings f ON f.id=t.finding_id WHERE p.organization_id=? AND t.project_id=? ORDER BY t.priority DESC,t.created_at DESC`).bind(org,project).all<Row>().results.map(row=>({id:String(row.id),type:String(row.type),title:String(row.title),description:String(row.description),priority:Number(row.priority),status:String(row.status),createdAt:Number(row.created_at),url:row.url?String(row.url):undefined,evidence:row.evidence?String(row.evidence):undefined,category:row.category?String(row.category):undefined,severity:row.severity?String(row.severity):undefined} satisfies LegacyTaskItem));}
  artifacts(org:string,project:string,now:number){return this.database.prepare("SELECT * FROM execution_artifacts WHERE organization_id=? AND project_id=? AND scan_state='clean' AND (expires_at IS NULL OR expires_at>?) ORDER BY created_at DESC,id DESC").bind(org,project,now).all<Row>().results.map(row=>this.artifact(row));}
  private task(row:Row):ExecutionTask{return{id:String(row.id),organizationId:String(row.organization_id),projectId:String(row.project_id),requestedByAccountId:row.requested_by_account_id===null?null:String(row.requested_by_account_id),triggerType:row.trigger_type as ExecutionTask["triggerType"],taskType:String(row.task_type),capability:String(row.capability),state:row.state as ExecutionTask["state"],progress:Number(row.progress),cancellable:Boolean(Number(row.cancellable)),input:parse(row.input_json),locale:row.locale as ExecutionTask["locale"],idempotencyKey:String(row.idempotency_key),correlationId:String(row.correlation_id),version:Number(row.version),createdAt:Number(row.created_at),updatedAt:Number(row.updated_at),startedAt:row.started_at===null?null:Number(row.started_at),completedAt:row.completed_at===null?null:Number(row.completed_at)};}
  private artifact(row:Row):ArtifactRecord{return{id:String(row.id),organizationId:String(row.organization_id),projectId:String(row.project_id),taskId:String(row.task_id),attemptId:row.attempt_id===null?null:String(row.attempt_id),kind:String(row.kind),objectKey:String(row.object_key),sha256:String(row.sha256),mimeType:String(row.mime_type),sizeBytes:Number(row.size_bytes),scanState:row.scan_state as ArtifactRecord["scanState"],retentionClass:String(row.retention_class),expiresAt:row.expires_at===null?null:Number(row.expires_at),provenance:parse(row.provenance_json),idempotencyKey:String(row.idempotency_key),createdAt:Number(row.created_at)};}
}
