"use client";
import { useCallback,useEffect,useState } from "react";
import { CheckCircle,Database,FloppyDisk,Key,LockKey,Trash,WarningCircle } from "@phosphor-icons/react";

type Source={provider:string;name:string;description:string;enabled:boolean;configured:boolean;configuredFields:number;totalFields:number;lastTestStatus:string|null;lastTestedAt:number|null;lastError:string|null;fields:{key:string;label:string;required:boolean;configured:boolean}[]};

export function DataSourceSettings(){
 const [sources,setSources]=useState<Source[]>([]),[values,setValues]=useState<Record<string,Record<string,string>>>({}),[busy,setBusy]=useState(""),[message,setMessage]=useState(""),[encryptionReady,setEncryptionReady]=useState(false);
 const load=useCallback(async()=>{const response=await fetch("/api/admin/data-sources",{cache:"no-store"});const data=await response.json();if(response.ok){setSources(data.sources);setEncryptionReady(data.encryptionReady)}else setMessage(data.error||"读取数据源失败")},[]);
 useEffect(()=>{const timer=setTimeout(()=>load(),0);return()=>clearTimeout(timer)},[load]);
 const save=async(source:Source,enabled:boolean)=>{setBusy(source.provider);setMessage("");const response=await fetch("/api/admin/data-sources",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({provider:source.provider,enabled,values:values[source.provider]||{}})});const data=await response.json();setBusy("");if(!response.ok)return setMessage(data.error||"保存失败");setValues(current=>({...current,[source.provider]:{}}));setMessage(`${source.name} 已保存${enabled?"并启用":""}`);await load()};
 const clear=async(source:Source)=>{if(!confirm(`确定清除 ${source.name} 的平台配置吗？`))return;setBusy(source.provider);const response=await fetch("/api/admin/data-sources",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({provider:source.provider})});setBusy("");if(!response.ok){const data=await response.json();return setMessage(data.error||"清除失败")}setMessage(`${source.name} 配置已清除`);await load()};
 return <section className="admin-panel data-source-admin"><div className="admin-panel-title"><div><h2>平台数据源</h2><p>密钥仅在服务端加密保存。用户工作台不会接触或展示这些配置。</p></div><span className={encryptionReady?"secure-ready":"secure-warning"}>{encryptionReady?<><LockKey/>加密存储已就绪</>:<><WarningCircle/>需要配置加密密钥</>}</span></div>
  {message&&<div className="data-source-message">{message}</div>}
  <div className="data-source-grid">{sources.map(source=><article key={source.provider} className={source.enabled?"enabled":""}><header><span><Database/></span><div><strong>{source.name}</strong><p>{source.description}</p></div><em>{source.enabled?"运行中":source.configured?"已配置":"未配置"}</em></header><div className="data-source-fields">{source.fields.map(field=><label key={field.key}><span>{field.label}{field.required&&" *"}</span><div><Key/><input type="password" autoComplete="new-password" value={values[source.provider]?.[field.key]||""} onChange={event=>setValues(current=>({...current,[source.provider]:{...current[source.provider],[field.key]:event.target.value}}))} placeholder={source.configured?"已安全保存；留空保持不变":"输入后将加密保存"}/></div></label>)}</div><footer><small>{source.configuredFields}/{source.totalFields} 个配置项已保存</small><div>{source.configured&&<button className="danger-ghost" onClick={()=>clear(source)} disabled={busy===source.provider}><Trash/>清除</button>}<button onClick={()=>save(source,false)} disabled={busy===source.provider||!encryptionReady}><FloppyDisk/>仅保存</button><button className="enable-source" onClick={()=>save(source,true)} disabled={busy===source.provider||!encryptionReady}><CheckCircle/>保存并启用</button></div></footer></article>)}</div>
 </section>;
}
