"use client";

import { useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { SquaresFour, Buildings, Users, Queue, Pulse, Plug, Receipt, ShieldCheck, Gear, MagnifyingGlass, Bell, CaretDown, ArrowUp, ArrowDown, CheckCircle, Warning, Clock, ArrowClockwise, DotsThree, UserCircle, DownloadSimple } from "@phosphor-icons/react";
import { AreaChart, Area, ResponsiveContainer, XAxis, Tooltip } from "recharts";
import { CommercialUsers } from "./CommercialUsers";

const data=[42,55,51,68,74,86,92,88,104,119,126,138].map((v,i)=>({x:`${i+1}日`,v}));
const tenants=[["offersteady.com","Ethan","Pro","运行中","1,248","96%"],["mianshiwen.cn","OneShow 团队","Business","运行中","3,912","98%"],["resume-boost.ai","Lucas","Pro","需关注","842","87%"],["interviewpro.io","Sophia","Starter","运行中","512","94%"],["codecraft.dev","Mason","Business","已暂停","2,109","—"]];

export default function AdminPage(){
 const [filter,setFilter]=useState(""); const [toast,setToast]=useState(""); const notify=(x:string)=>{setToast(x);setTimeout(()=>setToast(""),2200)};
 return <main className="admin-shell"><aside className="admin-sidebar"><Link href="/"><Image src="/brand/oneshowseo.png" alt="OneShowSEO" width={164} height={42} unoptimized/></Link><span className="admin-badge">ADMIN CONSOLE</span><nav>{[[SquaresFour,"总览"],[Buildings,"租户管理"],[Users,"用户与权限"],[Queue,"任务队列"],[Pulse,"系统监控"],[Plug,"集成管理"],[Receipt,"订阅与账单"],[ShieldCheck,"审计日志"],[Gear,"系统设置"]].map(([Icon,label],i)=><button className={i===0?"active":""} key={label as string} onClick={()=>notify(`${label}已选择`)}><Icon/>{label as string}</button>)}</nav><div className="admin-user"><UserCircle weight="fill"/><div><strong>Yulong Li</strong><small>超级管理员</small></div><CaretDown/></div></aside>
 <section className="admin-main"><header><div className="admin-search"><MagnifyingGlass/><input placeholder="搜索租户、用户或任务 ID"/></div><div><button><Bell/><b>5</b></button><span>生产环境</span><UserCircle weight="fill"/></div></header><div className="admin-inner"><div className="admin-title"><div><span>平台总览</span><h1>OneShowSEO 运营中心</h1><p>统一查看客户、自动化任务、数据连接与平台健康状态。</p></div><button onClick={()=>notify("运营报表已导出")}><DownloadSimple/>导出运营报表</button></div>
 <div className="admin-kpis">{[["活跃租户","2,418","12.6%","up"],["今日任务","18,642","8.3%","up"],["任务成功率","96.8%","1.4%","up"],["待处理异常","27","6","down"]].map(x=><article key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong><em className={x[3]}>{x[3]==="up"?<ArrowUp/>:<ArrowDown/>}{x[2]}</em><small>较昨日</small></article>)}</div>
 <div className="admin-grid"><section className="admin-panel usage-chart"><div className="admin-panel-title"><div><h2>平台任务执行量</h2><p>近 12 天自动化任务趋势</p></div><button>12 天 <CaretDown/></button></div><div><ResponsiveContainer><AreaChart data={data}><XAxis dataKey="x" axisLine={false} tickLine={false} fontSize={11}/><Tooltip/><Area dataKey="v" type="monotone" stroke="#5b5cf6" fill="#e9eaff" strokeWidth={3}/></AreaChart></ResponsiveContainer></div></section><section className="admin-panel system-health"><div className="admin-panel-title"><div><h2>系统健康</h2><p>核心服务实时状态</p></div><span>全部正常</span></div>{[["抓取与渲染服务","99.98%","正常"],["AI 任务调度","99.94%","正常"],["搜索数据采集","98.72%","延迟"],["发布与验证服务","99.91%","正常"]].map(x=><div className="service-row" key={x[0]}><i className={x[2]==="正常"?"good":"warn"}/><strong>{x[0]}</strong><span>{x[1]}</span><em>{x[2]}</em></div>)}</section></div>
 <CommercialUsers notify={notify}/>
 <section className="admin-panel tenant-table"><div className="table-toolbar"><div><h2>租户运行状态</h2><p>查看客户项目的套餐、使用量和自动化状态</p></div><label><MagnifyingGlass/><input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="搜索域名"/></label><button>全部状态 <CaretDown/></button></div><div className="table-head"><span>项目</span><span>负责人</span><span>套餐</span><span>状态</span><span>本月任务</span><span>成功率</span><span/></div>{tenants.filter(x=>x[0].includes(filter)).map(x=><div className="tenant-row" key={x[0]}><strong>{x[0]}<small>最近运行 8 分钟前</small></strong><span>{x[1]}</span><span>{x[2]}</span><em className={x[3]==="运行中"?"running":x[3]==="需关注"?"attention":"paused"}>{x[3]}</em><span>{x[4]}</span><span>{x[5]}</span><button onClick={()=>notify(`${x[0]} 操作菜单已打开`)}><DotsThree/></button></div>)}</section>
 <div className="admin-grid bottom"><section className="admin-panel queue-panel"><div className="admin-panel-title"><div><h2>任务队列</h2><p>当前调度与异常重试</p></div><Link href="/workspace">查看工作台</Link></div>{[[CheckCircle,"已完成","15,834","success"],[Clock,"执行中","326","active"],[Warning,"等待审批","118","warn"],[ArrowClockwise,"重试队列","23","danger"]].map(([Icon,label,count,state])=><button key={label as string} onClick={()=>notify(`${label}队列已打开`)}><Icon className={state as string}/><span>{label as string}</span><strong>{count as string}</strong></button>)}</section><section className="admin-panel alerts"><div className="admin-panel-title"><div><h2>近期告警</h2><p>需要运营团队关注</p></div><a>全部告警</a></div><p><Warning/><span><strong>DataForSEO 配额使用 82%</strong><small>建议在 3 天内调整套餐或限流规则</small></span><time>12 分钟前</time></p><p><Clock/><span><strong>3 个租户数据采集延迟</strong><small>Google Search Console 同步超过 30 分钟</small></span><time>28 分钟前</time></p></section></div>
 </div></section>{toast&&<div className="toast"><CheckCircle weight="fill"/>{toast}</div>}</main>
}
