import{NextResponse}from"next/server";import{getCurrentUser}from"../../../../lib/auth";import{authorizeOperator,operatorDashboardSnapshot}from"../../../../lib/operator-administration";import{observabilityService}from"../../../../lib/observability";import{requestCorrelationId}from"../../../../platform/modules/developer/rest-contract";import{OperatorAuthorizationError,operatorPermissions}from"../../../../platform/modules/operations/administration";
import{getDatabase}from"../../../../lib/auth";import{SqliteFeatureFlagRepository}from"../../../../platform/adapters/sqlite/feature-flag-repository";
export async function GET(request:Request){const started=Date.now(),correlationId=requestCorrelationId(request),user=await getCurrentUser();if(!user){observabilityService().record({kind:"http",service:"admin",operation:"operations.get",outcome:"failure",durationMs:Date.now()-started,errorCode:"UNAUTHENTICATED",organizationId:null,projectId:null,correlationId,parentSpanId:null});return NextResponse.json({error:"请先登录"},{status:401,headers:{"x-correlation-id":correlationId}});}try{const authorization=await authorizeOperator(user,"tenants.read"),query=new URL(request.url).searchParams.get("q")??"",snapshot=await operatorDashboardSnapshot(query,operatorPermissions(authorization.role));observabilityService().record({kind:"http",service:"admin",operation:"operations.get",outcome:"success",durationMs:Date.now()-started,errorCode:null,organizationId:null,projectId:null,correlationId,parentSpanId:null,attributes:{role:authorization.role}});return NextResponse.json(snapshot,{headers:{"cache-control":"private, no-store","x-correlation-id":correlationId}});}catch(error){observabilityService().record({kind:"http",service:"admin",operation:"operations.get",outcome:"failure",durationMs:Date.now()-started,errorCode:error instanceof OperatorAuthorizationError?error.code:"INTERNAL_ERROR",organizationId:null,projectId:null,correlationId,parentSpanId:null});if(error instanceof OperatorAuthorizationError)return NextResponse.json({error:"无权访问后台运营数据"},{status:403,headers:{"x-correlation-id":correlationId}});throw error;}}

export async function POST(request:Request){const user=await getCurrentUser();if(!user)return NextResponse.json({error:"请先登录"},{status:401});const body=await request.json().catch(()=>null) as Record<string,unknown>|null,action=String(body?.action||""),reason=String(body?.reason||""),targetId=String(body?.targetId||""),correlationId=requestCorrelationId(request),db=getDatabase();try{
 if(action==="recover_job"){const authorization=await authorizeOperator(user,"jobs.recover",{reason,targetType:"execution_job",targetId,correlationId});const job=db.prepare("SELECT task_id taskId,state FROM execution_jobs WHERE id=?").bind(targetId).first<{taskId:string;state:string}>();if(!job)return NextResponse.json({error:"任务不存在"},{status:404});if(!["failed","quarantined"].includes(job.state))return NextResponse.json({error:"只有失败或隔离任务可以恢复"},{status:409});const now=Math.floor(Date.now()/1000);db.transaction(()=>{db.prepare("UPDATE execution_jobs SET state='queued',attempt_count=0,available_at=?,completed_at=NULL,updated_at=? WHERE id=?").bind(now,now,targetId).run();db.prepare("UPDATE execution_tasks SET state='queued',updated_at=? WHERE id=? AND state IN ('failed','quarantined')").bind(now,job.taskId).run();});authorization.record("success",{previousState:job.state});return NextResponse.json({ok:true});}
 if(action==="update_flag"){const key=String(body?.key||"").trim(),enabled=body?.enabled===true;if(!key)return NextResponse.json({error:"缺少功能开关键"},{status:400});const authorization=await authorizeOperator(user,"flags.manage",{reason,targetType:"feature_flag",targetId:key,correlationId});const flag=await new SqliteFeatureFlagRepository(db).upsert({key,enabled,scope:"global",scopeValue:"*",reason,actorId:user.id,correlationId});authorization.record("success",{enabled,version:flag.version});return NextResponse.json({ok:true,flag});}
 if(action==="incident"){const state=String(body?.state||"open"),severity=String(body?.severity||"medium"),title=String(body?.title||"").trim();if(!["open","investigating","monitoring","resolved"].includes(state)||!["low","medium","high","critical"].includes(severity)||title.length<3)return NextResponse.json({error:"事故信息无效"},{status:400});const id=targetId||crypto.randomUUID(),authorization=await authorizeOperator(user,"incidents.manage",{reason,targetType:"incident",targetId:id,correlationId}),now=Math.floor(Date.now()/1000);db.prepare(`INSERT INTO operations_incidents(id,severity,state,title,organization_id,correlation_id,owner_account_id,created_at,updated_at,resolved_at) VALUES(?,?,?,?,NULL,?,?,?, ?,?) ON CONFLICT(id) DO UPDATE SET severity=excluded.severity,state=excluded.state,title=excluded.title,owner_account_id=excluded.owner_account_id,updated_at=excluded.updated_at,resolved_at=excluded.resolved_at`).bind(id,severity,state,title,correlationId,user.id,now,now,state==="resolved"?now:null).run();authorization.record("success",{state,severity});return NextResponse.json({ok:true,id});}
 return NextResponse.json({error:"不支持的后台操作"},{status:400});
 }catch(error){if(error instanceof OperatorAuthorizationError)return NextResponse.json({error:error.message,code:error.code},{status:403});throw error;}}
