import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { AgentManifestError, validateAgentManifest } from "../platform/modules/agents/manifest";

const valid=()=>({schemaVersion:"1",key:"seo.audit",version:"1.2.0",metadata:{"zh-CN":{name:"SEO 审计",description:"检查网站技术与内容证据"},en:{name:"SEO Audit",description:"Inspect technical and content evidence"}},capabilities:[{key:"audit.run",input:{type:"object",additionalProperties:false,properties:{url:{type:"string",format:"uri"}},required:["url"]},output:{type:"object",properties:{score:{type:"integer"}}},events:[{key:"audit.progress",schema:{type:"object",properties:{progress:{type:"integer"}}}}],permissions:["audits.run","reports.read"]}],dependencies:{providers:["public.crawl"],agents:[{key:"research.agent",versionRange:"^1.0.0"}]},entitlements:[{key:"pages-per-audit",minimumPlan:"trial",quantity:100}],risks:[{capability:"audit.run",level:"medium",approval:"policy"}],schedules:[{key:"daily",cron:"0 2 * * *",minimumIntervalSeconds:3600,timezone:"project"}],compatibility:{platform:{minimum:"1.0.0",maximum:"2.0.0"},manifestVersions:["1"]}});

test("manifest validates the complete bilingual, versioned agent contract",()=>{const manifest=validateAgentManifest(valid());assert.equal(manifest.key,"seo.audit");assert.equal(manifest.metadata.en.name,"SEO Audit");assert.equal(manifest.capabilities[0].events[0].key,"audit.progress");assert.equal(manifest.compatibility.platform.minimum,"1.0.0");});

test("manifest requires both locales and every capability risk declaration",()=>{const missing=valid() as Record<string,unknown>,metadata=missing.metadata as Record<string,unknown>;delete metadata.en;assert.throws(()=>validateAgentManifest(missing),error=>error instanceof AgentManifestError&&error.issues.some(item=>item.path==="metadata.en"));const riskless=valid();riskless.risks=[];assert.throws(()=>validateAgentManifest(riskless),error=>error instanceof AgentManifestError&&error.issues.some(item=>item.code==="RISK_REQUIRED"));});

test("manifest rejects duplicate identifiers, unsafe schemas, and unapproved high risk",()=>{const manifest=valid();manifest.capabilities.push(structuredClone(manifest.capabilities[0]));manifest.capabilities[0].input={type:"object",properties:{apiToken:{type:"string"},remote:{$ref:"https://evil.example/schema.json"}}};manifest.risks[0]={capability:"audit.run",level:"critical",approval:"policy"};assert.throws(()=>validateAgentManifest(manifest),error=>error instanceof AgentManifestError&&["DUPLICATE","SENSITIVE_FIELD","EXTERNAL_REF","APPROVAL"].every(code=>error.issues.some(item=>item.code===code)));});

test("manifest rejects incompatible versions, invalid schedules, and malformed dependency ranges",()=>{const manifest=valid();manifest.compatibility.platform={minimum:"2.0.0",maximum:"1.0.0"};manifest.schedules[0].minimumIntervalSeconds=30;manifest.schedules[0].cron="* * *";manifest.dependencies.agents[0].versionRange="latest";assert.throws(()=>validateAgentManifest(manifest),error=>error instanceof AgentManifestError&&["COMPATIBILITY","INTERVAL","CRON","VERSION_RANGE"].every(code=>error.issues.some(item=>item.code===code)));});

test("published JSON schema is immutable in identity and covers every top-level contract",async()=>{const schema=JSON.parse(await readFile(new URL("../platform/modules/agents/agent-manifest.schema.json",import.meta.url),"utf8")) as {"$id":string;required:string[];additionalProperties:boolean};assert.equal(schema.$id,"https://oneshowseo.com/schemas/agent-manifest-v1.json");assert.equal(schema.additionalProperties,false);assert.deepEqual(schema.required,["schemaVersion","key","version","metadata","capabilities","dependencies","entitlements","risks","schedules","compatibility"]);});
