import assert from "node:assert/strict";
import test from "node:test";
import { AgentDevelopmentHarness } from "../platform/sdk/development-harness";
import { certifyAgentRelease, requiredAgentReleaseGates } from "../platform/modules/agents/certification";
import { SeoAuditAgent, auditAgentManifest, type AuditSourceAcquirer } from "../platform/modules/agents/audit-agent";

const envelope=()=>({schemaVersion:"1" as const,kind:"execution" as const,organizationId:"org_audit",projectId:"project_audit",taskId:"task_audit_0001",jobId:"job_audit_0001",attemptId:"attempt_audit_0001",correlationId:"correlation_audit_0001",idempotencyKey:"audit:idempotency:0001",agent:{key:"seo.audit",version:"1.0.0",capability:"audit.run"},actor:{type:"user" as const,id:"account_audit"},locale:"zh-CN" as const,input:{siteUrl:"https://example.com/",maximumPages:10},artifactRefs:[],integrationRefs:[],memoryRefs:[],deadlineAt:2_000_000_000,cancellation:{tokenRef:"cancel_audit_0001",pollAfterSeconds:2},limits:{maxRuntimeSeconds:900,maxOutputBytes:4_000_000,maxArtifacts:1,maxUsageUnits:10}});
const source:AuditSourceAcquirer={acquire:async()=>({capturedAt:1_800_000_000,freshUntil:1_800_086_400,degradedSources:["google_search_console"],result:{pages:[{url:"https://example.com/",statusCode:200,title:"Example",description:"Example page",canonical:"https://example.com/",h1Count:1,imagesWithoutAlt:0,findings:[]}],findings:[{category:"on_page",severity:"high",title:"Meta description",description:"Add a useful description",evidence:"missing",url:"https://example.com/"}],checks:[{category:"technical",key:"http_status",status:"pass",severity:"info",confidence:"confirmed",title:"HTTP status",description:"Page is reachable",evidence:"200",url:"https://example.com/"},{category:"on_page",key:"meta_description",status:"fail",severity:"high",confidence:"confirmed",title:"Meta description",description:"Description is required",evidence:"missing",impact:"Search snippets are weak",recommendation:"Add a useful description",url:"https://example.com/"}],categoryScores:[{category:"technical",score:100,confidence:"low",checksTotal:1,checksKnown:1},{category:"on_page",score:0,confidence:"low",checksTotal:1,checksKnown:1}],score:50,urlsDiscovered:2,urlsBlockedByRobots:0,partial:true,partialReasons:["page_limit"],summary:{total:2,passed:1,warning:0,failed:1,unknown:0,skipped:0}}})};

test("SEO Audit Agent emits evidence-linked read-only recommendations, coverage and final usage",async()=>{const agent=new SeoAuditAgent(source),detail=await agent.runDetailed(envelope()),result=await new AgentDevelopmentHarness().run(agent,envelope());assert.equal(result.terminal,"completed");assert.equal(result.evidenceCount,2);assert.equal(result.artifactCount,1);assert.equal(result.usageUnits,1);assert.equal(detail.audit?.partial,true);assert.equal(detail.recommendations.length,1);assert.deepEqual(detail.recommendations[0].evidenceRefs,["evidence-2"]);const recommendation=detail.events.find(event=>event.kind==="recommendation");assert.equal(recommendation?.kind,"recommendation");if(recommendation?.kind==="recommendation"){assert.equal(recommendation.recommendation.changeSetRef,null);assert.equal(recommendation.recommendation.rollbackRequired,true);}});
test("SEO Audit Agent emits a retryable localized error without billable usage when crawl evidence is unavailable",async()=>{const unavailable:AuditSourceAcquirer={acquire:async()=>{throw new Error("CRAWL_TIMEOUT")}},result=await new AgentDevelopmentHarness().run(new SeoAuditAgent(unavailable),envelope());assert.equal(result.terminal,"failed");assert.equal(result.evidenceCount,0);assert.equal(result.usageUnits,0);});
test("SEO Audit Agent manifest is versioned and all release gates are evidenced",()=>{assert.equal(auditAgentManifest.key,"seo.audit");assert.equal(auditAgentManifest.version,"1.0.0");assert.equal(auditAgentManifest.capabilities[0].key,"audit.run");assert.deepEqual(auditAgentManifest.dependencies.providers,["public.crawl"]);assert.equal(auditAgentManifest.risks[0].approval,"policy");const evidence=requiredAgentReleaseGates.map(gate=>({gate,passed:true,evidence:`tests/audit-agent.test.ts#${gate}`,observedAt:1_800_000_000,owner:"audit-platform"}));assert.equal(certifyAgentRelease({agentKey:"seo.audit",version:"1.0.0",manifestVersion:"1",evidence,approvedBy:"release-owner",approvedAt:1_800_000_000}).certified,true);});
