import assert from "node:assert/strict";
import { createCipheriv,createSign,generateKeyPairSync } from "node:crypto";
import { readFile } from "node:fs/promises";
import { mkdtemp } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { alipaySign,buildAlipayPagePayment,decryptWechatResource,verifyAlipayNotification,verifyWechatNotification,wechatAuthorization } from "../platform/modules/commerce/china-payment-crypto";

const keys=generateKeyPairSync("rsa",{modulusLength:2048,publicKeyEncoding:{type:"spki",format:"pem"},privateKeyEncoding:{type:"pkcs8",format:"pem"}});

test("Alipay RSA2 page payment and notification signatures reject tampering",()=>{
 const url=new URL(buildAlipayPagePayment({gatewayUrl:"https://openapi.alipay.com/gateway.do",appId:"2026000000000000",privateKey:keys.privateKey,notifyUrl:"https://oneshowseo.com/api/billing/webhooks/alipay",returnUrl:"https://oneshowseo.com/workspace",orderNo:"OSPAY123456",amountFen:6800,subject:"OneShowSEO Pro",timestamp:new Date("2026-08-11T08:00:00Z")}));
 const signed=Object.fromEntries(url.searchParams.entries());assert.equal(signed.method,"alipay.trade.page.pay");assert.equal(JSON.parse(signed.biz_content).total_amount,"68.00");assert.equal(verifyAlipayNotification({...signed,sign_type:"RSA2"},keys.publicKey),true);assert.equal(verifyAlipayNotification({...signed,biz_content:signed.biz_content.replace("68.00","0.01"),sign_type:"RSA2"},keys.publicKey),false);
 const notice={app_id:"2026000000000000",out_trade_no:"OSPAY123456",trade_no:"ALI123",trade_status:"TRADE_SUCCESS",total_amount:"68.00",notify_id:"notify-1",sign_type:"RSA2"};const sign=alipaySign(notice,keys.privateKey);assert.equal(verifyAlipayNotification({...notice,sign},keys.publicKey),true);assert.equal(verifyAlipayNotification({...notice,total_amount:"6.80",sign},keys.publicKey),false);
});

test("WeChat API v3 authorization, callback freshness, public-key id, and probe signatures are enforced",()=>{
 const authorization=wechatAuthorization({method:"POST",path:"/v3/pay/transactions/native",body:'{"amount":{"total":6800}}',mchId:"1900000001",serialNo:"SERIAL1",privateKey:keys.privateKey,timestamp:1786435200,nonce:"nonce-1"});assert.match(authorization,/WECHATPAY2-SHA256-RSA2048/);assert.match(authorization,/mchid="1900000001"/);
 const body='{"id":"evt-1"}',timestamp="1786435200",nonce="notify-nonce",message=`${timestamp}\n${nonce}\n${body}\n`,signer=createSign("RSA-SHA256");signer.update(message);signer.end();const signature=signer.sign(keys.privateKey,"base64"),base={timestamp,nonce,body,signature,serial:"PUB_KEY_ID_3000000001",expectedSerial:"PUB_KEY_ID_3000000001",publicKey:keys.publicKey,now:1786435200};assert.equal(verifyWechatNotification(base),true);assert.equal(verifyWechatNotification({...base,body:'{"id":"tampered"}'}),false);assert.equal(verifyWechatNotification({...base,serial:"PUB_KEY_ID_999"}),false);assert.equal(verifyWechatNotification({...base,now:1786435601}),false);assert.equal(verifyWechatNotification({...base,signature:"WECHATPAY/SIGNTEST/probe"}),false);
});

test("WeChat callback resource decrypts with AES-256-GCM and rejects modified ciphertext",()=>{
 const key="0123456789abcdef0123456789abcdef",nonce="123456789012",associated_data="transaction",data=Buffer.from(JSON.stringify({out_trade_no:"OSPAY123456",trade_state:"SUCCESS",amount:{total:6800,currency:"CNY"}})),cipher=createCipheriv("aes-256-gcm",Buffer.from(key),Buffer.from(nonce));cipher.setAAD(Buffer.from(associated_data));const encrypted=Buffer.concat([cipher.update(data),cipher.final(),cipher.getAuthTag()]),resource={algorithm:"AEAD_AES_256_GCM",nonce,associated_data,ciphertext:encrypted.toString("base64")};assert.equal(decryptWechatResource(resource,key).trade_state,"SUCCESS");const changed=Buffer.from(encrypted);changed[0]^=1;assert.throws(()=>decryptWechatResource({...resource,ciphertext:changed.toString("base64")},key));
});

test("payment routes keep live checkout gated and never expose saved secrets",async()=>{
 const checkout=await readFile(new URL("../app/api/billing/checkout/route.ts",import.meta.url),"utf8"),admin=await readFile(new URL("../app/api/admin/payment-providers/route.ts",import.meta.url),"utf8"),service=await readFile(new URL("../lib/payment-checkout.ts",import.meta.url),"utf8"),ui=await readFile(new URL("../app/admin/PaymentProviderSettings.tsx",import.meta.url),"utf8");assert.match(service,/BILLING_LIVE_ENABLED/);assert.match(service,/PAYMENT_NOTIFICATION_MISMATCH/);assert.match(service,/status='paid'/);assert.match(service,/db\.transaction/);assert.match(checkout,/billingManage/);assert.match(admin,/authorizePlatformAccount/);assert.doesNotMatch(admin,/appPrivateKey|apiV3Key|wechatPayPublicKey/);assert.match(ui,/type=\{field\.secret \? "password" : "text"\}/);
});

test("verified Alipay callback settles one order, invoice, subscription, and Credits entitlement exactly once",async()=>{
 const directory=await mkdtemp(path.join(os.tmpdir(),"oneshowseo-china-payments-"));process.env.DATABASE_PATH=path.join(directory,"payment.sqlite");process.env.PAYMENT_CONFIG_ENCRYPTION_KEY="test-payment-encryption-key-32-bytes-long";process.env.BILLING_LIVE_ENABLED="true";process.env.APP_URL="https://oneshowseo.com";globalThis.__oneShowSeoDatabase=undefined;
 const auth=await import("../lib/auth"),billing=await import("../lib/billing"),providers=await import("../lib/payment-providers"),pricing=await import("../lib/plan-pricing"),checkoutModule=await import("../lib/payment-checkout");const db=auth.getDatabase(),now=Math.floor(Date.now()/1000);await auth.ensureAuthSchema(db);db.prepare("INSERT INTO users(id,email,name,password_hash,role,status,plan,trial_ends_at,email_verified_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)").bind("account_china_pay","pay-owner@example.com","Pay Owner","hash","admin","active","trial",now+1209600,now,now,now).run();await auth.ensureAuthSchema(db);await billing.ensureBillingSchema();billing.commerceService().resolve({accountId:"account_china_pay",organizationId:"org_account_china_pay",organizationStatus:"trial",planKey:"trial",trialEndsAt:now+1209600,accountCreatedAt:now});
 await pricing.updateProductPrices([{planKey:"starter",monthlyPriceFen:3500,available:true,featured:false},{planKey:"pro",monthlyPriceFen:6800,available:true,featured:true},{planKey:"business",monthlyPriceFen:16800,available:true,featured:false}],"account_china_pay");await providers.savePaymentProvider("alipay",{appId:"2026000000000000",gatewayUrl:"https://openapi.alipay.com/gateway.do",appPrivateKey:keys.privateKey,alipayPublicKey:keys.publicKey},true,"account_china_pay");const checkout=await checkoutModule.createPaymentCheckout({organizationId:"org_account_china_pay",userId:"account_china_pay",provider:"alipay",planKey:"pro"});assert.equal(checkout.checkout.type,"redirect");assert.equal(checkout.amountFen,6800);
 const notice={app_id:"2026000000000000",out_trade_no:checkout.orderNo,trade_no:"ALI-END-TO-END-1",trade_status:"TRADE_SUCCESS",total_amount:"68.00",notify_id:"notify-end-to-end-1",sign_type:"RSA2"},raw=new URLSearchParams({...notice,sign:alipaySign(notice,keys.privateKey)}).toString();assert.equal((await checkoutModule.receiveAlipayNotification(raw)).duplicate,false);assert.equal((await checkoutModule.receiveAlipayNotification(raw)).duplicate,true);assert.equal((await checkoutModule.paymentOrderStatus(checkout.orderId,"org_account_china_pay")).status,"paid");assert.equal(billing.commerceRepository().subscription("org_account_china_pay")?.planKey,"pro");assert.equal(db.prepare("SELECT COUNT(*) AS count FROM billing_invoices WHERE organization_id=? AND status='paid'").bind("org_account_china_pay").first<{count:number}>()?.count,1);assert.equal(db.prepare("SELECT plan FROM users WHERE id=?").bind("account_china_pay").first<{plan:string}>()?.plan,"pro");assert.equal(billing.commerceService().balance({accountId:"account_china_pay",organizationId:"org_account_china_pay",organizationStatus:"active",planKey:"pro",trialEndsAt:null,accountCreatedAt:now}).granted,15000);
});
