import test from "node:test";
import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Worker } from "node:worker_threads";
import { ensureAuthSchema } from "../lib/auth";
import { AppDatabase } from "../lib/database";
import { SqliteCommerceRepository } from "../platform/adapters/sqlite/commerce-repository";
import { CommerceError, CommercialEntitlementService } from "../platform/modules/commerce/service";
import type { CommercialSubject } from "../platform/modules/commerce";

type Operation={type:"reserve"|"commit"|"release"|"adjust"|"usage"|"project";quantity?:number;key?:string;taskId?:string;reservationId?:string;entryType?:"refund"|"adjustment"|"expiry";relatedEntryId?:string|null;projectId?:string;limit?:number};
type WorkerResult={ok:boolean;result?:{id?:string};code?:string;message?:string};

async function fixture(){
 const databasePath=join(mkdtempSync(join(tmpdir(),"oneshowseo-commerce-concurrency-")),"test.sqlite"),sqlite=new DatabaseSync(databasePath);sqlite.exec("PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000;");const database=new AppDatabase(sqlite);await ensureAuthSchema(database);const now=1_786_000_000;
 database.prepare("INSERT INTO users(id,email,name,password_hash,role,status,plan,trial_ends_at,email_verified_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)").bind("account_1","owner@example.com","Owner","hash","user","active","trial",now+86400*14,now,now-100,now-100).run();await ensureAuthSchema(database);
 database.exec("CREATE TABLE projects(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,status TEXT NOT NULL)");new SqliteCommerceRepository(database).ensureSchema();sqlite.close();
 const subject:CommercialSubject={accountId:"account_1",organizationId:"org_account_1",organizationStatus:"trial",planKey:"trial",trialEndsAt:now+86400*14,accountCreatedAt:now-100};return{databasePath,subject,now};
}

async function concurrent(databasePath:string,subject:CommercialSubject,operations:Operation[]):Promise<WorkerResult[]>{
 const gate=new SharedArrayBuffer(4),ready:Promise<void>[]=[],results:Promise<WorkerResult>[]=[];
 for(const operation of operations){let signalReady!:()=>void,rejectReady!:(error:Error)=>void,signalResult!:(value:WorkerResult)=>void,rejectResult!:(error:Error)=>void;ready.push(new Promise((resolve,reject)=>{signalReady=resolve;rejectReady=reject;}));results.push(new Promise((resolve,reject)=>{signalResult=resolve;rejectResult=reject;}));const worker=new Worker(new URL("./helpers/commerce-concurrency-worker.ts",import.meta.url),{workerData:{databasePath,gate,subject,operation},execArgv:["--import","tsx"]});worker.on("message",message=>{if(message?.ready)signalReady();else signalResult(message as WorkerResult);});worker.on("error",error=>{rejectReady(error);rejectResult(error);});}
 await Promise.all(ready);const lock=new Int32Array(gate);Atomics.store(lock,0,1);Atomics.notify(lock,0,operations.length);return Promise.all(results);
}

function inspect(databasePath:string){const sqlite=new DatabaseSync(databasePath);sqlite.exec("PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;");const database=new AppDatabase(sqlite),repository=new SqliteCommerceRepository(database);return{sqlite,database,repository,service:new CommercialEntitlementService(repository,()=>1_786_000_000)};}

test("concurrent retries create one grant and one reservation",async()=>{const {databasePath,subject}=await fixture();const results=await concurrent(databasePath,subject,[{type:"reserve",quantity:600,key:"same",taskId:"task"},{type:"reserve",quantity:600,key:"same",taskId:"task"}]);assert.ok(results.every(result=>result.ok));assert.equal(results[0].result?.id,results[1].result?.id);const {sqlite,database,repository}=inspect(databasePath);assert.equal(database.prepare("SELECT COUNT(*) AS count FROM commerce_credit_ledger WHERE entry_type='grant'").first<{count:number}>()?.count,1);assert.equal(database.prepare("SELECT COUNT(*) AS count FROM commerce_credit_ledger WHERE entry_type='reservation'").first<{count:number}>()?.count,1);assert.equal(repository.creditBalance(subject.organizationId,1_786_000_000).reserved,600);sqlite.close();});

test("concurrent reservations cannot overspend available Credits",async()=>{const {databasePath,subject}=await fixture();const results=await concurrent(databasePath,subject,[{type:"reserve",quantity:600,key:"first",taskId:"first"},{type:"reserve",quantity:600,key:"second",taskId:"second"}]);assert.equal(results.filter(result=>result.ok).length,1);assert.deepEqual(results.filter(result=>!result.ok).map(result=>result.code),["INSUFFICIENT_CREDITS"]);const {sqlite,database,repository}=inspect(databasePath);assert.equal(database.prepare("SELECT COUNT(*) AS count FROM commerce_credit_ledger WHERE entry_type='reservation'").first<{count:number}>()?.count,1);assert.equal(repository.creditBalance(subject.organizationId,1_786_000_000).available,400);sqlite.close();});

test("commit and release racing on one reservation produce one terminal entry",async()=>{const {databasePath,subject}=await fixture(),opened=inspect(databasePath);const reservation=opened.service.reserveCredits(subject,{quantity:100,idempotencyKey:"terminal",taskId:"terminal",correlationId:"setup"});opened.sqlite.close();const results=await concurrent(databasePath,subject,[{type:"commit",reservationId:reservation.id,key:"commit"},{type:"release",reservationId:reservation.id,key:"release"}]);assert.equal(results.filter(result=>result.ok).length,1);assert.deepEqual(results.filter(result=>!result.ok).map(result=>result.code),["RESERVATION_SETTLED"]);const checked=inspect(databasePath);assert.equal(checked.database.prepare("SELECT COUNT(*) AS count FROM commerce_credit_ledger WHERE related_entry_id=? AND entry_type IN ('commit','release')").bind(reservation.id).first<{count:number}>()?.count,1);checked.sqlite.close();});

test("concurrent charge retries return one commit",async()=>{const {databasePath,subject}=await fixture(),opened=inspect(databasePath);const reservation=opened.service.reserveCredits(subject,{quantity:100,idempotencyKey:"charge",taskId:"charge",correlationId:"setup"});opened.sqlite.close();const results=await concurrent(databasePath,subject,[{type:"commit",reservationId:reservation.id,key:"charge-a"},{type:"commit",reservationId:reservation.id,key:"charge-b"}]);assert.ok(results.every(result=>result.ok));assert.equal(results[0].result?.id,results[1].result?.id);const checked=inspect(databasePath);assert.equal(checked.database.prepare("SELECT COUNT(*) AS count FROM commerce_credit_ledger WHERE related_entry_id=? AND entry_type='commit'").bind(reservation.id).first<{count:number}>()?.count,1);checked.sqlite.close();});

test("concurrent refund retries append one refund",async()=>{const {databasePath,subject}=await fixture();const results=await concurrent(databasePath,subject,[{type:"adjust",entryType:"refund",quantity:50,key:"refund",relatedEntryId:null},{type:"adjust",entryType:"refund",quantity:50,key:"refund",relatedEntryId:null}]);assert.ok(results.every(result=>result.ok));assert.equal(results[0].result?.id,results[1].result?.id);const checked=inspect(databasePath);assert.equal(checked.database.prepare("SELECT COUNT(*) AS count FROM commerce_credit_ledger WHERE entry_type='refund'").first<{count:number}>()?.count,1);checked.sqlite.close();});

test("concurrent usage payload drift is rejected after the unique-key race",async()=>{const {databasePath,subject}=await fixture();const results=await concurrent(databasePath,subject,[{type:"usage",quantity:10,key:"usage-race",taskId:"audit"},{type:"usage",quantity:11,key:"usage-race",taskId:"audit"}]);assert.equal(results.filter(result=>result.ok).length,1);assert.deepEqual(results.filter(result=>!result.ok).map(result=>result.code),["IDEMPOTENCY_CONFLICT"]);const checked=inspect(databasePath);assert.equal(checked.database.prepare("SELECT COUNT(*) AS count FROM commerce_usage_events WHERE idempotency_key='usage-race'").first<{count:number}>()?.count,1);checked.sqlite.close();});

test("project capacity check and insert share one write lock",async()=>{const {databasePath,subject}=await fixture();const results=await concurrent(databasePath,subject,[{type:"project",projectId:"project_1",limit:1},{type:"project",projectId:"project_2",limit:1}]);assert.equal(results.filter(result=>result.ok).length,1);assert.deepEqual(results.filter(result=>!result.ok).map(result=>result.code),["LIMIT_REACHED"]);const checked=inspect(databasePath);assert.equal(checked.database.prepare("SELECT COUNT(*) AS count FROM projects").first<{count:number}>()?.count,1);checked.sqlite.close();});

test("generated retries remain idempotent and reject payload drift",async()=>{const {databasePath,subject}=await fixture(),opened=inspect(databasePath);for(let index=0;index<40;index++){const quantity=(index*37%97)+1,key=`property-${index}`,taskId=`task-${index}`;const reservation=opened.service.reserveCredits(subject,{quantity,idempotencyKey:key,taskId,correlationId:"property"});assert.equal(opened.service.reserveCredits(subject,{quantity,idempotencyKey:key,taskId,correlationId:"retry"}).id,reservation.id);assert.throws(()=>opened.service.reserveCredits(subject,{quantity:quantity+1,idempotencyKey:key,taskId,correlationId:"drift"}),(error:unknown)=>error instanceof CommerceError&&error.code==="IDEMPOTENCY_CONFLICT");const release=opened.service.releaseCredits(subject,{reservationId:reservation.id,idempotencyKey:key,correlationId:"property"});assert.equal(opened.service.releaseCredits(subject,{reservationId:reservation.id,idempotencyKey:key,correlationId:"retry"}).id,release.id);}assert.equal(opened.repository.creditBalance(subject.organizationId,1_786_000_000).available,1000);assert.equal(opened.database.prepare("SELECT COUNT(*) AS count FROM commerce_credit_ledger WHERE entry_type='reservation'").first<{count:number}>()?.count,40);assert.equal(opened.database.prepare("SELECT COUNT(*) AS count FROM commerce_credit_ledger WHERE entry_type='release'").first<{count:number}>()?.count,40);opened.sqlite.close();});
