import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { mkdtemp, readFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { ensureAuthSchema } from "../lib/auth";
import { ensureBillingSchema, commerceRepository } from "../lib/billing";
import { AppDatabase } from "../lib/database";
import { atomicTaskCreationService, executionRepository, executionWorkerSupervisor } from "../lib/execution";
import { ensureProductSchema } from "../lib/product";
import { contentWorkerHandler } from "../lib/production-worker";
import { permissions } from "../platform/modules/identity/authorization";
import { contentAgentManifest } from "../platform/modules/agents/content-agent";

async function fixture(){const sqlite=new DatabaseSync(":memory:");sqlite.exec("PRAGMA foreign_keys=ON");const database=new AppDatabase(sqlite);globalThis.__oneShowSeoDatabase=database;const now=Math.floor(Date.now()/1000);await ensureAuthSchema(database);database.prepare("INSERT INTO users(id,email,name,password_hash,role,status,plan,trial_ends_at,email_verified_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)").bind("content_account","content@example.com","Content Owner","hash","user","active","trial",now+86400,now,now-100,now-100).run();await ensureAuthSchema(database);await ensureProductSchema();database.prepare("INSERT INTO projects(id,user_id,name,site_url,host,market,language,timezone,business_goal,approval_mode,schedule_enabled,created_at,updated_at,organization_id,slug,status,business_type,search_engines,version) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind("content_project","content_account","Content Project","https://example.com/","example.com","CN","zh-CN","Asia/Shanghai","organic_growth","required",0,now,now,"org_content_account","content-project","active","website",'["google"]',1).run();await ensureBillingSchema();return{database,now};}

const contentInput={projectId:"content_project",title:"AI SEO 内容工作流指南",keyword:"AI SEO",contentType:"guide" as const,audience:"负责自然增长的内容负责人",intent:"信息型",tone:"专业、清晰、可信",goal:"自然搜索增长",sourceRef:"https://example.com/research",brief:"必须说明证据边界，并包含 FAQ。"};

test("Content Agent manifest declares generation, Credits and mandatory approval",()=>{assert.equal(contentAgentManifest.key,"content.agent");assert.equal(contentAgentManifest.capabilities[0].key,"content.generate");assert.equal(contentAgentManifest.risks[0].approval,"required");assert.equal(contentAgentManifest.entitlements.find(item=>item.key==="monthly-credits")?.quantity,20);});

test("production Content Worker stores the draft, finalizes usage, creates review, and commits Credits",async()=>{const{database,now}=await fixture(),root=await mkdtemp(path.join(os.tmpdir(),"oneshowseo-content-worker-"));process.env.OBJECT_STORAGE_ROOT=root;process.env.OBJECT_STORAGE_SIGNING_SECRET="content-worker-test-signing-secret-long-enough";const subject={accountId:"content_account",organizationId:"org_content_account",organizationStatus:"trial" as const,planKey:"trial" as const,trialEndsAt:now+86400,accountCreatedAt:now-100},created=(await atomicTaskCreationService()).create({activeOrganizationId:subject.organizationId,organizationId:subject.organizationId,projectId:"content_project",requestedByAccountId:subject.accountId,role:"owner",permission:permissions.contentCreate,subject,triggerType:"manual",taskType:"content_agent",capability:"content.generate",input:{...contentInput,description:"目标关键词：AI SEO；目标受众：内容负责人"},locale:"zh-CN",idempotencyKey:"content:worker:test:0001",correlationId:"content-worker-correlation",entitlements:[{key:"contentItems",quantity:1,currentUsage:0}],creditCost:20,queue:"agents",jobType:"content.generate",priority:65,maxAttempts:1,timeoutSeconds:60});const handler=contentWorkerHandler(),supervisor=await executionWorkerSupervisor({"content.generate":handler},{workerId:"content-worker-test",queue:"agents",concurrency:1,pollIntervalMs:10,leaseSeconds:10,heartbeatIntervalMs:100,shutdownGraceMs:100,maintenanceLimit:10,baseBackoffSeconds:1,maxBackoffSeconds:10});assert.equal(await supervisor.runOne(),true);assert.equal(executionRepository().task(subject.organizationId,created.task.id)?.state,"completed");const artifact=database.prepare("SELECT object_key AS objectKey,kind FROM execution_artifacts WHERE task_id=?").bind(created.task.id).first<{objectKey:string;kind:string}>();assert.equal(artifact?.kind,"content_draft");assert.match(await readFile(path.join(root,artifact!.objectKey),"utf8"),/AI 辅助草稿/);assert.equal(database.prepare("SELECT state FROM commerce_usage_events WHERE task_id=? AND metric='content_generated'").bind(created.task.id).first<{state:string}>()?.state,"final");assert.equal(commerceRepository().terminalForReservation(subject.organizationId,created.reservationId!)?.entryType,"commit");assert.equal(database.prepare("SELECT status FROM seo_tasks WHERE id=?").bind(`content-review-${created.task.id}`).first<{status:string}>()?.status,"proposed");});
