import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { MCP_PROTOCOL_VERSION, dispatchMcp, mcpTools, validateMcpRouting } from "../platform/modules/developer/mcp";

const context=(scopes=new Set(["projects:read","tasks:write"] as const))=>({scopes,projectAllowed:(id:string)=>id==="project_a",listProjects:async(limit:number)=>[{id:"project_a",limit}],getProject:async(id:string)=>id==="project_a"?{id}:null,startTask:async(input:Record<string,unknown>)=>({taskId:"task_a",state:"queued",...input})});
test("MCP discovery is stateless and advertises only shared governed tools",async()=>{const value=await dispatchMcp({jsonrpc:"2.0",id:1,method:"server/discover"},context());assert.equal(value.result.protocolVersion,MCP_PROTOCOL_VERSION);assert.equal(value.result.capabilities.tools.listChanged,false);assert.deepEqual(mcpTools.map(tool=>tool.name),["list_projects","get_project","start_agent_task"]);const list=await dispatchMcp({jsonrpc:"2.0",id:2,method:"tools/list"},context(new Set(["projects:read"])));assert.deepEqual(list.result.tools.map((tool:{name:string})=>tool.name),["list_projects","get_project"]);assert.equal(list.result.cacheScope,"private");});
test("MCP tool calls enforce scope, project, validation, and idempotent task references",async()=>{const listed=await dispatchMcp({jsonrpc:"2.0",id:1,method:"tools/call",params:{name:"list_projects",arguments:{limit:5}}},context());assert.equal(listed.result.structuredContent.projects[0].id,"project_a");const denied=await dispatchMcp({jsonrpc:"2.0",id:2,method:"tools/call",params:{name:"get_project",arguments:{projectId:"project_b"}}},context());assert.equal(denied.error.data.code,"NOT_FOUND");const started=await dispatchMcp({jsonrpc:"2.0",id:3,method:"tools/call",params:{name:"start_agent_task",arguments:{projectId:"project_a",capability:"platform.synthetic",idempotencyKey:"mcp:task:create:0001",input:{mode:"success"}}}},context());assert.equal(started.result.structuredContent.task.taskId,"task_a");const forbidden=await dispatchMcp({jsonrpc:"2.0",id:4,method:"tools/call",params:{name:"start_agent_task",arguments:{}}},context(new Set(["projects:read"])));assert.equal(forbidden.error.data.code,"FORBIDDEN");});
test("MCP 2026 routing headers must match the JSON-RPC request",()=>{const body={jsonrpc:"2.0",id:1,method:"tools/call",params:{name:"get_project",arguments:{projectId:"project_a"}}};assert.equal(validateMcpRouting(new Headers({"mcp-protocol-version":MCP_PROTOCOL_VERSION,"mcp-method":"tools/call","mcp-name":"get_project"}),body),null);assert.match(validateMcpRouting(new Headers({"mcp-protocol-version":MCP_PROTOCOL_VERSION,"mcp-method":"tools/list","mcp-name":"get_project"}),body)||"",/does not match/);});
test("HTTP facade reuses API authentication, commerce, task, usage, and audit services",()=>{const source=readFileSync("app/api/mcp/route.ts","utf8");for(const pattern of [/authenticateApiRequest/,/requiredScopes/,/projectId/,/atomicTaskCreationService/,/commercialSubject/,/triggerType:"mcp"/,/recordApiRequest/,/writeAudit/])assert.match(source,pattern);});
