import assert from "node:assert/strict";
import { mkdtempSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { randomBytes } from "node:crypto";
import test from "node:test";
import { ensureAuthSchema, getDatabase, type AppUser } from "../lib/auth";
import { acceptSignedWebhook, createWebhookSubscription, disableWebhookSubscription, enqueueWebhookEvent, retryWebhookDelivery } from "../lib/developer-webhooks";
import { safeWebhookPayload, validateWebhookEvents, webhookRetry, webhookSignature, verifyWebhookSignature } from "../platform/modules/developer/webhooks";
process.env.DATABASE_PATH=join(mkdtempSync(join(tmpdir(),"oneshowseo-webhooks-")),"test.sqlite");process.env.INTEGRATION_VAULT_ACTIVE_KEY_VERSION="v1";process.env.INTEGRATION_VAULT_KEYS=JSON.stringify({v1:randomBytes(32).toString("base64url")});
async function fixture():Promise<AppUser>{await ensureAuthSchema();const id=`webhook_${crypto.randomUUID()}`,email=`${id}@example.com`,at=Math.floor(Date.now()/1000);getDatabase().prepare("INSERT INTO users(id,email,name,password_hash,role,status,plan,email_verified_at,created_at,updated_at)VALUES(?,?,?,'hash','user','active','business',?,?,?)").bind(id,email,"Webhook Owner",at,at,at).run();await ensureAuthSchema();const organization=getDatabase().prepare("SELECT o.id organizationId,o.name organizationName,o.slug organizationSlug,o.status organizationStatus,m.id membershipId,m.status membershipStatus,r.role_key roleKey FROM identity_organizations o JOIN identity_memberships m ON m.organization_id=o.id JOIN identity_roles r ON r.id=m.role_id WHERE m.user_id=?").bind(id).first<AppUser["organization"]>()!;return{id,email,name:"Webhook Owner",role:"user",status:"active",plan:"business",trialEndsAt:null,emailVerifiedAt:at,createdAt:at,organization};}
test("webhook signatures authenticate exact body and reject stale or tampered replay",async()=>{const secret="whsec_test",body=JSON.stringify({id:"event_a"}),signature=webhookSignature(secret,100,body);assert.equal(verifyWebhookSignature({secret,timestamp:100,body,signature,now:120}),true);assert.equal(verifyWebhookSignature({secret,timestamp:100,body:`${body} `,signature,now:120}),false);assert.equal(verifyWebhookSignature({secret,timestamp:100,body,signature,now:1000}),false);const user=await fixture(),first=await acceptSignedWebhook({organizationId:user.organization.organizationId,source:"provider",eventId:"event_a",body,timestamp:100,signature,secret,now:120}),duplicate=await acceptSignedWebhook({organizationId:user.organization.organizationId,source:"provider",eventId:"event_a",body,timestamp:100,signature,secret,now:120});assert.equal(first.accepted,true);assert.equal(duplicate.duplicate,true);});
test("subscription secret is shown once, encrypted at rest, and events enqueue idempotently",async()=>{const user=await fixture(),created=await createWebhookSubscription(user,{url:"https://hooks.example.com/oneshow",events:["task.completed"]});assert.match(created.signingSecret,/^whsec_/);const row=getDatabase().prepare("SELECT signing_secret_envelope envelope FROM api_webhooks WHERE id=?").bind(created.subscription.id).first<{envelope:string}>()!;assert.match(row.envelope,/^sv1\.v1\./);assert.equal(row.envelope.includes(created.signingSecret),false);assert.equal(await enqueueWebhookEvent({organizationId:user.organization.organizationId,eventId:"event_1",eventType:"task.completed",payload:{taskId:"task_a",authorization:"Bearer hidden"},correlationId:"webhook:test:0001"}),1);assert.equal(await enqueueWebhookEvent({organizationId:user.organization.organizationId,eventId:"event_1",eventType:"task.completed",payload:{taskId:"task_a"},correlationId:"webhook:test:0001"}),1);const delivery=getDatabase().prepare("SELECT id,payload_json payload,state FROM webhook_outbox WHERE event_id='event_1'").first<{id:string;payload:string;state:string}>()!;assert.equal(getDatabase().prepare("SELECT COUNT(*) total FROM webhook_outbox WHERE event_id='event_1'").first<{total:number}>()?.total,1);assert.equal(delivery.payload.includes("hidden"),false);getDatabase().prepare("UPDATE webhook_outbox SET state='quarantined' WHERE id=?").bind(delivery.id).run();const outsider=await fixture();await assert.rejects(retryWebhookDelivery(outsider,delivery.id),/DELIVERY_NOT_RETRYABLE/);assert.equal(getDatabase().prepare("SELECT state FROM webhook_outbox WHERE id=?").bind(delivery.id).first<{state:string}>()?.state,"quarantined");await retryWebhookDelivery(user,delivery.id);assert.equal(getDatabase().prepare("SELECT state FROM webhook_outbox WHERE id=?").bind(delivery.id).first<{state:string}>()?.state,"pending");await disableWebhookSubscription(user,created.subscription.id);assert.equal(getDatabase().prepare("SELECT status FROM api_webhooks WHERE id=?").bind(created.subscription.id).first<{status:string}>()?.status,"disabled");});
test("event validation, redaction, backoff, and quarantine are bounded",()=>{assert.deepEqual(validateWebhookEvents(["task.created","task.created"]),["task.created"]);assert.throws(()=>validateWebhookEvents(["unknown"]));assert.equal(JSON.stringify(safeWebhookPayload({apiKey:"secret",safe:"ok"})).includes("secret"),false);assert.deepEqual(webhookRetry(1,100),{state:"retrying",nextAttemptAt:130});assert.deepEqual(webhookRetry(6,100),{state:"quarantined",nextAttemptAt:null});});
test("webhook migration and management expose inspection without signing material",()=>{const sql=readFileSync("platform/adapters/postgres/migrations/0021_expand_webhook_delivery.sql","utf8"),route=readFileSync("app/api/api-access/route.ts","utf8");for(const pattern of [/webhook_subscriptions/,/webhook_outbox/,/webhook_delivery_attempts/,/webhook_inbox/,/quarantined/,/REVOKE DELETE/])assert.match(sql,pattern);assert.match(route,/deliveries/);assert.match(route,/retryWebhookDelivery/);assert.doesNotMatch(route,/signing_secret_envelope AS/);});
