import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { DeveloperRateLimitService, MemoryDistributedRateLimitRepository } from "../platform/modules/developer/rate-limit";

const input=(overrides:Record<string,unknown>={})=>({credentialId:"key_a",organizationId:"org_a",projectId:"project_a",endpoint:"GET /projects",cost:1,credentialRequestsPerMinute:2,credentialCostUnitsPerMinute:10,organizationRequestsPerMinute:10,projectRequestsPerMinute:10,endpointRequestsPerMinute:10,now:100,...overrides});
test("distributed policy atomically limits credentials across endpoints with stable retry metadata",async()=>{const service=new DeveloperRateLimitService(new MemoryDistributedRateLimitRepository());assert.equal((await service.consume(input())).allowed,true);assert.equal((await service.consume(input({endpoint:"GET /projects/:id"}))).allowed,true);const denied=await service.consume(input({endpoint:"MCP tools/list"}));assert.equal(denied.allowed,false);assert.equal(denied.limitedBy,"credential");assert.equal(denied.retryAfterSeconds,20);assert.equal(denied.resetsAt,120);assert.equal(denied.policyVersion,"developer-rate-v1");const next=await service.consume(input({now:121}));assert.equal(next.allowed,true);});
test("cost, organization, project, and endpoint dimensions are independently enforced",async()=>{const costly=new DeveloperRateLimitService(new MemoryDistributedRateLimitRepository()),costDenied=await costly.consume(input({cost:11,credentialRequestsPerMinute:100}));assert.equal(costDenied.allowed,false);assert.equal(costDenied.limitedBy,"cost");const endpoint=new DeveloperRateLimitService(new MemoryDistributedRateLimitRepository());await endpoint.consume(input({credentialRequestsPerMinute:100,endpointRequestsPerMinute:1}));assert.equal((await endpoint.consume(input({credentialRequestsPerMinute:100,endpointRequestsPerMinute:1}))).limitedBy,"endpoint");const project=new DeveloperRateLimitService(new MemoryDistributedRateLimitRepository());await project.consume(input({credentialRequestsPerMinute:100,projectRequestsPerMinute:1}));assert.equal((await project.consume(input({credentialRequestsPerMinute:100,projectRequestsPerMinute:1,endpoint:"other"}))).limitedBy,"project");});
test("PostgreSQL adapter uses atomic upsert and public routes expose retry metadata",()=>{const adapter=readFileSync("platform/adapters/postgres/developer-rate-limit-repository.ts","utf8"),migration=readFileSync("platform/adapters/postgres/migrations/0020_expand_distributed_rate_limits.sql","utf8"),routes=readFileSync("app/api/v1/projects/route.ts","utf8")+readFileSync("app/api/mcp/route.ts","utf8");assert.match(adapter,/ON CONFLICT/);assert.match(adapter,/BEGIN/);assert.match(adapter,/ROLLBACK/);for(const value of ["credential","organization","project","endpoint","cost"])assert.match(migration,new RegExp(value));assert.match(routes,/retry-after/);assert.match(routes,/x-rate-limit-policy/);});
