import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { EventEmitter } from "node:events";
import { DatabaseSync } from "node:sqlite";
import test from "node:test";
import { ensureAuthSchema } from "../lib/auth";
import { AppDatabase } from "../lib/database";
import { SqliteExecutionRepository } from "../platform/adapters/sqlite/execution-repository";
import type { CancellationRequest, ExecutionJob, ExecutionTask } from "../platform/modules/execution";
import { ExecutionWorkerSupervisor, WorkerJobError, type WorkerSupervisorOptions } from "../platform/modules/execution/worker";
import { runSupervisedWorker } from "../platform/workers/supervisor-runtime";

async function fixture(){const sqlite=new DatabaseSync(":memory:");sqlite.exec("PRAGMA foreign_keys=ON");const database=new AppDatabase(sqlite);await ensureAuthSchema(database);const now=1_786_300_000;database.prepare("INSERT INTO users(id,email,name,password_hash,role,status,plan,trial_ends_at,email_verified_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)").bind("account_a","owner@example.com","Owner","hash","user","active","trial",now+14*86400,now,now-100,now-100).run();await ensureAuthSchema(database);database.exec("CREATE TABLE projects(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES identity_organizations(id),status TEXT NOT NULL);INSERT INTO projects VALUES ('project_a','org_account_a','active')");const repository=new SqliteExecutionRepository(database);repository.ensureSchema();return{sqlite,database,repository,now};}
function enqueue(repository:SqliteExecutionRepository,now:number,overrides:Partial<ExecutionJob>={}){const id=overrides.id??crypto.randomUUID(),taskId=overrides.taskId??crypto.randomUUID(),task:ExecutionTask={id:taskId,organizationId:"org_account_a",projectId:"project_a",requestedByAccountId:"account_a",triggerType:"manual",taskType:"test",capability:"test.run",state:"queued",progress:0,cancellable:true,input:{value:42},locale:"zh-CN",idempotencyKey:`task-${taskId}`,correlationId:`correlation-${taskId}`,version:1,createdAt:now,updatedAt:now,startedAt:null,completedAt:null},job:ExecutionJob={id,organizationId:"org_account_a",projectId:"project_a",taskId,queue:"test",jobType:"synthetic",state:"queued",priority:50,availableAt:now,maxAttempts:3,timeoutSeconds:30,attemptCount:0,idempotencyKey:`job-${id}`,correlationId:task.correlationId,createdAt:now,updatedAt:now,completedAt:null,...overrides};repository.createTask(task);repository.createJob(job);return{task,job};}
function options(overrides:Partial<WorkerSupervisorOptions>={}):WorkerSupervisorOptions{return{workerId:"worker-a",queue:"test",concurrency:1,pollIntervalMs:10,leaseSeconds:5,heartbeatIntervalMs:100,shutdownGraceMs:100,maintenanceLimit:20,baseBackoffSeconds:5,maxBackoffSeconds:60,...overrides};}
const digest=(value:string)=>createHash("sha256").update(value).digest("hex");

test("worker claims by priority, stores only a hashed lease, heartbeats, and emits settlement intent",async()=>{const{database,repository,now}=await fixture();const low=enqueue(repository,now,{priority:10}),high=enqueue(repository,now,{priority:90});const token="raw-lease-token",claim=repository.claimJob({queue:"test",jobTypes:["synthetic"],workerId:"worker-a",tokenHash:digest(token),now,leaseSeconds:10});assert.equal(claim?.job.id,high.job.id);assert.equal(claim?.lease.tokenHash,digest(token));assert.doesNotMatch(claim?.lease.tokenHash??"",/raw-lease-token/);assert.equal(repository.claimJob({queue:"test",jobTypes:["synthetic"],workerId:"worker-b",tokenHash:digest("other"),now,leaseSeconds:10})?.job.id,low.job.id);assert.equal(repository.claimJob({queue:"test",jobTypes:["synthetic"],workerId:"worker-c",tokenHash:digest("third"),now,leaseSeconds:10}),null);
  assert.equal(repository.heartbeatLease({organizationId:"org_account_a",jobId:high.job.id,attemptId:claim!.attempt.id,workerId:"worker-a",tokenHash:digest("wrong"),now:now+1,leaseSeconds:10}),null);const heartbeat=repository.heartbeatLease({organizationId:"org_account_a",jobId:high.job.id,attemptId:claim!.attempt.id,workerId:"worker-a",tokenHash:digest(token),now:now+1,leaseSeconds:10});assert.equal(heartbeat?.lease.expiresAt,now+11);assert.equal(repository.succeedAttempt({claim:claim!,workerId:"worker-a",tokenHash:digest(token),now:now+2}),true);assert.equal(repository.job("org_account_a",high.job.id)?.state,"completed");assert.equal(repository.attempts("org_account_a",high.job.id)[0].state,"succeeded");assert.equal(repository.lease("org_account_a",high.job.id)?.state,"released");assert.equal(repository.pendingOutbox(20,now+2).some(event=>event.eventType==="execution.job.completed"),true);assert.equal(database.prepare("SELECT COUNT(*) count FROM operations_audit_events WHERE action='execution.job.completed'").first<{count:number}>()?.count,1);
});

test("supervisor applies bounded exponential retry and quarantines exhausted work",async()=>{const{repository,now}=await fixture();let clock=now,runs=0;const queued=enqueue(repository,now,{maxAttempts:2});const supervisor=new ExecutionWorkerSupervisor(repository,{synthetic:{authorize:()=>{},execute:async()=>{runs++;throw new WorkerJobError("UPSTREAM_TIMEOUT","apiKey=must-not-leak",true);}}},options(),{now:()=>clock,randomToken:()=>`token-${runs}`});assert.equal(await supervisor.runOne(),true);let job=repository.job("org_account_a",queued.job.id);assert.equal(job?.state,"retrying");assert.equal(job?.availableAt,now+5);assert.equal(repository.attempts("org_account_a",queued.job.id)[0].errorMessage?.includes("must-not-leak"),false);clock=now+4;assert.equal(await supervisor.runOne(),false);clock=now+5;assert.equal(await supervisor.runOne(),true);job=repository.job("org_account_a",queued.job.id);assert.equal(job?.state,"quarantined");assert.equal(repository.attempts("org_account_a",queued.job.id).length,2);assert.deepEqual(repository.pendingOutbox(20,clock).filter(event=>event.aggregateId===queued.job.id).map(event=>event.eventType),["execution.job.retrying","execution.job.quarantined"]);
});

test("worker re-authorizes immediately before execution and never runs revoked work",async()=>{const{repository,now}=await fixture();const queued=enqueue(repository,now);let executed=false;const supervisor=new ExecutionWorkerSupervisor(repository,{synthetic:{authorize:()=>{throw new Error("SUBSCRIPTION_REQUIRED");},execute:async()=>{executed=true;}}},options(),{now:()=>now});assert.equal(await supervisor.runOne(),true);assert.equal(executed,false);assert.equal(repository.job("org_account_a",queued.job.id)?.state,"failed");const attempt=repository.attempts("org_account_a",queued.job.id)[0];assert.equal(attempt.errorCode,"EXECUTION_NOT_AUTHORIZED");assert.equal(attempt.retryAt,null);
});

test("cancellation blocks queued claims and is signalled through a running lease heartbeat",async()=>{const{repository,now}=await fixture();const queued=enqueue(repository,now),queuedCancellation:CancellationRequest={id:crypto.randomUUID(),organizationId:"org_account_a",projectId:"project_a",taskId:queued.task.id,requestedByAccountId:"account_a",state:"requested",reason:"user request",idempotencyKey:"cancel-queued",correlationId:queued.task.correlationId,requestedAt:now,acknowledgedAt:null,completedAt:null};repository.requestCancellation(queuedCancellation);const maintenance=repository.maintainJobs({queue:"test",jobTypes:["synthetic"],workerId:"worker-a",now,limit:10,baseBackoffSeconds:5,maxBackoffSeconds:60});assert.equal(maintenance.cancelled,1);assert.equal(repository.job("org_account_a",queued.job.id)?.state,"cancelled");assert.equal(repository.attempts("org_account_a",queued.job.id).length,0);assert.equal(repository.cancellation("org_account_a",queued.task.id)?.state,"completed");
  const running=enqueue(repository,now,{id:"running-job"}),tokenHash=digest("running-token"),claim=repository.claimJob({queue:"test",jobTypes:["synthetic"],workerId:"worker-a",tokenHash,now,leaseSeconds:10})!;repository.requestCancellation({...queuedCancellation,id:crypto.randomUUID(),taskId:running.task.id,idempotencyKey:"cancel-running",correlationId:running.task.correlationId});const heartbeat=repository.heartbeatLease({organizationId:"org_account_a",jobId:running.job.id,attemptId:claim.attempt.id,workerId:"worker-a",tokenHash,now:now+1,leaseSeconds:10});assert.equal(heartbeat?.cancellationRequested,true);assert.equal(repository.cancellation("org_account_a",running.task.id)?.state,"acknowledged");assert.equal(repository.cancelAttempt({claim,workerId:"worker-a",tokenHash,now:now+2,reason:"Job cancellation requested"}),true);assert.equal(repository.job("org_account_a",running.job.id)?.state,"cancelled");assert.equal(repository.cancellation("org_account_a",running.task.id)?.state,"completed");
});

test("expired leases recover with backoff and eventually quarantine without duplicate active leases",async()=>{const{repository,now}=await fixture();const queued=enqueue(repository,now,{maxAttempts:2}),first=repository.claimJob({queue:"test",jobTypes:["synthetic"],workerId:"dead-a",tokenHash:digest("one"),now,leaseSeconds:5})!;let result=repository.maintainJobs({queue:"test",jobTypes:["synthetic"],workerId:"recovery",now:now+5,limit:10,baseBackoffSeconds:5,maxBackoffSeconds:60});assert.equal(result.recovered[0].state,"retrying");assert.equal(repository.lease("org_account_a",queued.job.id)?.state,"expired");assert.equal(repository.attempts("org_account_a",queued.job.id)[0].state,"timed_out");assert.equal(repository.job("org_account_a",queued.job.id)?.availableAt,now+10);assert.equal(first.attempt.attemptNumber,1);
  const second=repository.claimJob({queue:"test",jobTypes:["synthetic"],workerId:"dead-b",tokenHash:digest("two"),now:now+10,leaseSeconds:5})!;result=repository.maintainJobs({queue:"test",jobTypes:["synthetic"],workerId:"recovery",now:now+15,limit:10,baseBackoffSeconds:5,maxBackoffSeconds:60});assert.equal(result.recovered[0].state,"quarantined");assert.equal(repository.job("org_account_a",queued.job.id)?.state,"quarantined");assert.equal(second.attempt.attemptNumber,2);assert.equal(repository.attempts("org_account_a",queued.job.id).filter(attempt=>attempt.state==="timed_out").length,2);
});

test("graceful shutdown drains cooperative work and leaves forced work recoverable",async()=>{const first=await fixture();enqueue(first.repository,first.now);let release:()=>void=()=>{},started:()=>void=()=>{};const began=new Promise<void>(resolve=>{started=resolve;}),gate=new Promise<void>(resolve=>{release=resolve;});const cooperative=new ExecutionWorkerSupervisor(first.repository,{synthetic:{authorize:()=>{},execute:async()=>{started();await gate;}}},options({shutdownGraceMs:200}),{now:()=>first.now});cooperative.start();await began;const stopping=cooperative.stop();release();await stopping;assert.equal(first.database.prepare("SELECT state FROM execution_jobs").first<{state:string}>()?.state,"completed");assert.equal(cooperative.activeCount,0);
  const second=await fixture();const queued=enqueue(second.repository,second.now);let forcedStarted:()=>void=()=>{};const forcedBegan=new Promise<void>(resolve=>{forcedStarted=resolve;});const forced=new ExecutionWorkerSupervisor(second.repository,{synthetic:{authorize:()=>{},execute:async(_input,context)=>{forcedStarted();await new Promise((_resolve,reject)=>context.signal.addEventListener("abort",()=>reject(context.signal.reason),{once:true}));}}},options({shutdownGraceMs:10}),{now:()=>second.now});forced.start();await forcedBegan;await forced.stop();assert.equal(second.repository.job("org_account_a",queued.job.id)?.state,"running");assert.equal(second.repository.lease("org_account_a",queued.job.id)?.state,"active");const recovery=second.repository.maintainJobs({queue:"test",jobTypes:["synthetic"],workerId:"recovery",now:second.now+5,limit:10,baseBackoffSeconds:5,maxBackoffSeconds:60});assert.equal(recovery.recovered[0].state,"retrying");
});

test("process signal wiring performs one graceful shutdown",async()=>{const{repository,now}=await fixture();const signals=new EventEmitter(),supervisor=new ExecutionWorkerSupervisor(repository,{synthetic:{authorize:()=>{},execute:async()=>{}}},options(),{now:()=>now}),runtime=runSupervisedWorker(supervisor,signals);signals.emit("SIGTERM");await runtime.stopped;assert.equal(supervisor.activeCount,0);assert.equal(signals.listenerCount("SIGTERM"),0);assert.equal(signals.listenerCount("SIGINT"),0);
});
