import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import test from "node:test";
import { AppDatabase } from "../lib/database";
import { SqliteExecutionRepository } from "../platform/adapters/sqlite/execution-repository";
import type { ArtifactRecord, CancellationRequest, ExecutionAuditEvent, ExecutionIdempotencyRecord, ExecutionJob, ExecutionTask, InboxMessage, JobAttempt, JobLease, NotificationRecord, OutboxMessage, TaskProgressEvent } from "../platform/modules/execution";

function fixture(){const sqlite=new DatabaseSync(":memory:");sqlite.exec("PRAGMA foreign_keys=ON");const database=new AppDatabase(sqlite);database.exec(`
  CREATE TABLE users(id TEXT PRIMARY KEY);
  CREATE TABLE identity_organizations(id TEXT PRIMARY KEY);
  CREATE TABLE projects(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES identity_organizations(id));
  INSERT INTO users VALUES ('account_a'),('account_b');INSERT INTO identity_organizations VALUES ('org_a'),('org_b');INSERT INTO projects VALUES ('project_a','org_a'),('project_b','org_b');
`);const repository=new SqliteExecutionRepository(database);repository.ensureSchema();return{sqlite,database,repository};}
const now=1_786_200_000,hash="a".repeat(64),correlationId="correlation-1";
const task=(overrides:Partial<ExecutionTask>={}):ExecutionTask=>({id:"task_a",organizationId:"org_a",projectId:"project_a",requestedByAccountId:"account_a",triggerType:"manual",taskType:"seo_audit",capability:"audit.run",state:"queued",progress:0,cancellable:true,input:{depth:2},locale:"zh-CN",idempotencyKey:"task-request-1",correlationId,version:1,createdAt:now,updatedAt:now,startedAt:null,completedAt:null,...overrides});
const job=(overrides:Partial<ExecutionJob>={}):ExecutionJob=>({id:"job_a",organizationId:"org_a",projectId:"project_a",taskId:"task_a",queue:"seo",jobType:"audit",state:"queued",priority:60,availableAt:now,maxAttempts:3,timeoutSeconds:900,attemptCount:0,idempotencyKey:"job-request-1",correlationId,createdAt:now,updatedAt:now,completedAt:null,...overrides});
const attempt=(overrides:Partial<JobAttempt>={}):JobAttempt=>({id:"attempt_a",organizationId:"org_a",jobId:"job_a",taskId:"task_a",attemptNumber:1,workerId:"worker-1",state:"running",startedAt:now,finishedAt:null,errorCode:null,errorMessage:null,retryAt:null,correlationId,...overrides});

test("execution repository creates the complete durable kernel and scopes task/job reads",()=>{const{database,repository}=fixture();
  const tables=database.prepare("SELECT name FROM sqlite_master WHERE type='table' AND (name LIKE 'execution_%' OR name IN ('operations_notifications','operations_audit_events')) ORDER BY name").all<{name:string}>().results.map(row=>row.name);
  assert.deepEqual(tables,["execution_artifacts","execution_cancellations","execution_external_effects","execution_idempotency_keys","execution_inbox","execution_job_attempts","execution_job_leases","execution_jobs","execution_outbox","execution_progress_events","execution_tasks","operations_audit_events","operations_notifications"]);
  repository.createTask(task());repository.createJob(job());assert.equal(repository.task("org_a","task_a")?.input.depth,2);assert.equal(repository.task("org_b","task_a"),null);assert.equal(repository.taskByIdempotency("org_a","task-request-1")?.id,"task_a");assert.equal(repository.job("org_a","job_a")?.priority,60);assert.equal(repository.job("org_b","job_a"),null);
  assert.throws(()=>repository.createJob(job({id:"job_cross",organizationId:"org_b",projectId:"project_b",idempotencyKey:"cross"})),/FOREIGN KEY constraint failed/);
});

test("attempts, hashed leases, progress, and cancellation enforce bounded uniqueness",()=>{const{repository}=fixture();repository.createTask(task());repository.createJob(job());repository.appendAttempt(attempt());
  const lease:JobLease={id:"lease_a",organizationId:"org_a",jobId:"job_a",attemptId:"attempt_a",workerId:"worker-1",tokenHash:hash,state:"active",acquiredAt:now,heartbeatAt:now,expiresAt:now+60,releasedAt:null,version:1};repository.putLease(lease);
  assert.equal(repository.attempts("org_a","job_a")[0].state,"running");assert.equal(repository.lease("org_a","job_a")?.tokenHash,hash);assert.throws(()=>repository.putLease({...lease,id:"lease_b"}),/UNIQUE constraint failed/);
  const progress:TaskProgressEvent={id:"progress_1",organizationId:"org_a",projectId:"project_a",taskId:"task_a",attemptId:"attempt_a",sequence:1,progress:25,stage:"crawl",messageKey:"task.progress.crawl",metadata:{pages:5},correlationId,createdAt:now};repository.appendProgress(progress);assert.equal(repository.progress("org_a","task_a",10)[0].metadata.pages,5);assert.throws(()=>repository.appendProgress({...progress,id:"progress_2"}),/UNIQUE constraint failed/);
  const cancellation:CancellationRequest={id:"cancel_1",organizationId:"org_a",projectId:"project_a",taskId:"task_a",requestedByAccountId:"account_a",state:"requested",reason:"customer request",idempotencyKey:"cancel-request-1",correlationId,requestedAt:now,acknowledgedAt:null,completedAt:null};repository.requestCancellation(cancellation);assert.equal(repository.cancellation("org_a","task_a")?.reason,"customer request");assert.throws(()=>repository.requestCancellation({...cancellation,id:"cancel_2",idempotencyKey:"cancel-request-2"}),/UNIQUE constraint failed/);
});

test("idempotency, inbox, and outbox repositories reject duplicates and preserve delivery order",()=>{const{repository}=fixture();repository.createTask(task());
  const key:ExecutionIdempotencyRecord={id:"idem_1",organizationId:"org_a",scope:"task.create",idempotencyKey:"client-1",requestHash:hash,resourceType:"task",resourceId:"task_a",responseStatus:202,response:{accepted:true},expiresAt:now+86400,createdAt:now,updatedAt:now};repository.putIdempotency(key);assert.equal(repository.idempotency("org_a","task.create","client-1")?.response?.accepted,true);assert.throws(()=>repository.putIdempotency({...key,id:"idem_2"}),/UNIQUE constraint failed/);
  const first:OutboxMessage={id:"outbox_1",organizationId:"org_a",projectId:"project_a",aggregateType:"task",aggregateId:"task_a",eventType:"task.created",payload:{taskId:"task_a"},state:"pending",attempts:0,availableAt:now,publishedAt:null,lastError:null,idempotencyKey:"task-created-1",correlationId,createdAt:now};repository.appendOutbox(first);repository.appendOutbox({...first,id:"outbox_2",eventType:"task.later",idempotencyKey:"task-later",availableAt:now+60,createdAt:now+1});assert.deepEqual(repository.pendingOutbox(10,now).map(row=>row.id),["outbox_1"]);assert.throws(()=>repository.appendOutbox({...first,id:"outbox_duplicate"}),/UNIQUE constraint failed/);
  const inbox:InboxMessage={id:"inbox_1",organizationId:"org_a",source:"scheduler",messageId:"message-1",messageType:"schedule.fired",payloadHash:hash,payload:{scheduleId:"schedule-1"},state:"received",receivedAt:now,processedAt:null,lastError:null,correlationId};assert.equal(repository.recordInbox(inbox),true);assert.equal(repository.recordInbox({...inbox,id:"inbox_2"}),false);assert.equal(repository.inbox("scheduler","message-1")?.payload.scheduleId,"schedule-1");
});

test("artifacts, notifications, and append-only audits cannot cross tenant boundaries",()=>{const{database,repository}=fixture();repository.createTask(task());
  const artifact:ArtifactRecord={id:"artifact_1",organizationId:"org_a",projectId:"project_a",taskId:"task_a",attemptId:null,kind:"report",objectKey:"oneshowseo/org_a/project_a/task_a/report.json",sha256:hash,mimeType:"application/json",sizeBytes:120,scanState:"clean",retentionClass:"standard",expiresAt:now+86400,provenance:{source:"audit"},idempotencyKey:"artifact-task-a",createdAt:now};repository.appendArtifact(artifact);assert.equal(repository.artifact("org_a","artifact_1")?.mimeType,"application/json");assert.equal(repository.artifact("org_b","artifact_1"),null);assert.throws(()=>repository.appendArtifact({...artifact,id:"artifact_cross",organizationId:"org_b",projectId:"project_b",objectKey:"oneshowseo/org_b/cross",idempotencyKey:"cross"}),/FOREIGN KEY constraint failed/);
  const notification:NotificationRecord={id:"notification_1",organizationId:"org_a",accountId:"account_a",projectId:"project_a",taskId:"task_a",channel:"in_app",notificationType:"task_completed",locale:"zh-CN",titleKey:"notification.task.completed.title",bodyKey:"notification.task.completed.body",arguments:{taskId:"task_a"},state:"pending",idempotencyKey:"notify-task-a",availableAt:now,sentAt:null,readAt:null,lastError:null,createdAt:now,updatedAt:now};repository.appendNotification(notification);assert.equal(repository.notifications("org_a","account_a",10)[0].arguments.taskId,"task_a");assert.throws(()=>repository.appendNotification({...notification,id:"notification_cross",organizationId:"org_b",accountId:"account_b",projectId:"project_b",idempotencyKey:"cross"}),/FOREIGN KEY constraint failed/);
  const audit:ExecutionAuditEvent={id:"audit_1",organizationId:"org_a",projectId:"project_a",actorType:"user",actorId:"account_a",action:"task.create",targetType:"task",targetId:"task_a",outcome:"success",reason:null,policyVersion:"execution-v1",correlationId,metadata:{source:"manual"},occurredAt:now};repository.appendAudit(audit);assert.equal(repository.auditEvents("org_a",10)[0].action,"task.create");assert.throws(()=>database.prepare("UPDATE operations_audit_events SET action='changed' WHERE id='audit_1'").run(),/AUDIT_EVENTS_APPEND_ONLY/);assert.throws(()=>database.prepare("DELETE FROM operations_audit_events WHERE id='audit_1'").run(),/AUDIT_EVENTS_APPEND_ONLY/);
});

test("execution transaction rolls back task intent when a dependent write fails",()=>{const{repository}=fixture();assert.throws(()=>repository.transaction(()=>{repository.createTask(task({id:"task_rollback",idempotencyKey:"rollback"}));repository.createJob(job({id:"job_rollback",taskId:"missing",idempotencyKey:"rollback"}));}),/FOREIGN KEY constraint failed/);assert.equal(repository.task("org_a","task_rollback"),null);});
