import assert from "node:assert/strict";
import { randomBytes } from "node:crypto";
import { DatabaseSync } from "node:sqlite";
import test from "node:test";
import { AppDatabase } from "../lib/database";
import { SqliteIntegrationConnectionRepository } from "../platform/adapters/sqlite/integration-connection-repository";
import { providerDefinition, type ProviderAdapter } from "../platform/modules/integrations";
import { IntegrationConnectionError, IntegrationConnectionService, type IntegrationActor } from "../platform/modules/integrations/connections";
import { integrationSecretVault } from "../platform/modules/integrations/vault";

function fixture() {
  const db = new AppDatabase(new DatabaseSync(":memory:"));
  db.exec("PRAGMA foreign_keys=ON;CREATE TABLE projects(id TEXT,organization_id TEXT,status TEXT,UNIQUE(organization_id,id));INSERT INTO projects VALUES('project_a','org_a','active'),('project_b','org_b','active')");
  const repository = new SqliteIntegrationConnectionRepository(db);repository.ensureSchema();
  let disconnects=0,deletions=0;
  const adapter:ProviderAdapter={definition:providerDefinition("dataforseo")!,async checkHealth(){return{state:"healthy",checkedAt:101,latencyMs:15,error:null,rateLimit:{limit:100,remaining:99,resetsAt:200,retryAfterSeconds:null}};},async sync(){throw new Error("unused");},async disconnect(){disconnects++;return{disconnectedAt:102,remoteAuthorizationRevoked:true};},async deleteConnectionData(){deletions++;return{deletedAt:103,remoteDataDeleted:true,deletionReference:"deletion:1"};}};
  const vault=integrationSecretVault({INTEGRATION_VAULT_ACTIVE_KEY_VERSION:"v1",INTEGRATION_VAULT_KEYS:JSON.stringify({v1:randomBytes(32).toString("base64url")})});
  return{db,repository,service:new IntegrationConnectionService(repository,vault,new Map([["dataforseo",adapter]]),()=>100),calls:()=>({disconnects,deletions})};
}
const actor=(overrides:Partial<IntegrationActor>={}):IntegrationActor=>({accountId:"account_a",organizationId:"org_a",role:"owner",projectIds:new Set(["project_a"]),active:true,...overrides});
const entitlement={enabled:true,allowedProviders:new Set(["dataforseo"]),maxConnections:2};
const request={organizationId:"org_a",projectId:"project_a",providerId:"dataforseo",scopes:["serp.read"],secret:"super-secret-provider-key",environment:"production" as const,correlationId:"integration:connect:0001"};

test("tenant-scoped API-key connection stores only authenticated ciphertext and masked metadata",async()=>{const{db,service}=fixture(),view=await service.connectApiKey(actor(),entitlement,request);assert.equal(view.state,"connected");assert.equal(view.maskedHint,"••••-key");assert.equal(JSON.stringify(view).includes(request.secret),false);const row=db.prepare("SELECT encrypted_envelope envelope,key_version keyVersion FROM integration_credentials").first<{envelope:string;keyVersion:string}>()!;assert.equal(row.envelope.startsWith("sv1.v1."),true);assert.equal(row.envelope.includes(request.secret),false);assert.equal(row.keyVersion,"v1");assert.equal(db.prepare("SELECT COUNT(*) count FROM integration_audit_events WHERE action='integration.connected'").first<{count:number}>()?.count,1);assert.throws(()=>db.prepare("UPDATE integration_audit_events SET reason='changed'").run(),/INTEGRATION_AUDIT_APPEND_ONLY/);});

test("ownership, permission, provider, entitlement, and connection limits fail closed",async()=>{for(const invalid of [actor({organizationId:"org_b"}),actor({projectIds:new Set()}),actor({role:"viewer"}),actor({active:false})]){const item=fixture();await assert.rejects(item.service.connectApiKey(invalid,entitlement,request),error=>error instanceof IntegrationConnectionError&&error.code==="FORBIDDEN");}await assert.rejects(fixture().service.connectApiKey(actor(),{...entitlement,enabled:false},request),error=>error instanceof IntegrationConnectionError&&error.code==="ENTITLEMENT_REQUIRED");await assert.rejects(fixture().service.connectApiKey(actor(),{...entitlement,allowedProviders:new Set()},request),error=>error instanceof IntegrationConnectionError&&error.code==="ENTITLEMENT_REQUIRED");const limited=fixture();await limited.service.connectApiKey(actor(),entitlement,request);await assert.rejects(limited.service.connectApiKey(actor(),{...entitlement,maxConnections:1},{...request,correlationId:"integration:connect:0002"}),error=>error instanceof IntegrationConnectionError&&error.code==="LIMIT_REACHED");});

test("connection test persists coarse health and optimistic revisions",async()=>{const{db,service}=fixture(),connection=await service.connectApiKey(actor(),entitlement,request);const tested=await service.testConnection(actor(),{organizationId:"org_a",projectId:"project_a",connectionId:connection.id,expectedRevision:1,correlationId:"integration:test:0001"});assert.equal(tested.health?.state,"healthy");assert.equal(tested.revision,2);await assert.rejects(service.testConnection(actor(),{organizationId:"org_a",projectId:"project_a",connectionId:connection.id,expectedRevision:1,correlationId:"integration:test:0002"}),error=>error instanceof IntegrationConnectionError&&error.code==="STATE_CONFLICT");assert.equal(db.prepare("SELECT COUNT(*) count FROM integration_audit_events WHERE action='integration.tested'").first<{count:number}>()?.count,1);});

test("disconnect revokes credentials and deletion is soft, audited, and cross-tenant safe",async()=>{const first=fixture(),connection=await first.service.connectApiKey(actor(),entitlement,request),credentialId=first.repository.credential(connection.id)!.id,disconnected=await first.service.disconnect(actor(),{organizationId:"org_a",projectId:"project_a",connectionId:connection.id,expectedRevision:1,reason:"No longer needed",correlationId:"integration:disconnect:0001"});assert.equal(disconnected.state,"disconnected");assert.equal(first.repository.credential(connection.id)?.revokedAt,100);assert.equal(first.repository.credentialContext(credentialId),null);assert.equal(first.calls().disconnects,1);const second=fixture(),other=await second.service.connectApiKey(actor(),entitlement,request);await assert.rejects(second.service.delete(actor({organizationId:"org_b",projectIds:"*"}),{organizationId:"org_a",projectId:"project_a",connectionId:other.id,expectedRevision:1,reason:"cross tenant",correlationId:"integration:delete:0001"}),/没有管理/);const deleted=await second.service.delete(actor(),{organizationId:"org_a",projectId:"project_a",connectionId:other.id,expectedRevision:1,reason:"Customer requested",correlationId:"integration:delete:0002"});assert.equal(deleted.deleted,true);assert.equal(second.calls().deletions,1);assert.equal(second.db.prepare("SELECT COUNT(*) count FROM integration_connections WHERE deleted_at IS NOT NULL").first<{count:number}>()?.count,1);});
