import assert from "node:assert/strict";
import { mkdtempSync,readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

process.env.DATABASE_PATH=join(mkdtempSync(join(tmpdir(),"oneshowseo-models-")),"test.sqlite");
process.env.MODEL_CONFIG_ENCRYPTION_KEY="commercial-model-encryption-key-2026";

test("model credentials are encrypted, omitted from listings, and resolved only for server runtime",async()=>{const {ensureAuthSchema,getDatabase}=await import("../lib/auth");await ensureAuthSchema();const now=Math.floor(Date.now()/1000);getDatabase().prepare("INSERT OR IGNORE INTO users (id,email,name,password_hash,role,status,plan,email_verified_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)").bind("model-admin","model-admin@test.local","Admin","test","admin","active","business",now,now,now).run();const {getDefaultModelConfig,listModelProviders,saveModelProvider}=await import("../lib/model-providers");await saveModelProvider({provider:"deepseek",enabled:true,isDefault:true,baseUrl:"https://api.deepseek.com",model:"deepseek-chat",apiKey:"secret-model-key",temperature:.5,maxOutputTokens:4096},"model-admin");const providers=await listModelProviders();assert.equal(JSON.stringify(providers).includes("secret-model-key"),false);assert.equal(providers.find(item=>item.provider==="deepseek")?.isDefault,true);assert.equal((await getDefaultModelConfig())?.apiKey,"secret-model-key");const stored=getDatabase().prepare("SELECT encrypted_api_key AS value FROM platform_model_providers WHERE provider='deepseek'").first<{value:string}>();assert.equal(stored?.value.includes("secret-model-key"),false);});

test("model endpoints cannot be redirected to arbitrary hosts",async()=>{const {saveModelProvider}=await import("../lib/model-providers");await assert.rejects(()=>saveModelProvider({provider:"deepseek",enabled:false,isDefault:false,baseUrl:"https://example.com/v1",model:"deepseek-chat",temperature:.4,maxOutputTokens:4000},"model-admin"),/MODEL_ENDPOINT_INVALID/);});

test("content generation uses the enabled server-side model without exposing its key",async()=>{const {generateWithDefaultModel}=await import("../lib/model-providers"),original=globalThis.fetch;let authorization="";globalThis.fetch=async(_input,init)=>{authorization=String((init?.headers as Record<string,string>)?.authorization||"");return new Response(JSON.stringify({choices:[{message:{content:"# 模型草稿\n\n## 常见问题\n\n可审核内容"}}]}),{status:200,headers:{"content-type":"application/json"}})};try{const output=await generateWithDefaultModel({title:"模型内容",keyword:"内容模型",contentType:"guide",audience:"产品团队",intent:"研究",tone:"专业",goal:"完成内容",evidence:[{sourceRef:"https://example.com",summary:"可验证来源"}]});assert.equal(output?.markdown.startsWith("# 模型草稿"),true);assert.equal(output?.provider,"DeepSeek");assert.equal(authorization,"Bearer secret-model-key");assert.equal(JSON.stringify(output).includes("secret-model-key"),false);}finally{globalThis.fetch=original;}});

test("commercial model administration and content studio expose truthful model state",()=>{const navigation=readFileSync(new URL("../app/admin/AdminNavigation.tsx",import.meta.url),"utf8"),route=readFileSync(new URL("../app/api/admin/model-providers/route.ts",import.meta.url),"utf8"),studio=readFileSync(new URL("../app/workspace/ContentCreationStudio.tsx",import.meta.url),"utf8");assert.match(navigation,/\/admin\/models/);assert.match(route,/writeAudit/);assert.doesNotMatch(route,/encrypted_api_key/);assert.match(studio,/内容模型未配置/);assert.match(studio,/结构化草稿模式/);});
