import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import test from "node:test";
import { ensureAuthSchema } from "../lib/auth";
import { AppDatabase } from "../lib/database";
import { SqliteExecutionRepository } from "../platform/adapters/sqlite/execution-repository";
import { SqliteNotificationRepository } from "../platform/adapters/sqlite/notification-repository";
import { NotificationError, NotificationService, RecoveryLinkSigner, redactNotificationArguments, renderNotification } from "../platform/modules/notifications";

const now=1_786_500_000;
async function fixture(){const sqlite=new DatabaseSync(":memory:");sqlite.exec("PRAGMA foreign_keys=ON");const database=new AppDatabase(sqlite);await ensureAuthSchema(database);database.prepare("INSERT INTO users(id,email,name,password_hash,role,status,plan,email_verified_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)").bind("account_a","owner@example.com","Owner","hash","user","active","trial",now,now,now).run();await ensureAuthSchema(database);database.exec("CREATE TABLE projects(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES identity_organizations(id));");new SqliteExecutionRepository(database).ensureSchema();const repository=new SqliteNotificationRepository(database);repository.ensureSchema();const service=new NotificationService(repository,new RecoveryLinkSigner("s".repeat(32)),()=>now);return{sqlite,database,repository,service};}

test("bilingual preferences use optimistic concurrency and control each channel",async()=>{const{service}=await fixture();assert.equal(service.preference({organizationId:"org_account_a",accountId:"account_a",notificationType:"task_failed"}).locale,"zh-CN");const preference=service.updatePreference({organizationId:"org_account_a",accountId:"account_a",notificationType:"task_failed",inAppEnabled:true,emailEnabled:false,locale:"en",expectedVersion:0});assert.equal(preference.version,1);assert.throws(()=>service.updatePreference({...preference,expectedVersion:0}),error=>error instanceof NotificationError&&error.code==="PREFERENCE_CONFLICT");const created=service.enqueue({organizationId:"org_account_a",accountId:"account_a",notificationType:"task_failed",arguments:{taskName:"Audit"},idempotencyKey:"task-a:failed",correlationId:"corr-a"});assert.equal(created.length,1);assert.equal(created[0].channel,"in_app");assert.equal(service.list("org_account_a","account_a")[0].title,"Task failed");});

test("notification enqueue is channel-scoped idempotent and redacts sensitive arguments",async()=>{const{service,database}=await fixture(),input={organizationId:"org_account_a",accountId:"account_a",notificationType:"task_completed",arguments:{taskName:"Audit",apiKey:"sk-super-secret-value",nested:{authorization:"Bearer abcdefghijklmnop"}},idempotencyKey:"task-a:done",correlationId:"corr-a"};assert.equal(service.enqueue(input).length,2);assert.equal(service.enqueue(input).length,0);assert.equal(database.prepare("SELECT COUNT(*) count FROM operations_notifications").first<{count:number}>()?.count,2);const item=service.list("org_account_a","account_a")[0];assert.equal(item.arguments.apiKey,"[REDACTED]");assert.deepEqual((item.arguments.nested as Record<string,unknown>).authorization,"[REDACTED]");assert.equal(item.arguments.correlationId,"corr-a");assert.equal(JSON.stringify(redactNotificationArguments({message:"Bearer abcdefghijklmnop"})).includes("abcdefghijklmnop"),false);});

test("recovery links are short lived, account scoped, and reject external destinations",async()=>{const{service}=await fixture();const notification=service.enqueue({organizationId:"org_account_a",accountId:"account_a",notificationType:"task_quarantined",arguments:{taskName:"Audit"},idempotencyKey:"task-a:q",correlationId:"corr-q"}).find(item=>item.channel==="in_app")!;const issued=service.recovery({origin:"https://oneshowseo.com/path",organizationId:"org_account_a",accountId:"account_a",notificationId:notification.id,destination:"/tasks?id=task-a"});assert.match(issued.url,/^https:\/\/oneshowseo\.com\/api\/notifications\/recover\?token=/);const token=new URL(issued.url).searchParams.get("token")!;assert.equal(service.consumeRecovery(token,{organizationId:"org_account_a",accountId:"account_a"}),"/tasks?id=task-a");assert.equal(service.list("org_account_a","account_a").find(item=>item.id===notification.id)?.state,"read");assert.throws(()=>service.consumeRecovery(token,{organizationId:"org_account_a",accountId:"other"}),error=>error instanceof NotificationError&&error.code==="RECOVERY_SCOPE_MISMATCH");assert.throws(()=>service.recovery({origin:"https://oneshowseo.com",organizationId:"org_account_a",accountId:"account_a",notificationId:notification.id,destination:"https://evil.example"}),/恢复目标地址无效/);});

test("notification migration preserves delivery evidence and least-privilege grants",async()=>{const sql=await import("node:fs/promises").then(fs=>fs.readFile(new URL("../platform/adapters/postgres/migrations/0010_expand_notifications.sql",import.meta.url),"utf8"));assert.match(sql,/CREATE TABLE operations\.notification_preferences/);assert.match(sql,/CREATE TABLE operations\.notification_deliveries/);assert.match(sql,/UNIQUE \(notification_id,attempt_number\)/);assert.match(sql,/oneshowseo_app/);assert.match(sql,/oneshowseo_worker/);});

test("email delivery records outcome, provider reference, and redacted retry errors",async()=>{const{service,database}=await fixture();const email=service.enqueue({organizationId:"org_account_a",accountId:"account_a",notificationType:"security_alert",idempotencyKey:"security-a",correlationId:"corr-security"}).find(item=>item.channel==="email")!;const sent=await service.deliverEmail(email,"owner@example.com",{send:async input=>{assert.equal(input.locale,"zh-CN");assert.match(input.recoveryUrl!,/token=/);return{providerReference:"provider-1"};}},{origin:"https://oneshowseo.com",destination:"/settings"});assert.equal(sent.state,"sent");const delivery=database.prepare("SELECT state,provider_reference providerReference FROM operations_notification_deliveries").first<{state:string;providerReference:string}>()!;assert.equal(delivery.state,"sent");assert.equal(delivery.providerReference,"provider-1");assert.deepEqual(await service.deliverEmail(email,"owner@example.com",{send:async()=>{throw new Error("must not send");}},{origin:"https://oneshowseo.com"}),{duplicate:true});
  const failed=service.enqueue({organizationId:"org_account_a",accountId:"account_a",notificationType:"task_failed",arguments:{taskName:"Audit"},idempotencyKey:"task-fail-email",correlationId:"corr-fail"}).find(item=>item.channel==="email")!;const result=await service.deliverEmail(failed,"owner@example.com",{send:async()=>{throw new Error("timeout Bearer abcdefghijklmnop");}},{origin:"https://oneshowseo.com"});assert.equal(result.state,"retrying");const stored=database.prepare("SELECT state,last_error lastError FROM operations_notifications WHERE id=?").bind(failed.id).first<{state:string;lastError:string}>()!;assert.equal(stored.state,"pending");assert.equal(stored.lastError.includes("abcdefghijklmnop"),false);
});

test("template rendering is complete in Chinese and English",()=>{assert.equal(renderNotification("task_completed","zh-CN",{taskName:"审计"}).body,"任务 审计 已完成。");assert.equal(renderNotification("task_completed","en",{taskName:"Audit"}).body,"Task Audit completed.");});
