import assert from "node:assert/strict";
import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { LocalObjectStorageProvider } from "../platform/adapters/object-storage/local-object-storage";
import type { ArtifactRecord } from "../platform/modules/execution";
import { ArtifactObjectService, ObjectStorageError, SignatureArtifactScanner, type ArtifactCatalog } from "../platform/modules/execution/object-storage";

class Catalog implements ArtifactCatalog{records=new Map<string,ArtifactRecord>();bytes=0;artifact(organizationId:string,artifactId:string){const value=this.records.get(artifactId);return value?.organizationId===organizationId?value:null;}artifactStorageBytes(){return this.bytes;}}
async function fixture(){const root=await mkdtemp(join(tmpdir(),"oneshowseo-objects-")),provider=new LocalObjectStorageProvider(root),catalog=new Catalog();let now=1_786_500_000;const service=new ArtifactObjectService(provider,catalog,new SignatureArtifactScanner(),"a-secure-object-signing-secret-with-more-than-32-bytes","/api/artifacts/download",()=>now);return{root,provider,catalog,service,get now(){return now;},set now(value:number){now=value;}};}
const input=(body=new TextEncoder().encode('{"ok":true}'))=>({organizationId:"org-a",projectId:"project-a",taskId:"task-a",attemptId:"attempt-a",artifactId:"artifact-a",kind:"report",filename:"report.json",mimeType:"application/json",body,provenance:{agentVersion:"1.0.0"},idempotencyKey:"artifact-a",correlationId:"correlation-a",storageLimitBytes:1024,retentionDays:30});

test("provider-neutral storage writes immutable tenant/project/task keys with hashes and retention",async()=>{const state=await fixture(),artifact=await state.service.store(input());assert.match(artifact.objectKey,/^oneshowseo\/org-a\/project-a\/task-a\/artifact-a\/report\.json$/);assert.equal(artifact.sha256.length,64);assert.equal(artifact.sizeBytes,11);assert.equal(artifact.scanState,"clean");assert.equal(artifact.expiresAt,state.now+30*86400);assert.deepEqual(await state.provider.read(artifact.objectKey),input().body);assert.equal((await state.provider.health()).ok,true);const retry=await state.service.store(input());assert.equal(retry.sha256,artifact.sha256);await assert.rejects(()=>state.service.store(input(new TextEncoder().encode('{"ok":false}'))),/IMMUTABLE_OBJECT_CONFLICT/);
});

test("short-lived access is tenant/project authorized, signed, expiry-bound, and integrity checked",async()=>{const state=await fixture(),artifact=await state.service.store(input());state.catalog.records.set(artifact.id,artifact);const access=state.service.authorizeAccess({activeOrganizationId:"org-a",organizationId:"org-a",activeProjectId:"project-a",artifactId:"artifact-a",ttlSeconds:60}),token=new URL(`https://example.test${access.url}`).searchParams.get("token")!;const resolved=await state.service.resolveAccess(token);assert.equal(resolved.artifact.id,"artifact-a");assert.deepEqual(resolved.body,input().body);assert.throws(()=>state.service.authorizeAccess({activeOrganizationId:"org-b",organizationId:"org-a",activeProjectId:"project-a",artifactId:"artifact-a"}),error=>error instanceof ObjectStorageError&&error.code==="TENANT_MISMATCH");assert.throws(()=>state.service.authorizeAccess({activeOrganizationId:"org-a",organizationId:"org-a",activeProjectId:"project-b",artifactId:"artifact-a"}),error=>error instanceof ObjectStorageError&&error.code==="ARTIFACT_NOT_FOUND");await assert.rejects(()=>state.service.resolveAccess(`${token}x`),error=>error instanceof ObjectStorageError&&error.code==="INVALID_ARTIFACT_TOKEN");state.now+=61;await assert.rejects(()=>state.service.resolveAccess(token),error=>error instanceof ObjectStorageError&&error.code==="ARTIFACT_TOKEN_EXPIRED");
});

test("MIME, size, quota, scan, metadata, filename, and signing policies fail closed",async()=>{const state=await fixture();await assert.rejects(()=>state.service.store({...input(),mimeType:"image/svg+xml"}),error=>error instanceof ObjectStorageError&&error.code==="MIME_NOT_ALLOWED");await assert.rejects(()=>state.service.store({...input(),mimeType:"application/pdf"}),error=>error instanceof ObjectStorageError&&error.code==="MIME_MISMATCH");await assert.rejects(()=>state.service.store(input(new Uint8Array())),error=>error instanceof ObjectStorageError&&error.code==="ARTIFACT_SIZE_INVALID");state.catalog.bytes=1020;await assert.rejects(()=>state.service.store(input()),error=>error instanceof ObjectStorageError&&error.code==="STORAGE_LIMIT_REACHED");state.catalog.bytes=0;await assert.rejects(()=>state.service.store({...input(new TextEncoder().encode("EICAR-STANDARD-ANTIVIRUS-TEST-FILE")),mimeType:"text/plain"}),error=>error instanceof ObjectStorageError&&error.code==="ARTIFACT_BLOCKED");await assert.rejects(()=>state.service.store({...input(),provenance:{apiToken:"secret"}}),error=>error instanceof ObjectStorageError&&error.code==="SENSITIVE_ARTIFACT_METADATA");await assert.rejects(()=>state.service.store({...input(),filename:"../secret.json"}),error=>error instanceof ObjectStorageError&&error.code==="INVALID_ARTIFACT_FILENAME");assert.throws(()=>new ArtifactObjectService(state.provider,state.catalog,new SignatureArtifactScanner(),"short"),error=>error instanceof ObjectStorageError&&error.code==="SIGNING_SECRET_INVALID");
});

test("expired or unscanned catalog artifacts never receive or resolve access",async()=>{const state=await fixture(),artifact=await state.service.store(input());state.catalog.records.set(artifact.id,{...artifact,scanState:"blocked"});assert.throws(()=>state.service.authorizeAccess({activeOrganizationId:"org-a",organizationId:"org-a",activeProjectId:"project-a",artifactId:"artifact-a"}),error=>error instanceof ObjectStorageError&&error.code==="ARTIFACT_NOT_AVAILABLE");state.catalog.records.set(artifact.id,{...artifact,expiresAt:state.now});assert.throws(()=>state.service.authorizeAccess({activeOrganizationId:"org-a",organizationId:"org-a",activeProjectId:"project-a",artifactId:"artifact-a"}),error=>error instanceof ObjectStorageError&&error.code==="ARTIFACT_EXPIRED");
});
