import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { mkdtemp, readFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { ensureAuthSchema } from "../lib/auth";
import { ensureBillingSchema, commerceRepository } from "../lib/billing";
import { AppDatabase } from "../lib/database";
import { atomicTaskCreationService, executionRepository, executionWorkerSupervisor } from "../lib/execution";
import { ensureProductSchema } from "../lib/product";
import { auditWorkerHandler } from "../lib/production-worker";
import { permissions } from "../platform/modules/identity/authorization";

test("production audit worker creates a report and commits reserved Credits",async()=>{
 const sqlite=new DatabaseSync(":memory:");sqlite.exec("PRAGMA foreign_keys=ON");const database=new AppDatabase(sqlite);globalThis.__oneShowSeoDatabase=database;const now=Math.floor(Date.now()/1000),root=await mkdtemp(path.join(os.tmpdir(),"oneshowseo-worker-"));process.env.OBJECT_STORAGE_ROOT=root;process.env.OBJECT_STORAGE_SIGNING_SECRET="worker-test-signing-secret-that-is-long-enough";
 await ensureAuthSchema(database);database.prepare("INSERT INTO users(id,email,name,password_hash,role,status,plan,trial_ends_at,email_verified_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)").bind("worker_account","worker@example.com","Worker Owner","hash","user","active","trial",now+86400,now,now-100,now-100).run();await ensureAuthSchema(database);await ensureProductSchema();database.prepare("INSERT INTO projects(id,user_id,name,site_url,host,market,language,timezone,business_goal,approval_mode,schedule_enabled,created_at,updated_at,organization_id,slug,status,business_type,search_engines,version) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind("worker_project","worker_account","Worker Project","https://example.com/","example.com","US","en","UTC","organic_growth","required",0,now,now,"org_worker_account","worker-project","active","website",'["google"]',1).run();await ensureBillingSchema();
 const subject={accountId:"worker_account",organizationId:"org_worker_account",organizationStatus:"trial" as const,planKey:"trial" as const,trialEndsAt:now+86400,accountCreatedAt:now-100},created=(await atomicTaskCreationService()).create({activeOrganizationId:subject.organizationId,organizationId:subject.organizationId,projectId:"worker_project",requestedByAccountId:subject.accountId,role:"owner",permission:permissions.auditsRun,subject,triggerType:"manual",taskType:"seo_audit",capability:"audit.run",input:{projectId:"worker_project",siteUrl:"https://example.com/",pageLimit:10},locale:"en",idempotencyKey:"audit:worker:test:0001",correlationId:"worker-test-correlation",entitlements:[{key:"pagesPerAudit",quantity:1,currentUsage:0}],creditCost:10,queue:"agents",jobType:"seo.audit",priority:80,maxAttempts:1,timeoutSeconds:60});
 const handler=auditWorkerHandler({executeAudit:async()=>({runId:"worker-run",score:91,pagesScanned:2,urlsDiscovered:2,findingCount:1,evidenceCount:3,partial:false,partialReasons:[],degradedSources:[],report:new TextEncoder().encode("# Verified SEO audit report\n\nEvidence attached."),reportTitle:"Worker SEO Audit"})}),supervisor=await executionWorkerSupervisor({"seo.audit":handler},{workerId:"worker-test",queue:"agents",concurrency:1,pollIntervalMs:10,leaseSeconds:10,heartbeatIntervalMs:100,shutdownGraceMs:100,maintenanceLimit:10,baseBackoffSeconds:1,maxBackoffSeconds:10});
 assert.equal(await supervisor.runOne(),true);const attempts=executionRepository().attempts(subject.organizationId,created.job.id);assert.equal(executionRepository().task(subject.organizationId,created.task.id)?.state,"completed",JSON.stringify(attempts));assert.equal(executionRepository().job(subject.organizationId,created.job.id)?.state,"completed",JSON.stringify(attempts));const artifacts=database.prepare("SELECT object_key AS objectKey FROM execution_artifacts WHERE task_id=?").bind(created.task.id).all<{objectKey:string}>().results;assert.equal(artifacts.length,1);assert.match(await readFile(path.join(root,artifacts[0].objectKey),"utf8"),/Verified SEO audit report/);const terminal=commerceRepository().terminalForReservation(subject.organizationId,created.reservationId!);assert.equal(terminal?.entryType,"commit");const balance=commerceRepository().creditBalance(subject.organizationId,now+1);assert.equal(balance.committed,10);assert.equal(balance.reserved,0);
});
