import assert from "node:assert/strict";
import {DatabaseSync} from "node:sqlite";
import test from "node:test";
import {ensureAuthSchema} from "../lib/auth";
import {AppDatabase} from "../lib/database";
import {ensureProductSchema} from "../lib/product";
import {executeResearchAgent} from "../lib/research-execution";
import type {ResearchSourceAcquirer} from "../platform/modules/agents/research-agent";

test("Research execution persists evidence and opportunities idempotently by task id",async()=>{
 const sqlite=new DatabaseSync(":memory:");sqlite.exec("PRAGMA foreign_keys=ON");const database=new AppDatabase(sqlite);globalThis.__oneShowSeoDatabase=database;const now=Math.floor(Date.now()/1000);await ensureAuthSchema(database);database.prepare("INSERT INTO users(id,email,name,password_hash,role,status,plan,trial_ends_at,email_verified_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)").bind("research_exec_account","exec@example.com","Exec Owner","hash","user","active","trial",now+86400,now,now,now).run();await ensureAuthSchema(database);await ensureProductSchema();database.prepare("INSERT INTO projects(id,user_id,name,site_url,host,market,language,timezone,business_goal,approval_mode,schedule_enabled,created_at,updated_at,organization_id,slug,status,business_type,search_engines,version) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind("research_exec_project","research_exec_account","Exec Project","https://example.com/","example.com","CN","zh-CN","Asia/Shanghai","growth","required",0,now,now,"org_research_exec_account","exec-project","active","website",'["google"]',1).run();
 const acquirer:ResearchSourceAcquirer={acquire:async()=>({capturedAt:now,freshUntil:now+86400,sourceRef:"https://example.com/",pages:[{url:"https://example.com/",title:"AI SEO Research",description:"Evidence-led SEO opportunities",statusCode:200}],degradedSources:["google_search_console","rank_provider"]})},input={projectId:"research_exec_project",siteUrl:"https://example.com/",market:"CN",language:"zh-CN",maximumPages:10},context={organizationId:"org_research_exec_account",taskId:"research_task_0001",jobId:"research_job_0001",attemptId:"research_attempt_0001",accountId:"research_exec_account",correlationId:"research_correlation_0001",locale:"zh-CN" as const};
 const first=await executeResearchAgent(input,context,undefined,{acquirer}),second=await executeResearchAgent(input,{...context,attemptId:"research_attempt_0002"},undefined,{acquirer});assert.equal(first.opportunitiesFound,1);assert.equal(second.runId,first.runId);assert.equal(database.prepare("SELECT COUNT(*) count FROM research_runs").first<{count:number}>()?.count,1);assert.equal(database.prepare("SELECT COUNT(*) count FROM research_evidence").first<{count:number}>()?.count,1);assert.equal(database.prepare("SELECT COUNT(*) count FROM research_opportunities").first<{count:number}>()?.count,1);const row=database.prepare("SELECT search_volume searchVolume,keyword_difficulty keywordDifficulty,evidence_refs evidenceRefs FROM research_opportunities").first<{searchVolume:number|null;keywordDifficulty:number|null;evidenceRefs:string}>();assert.equal(row?.searchVolume,null);assert.equal(row?.keywordDifficulty,null);assert.equal(JSON.parse(row!.evidenceRefs).length,1);assert.match(new TextDecoder().decode(first.report),/不进行估算/);
});
