import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { DatabaseSync } from "node:sqlite";
import test from "node:test";
import { ensureAuthSchema } from "../lib/auth";
import { AppDatabase } from "../lib/database";
import { SqliteCommerceRepository } from "../platform/adapters/sqlite/commerce-repository";
import { SqliteExecutionProjectGate } from "../platform/adapters/sqlite/execution-project-gate";
import { SqliteExecutionRepository } from "../platform/adapters/sqlite/execution-repository";
import { CommercialEntitlementService } from "../platform/modules/commerce/service";
import type { ArtifactRecord, ExecutionSettlementRepository, ExternalEffectRecord, NotificationRecord } from "../platform/modules/execution";
import { AtomicTaskCreationService, type AtomicTaskCreationInput } from "../platform/modules/execution/task-creation";
import { AtomicTaskSettlementService, TaskSettlementError, type AtomicTaskSettlementInput, type TaskTerminalState } from "../platform/modules/execution/task-settlement";
import { permissions } from "../platform/modules/identity/authorization";

const sha=(value:string)=>createHash("sha256").update(value).digest("hex");
async function fixture(){const sqlite=new DatabaseSync(":memory:");sqlite.exec("PRAGMA foreign_keys=ON");const database=new AppDatabase(sqlite);await ensureAuthSchema(database);const now=1_786_400_000;database.prepare("INSERT INTO users(id,email,name,password_hash,role,status,plan,trial_ends_at,email_verified_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)").bind("account_a","owner@example.com","Owner","hash","user","active","trial",now+14*86400,now,now-100,now-100).run();await ensureAuthSchema(database);database.exec("CREATE TABLE projects(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES identity_organizations(id),status TEXT NOT NULL);INSERT INTO projects VALUES ('project_a','org_account_a','active')");const commerceRepository=new SqliteCommerceRepository(database),commerce=new CommercialEntitlementService(commerceRepository,()=>now),execution=new SqliteExecutionRepository(database),creation=new AtomicTaskCreationService(execution,commerce,new SqliteExecutionProjectGate(database),()=>now),settlement=new AtomicTaskSettlementService(execution,commerce,()=>now+20);return{sqlite,database,commerceRepository,commerce,execution,creation,settlement,now};}
function request(now:number):AtomicTaskCreationInput{return{activeOrganizationId:"org_account_a",organizationId:"org_account_a",projectId:"project_a",requestedByAccountId:"account_a",role:"owner",permission:permissions.auditsRun,subject:{accountId:"account_a",organizationId:"org_account_a",organizationStatus:"trial",planKey:"trial",trialEndsAt:now+14*86400,accountCreatedAt:now-100},triggerType:"manual",taskType:"seo_audit",capability:"audit.run",input:{depth:2},locale:"zh-CN",idempotencyKey:"task-create",correlationId:"correlation-settle",entitlements:[{key:"pagesPerAudit",quantity:10,currentUsage:0}],creditCost:100,queue:"seo",jobType:"audit",priority:70,maxAttempts:3,timeoutSeconds:900};}
function claim(execution:SqliteExecutionRepository,now:number){const tokenHash=sha("lease-token"),value=execution.claimJob({queue:"seo",jobTypes:["audit"],workerId:"worker-a",tokenHash,now:now+1,leaseSeconds:30});assert.ok(value);return{value,tokenHash};}
function records(created:ReturnType<AtomicTaskCreationService["create"]>,attemptId:string,now:number){const artifact:ArtifactRecord={id:"artifact-a",organizationId:"org_account_a",projectId:"project_a",taskId:created.task.id,attemptId,kind:"audit_report",objectKey:`oneshowseo/org_account_a/project_a/${created.task.id}/artifact-a/report.json`,sha256:sha("artifact"),mimeType:"application/json",sizeBytes:128,scanState:"clean",retentionClass:"days:30",expiresAt:now+30*86400,provenance:{agentVersion:"1.0.0"},idempotencyKey:"artifact-a",createdAt:now+10},notification:NotificationRecord={id:"notification-a",organizationId:"org_account_a",accountId:"account_a",projectId:"project_a",taskId:created.task.id,channel:"in_app",notificationType:"task_completed",locale:"zh-CN",titleKey:"task.completed.title",bodyKey:"task.completed.body",arguments:{taskId:created.task.id},state:"pending",idempotencyKey:"notification-a",availableAt:now+20,sentAt:null,readAt:null,lastError:null,createdAt:now+20,updatedAt:now+20},effect:ExternalEffectRecord={id:"effect-a",organizationId:"org_account_a",projectId:"project_a",taskId:created.task.id,attemptId,provider:"search-provider",operation:"read_serp",externalReference:"provider-run-1",requestHash:sha("bounded-request"),state:"succeeded",evidence:{statusCode:200},errorCode:null,idempotencyKey:"effect-a",correlationId:created.task.correlationId,createdAt:now+5,updatedAt:now+10};return{artifact,notification,effect};}
function settlementInput(created:ReturnType<AtomicTaskCreationService["create"]>,attemptId:string,now:number,overrides:Partial<AtomicTaskSettlementInput>={}):AtomicTaskSettlementInput{const{artifact,notification,effect}=records(created,attemptId,now);return{organizationId:"org_account_a",projectId:"project_a",taskId:created.task.id,jobId:created.job.id,attemptId,state:"completed",subject:request(now).subject,reservationId:created.reservationId,artifacts:[artifact],notifications:[notification],externalEffects:[effect],idempotencyKey:"settle-task",correlationId:created.task.correlationId,...overrides};}

test("successful terminal settlement atomically commits Credits, task state, artifacts, notifications, effects, event, and audit",async()=>{const{database,commerceRepository,execution,creation,settlement,now}=await fixture(),created=creation.create(request(now)),leased=claim(execution,now);assert.equal(execution.succeedAttempt({claim:leased.value,workerId:"worker-a",tokenHash:leased.tokenHash,now:now+10}),true);const input=settlementInput(created,leased.value.attempt.id,now);execution.appendExternalEffect({...input.externalEffects[0],externalReference:null,state:"pending",evidence:{},updatedAt:now+5});const result=settlement.settle(input);assert.equal(result.duplicate,false);assert.equal(execution.task("org_account_a",created.task.id)?.state,"completed");assert.equal(execution.task("org_account_a",created.task.id)?.progress,100);assert.equal(database.prepare("SELECT COUNT(*) count FROM execution_artifacts").first<{count:number}>()?.count,1);assert.equal(database.prepare("SELECT COUNT(*) count FROM operations_notifications").first<{count:number}>()?.count,1);assert.equal(database.prepare("SELECT COUNT(*) count FROM execution_external_effects").first<{count:number}>()?.count,1);assert.equal(execution.externalEffect("org_account_a","search-provider","effect-a")?.state,"succeeded");assert.equal(database.prepare("SELECT COUNT(*) count FROM execution_outbox WHERE event_type='execution.task.settled'").first<{count:number}>()?.count,1);assert.equal(commerceRepository.terminalForReservation("org_account_a",created.reservationId!)?.entryType,"commit");assert.equal(commerceRepository.creditBalance("org_account_a",now+20).reserved,0);
  const duplicate=settlement.settle(input);assert.equal(duplicate.duplicate,true);assert.equal(duplicate.creditEntryId,result.creditEntryId);assert.equal(database.prepare("SELECT COUNT(*) count FROM commerce_credit_ledger WHERE entry_type='commit'").first<{count:number}>()?.count,1);assert.throws(()=>settlement.settle({...input,notifications:[]}),error=>error instanceof TaskSettlementError&&error.code==="IDEMPOTENCY_CONFLICT");
});

test("failed, cancelled, and quarantined jobs release their reservation exactly once",async()=>{for(const state of ["failed","cancelled","quarantined"] as TaskTerminalState[]){const{database,commerceRepository,execution,creation,settlement,now}=await fixture(),created=creation.create(request(now)),leased=claim(execution,now);if(state==="cancelled")execution.cancelAttempt({claim:leased.value,workerId:"worker-a",tokenHash:leased.tokenHash,now:now+10,reason:"cancelled"});else execution.failAttempt({claim:leased.value,workerId:"worker-a",tokenHash:leased.tokenHash,now:now+10,state,retryAt:null,errorCode:"TERMINAL",errorMessage:"terminal"});const result=settlement.settle(settlementInput(created,leased.value.attempt.id,now,{state,artifacts:[],notifications:[],externalEffects:[],idempotencyKey:`settle-${state}`}));assert.equal(result.state,state);assert.equal(execution.task("org_account_a",created.task.id)?.state,state);assert.equal(commerceRepository.terminalForReservation("org_account_a",created.reservationId!)?.entryType,"release");assert.equal(database.prepare("SELECT COUNT(*) count FROM commerce_credit_ledger WHERE entry_type='release'").first<{count:number}>()?.count,1);}}
);

test("unresolved effects, tenant drift, and non-terminal jobs are rejected without partial settlement",async()=>{const{database,execution,creation,settlement,now}=await fixture(),created=creation.create(request(now)),leased=claim(execution,now),input=settlementInput(created,leased.value.attempt.id,now);assert.throws(()=>settlement.settle({...input,externalEffects:[{...input.externalEffects[0],state:"unknown"}]}),error=>error instanceof TaskSettlementError&&error.code==="UNRESOLVED_EXTERNAL_EFFECT");assert.throws(()=>settlement.settle({...input,notifications:[{...input.notifications[0],organizationId:"other"}]}),error=>error instanceof TaskSettlementError&&error.code==="SETTLEMENT_SCOPE_MISMATCH");assert.throws(()=>settlement.settle(input),error=>error instanceof TaskSettlementError&&error.code==="JOB_NOT_TERMINAL");assert.equal(database.prepare("SELECT COUNT(*) count FROM execution_artifacts").first<{count:number}>()?.count,0);assert.equal(database.prepare("SELECT COUNT(*) count FROM commerce_credit_ledger WHERE entry_type IN ('commit','release')").first<{count:number}>()?.count,0);
});

test("a late task-state failure rolls back credit, artifacts, notifications, effects, outbox, audit, and idempotency",async()=>{const{database,execution,commerce,creation,now}=await fixture(),created=creation.create(request(now)),leased=claim(execution,now);execution.succeedAttempt({claim:leased.value,workerId:"worker-a",tokenHash:leased.tokenHash,now:now+10});const baseline={outbox:database.prepare("SELECT COUNT(*) count FROM execution_outbox").first<{count:number}>()!.count,audit:database.prepare("SELECT COUNT(*) count FROM operations_audit_events").first<{count:number}>()!.count,idempotency:database.prepare("SELECT COUNT(*) count FROM execution_idempotency_keys").first<{count:number}>()!.count};const failing=new Proxy(execution,{get(target,property,receiver){if(property==="settleTask")return()=>false;const value=Reflect.get(target,property,receiver);return typeof value==="function"?value.bind(target):value;}}) as ExecutionSettlementRepository,settlement=new AtomicTaskSettlementService(failing,commerce,()=>now+20);assert.throws(()=>settlement.settle(settlementInput(created,leased.value.attempt.id,now)),error=>error instanceof TaskSettlementError&&error.code==="TASK_STATE_CONFLICT");for(const table of ["execution_artifacts","operations_notifications","execution_external_effects"])assert.equal(database.prepare(`SELECT COUNT(*) count FROM ${table}`).first<{count:number}>()?.count,0,table);assert.equal(database.prepare("SELECT COUNT(*) count FROM commerce_credit_ledger WHERE entry_type IN ('commit','release')").first<{count:number}>()?.count,0);assert.equal(database.prepare("SELECT COUNT(*) count FROM execution_outbox").first<{count:number}>()?.count,baseline.outbox);assert.equal(database.prepare("SELECT COUNT(*) count FROM operations_audit_events").first<{count:number}>()?.count,baseline.audit);assert.equal(database.prepare("SELECT COUNT(*) count FROM execution_idempotency_keys").first<{count:number}>()?.count,baseline.idempotency);
});
