import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import test from "node:test";
import { AppDatabase } from "../lib/database";
import { SqliteExecutionRepository } from "../platform/adapters/sqlite/execution-repository";
import { SqliteWorkspaceCatalogRepository } from "../platform/adapters/sqlite/workspace-catalog-repository";
import type { ArtifactRecord, ExecutionTask } from "../platform/modules/execution";
import { WorkspaceCatalogService } from "../platform/modules/execution/workspace-catalog";

const now=1_786_600_000,hash="a".repeat(64);
function fixture(){const sqlite=new DatabaseSync(":memory:");sqlite.exec("PRAGMA foreign_keys=ON");const db=new AppDatabase(sqlite);db.exec(`CREATE TABLE users(id TEXT PRIMARY KEY);CREATE TABLE identity_organizations(id TEXT PRIMARY KEY);CREATE TABLE projects(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES identity_organizations(id));CREATE TABLE findings(id TEXT PRIMARY KEY,url TEXT,evidence TEXT,category TEXT,severity TEXT);CREATE TABLE seo_tasks(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects(id),finding_id TEXT,type TEXT NOT NULL,title TEXT NOT NULL,description TEXT NOT NULL,priority INTEGER NOT NULL,status TEXT NOT NULL,created_at INTEGER NOT NULL);CREATE TABLE commerce_credit_ledger(id TEXT PRIMARY KEY);INSERT INTO users VALUES ('account_a');INSERT INTO identity_organizations VALUES ('org_a');INSERT INTO projects VALUES ('project_a','org_a');INSERT INTO findings VALUES ('finding_a','https://example.com','evidence','content','high');INSERT INTO seo_tasks VALUES ('legacy_a','project_a','finding_a','content_blog','Old linked task','legacy',60,'proposed',${now-30}),('legacy_b','project_a',NULL,'knowledge_document','Knowledge note','source',70,'completed',${now-20});`);const execution=new SqliteExecutionRepository(db);execution.ensureSchema();const task:ExecutionTask={id:"task_a",organizationId:"org_a",projectId:"project_a",requestedByAccountId:"account_a",triggerType:"system",taskType:"content_blog",capability:"content.read",state:"completed",progress:100,cancellable:false,input:{legacyTaskId:"legacy_a",title:"Canonical content",description:"durable",category:"content"},locale:"en",idempotencyKey:"catalog-a",correlationId:"corr-a",version:1,createdAt:now,updatedAt:now,startedAt:now,completedAt:now};execution.createTask(task);const artifact:ArtifactRecord={id:"artifact_a",organizationId:"org_a",projectId:"project_a",taskId:"task_a",attemptId:null,kind:"audit_report",objectKey:"oneshowseo/org_a/project_a/task_a/artifact_a/report.pdf",sha256:hash,mimeType:"application/pdf",sizeBytes:1024,scanState:"clean",retentionClass:"days:30",expiresAt:now+86400,provenance:{title:"SEO report"},idempotencyKey:"artifact-a",createdAt:now};execution.appendArtifact(artifact);execution.appendArtifact({...artifact,id:"expired",objectKey:"oneshowseo/org_a/project_a/task_a/expired/report.pdf",idempotencyKey:"expired",expiresAt:now-1});return{sqlite,db,service:new WorkspaceCatalogService(new SqliteWorkspaceCatalogRepository(db),()=>now)};}

test("shared catalog prefers canonical tasks, keeps unlinked history, and never duplicates legacy rows",()=>{const{service}=fixture(),result=service.read("org_a","project_a"),canonical=result.tasks.find(item=>item.id==="task_a"),legacy=result.tasks.find(item=>item.id==="legacy_b");assert.deepEqual(result.tasks.map(item=>item.id).sort(),["legacy_b","task_a"]);assert.equal(canonical?.source,"execution");assert.equal(canonical?.status,"completed");assert.equal(legacy?.source,"legacy");assert.equal(legacy?.type,"knowledge_document");});

test("shared artifact projections exclude expired or unsafe records and expose authorized access routes",()=>{const{service}=fixture(),result=service.read("org_a","project_a");assert.equal(result.artifacts.length,1);assert.equal(result.reports[0].title,"SEO report");assert.equal(result.reports[0].accessPath,"/api/artifacts/artifact_a/access?projectId=project_a");assert.equal(result.content.length,0);});

test("catalog reads do not create work, rerun history, or write Credits",()=>{const{db,service}=fixture(),before={tasks:db.prepare("SELECT COUNT(*) count FROM execution_tasks").first<{count:number}>()!.count,legacy:db.prepare("SELECT COUNT(*) count FROM seo_tasks").first<{count:number}>()!.count,credits:db.prepare("SELECT COUNT(*) count FROM commerce_credit_ledger").first<{count:number}>()!.count};service.read("org_a","project_a");service.read("org_a","project_a");const after={tasks:db.prepare("SELECT COUNT(*) count FROM execution_tasks").first<{count:number}>()!.count,legacy:db.prepare("SELECT COUNT(*) count FROM seo_tasks").first<{count:number}>()!.count,credits:db.prepare("SELECT COUNT(*) count FROM commerce_credit_ledger").first<{count:number}>()!.count};assert.deepEqual(after,before);});

test("catalog SQL always applies organization and project scope",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile(new URL("../platform/adapters/sqlite/workspace-catalog-repository.ts",import.meta.url),"utf8"));assert.match(source,/t\.organization_id=\? AND t\.project_id=\?/);assert.match(source,/p\.organization_id=\? AND t\.project_id=\?/);assert.match(source,/organization_id=\? AND project_id=\?/);});
