import { providerCatalog, type ProviderAdapter, type ProviderDefinition, type ProviderHealth, type ProviderOperationContext, type ProviderSyncCursor, type ProviderSyncRequest, type ProviderSyncResult } from ".";
import type { SafeHttpRequest, SafeHttpResponse } from "./safe-http";
import { SafeHttpError } from "./safe-http";

export interface ProviderHttpClient { request(input:SafeHttpRequest):Promise<SafeHttpResponse>; }
export interface ProviderCredentialResolver { withAuthorization<T>(credentialHandle:string,operation:(authorization:string)=>Promise<T>):Promise<T>; }
type JsonRecord=Record<string,unknown>;
type AdapterConfig={definition:ProviderDefinition;health:(context:ProviderOperationContext)=>SafeHttpRequest;sync:(context:ProviderOperationContext,input:ProviderSyncRequest)=>SafeHttpRequest;records:(payload:unknown)=>readonly JsonRecord[];nextCursor:(payload:unknown,input:ProviderSyncRequest)=>ProviderSyncCursor|null};
const decoder=new TextDecoder();
function metadata(context:ProviderOperationContext,key:string){const value=context.metadata?.[key]?.trim();if(!value)throw new Error(`INTEGRATION_METADATA_REQUIRED:${key}`);return value;}
function json(response:SafeHttpResponse):unknown{return JSON.parse(decoder.decode(response.body))as unknown;}
function object(value:unknown):value is JsonRecord{return Boolean(value)&&typeof value==="object"&&!Array.isArray(value);}
function healthy(now:number,latencyMs:number|null):ProviderHealth{return{state:"healthy",checkedAt:now,latencyMs,error:null,rateLimit:{limit:null,remaining:null,resetsAt:null,retryAfterSeconds:null}};}
function failed(error:unknown,now:number):ProviderHealth{if(error instanceof SafeHttpError){const state=error.normalized.remediation==="reauthorize"?"permission_required":error.normalized.category==="authentication"?"expired":error.normalized.category==="permission"?"permission_required":error.normalized.category==="rate_limit"?"rate_limited":"degraded";return{state,checkedAt:now,latencyMs:null,error:error.normalized,rateLimit:{limit:null,remaining:null,resetsAt:null,retryAfterSeconds:error.normalized.retryAfterSeconds}};}return{state:"error",checkedAt:now,latencyMs:null,error:{code:"PROVIDER_RESPONSE_INVALID",category:"provider",retryable:false,retryAfterSeconds:null,messageKey:"integration.provider.response_invalid",remediation:"contact_support",correlationId:"provider:response:invalid"},rateLimit:{limit:null,remaining:null,resetsAt:null,retryAfterSeconds:null}};}

class LaunchRestAdapter implements ProviderAdapter<JsonRecord>{
  readonly definition:ProviderDefinition;
  constructor(private readonly config:AdapterConfig,private readonly http:ProviderHttpClient,private readonly credentials:ProviderCredentialResolver,private readonly now:()=>number=()=>Math.floor(Date.now()/1000)){this.definition=config.definition;}
  async checkHealth(context:ProviderOperationContext){const started=Date.now();try{await this.authorized(context,this.config.health(context));return healthy(this.now(),Math.max(0,Date.now()-started));}catch(error){return failed(error,this.now());}}
  async sync(context:ProviderOperationContext,input:ProviderSyncRequest):Promise<ProviderSyncResult<JsonRecord>>{if(!Number.isInteger(input.limit)||input.limit<1||input.limit>1000)throw new Error("PROVIDER_SYNC_LIMIT_INVALID");const response=await this.authorized(context,this.config.sync(context,input)),payload=json(response),nextCursor=this.config.nextCursor(payload,input);return{records:this.config.records(payload),nextCursor,hasMore:nextCursor!==null,health:healthy(this.now(),null)};}
  async disconnect(){return{disconnectedAt:this.now(),remoteAuthorizationRevoked:false};}
  async deleteConnectionData(){return{deletedAt:this.now(),remoteDataDeleted:false,deletionReference:null};}
  private authorized(context:ProviderOperationContext,input:SafeHttpRequest){return this.credentials.withAuthorization(context.credentialHandle,authorization=>this.http.request({...input,credentialHeaders:{Authorization:authorization},correlationId:context.correlationId}));}
}

function cursorOffset(input:ProviderSyncRequest){const value=input.cursor?Number(input.cursor.value):0;if(!Number.isInteger(value)||value<0)throw new Error("PROVIDER_CURSOR_INVALID");return value;}
function nextOffset(payload:unknown,input:ProviderSyncRequest,field:string){const records=object(payload)&&Array.isArray(payload[field])?payload[field] as unknown[]:[];return records.length===input.limit?{value:String(cursorOffset(input)+records.length),capturedAt:Math.floor(Date.now()/1000),expiresAt:null}:null;}

export function googleSearchConsoleAdapter(http:ProviderHttpClient,credentials:ProviderCredentialResolver,now?:()=>number):ProviderAdapter<JsonRecord>{const definition=provider("google-search-console");return new LaunchRestAdapter({definition,health:context=>({url:"https://www.googleapis.com/webmasters/v3/sites",method:"GET",correlationId:context.correlationId}),sync:(context,input)=>({url:`https://www.googleapis.com/webmasters/v3/sites/${encodeURIComponent(metadata(context,"siteUrl"))}/searchAnalytics/query`,method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({startDate:metadata(context,"startDate"),endDate:metadata(context,"endDate"),rowLimit:input.limit,startRow:cursorOffset(input)}),idempotent:true,correlationId:context.correlationId}),records:payload=>object(payload)&&Array.isArray(payload.rows)?payload.rows as JsonRecord[]:[],nextCursor:(payload,input)=>nextOffset(payload,input,"rows")},http,credentials,now);}
export function googleAnalytics4Adapter(http:ProviderHttpClient,credentials:ProviderCredentialResolver,now?:()=>number):ProviderAdapter<JsonRecord>{const definition=provider("google-analytics-4");return new LaunchRestAdapter({definition,health:context=>({url:`https://analyticsdata.googleapis.com/v1beta/properties/${encodeURIComponent(metadata(context,"propertyId"))}/metadata`,method:"GET",correlationId:context.correlationId}),sync:(context,input)=>({url:`https://analyticsdata.googleapis.com/v1beta/properties/${encodeURIComponent(metadata(context,"propertyId"))}:runReport`,method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({dateRanges:[{startDate:metadata(context,"startDate"),endDate:metadata(context,"endDate")}],dimensions:[{name:"landingPage"}],metrics:[{name:"organicGoogleSearchClicks"}],limit:String(input.limit),offset:String(cursorOffset(input))}),idempotent:true,correlationId:context.correlationId}),records:payload=>object(payload)&&Array.isArray(payload.rows)?payload.rows as JsonRecord[]:[],nextCursor:(payload,input)=>nextOffset(payload,input,"rows")},http,credentials,now);}
export function wordpressAdapter(http:ProviderHttpClient,credentials:ProviderCredentialResolver,now?:()=>number):ProviderAdapter<JsonRecord>{const definition=provider("wordpress");const base=(context:ProviderOperationContext)=>metadata(context,"baseUrl").replace(/\/$/,"");return new LaunchRestAdapter({definition,health:context=>({url:`${base(context)}/wp-json/wp/v2/users/me?context=edit`,method:"GET",correlationId:context.correlationId}),sync:(context,input)=>({url:`${base(context)}/wp-json/wp/v2/posts?context=edit&per_page=${input.limit}&offset=${cursorOffset(input)}`,method:"GET",correlationId:context.correlationId}),records:payload=>Array.isArray(payload)?payload.filter(object):[],nextCursor:(payload,input)=>Array.isArray(payload)&&payload.length===input.limit?{value:String(cursorOffset(input)+payload.length),capturedAt:Math.floor(Date.now()/1000),expiresAt:null}:null},http,credentials,now);}
function provider(id:string){const value=providerCatalog.get(id);if(!value)throw new Error("PROVIDER_DEFINITION_MISSING");return value;}
