import { lookup } from "node:dns/promises";
import { request as httpsRequest } from "node:https";
import { isIP } from "node:net";
import type { NormalizedProviderError } from ".";

export type SafeHttpPolicy = { allowedHosts: readonly string[]; credentialHosts: readonly string[]; timeoutMs: number; maxRedirects: number; maxRetries: number; maxResponseBytes: number; circuitFailureThreshold: number; circuitResetSeconds: number };
export type SafeHttpRequest = { url: string; method?: "GET" | "HEAD" | "POST" | "PUT" | "PATCH" | "DELETE"; headers?: Readonly<Record<string,string>>; credentialHeaders?: Readonly<Record<string,string>>; body?: string | Uint8Array; idempotent?: boolean; correlationId: string };
export type SafeHttpResponse = { status: number; headers: Readonly<Record<string,string>>; body: Uint8Array; finalUrl: string; attempts: number };
export type ResolvedAddress = { address: string; family: 4 | 6 };
export interface SafeHttpResolver { resolve(hostname:string):Promise<readonly ResolvedAddress[]>; }
export interface SafeHttpTransport { request(input:{url:URL;method:string;headers:Readonly<Record<string,string>>;body?:string|Uint8Array;addresses:readonly ResolvedAddress[];timeoutMs:number;maxResponseBytes:number}):Promise<{status:number;headers:Readonly<Record<string,string>>;body:Uint8Array}>; }

export class SafeHttpError extends Error { constructor(readonly normalized:NormalizedProviderError){super(normalized.messageKey);} }
const unsafeHeader=/^(host|connection|proxy-|transfer-encoding|content-length|forwarded|x-forwarded-|via$)/i;
const credentialHeader=/^(authorization|proxy-authorization|cookie|.*(?:api[-_]?key|access[-_]?token|secret|credential).*)$/i;
const metadataHosts=new Set(["metadata.google.internal","metadata.azure.internal","instance-data","169.254.169.254"]);

function ipv4Unsafe(address:string){const octets=address.split(".").map(Number);if(octets.length!==4||octets.some(value=>!Number.isInteger(value)||value<0||value>255))return true;const[a,b,c]=octets;return a===0||a===10||a===127||a>=224||(a===100&&b>=64&&b<=127)||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&(b===0||b===168||(b===88&&c===99)))||(a===198&&(b===18||b===19||b===51&&c===100))||(a===203&&b===0&&c===113);}
export function unsafeNetworkAddress(address:string){const normalized=address.toLowerCase().split("%")[0];const family=isIP(normalized);if(family===4)return ipv4Unsafe(normalized);if(family!==6)return true;if(normalized==="::"||normalized==="::1"||normalized.startsWith("fc")||normalized.startsWith("fd")||/^fe[89ab]/.test(normalized)||normalized.startsWith("ff")||normalized.startsWith("2001:db8"))return true;if(normalized.startsWith("::ffff:")){const mapped=normalized.slice(7);return isIP(mapped)!==4||ipv4Unsafe(mapped);}return false;}
function hostAllowed(host:string,allowed:readonly string[]){const value=host.toLowerCase();return allowed.some(rule=>{const normalized=rule.toLowerCase();return normalized.startsWith("*.")?value.endsWith(normalized.slice(1))&&value!==normalized.slice(2):value===normalized;});}
function normalized(code:string,category:NormalizedProviderError["category"],retryable:boolean,correlationId:string,remediation:NormalizedProviderError["remediation"]="none",retryAfterSeconds:number|null=null):NormalizedProviderError{return{code,category,retryable,retryAfterSeconds,messageKey:`integration.http.${code.toLowerCase()}`,remediation,correlationId};}

export class NodeSafeHttpResolver implements SafeHttpResolver { async resolve(hostname:string){return(await lookup(hostname,{all:true,verbatim:true})).map(item=>({address:item.address,family:item.family as 4|6}));} }
export class NodePinnedHttpsTransport implements SafeHttpTransport {
  request(input:Parameters<SafeHttpTransport["request"]>[0]){return new Promise<{status:number;headers:Readonly<Record<string,string>>;body:Uint8Array}>((resolve,reject)=>{const selected=input.addresses[0];if(!selected)return reject(new Error("DNS_EMPTY"));const request=httpsRequest(input.url,{method:input.method,headers:input.headers,timeout:input.timeoutMs,lookup:(_hostname,_options,callback)=>callback(null,selected.address,selected.family)},response=>{const chunks:Buffer[]=[];let size=0;response.on("data",chunk=>{size+=chunk.length;if(size>input.maxResponseBytes){request.destroy(new Error("RESPONSE_TOO_LARGE"));return;}chunks.push(Buffer.from(chunk));});response.on("end",()=>resolve({status:response.statusCode||0,headers:Object.fromEntries(Object.entries(response.headers).flatMap(([key,value])=>value===undefined?[]:[[key,Array.isArray(value)?value.join(", "):String(value)]])),body:new Uint8Array(Buffer.concat(chunks))}));});request.on("timeout",()=>request.destroy(new Error("TIMEOUT")));request.on("error",reject);if(input.body)request.write(input.body);request.end();});}
}

export class SafeProviderHttpClient {
  private readonly circuits=new Map<string,{failures:number;openedAt:number|null}>();
  constructor(private readonly policy:SafeHttpPolicy,private readonly resolver:SafeHttpResolver=new NodeSafeHttpResolver(),private readonly transport:SafeHttpTransport=new NodePinnedHttpsTransport(),private readonly now:()=>number=()=>Math.floor(Date.now()/1000)){}
  async request(input:SafeHttpRequest):Promise<SafeHttpResponse>{let current=this.url(input.url,input.correlationId),redirects=0,attempts=0;const method=input.method||"GET";const retryableMethod=input.idempotent===true||method==="GET"||method==="HEAD";this.assertCircuit(current.origin,input.correlationId);while(true){const addresses=await this.addresses(current,input.correlationId);const sameCredentialHost=hostAllowed(current.hostname,this.policy.credentialHosts);const headers=this.headers(input.headers,input.credentialHeaders,sameCredentialHost,input.correlationId);try{attempts++;const response=await this.transport.request({url:current,method,headers,body:input.body,addresses,timeoutMs:this.policy.timeoutMs,maxResponseBytes:this.policy.maxResponseBytes});if(response.status>=300&&response.status<400&&response.headers.location){if(redirects++>=this.policy.maxRedirects)throw new SafeHttpError(normalized("REDIRECT_LIMIT","provider",false,input.correlationId));current=this.url(new URL(response.headers.location,current).toString(),input.correlationId);this.assertCircuit(current.origin,input.correlationId);continue;}if((response.status===429||response.status>=500)&&retryableMethod&&attempts<=this.policy.maxRetries){this.failure(current.origin);continue;}if(response.status>=400){this.failure(current.origin);throw new SafeHttpError(normalized(response.status===429?"RATE_LIMITED":"PROVIDER_REJECTED",response.status===429?"rate_limit":"provider",response.status===429||response.status>=500,input.correlationId,response.status===401||response.status===403?"reauthorize":"retry",null));}this.success(current.origin);return{...response,finalUrl:current.toString(),attempts};}catch(error){if(error instanceof SafeHttpError)throw error;this.failure(current.origin);if(retryableMethod&&attempts<=this.policy.maxRetries)continue;const timeout=error instanceof Error&&error.message==="TIMEOUT";throw new SafeHttpError(normalized(timeout?"TIMEOUT":"NETWORK_ERROR",timeout?"timeout":"network",true,input.correlationId,"retry"));}}
  }
  private url(value:string,correlationId:string){let parsed:URL;try{parsed=new URL(value);}catch{throw new SafeHttpError(normalized("URL_INVALID","validation",false,correlationId,"reconfigure"));}if(parsed.protocol!=="https:"||parsed.username||parsed.password||parsed.port&&parsed.port!=="443"||metadataHosts.has(parsed.hostname.toLowerCase())||!hostAllowed(parsed.hostname,this.policy.allowedHosts))throw new SafeHttpError(normalized("DESTINATION_DENIED","validation",false,correlationId,"reconfigure"));return parsed;}
  private async addresses(url:URL,correlationId:string){let values:readonly ResolvedAddress[];try{values=await this.resolver.resolve(url.hostname);}catch{throw new SafeHttpError(normalized("DNS_FAILED","network",true,correlationId,"retry"));}if(values.length===0||values.some(item=>unsafeNetworkAddress(item.address)))throw new SafeHttpError(normalized("UNSAFE_ADDRESS","validation",false,correlationId,"reconfigure"));return values;}
  private headers(regular:Readonly<Record<string,string>>|undefined,credentials:Readonly<Record<string,string>>|undefined,allowCredentials:boolean,correlationId:string){const output:Record<string,string>={};for(const [key,value] of Object.entries(regular||{})){if(unsafeHeader.test(key)||credentialHeader.test(key)||/[\r\n]/.test(key+value))throw new SafeHttpError(normalized("HEADER_DENIED","validation",false,correlationId));output[key]=value;}if(allowCredentials)for(const[key,value]of Object.entries(credentials||{})){if(!credentialHeader.test(key)||/[\r\n]/.test(key+value))throw new SafeHttpError(normalized("CREDENTIAL_HEADER_DENIED","validation",false,correlationId));output[key]=value;}return output;}
  private assertCircuit(origin:string,correlationId:string){const item=this.circuits.get(origin);if(item?.openedAt!==null&&item?.openedAt!==undefined&&this.now()-item.openedAt<this.policy.circuitResetSeconds)throw new SafeHttpError(normalized("CIRCUIT_OPEN","provider",true,correlationId,"retry",this.policy.circuitResetSeconds-(this.now()-item.openedAt)));if(item?.openedAt!==null&&item?.openedAt!==undefined)this.circuits.set(origin,{failures:0,openedAt:null});}
  private failure(origin:string){const item=this.circuits.get(origin)||{failures:0,openedAt:null};item.failures++;if(item.failures>=this.policy.circuitFailureThreshold)item.openedAt=this.now();this.circuits.set(origin,item);}
  private success(origin:string){this.circuits.delete(origin);}
}
