import { NextResponse } from "next/server";
import { getCurrentUser,writeAudit } from "../../../../../lib/auth";
import { ensureProductSchema,ownedProject } from "../../../../../lib/product";
import { commerceService,commercialSubject,ensureBillingSchema } from "../../../../../lib/billing";
import { atomicTaskCreationService } from "../../../../../lib/execution";
import { ANALYTICS_CREDIT_COST,analyticsDashboard,ensureAnalyticsSchema } from "../../../../../lib/analytics-execution";
import { permissions,type OrganizationRoleKey } from "../../../../../platform/modules/identity/authorization";
import { CommerceError } from "../../../../../platform/modules/commerce/service";
import { TaskCreationError } from "../../../../../platform/modules/execution/task-creation";

export async function GET(_:Request,context:{params:Promise<{id:string}>}){const user=await getCurrentUser();if(!user)return NextResponse.json({error:"请先登录"},{status:401});const{id}=await context.params;await ensureAnalyticsSchema();const project=await ownedProject(user.organization.organizationId,id);if(!project)return NextResponse.json({error:"项目不存在"},{status:404});return NextResponse.json({...analyticsDashboard(user.organization.organizationId,id),creditCost:ANALYTICS_CREDIT_COST,capabilities:{internalEvidence:true,searchPerformanceSnapshot:false,analyticsSnapshot:false,aiVisibilitySnapshot:false}})}

export async function POST(request:Request,context:{params:Promise<{id:string}>}){const user=await getCurrentUser();if(!user)return NextResponse.json({error:"请先登录"},{status:401});const{id}=await context.params;await ensureProductSchema();await ensureAnalyticsSchema();await ensureBillingSchema();const project=await ownedProject(user.organization.organizationId,id);if(!project)return NextResponse.json({error:"项目不存在"},{status:404});try{commerceService().authorizeAccess(commercialSubject(user));const correlationId=`analytics:${crypto.randomUUID()}`,idempotencyKey=request.headers.get("idempotency-key")||`analytics:${id}:${Date.now()}`,created=(await atomicTaskCreationService()).create({activeOrganizationId:user.organization.organizationId,organizationId:user.organization.organizationId,projectId:id,requestedByAccountId:user.id,role:user.organization.roleKey as OrganizationRoleKey,permission:permissions.auditsRun,subject:commercialSubject(user),triggerType:"manual",taskType:"analytics_agent",capability:"analytics.snapshot",input:{projectId:id,lookbackDays:30,title:`${project.name} Analytics 分析快照`,description:"汇总审计、研究、内容、发布、GEO 与任务证据，检测变化并生成可追溯报告"},locale:project.language.startsWith("en")?"en":"zh-CN",idempotencyKey,correlationId,entitlements:[],creditCost:ANALYTICS_CREDIT_COST,queue:"agents",jobType:"analytics.snapshot",priority:65,maxAttempts:3,timeoutSeconds:300});await writeAudit("analytics_snapshot_queued",user.id,request,JSON.stringify({projectId:id,taskId:created.task.id,creditsReserved:ANALYTICS_CREDIT_COST,agent:"analytics.agent@1.0.0"}));return NextResponse.json({taskId:created.task.id,state:created.task.state,creditsReserved:ANALYTICS_CREDIT_COST,duplicate:created.duplicate},{status:202})}catch(error){if(error instanceof CommerceError||error instanceof TaskCreationError)return NextResponse.json({error:error.message,code:error.code},{status:error.status});console.error("Failed to queue Analytics Agent",error);return NextResponse.json({error:"分析快照创建失败，请稍后重试"},{status:500})}}
