import { createHash } from "node:crypto";
import type { AgentImplementation } from "../../sdk/development-harness";
import type { AgentEventEnvelope,AgentExecutionEnvelope } from "./contracts";
import { validateAgentManifest,type AgentManifest } from "./manifest";

export const ANALYTICS_AGENT_KEY="analytics.agent",ANALYTICS_AGENT_VERSION="1.0.0",ANALYTICS_CAPABILITY="analytics.snapshot";
export const analyticsAgentManifest:AgentManifest=validateAgentManifest({schemaVersion:"1",key:ANALYTICS_AGENT_KEY,version:ANALYTICS_AGENT_VERSION,metadata:{"zh-CN":{name:"Analytics Agent",description:"汇总站内 Agent 结果与已接入表现数据，生成可追溯的变化判断、行动建议和分析报告。"},en:{name:"Analytics Agent",description:"Combine attributable agent outcomes and connected performance data into traceable change detection, actions, and analytics reports."}},capabilities:[{key:ANALYTICS_CAPABILITY,input:{type:"object",additionalProperties:false,properties:{projectId:{type:"string",minLength:1},lookbackDays:{type:"integer",minimum:7,maximum:90}},required:["projectId","lookbackDays"]},output:{type:"object",additionalProperties:false,properties:{evidenceSources:{type:"integer",minimum:0},insights:{type:"integer",minimum:0},recommendations:{type:"integer",minimum:0},degradedSources:{type:"array",items:{type:"string"}}},required:["evidenceSources","insights","recommendations","degradedSources"]},events:[{key:"analytics.progress",schema:{type:"object",properties:{percent:{type:"integer"}}}},{key:"analytics.evidence",schema:{type:"object",properties:{digest:{type:"string"}}}},{key:"analytics.recommendation",schema:{type:"object",properties:{evidenceRefs:{type:"array"}}}},{key:"analytics.artifact",schema:{type:"object",properties:{mimeType:{type:"string"}}}},{key:"analytics.usage",schema:{type:"object",properties:{quantity:{type:"number"}}}},{key:"analytics.error",schema:{type:"object",properties:{code:{type:"string"}}}}],permissions:["reports.read","audits.run"]}],dependencies:{providers:[],agents:[]},entitlements:[{key:"analytics-runs",minimumPlan:"trial",quantity:1},{key:"monthly-credits",minimumPlan:"trial",quantity:3}],risks:[{capability:ANALYTICS_CAPABILITY,level:"low",approval:"none"}],schedules:[{key:"manual",cron:null,minimumIntervalSeconds:60,timezone:"project"},{key:"weekly",cron:"0 6 * * 1",minimumIntervalSeconds:3600,timezone:"project"}],compatibility:{platform:{minimum:"1.0.0",maximum:null},manifestVersions:["1"]}});

export type AnalyticsMetrics={healthScore:number|null;healthDelta:number|null;openIssues:number|null;issueDelta:number|null;opportunities:number;contentDrafts:number;published:number;geoScore:number|null;openTasks:number};
export type AnalyticsCoverage={audit:boolean;research:boolean;content:boolean;publish:boolean;geo:boolean;searchConsole:boolean;ga4:boolean;aiVisibility:boolean};
export type AnalyticsInsight={id:string;kind:"growth"|"risk"|"coverage"|"workflow";title:string;summary:string;action:string;priority:number;confidence:number;delta:number|null;sourceRefs:string[];digest:string};
export type AnalyticsAcquisition={capturedAt:number;freshUntil:number;metrics:AnalyticsMetrics;coverage:AnalyticsCoverage;auditHistory:Array<{capturedAt:number;score:number;issues:number}>;degradedSources:string[]};
export interface AnalyticsSourceAcquirer{acquire(input:{projectId:string;lookbackDays:number;signal?:AbortSignal}):Promise<AnalyticsAcquisition>}
export type AnalyticsAgentResult={events:AgentEventEnvelope[];metrics:AnalyticsMetrics;coverage:AnalyticsCoverage;auditHistory:AnalyticsAcquisition["auditHistory"];insights:AnalyticsInsight[];recommendations:AnalyticsInsight[];evidenceSources:number;degradedSources:string[];capturedAt:number};

const sha=(value:string)=>createHash("sha256").update(value).digest("hex");
const base=(input:AgentExecutionEnvelope,sequence:number,kind:AgentEventEnvelope["kind"])=>({schemaVersion:"1" as const,eventId:`${input.taskId}:${sequence}`,sequence,occurredAt:Math.floor(Date.now()/1000),organizationId:input.organizationId,projectId:input.projectId,taskId:input.taskId,jobId:input.jobId,attemptId:input.attemptId,correlationId:input.correlationId,agent:{key:ANALYTICS_AGENT_KEY,version:ANALYTICS_AGENT_VERSION},kind});
const insight=(value:Omit<AnalyticsInsight,"id"|"digest">):AnalyticsInsight=>({...value,id:`analytics-${sha(`${value.kind}:${value.title}`).slice(0,16)}`,digest:sha(JSON.stringify(value))});

export class AnalyticsAgent implements AgentImplementation{
 readonly manifest=analyticsAgentManifest;
 constructor(private readonly sources:AnalyticsSourceAcquirer){}
 async run(input:AgentExecutionEnvelope){return(await this.runDetailed(input)).events}
 async runDetailed(input:AgentExecutionEnvelope):Promise<AnalyticsAgentResult>{let sequence=0;const events:AgentEventEnvelope[]=[];const progress=(step:string,percent:number)=>events.push({...base(input,++sequence,"progress"),kind:"progress",progress:{step,percent,messageKey:`analytics.${step}`,messageArgs:{}}});progress("sources.reading",10);let acquired:AnalyticsAcquisition;try{acquired=await this.sources.acquire({projectId:String(input.input.projectId||""),lookbackDays:Number(input.input.lookbackDays||30)})}catch(error){events.push({...base(input,++sequence,"error"),kind:"error",error:{code:"analytics.source.unavailable",category:"dependency",retryable:true,messageKey:"analytics.source.unavailable",redactedDetail:error instanceof Error?error.message.slice(0,300):null,recoveryAction:"retry"}});throw error}const sourceEntries=Object.entries(acquired.coverage).filter(([,ready])=>ready);for(const [index,[source]] of sourceEntries.entries()){const summary=`${source} data available for the current project`;events.push({...base(input,++sequence,"evidence"),kind:"evidence",evidence:{id:`analytics-evidence-${index+1}`,capturedAt:acquired.capturedAt,source:{type:"artifact",ref:`project:${input.projectId}:${source}`},summary,digest:sha(`${summary}:${acquired.capturedAt}`),confidence:.98}})}progress("changes.detected",50);const m=acquired.metrics,insights:AnalyticsInsight[]=[];
 if(m.healthScore!==null)insights.push(insight({kind:m.healthDelta!==null&&m.healthDelta<0?"risk":"growth",title:m.healthDelta===null?"已建立 SEO 健康基线":m.healthDelta>=0?"SEO 健康度保持或提升":"SEO 健康度出现下降",summary:`当前健康分 ${m.healthScore}${m.healthDelta===null?"":`，较上一快照 ${m.healthDelta>0?"+":""}${m.healthDelta}`}`,action:m.healthDelta!==null&&m.healthDelta<0?"查看新增问题并优先处理高影响项":"继续按相同口径运行审计，验证趋势是否持续",priority:m.healthDelta!==null&&m.healthDelta<0?90:55,confidence:.98,delta:m.healthDelta,sourceRefs:["audit_runs"]}));
 if(m.openIssues!==null&&m.openIssues>0)insights.push(insight({kind:"risk",title:`仍有 ${m.openIssues} 个开放诊断问题`,summary:m.issueDelta===null?"当前问题数量已纳入分析基线":m.issueDelta<0?`较上一快照减少 ${Math.abs(m.issueDelta)} 个`:`较上一快照增加 ${m.issueDelta} 个`,action:"进入任务中心审阅高优先级修复建议",priority:m.issueDelta!==null&&m.issueDelta>0?88:72,confidence:.98,delta:m.issueDelta,sourceRefs:["audit_runs","seo_tasks"]}));
 if(m.opportunities>0)insights.push(insight({kind:"growth",title:`研究池中有 ${m.opportunities} 个可追踪机会`,summary:"机会来自 Research Agent 的持久化证据，不包含未接入的搜索量或排名估算。",action:"选择高优先级机会进入关键词与内容流程",priority:65,confidence:.9,delta:null,sourceRefs:["research_opportunities"]}));
 if(m.published===0&&m.contentDrafts>0)insights.push(insight({kind:"workflow",title:"内容产出尚未形成发布验证",summary:`已有 ${m.contentDrafts} 份内容记录，但没有已验证发布结果。`,action:"完成内容审核并通过 Publish Agent 建立上线证据",priority:75,confidence:.95,delta:null,sourceRefs:["content_runs","publish_requests"]}));
 if(!acquired.coverage.searchConsole||!acquired.coverage.ga4)insights.push(insight({kind:"coverage",title:"搜索与转化归因仍不完整",summary:"当前可判断站内执行结果，但点击、会话、转化和收入仍缺少权威数据快照。",action:"接入并验证 GSC 与 GA4 后再评估商业增长",priority:80,confidence:1,delta:null,sourceRefs:["integration_connections"]}));
 if(!acquired.coverage.aiVisibility)insights.push(insight({kind:"coverage",title:"AI 可见性暂不能归因",summary:"GEO 就绪度不等于外部 AI 提及或引用，当前不会估算 AI 流量。",action:"接入 AI 可见性监控提供方后建立外部趋势",priority:50,confidence:1,delta:null,sourceRefs:["geo_runs"]}));
 const recommendations=insights.filter(item=>item.kind!=="growth").sort((a,b)=>b.priority-a.priority);for(const [index,item] of recommendations.entries())events.push({...base(input,++sequence,"recommendation"),kind:"recommendation",recommendation:{id:`analytics-recommendation-${index+1}`,title:item.title,evidenceRefs:item.sourceRefs,confidence:item.confidence,impactHypothesis:item.summary,risk:item.priority>=85?"high":item.priority>=60?"medium":"low",changeSetRef:null,estimatedCost:0,expiresAt:acquired.freshUntil,rollbackRequired:false}});progress("report.generated",85);const preview=JSON.stringify({agent:`${ANALYTICS_AGENT_KEY}@${ANALYTICS_AGENT_VERSION}`,metrics:m,coverage:acquired.coverage,insights:insights.map(item=>item.digest),degradedSources:acquired.degradedSources});events.push({...base(input,++sequence,"artifact"),kind:"artifact",artifact:{uploadRef:`analytics-report:${input.taskId}`,filename:`analytics-report-${input.taskId}.md`,mimeType:"text/markdown",size:Buffer.byteLength(preview),digest:sha(preview),retentionClass:"standard"}},{...base(input,++sequence,"usage"),kind:"usage",usage:{eventId:`analytics:${input.taskId}:snapshot`,meter:"analytics.snapshots",quantity:1,unit:"snapshot",measuredAt:Math.floor(Date.now()/1000),final:true}});progress("completed",100);return{events,metrics:m,coverage:acquired.coverage,auditHistory:acquired.auditHistory,insights,recommendations,evidenceSources:sourceEntries.length,degradedSources:acquired.degradedSources,capturedAt:acquired.capturedAt}}
}
