export type AgentLocale="zh-CN"|"en";
export type JsonSchema=Record<string,unknown>;
export type AgentManifest={schemaVersion:"1";key:string;version:string;metadata:Record<AgentLocale,{name:string;description:string}>;capabilities:Array<{key:string;input:JsonSchema;output:JsonSchema;events:Array<{key:string;schema:JsonSchema}>;permissions:string[]}>;dependencies:{providers:string[];agents:Array<{key:string;versionRange:string}>};entitlements:Array<{key:string;minimumPlan:"trial"|"starter"|"pro"|"business";quantity:number}>;risks:Array<{capability:string;level:"low"|"medium"|"high"|"critical";approval:"none"|"policy"|"required"}>;schedules:Array<{key:string;cron:string|null;minimumIntervalSeconds:number;timezone:"project"|"utc"}>;compatibility:{platform:{minimum:string;maximum:string|null};manifestVersions:string[]}};
export type AgentManifestIssue={path:string;code:string;message:string};
export class AgentManifestError extends Error{constructor(readonly issues:AgentManifestIssue[]){super("AGENT_MANIFEST_INVALID");}}

const keyPattern=/^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$/;
const semverPattern=/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-([0-9A-Za-z.-]+))?$/;
const rangePattern=/^(?:\^|~|>=|<=|>|<)?\s*(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:\s+(?:<|<=|>|>=)\s*(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*))?$/;
const sensitive=/password|secret|token|credential|api[_-]?key|private[_-]?key|reasoning|chain[_-]?of[_-]?thought/i;
const object=(value:unknown):value is Record<string,unknown>=>Boolean(value)&&typeof value==="object"&&!Array.isArray(value);
const string=(value:unknown)=>typeof value==="string"&&value.trim().length>0;
const issue=(issues:AgentManifestIssue[],path:string,code:string,message:string)=>issues.push({path,code,message});
function compareSemver(a:string,b:string){const left=a.split(".").slice(0,3).map(Number),right=b.split(".").slice(0,3).map(Number);for(let index=0;index<3;index++)if(left[index]!==right[index])return left[index]-right[index];return 0;}
function uniqueKeys(values:unknown,path:string,issues:AgentManifestIssue[],read:(item:Record<string,unknown>)=>unknown=(item)=>item.key){if(!Array.isArray(values)){issue(issues,path,"TYPE","必须是数组");return [];}const seen=new Set<string>();for(const [index,value] of values.entries()){if(!object(value)){issue(issues,`${path}[${index}]`,"TYPE","必须是对象");continue;}const key=read(value);if(!string(key)||!keyPattern.test(key)){issue(issues,`${path}[${index}].key`,"KEY","标识格式无效");continue;}if(seen.has(key))issue(issues,`${path}[${index}].key`,"DUPLICATE","标识不能重复");seen.add(key);}return values.filter(object);}
function validateSchema(value:unknown,path:string,issues:AgentManifestIssue[],depth=0){if(!object(value)){issue(issues,path,"SCHEMA","必须是 JSON Schema 对象");return;}if(depth>12){issue(issues,path,"SCHEMA_DEPTH","Schema 嵌套过深");return;}for(const[key,item]of Object.entries(value)){if(sensitive.test(key))issue(issues,`${path}.${key}`,"SENSITIVE_FIELD","共享契约不能声明敏感或推理字段");if(key==="$ref"&&typeof item==="string"&&!item.startsWith("#"))issue(issues,`${path}.$ref`,"EXTERNAL_REF","禁止外部 Schema 引用");if(item&&typeof item==="object"){if(Array.isArray(item)){for(const[index,nested]of item.entries())if(nested&&typeof nested==="object")validateSchema(nested,`${path}.${key}[${index}]`,issues,depth+1);}else validateSchema(item,`${path}.${key}`,issues,depth+1);}}}

export function validateAgentManifest(value:unknown):AgentManifest{
  const issues:AgentManifestIssue[]=[];if(!object(value))throw new AgentManifestError([{path:"$",code:"TYPE",message:"清单必须是对象"}]);
  if(value.schemaVersion!=="1")issue(issues,"schemaVersion","VERSION","仅支持清单版本 1");if(!string(value.key)||!keyPattern.test(value.key))issue(issues,"key","KEY","Agent key 格式无效");if(!string(value.version)||!semverPattern.test(value.version))issue(issues,"version","SEMVER","版本必须是完整 SemVer");
  if(!object(value.metadata))issue(issues,"metadata","TYPE","必须提供本地化元数据");else for(const locale of ["zh-CN","en"] as const){const metadata=value.metadata[locale];if(!object(metadata)||!string(metadata.name)||!string(metadata.description))issue(issues,`metadata.${locale}`,"LOCALE_REQUIRED","名称和描述必须完整");}
  const capabilities=uniqueKeys(value.capabilities,"capabilities",issues);if(!capabilities.length)issue(issues,"capabilities","REQUIRED","至少声明一项能力");for(const[index,capability]of capabilities.entries()){validateSchema(capability.input,`capabilities[${index}].input`,issues);validateSchema(capability.output,`capabilities[${index}].output`,issues);const events=uniqueKeys(capability.events,`capabilities[${index}].events`,issues);for(const[eventIndex,event]of events.entries())validateSchema(event.schema,`capabilities[${index}].events[${eventIndex}].schema`,issues);if(!Array.isArray(capability.permissions)||capability.permissions.some(permission=>!string(permission)||!keyPattern.test(permission)))issue(issues,`capabilities[${index}].permissions`,"PERMISSIONS","权限标识无效");}
  if(!object(value.dependencies))issue(issues,"dependencies","TYPE","依赖配置无效");else{if(!Array.isArray(value.dependencies.providers)||value.dependencies.providers.some(item=>!string(item)||!keyPattern.test(item))||new Set(value.dependencies.providers).size!==value.dependencies.providers.length)issue(issues,"dependencies.providers","DEPENDENCY","Provider 依赖必须有效且唯一");for(const[index,agent]of uniqueKeys(value.dependencies.agents,"dependencies.agents",issues).entries())if(!string(agent.versionRange)||!rangePattern.test(agent.versionRange))issue(issues,`dependencies.agents[${index}].versionRange`,"VERSION_RANGE","依赖版本范围无效");}
  const entitlements=uniqueKeys(value.entitlements,"entitlements",issues);for(const[index,item]of entitlements.entries()){if(!["trial","starter","pro","business"].includes(String(item.minimumPlan)))issue(issues,`entitlements[${index}].minimumPlan`,"PLAN","套餐无效");if(!Number.isSafeInteger(item.quantity)||Number(item.quantity)<0)issue(issues,`entitlements[${index}].quantity`,"QUANTITY","权益数量无效");}
  const capabilityKeys=new Set(capabilities.map(item=>String(item.key)));const risks=uniqueKeys(value.risks,"risks",issues,item=>item.capability);for(const[index,item]of risks.entries()){if(!capabilityKeys.has(String(item.capability)))issue(issues,`risks[${index}].capability`,"UNKNOWN_CAPABILITY","风险能力不存在");if(!["low","medium","high","critical"].includes(String(item.level)))issue(issues,`risks[${index}].level`,"RISK","风险级别无效");if(!["none","policy","required"].includes(String(item.approval))||(["high","critical"].includes(String(item.level))&&item.approval!=="required"))issue(issues,`risks[${index}].approval`,"APPROVAL","高风险与严重风险必须人工审批");}for(const key of capabilityKeys)if(!risks.some(item=>item.capability===key))issue(issues,"risks","RISK_REQUIRED",`能力 ${key} 缺少风险声明`);
  const schedules=uniqueKeys(value.schedules,"schedules",issues);for(const[index,item]of schedules.entries()){if(item.cron!==null&&(!string(item.cron)||item.cron.trim().split(/\s+/).length!==5))issue(issues,`schedules[${index}].cron`,"CRON","Cron 必须包含 5 个字段");if(!Number.isSafeInteger(item.minimumIntervalSeconds)||Number(item.minimumIntervalSeconds)<60)issue(issues,`schedules[${index}].minimumIntervalSeconds`,"INTERVAL","最短调度间隔为 60 秒");if(item.timezone!=="project"&&item.timezone!=="utc")issue(issues,`schedules[${index}].timezone`,"TIMEZONE","时区模式无效");}
  if(!object(value.compatibility)||!object(value.compatibility.platform)||!string(value.compatibility.platform.minimum)||!semverPattern.test(value.compatibility.platform.minimum))issue(issues,"compatibility.platform.minimum","COMPATIBILITY","最低平台版本无效");else if(value.compatibility.platform.maximum!==null&&(!string(value.compatibility.platform.maximum)||!semverPattern.test(value.compatibility.platform.maximum)||compareSemver(value.compatibility.platform.minimum,value.compatibility.platform.maximum)>0))issue(issues,"compatibility.platform.maximum","COMPATIBILITY","最高平台版本无效");if(!object(value.compatibility)||!Array.isArray(value.compatibility.manifestVersions)||!value.compatibility.manifestVersions.includes("1"))issue(issues,"compatibility.manifestVersions","COMPATIBILITY","必须兼容清单版本 1");
  if(issues.length)throw new AgentManifestError(issues);return structuredClone(value) as AgentManifest;
}
