import { createHash } from "node:crypto";
import { validateAgentManifest, type AgentManifest } from "./manifest";

export type AgentVersionRecord={id:string;agentKey:string;version:string;manifest:AgentManifest;digest:string;createdAt:number};
export type ProjectAgentRecord={id:string;organizationId:string;projectId:string;agentKey:string;agentVersion:string;enabled:boolean;configuration:Record<string,unknown>;revision:number;createdAt:number;updatedAt:number};
export interface AgentRegistryRepository{transaction<T>(operation:()=>T):T;version(agentKey:string,version:string):AgentVersionRecord|null;appendVersion(value:AgentVersionRecord):void;versions(agentKey:string):AgentVersionRecord[];projectAgent(organizationId:string,projectId:string,agentKey:string):ProjectAgentRecord|null;putProjectAgent(value:ProjectAgentRecord,expectedRevision:number):boolean;projectAgents(organizationId:string,projectId:string):ProjectAgentRecord[];projectExists(organizationId:string,projectId:string):boolean;}
export interface AgentFeatureGate{enabled(input:{organizationId:string;projectId:string;agentKey:string;agentVersion:string}):boolean;}
export class AgentRegistryError extends Error{constructor(readonly code:string,message:string,readonly status=400){super(message);}}
const stable=(value:unknown):string=>value&&typeof value==="object"?Array.isArray(value)?`[${value.map(stable).join(",")}]`:`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${stable(item)}`).join(",")}}`:JSON.stringify(value);
const digest=(value:unknown)=>createHash("sha256").update(stable(value)).digest("hex");
const sensitive=/password|secret|token|credential|api[_-]?key|private[_-]?key/i;
function safeConfiguration(value:unknown,depth=0):Record<string,unknown>{if(!value||typeof value!=="object"||Array.isArray(value))throw new AgentRegistryError("CONFIGURATION_INVALID","Agent 配置必须是对象");if(depth>6)throw new AgentRegistryError("CONFIGURATION_INVALID","Agent 配置嵌套过深");const entries=Object.entries(value as Record<string,unknown>);if(entries.length>100||Buffer.byteLength(JSON.stringify(value))>32_768)throw new AgentRegistryError("CONFIGURATION_TOO_LARGE","Agent 配置超过限制",413);return Object.fromEntries(entries.map(([key,item])=>{if(sensitive.test(key))throw new AgentRegistryError("SENSITIVE_CONFIGURATION","Agent 配置不能包含凭证或密钥");if(item&&typeof item==="object")return[key,Array.isArray(item)?item.slice(0,100).map(nested=>nested&&typeof nested==="object"?safeConfiguration({value:nested},depth+1).value:nested):safeConfiguration(item,depth+1)];if(item===null||typeof item==="string"||typeof item==="boolean"||typeof item==="number"&&Number.isFinite(item))return[key,item];throw new AgentRegistryError("CONFIGURATION_INVALID","Agent 配置值无效");}));}

export class AgentRegistryService{
  constructor(private readonly repository:AgentRegistryRepository,private readonly gate:AgentFeatureGate,private readonly now=()=>Math.floor(Date.now()/1000)){}
  publish(value:unknown){const manifest=validateAgentManifest(value),hash=digest(manifest);return this.repository.transaction(()=>{const existing=this.repository.version(manifest.key,manifest.version);if(existing){if(existing.digest!==hash)throw new AgentRegistryError("IMMUTABLE_VERSION_CONFLICT","同一 Agent 版本不可修改",409);return{record:existing,duplicate:true};}const record:AgentVersionRecord={id:crypto.randomUUID(),agentKey:manifest.key,version:manifest.version,manifest,digest:hash,createdAt:this.now()};this.repository.appendVersion(record);return{record,duplicate:false};});}
  history(agentKey:string){return this.repository.versions(agentKey);}
  configure(input:{organizationId:string;projectId:string;agentKey:string;agentVersion:string;enabled:boolean;configuration:unknown;expectedRevision:number}){return this.repository.transaction(()=>{if(!this.repository.projectExists(input.organizationId,input.projectId))throw new AgentRegistryError("PROJECT_NOT_FOUND","项目不存在",404);if(!this.repository.version(input.agentKey,input.agentVersion))throw new AgentRegistryError("AGENT_VERSION_NOT_FOUND","Agent 版本不存在",404);if(input.enabled&&!this.gate.enabled(input))throw new AgentRegistryError("AGENT_FEATURE_DISABLED","Agent 功能尚未对当前项目开放",403);if(!Number.isInteger(input.expectedRevision)||input.expectedRevision<0)throw new AgentRegistryError("REVISION_INVALID","配置版本无效");const current=this.repository.projectAgent(input.organizationId,input.projectId,input.agentKey),now=this.now(),record:ProjectAgentRecord={id:current?.id??crypto.randomUUID(),organizationId:input.organizationId,projectId:input.projectId,agentKey:input.agentKey,agentVersion:input.agentVersion,enabled:input.enabled,configuration:safeConfiguration(input.configuration),revision:(current?.revision??0)+1,createdAt:current?.createdAt??now,updatedAt:now};if(!this.repository.putProjectAgent(record,input.expectedRevision))throw new AgentRegistryError("CONFIGURATION_CONFLICT","Agent 配置已更新，请刷新后重试",409);return record;});}
  list(organizationId:string,projectId:string){if(!this.repository.projectExists(organizationId,projectId))throw new AgentRegistryError("PROJECT_NOT_FOUND","项目不存在",404);return this.repository.projectAgents(organizationId,projectId).map(record=>({...record,gateEnabled:this.gate.enabled(record)}));}
}
export class AllowlistedAgentFeatureGate implements AgentFeatureGate{constructor(private readonly allowed:Set<string>){ }enabled(input:{organizationId:string;projectId:string;agentKey:string}){return this.allowed.has("*")||this.allowed.has(input.agentKey)||this.allowed.has(`${input.organizationId}:${input.agentKey}`)||this.allowed.has(`${input.organizationId}:${input.projectId}:${input.agentKey}`);}}
