export type ScheduleWindow={days:number[];start:string;end:string};
export type AgentScheduleRecord={id:string;organizationId:string;projectId:string;projectAgentId:string;scheduleKey:string;cron:string;timezone:string;window:ScheduleWindow|null;enabled:boolean;pausedAt:number|null;nextRunAt:number|null;revision:number;createdAt:number;updatedAt:number};
export type AgentScheduleFire={id:string;scheduleId:string;organizationId:string;projectId:string;scheduledFor:number;idempotencyKey:string;createdAt:number};
export interface AgentScheduleRepository{transaction<T>(operation:()=>T):T;projectAgentExists(organizationId:string,projectId:string,projectAgentId:string):boolean;schedule(organizationId:string,projectId:string,id:string):AgentScheduleRecord|null;schedules(organizationId:string,projectId:string):AgentScheduleRecord[];put(value:AgentScheduleRecord,expectedRevision:number):boolean;due(now:number,limit:number):AgentScheduleRecord[];fireAndAdvance(schedule:AgentScheduleRecord,fire:AgentScheduleFire,nextRunAt:number):boolean;firings(scheduleId:string):AgentScheduleFire[];}
export class AgentScheduleError extends Error{constructor(readonly code:string,message:string,readonly status=400){super(message);}}
const timePattern=/^(?:[01]\d|2[0-3]):[0-5]\d$/;
function timezone(value:string){try{new Intl.DateTimeFormat("en-US",{timeZone:value}).format(0);return value;}catch{throw new AgentScheduleError("TIMEZONE_INVALID","项目时区无效");}}
function window(value:ScheduleWindow|null):ScheduleWindow|null{if(value===null)return null;if(!value||typeof value!=="object"||Array.isArray(value)||!Array.isArray(value.days)||!value.days.length||value.days.some(day=>!Number.isInteger(day)||day<0||day>6)||new Set(value.days).size!==value.days.length||!timePattern.test(value.start)||!timePattern.test(value.end)||value.start===value.end)throw new AgentScheduleError("WINDOW_INVALID","执行时窗无效");return{days:[...value.days].sort(),start:value.start,end:value.end};}
function cronField(value:string,min:number,max:number,weekday=false){const result=new Set<number>();for(const part of value.split(",")){const[base,stepText]=part.split("/"),step=stepText===undefined?1:Number(stepText);if(!Number.isInteger(step)||step<1)throw new AgentScheduleError("CRON_INVALID","Cron 步长无效");let start:number,end:number;if(base==="*"){start=min;end=max;}else if(base.includes("-")){const values=base.split("-").map(Number);if(values.length!==2)throw new AgentScheduleError("CRON_INVALID","Cron 范围无效");[start,end]=values;}else{start=Number(base);end=start;}if(weekday){if(start===7)start=0;if(end===7)end=0;}if(!Number.isInteger(start)||!Number.isInteger(end)||start<min||start>max||end<min||end>max||start>end)throw new AgentScheduleError("CRON_INVALID","Cron 字段越界");for(let current=start;current<=end;current+=step)result.add(current);}return result;}
function parseCron(value:string){const parts=value.trim().split(/\s+/);if(parts.length!==5)throw new AgentScheduleError("CRON_INVALID","Cron 必须包含 5 个字段");return{minute:cronField(parts[0],0,59),hour:cronField(parts[1],0,23),day:cronField(parts[2],1,31),month:cronField(parts[3],1,12),weekday:cronField(parts[4],0,6,true)};}
const formatter=new Map<string,Intl.DateTimeFormat>();
function localParts(epoch:number,zone:string){let value=formatter.get(zone);if(!value){value=new Intl.DateTimeFormat("en-US",{timeZone:zone,year:"numeric",month:"numeric",day:"numeric",hour:"numeric",minute:"numeric",hourCycle:"h23",weekday:"short"});formatter.set(zone,value);}const parts=Object.fromEntries(value.formatToParts(new Date(epoch*1000)).map(part=>[part.type,part.value]));return{minute:Number(parts.minute),hour:Number(parts.hour),day:Number(parts.day),month:Number(parts.month),weekday:["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].indexOf(parts.weekday)};}
function withinWindow(parts:ReturnType<typeof localParts>,value:ScheduleWindow|null){if(!value)return true;if(!value.days.includes(parts.weekday))return false;const minute=parts.hour*60+parts.minute,start=Number(value.start.slice(0,2))*60+Number(value.start.slice(3)),end=Number(value.end.slice(0,2))*60+Number(value.end.slice(3));return start<end?minute>=start&&minute<end:minute>=start||minute<end;}
export function nextAgentRun(cron:string,zone:string,value:ScheduleWindow|null,after:number){const parsed=parseCron(cron),validZone=timezone(zone),validWindow=window(value),start=Math.floor(after/60)*60+60;for(let candidate=start;candidate<=start+366*24*60*60;candidate+=60){const parts=localParts(candidate,validZone);if(parsed.minute.has(parts.minute)&&parsed.hour.has(parts.hour)&&parsed.day.has(parts.day)&&parsed.month.has(parts.month)&&parsed.weekday.has(parts.weekday)&&withinWindow(parts,validWindow))return candidate;}throw new AgentScheduleError("NEXT_RUN_UNAVAILABLE","未来一年内没有可执行时间");}
export class AgentScheduleService{constructor(private readonly repository:AgentScheduleRepository,private readonly now=()=>Math.floor(Date.now()/1000)){}
  list(organizationId:string,projectId:string){return this.repository.schedules(organizationId,projectId);}
  configure(input:{organizationId:string;projectId:string;projectAgentId:string;id?:string;scheduleKey:string;cron:string;timezone:string;window:ScheduleWindow|null;enabled:boolean;expectedRevision:number}){return this.repository.transaction(()=>{if(!this.repository.projectAgentExists(input.organizationId,input.projectId,input.projectAgentId))throw new AgentScheduleError("PROJECT_AGENT_NOT_FOUND","项目 Agent 不存在",404);if(!/^[a-z][a-z0-9._-]{0,63}$/.test(input.scheduleKey))throw new AgentScheduleError("SCHEDULE_KEY_INVALID","调度标识无效");if(!Number.isInteger(input.expectedRevision)||input.expectedRevision<0)throw new AgentScheduleError("REVISION_INVALID","配置版本无效");parseCron(input.cron);timezone(input.timezone);const safeWindow=window(input.window),now=this.now(),current=input.id?this.repository.schedule(input.organizationId,input.projectId,input.id):null;if(input.id&&!current)throw new AgentScheduleError("SCHEDULE_NOT_FOUND","调度不存在",404);if(current&&current.projectAgentId!==input.projectAgentId)throw new AgentScheduleError("PROJECT_AGENT_MISMATCH","不能变更调度所属 Agent",409);const active=input.enabled&&current?.pausedAt==null,record:AgentScheduleRecord={id:current?.id??crypto.randomUUID(),organizationId:input.organizationId,projectId:input.projectId,projectAgentId:input.projectAgentId,scheduleKey:input.scheduleKey,cron:input.cron,timezone:input.timezone,window:safeWindow,enabled:input.enabled,pausedAt:current?.pausedAt??null,nextRunAt:active?nextAgentRun(input.cron,input.timezone,safeWindow,now):null,revision:(current?.revision??0)+1,createdAt:current?.createdAt??now,updatedAt:now};if(!this.repository.put(record,input.expectedRevision))throw new AgentScheduleError("SCHEDULE_CONFLICT","调度已更新，请刷新后重试",409);return record;});}
  pause(organizationId:string,projectId:string,id:string,expectedRevision:number){return this.setPaused(organizationId,projectId,id,expectedRevision,true);}
  resume(organizationId:string,projectId:string,id:string,expectedRevision:number){return this.setPaused(organizationId,projectId,id,expectedRevision,false);}
  private setPaused(organizationId:string,projectId:string,id:string,expectedRevision:number,paused:boolean){return this.repository.transaction(()=>{const current=this.repository.schedule(organizationId,projectId,id);if(!current)throw new AgentScheduleError("SCHEDULE_NOT_FOUND","调度不存在",404);if(current.revision!==expectedRevision)throw new AgentScheduleError("SCHEDULE_CONFLICT","调度已更新，请刷新后重试",409);const now=this.now(),record={...current,pausedAt:paused?now:null,nextRunAt:paused||!current.enabled?null:nextAgentRun(current.cron,current.timezone,current.window,now),revision:current.revision+1,updatedAt:now};if(!this.repository.put(record,expectedRevision))throw new AgentScheduleError("SCHEDULE_CONFLICT","调度已更新，请刷新后重试",409);return record;});}
  fireDue(limit=100){const now=this.now(),fires:AgentScheduleFire[]=[];for(const schedule of this.repository.due(now,Math.max(1,Math.min(limit,100)))){const scheduledFor=schedule.nextRunAt;if(scheduledFor===null)continue;const fire:AgentScheduleFire={id:crypto.randomUUID(),scheduleId:schedule.id,organizationId:schedule.organizationId,projectId:schedule.projectId,scheduledFor,idempotencyKey:`agent-schedule:${schedule.id}:${scheduledFor}`,createdAt:now},next=nextAgentRun(schedule.cron,schedule.timezone,schedule.window,scheduledFor);if(this.repository.fireAndAdvance(schedule,fire,next))fires.push(fire);}return fires;}
}
