import { getDatabase } from "../lib/auth";
import { commerceRepository, commerceService, ensureBillingSchema } from "../lib/billing";
import { atomicTaskCreationService, ensureExecutionSchema, executionRepository } from "../lib/execution";
import { permissions, type OrganizationRoleKey } from "../platform/modules/identity/authorization";
import type { CommercialSubject } from "../platform/modules/commerce";

const db=getDatabase();await ensureBillingSchema();await ensureExecutionSchema();
const projectId=process.env.WORKER_SMOKE_PROJECT_ID;
const project=db.prepare(`SELECT p.id,p.name,p.site_url AS siteUrl,p.host,p.language,p.organization_id AS organizationId,u.id AS accountId,u.plan AS planKey,u.trial_ends_at AS trialEndsAt,u.created_at AS accountCreatedAt,o.status AS organizationStatus,r.role_key AS roleKey
 FROM projects p JOIN users u ON u.id=p.user_id JOIN identity_organizations o ON o.id=p.organization_id JOIN identity_memberships m ON m.organization_id=o.id AND m.user_id=u.id AND m.status='active' JOIN identity_roles r ON r.id=m.role_id
 WHERE p.status='active' AND (? IS NULL OR p.id=?) ORDER BY p.updated_at DESC LIMIT 1`).bind(projectId??null,projectId??null).first<Record<string,unknown>>();
if(!project)throw new Error("ACTIVE_PROJECT_NOT_FOUND");
const subject:CommercialSubject={accountId:String(project.accountId),organizationId:String(project.organizationId),organizationStatus:project.organizationStatus as CommercialSubject["organizationStatus"],planKey:project.planKey as CommercialSubject["planKey"],trialEndsAt:project.trialEndsAt===null?null:Number(project.trialEndsAt),accountCreatedAt:Number(project.accountCreatedAt)},commerce=commerceService(),effective=commerce.resolve(subject),usage=commerce.usageTotals(subject).find(row=>row.metric==="pages_crawled"),currentPages=Number(usage?.final??0)+Number(usage?.pending??0),pageLimit=Math.min(effective.limits.pagesPerAudit,effective.limits.pagesPerMonth-currentPages),before=commerce.balance(subject),idempotencyKey=process.env.WORKER_SMOKE_IDEMPOTENCY_KEY||`worker-smoke:${String(project.id)}:${Date.now()}`;
const created=(await atomicTaskCreationService()).create({activeOrganizationId:subject.organizationId,organizationId:subject.organizationId,projectId:String(project.id),requestedByAccountId:subject.accountId,role:project.roleKey as OrganizationRoleKey,permission:permissions.auditsRun,subject,triggerType:"system",taskType:"seo_audit",capability:"seo.audit",input:{projectId:String(project.id),siteUrl:String(project.siteUrl),pageLimit,title:`${String(project.name)} Worker 上线验收`,description:"生产 Worker 端到端验收"},locale:project.language==="en"?"en":"zh-CN",idempotencyKey,correlationId:`worker-smoke:${crypto.randomUUID()}`,entitlements:[{key:"pagesPerAudit",quantity:1,currentUsage:0},{key:"pagesPerMonth",quantity:1,currentUsage:currentPages}],creditCost:10,queue:"agents",jobType:"seo.audit",priority:100,maxAttempts:3,timeoutSeconds:900});
const deadline=Date.now()+16*60*1000;let task=created.task;while(Date.now()<deadline&&!['completed','failed','cancelled','quarantined'].includes(task.state)){await new Promise(resolve=>setTimeout(resolve,1000));task=executionRepository().task(subject.organizationId,created.task.id)!;}
const artifact=db.prepare("SELECT id,kind,mime_type AS mimeType,size_bytes AS sizeBytes,scan_state AS scanState FROM execution_artifacts WHERE organization_id=? AND task_id=? ORDER BY created_at DESC LIMIT 1").bind(subject.organizationId,created.task.id).first(),reservation=created.reservationId?commerceRepository().terminalForReservation(subject.organizationId,created.reservationId):null,after=commerce.balance(subject);
const result={taskId:created.task.id,jobId:created.job.id,state:task.state,progress:task.progress,artifact,reservationState:reservation?.entryType??null,credits:{beforeCommitted:before.committed,beforeReserved:before.reserved,afterCommitted:after.committed,afterReserved:after.reserved,charged:after.committed-before.committed}};console.log(JSON.stringify(result,null,2));if(task.state!=="completed"||!artifact||reservation?.entryType!=="commit"||result.credits.charged!==10)process.exitCode=1;
