import {getDatabase} from "../lib/auth";
import {ensureBillingSchema,commerceService} from "../lib/billing";
import {atomicTaskCreationService,executionRepository} from "../lib/execution";
import {ensureProductSchema} from "../lib/product";
import {permissions,type OrganizationRoleKey} from "../platform/modules/identity/authorization";
import type {CommercialSubject} from "../platform/modules/commerce";

const wait=(milliseconds:number)=>new Promise(resolve=>setTimeout(resolve,milliseconds));
await ensureProductSchema();await ensureBillingSchema();const db=getDatabase(),row=db.prepare(`SELECT u.id accountId,u.plan planKey,u.trial_ends_at trialEndsAt,u.created_at accountCreatedAt,o.id organizationId,o.status organizationStatus,p.id projectId,p.name projectName,p.site_url siteUrl,p.market,p.language,r.role_key roleKey FROM users u JOIN identity_organizations o ON o.owner_user_id=u.id JOIN identity_memberships m ON m.organization_id=o.id AND m.user_id=u.id AND m.status='active' JOIN identity_roles r ON r.id=m.role_id JOIN projects p ON p.organization_id=o.id AND p.status='active' WHERE u.status='active' ORDER BY p.created_at LIMIT 1`).first<{accountId:string;planKey:CommercialSubject["planKey"];trialEndsAt:number|null;accountCreatedAt:number;organizationId:string;organizationStatus:CommercialSubject["organizationStatus"];projectId:string;projectName:string;siteUrl:string;market:string;language:string;roleKey:OrganizationRoleKey}>();if(!row)throw new Error("RESEARCH_ACCEPTANCE_SUBJECT_NOT_FOUND");
const subject:CommercialSubject={accountId:row.accountId,organizationId:row.organizationId,organizationStatus:row.organizationStatus,planKey:row.planKey,trialEndsAt:row.trialEndsAt,accountCreatedAt:row.accountCreatedAt};commerceService().authorizeAccess(subject);const release=(process.env.RELEASE_COMMIT||"manual").replace(/[^A-Za-z0-9._-]/g,"-").slice(0,64),correlationId=`research:acceptance:${release}`,created=(await atomicTaskCreationService()).create({activeOrganizationId:row.organizationId,organizationId:row.organizationId,projectId:row.projectId,requestedByAccountId:row.accountId,role:row.roleKey,permission:permissions.researchRun,subject,triggerType:"manual",taskType:"research_agent_acceptance",capability:"research.discover",input:{projectId:row.projectId,siteUrl:row.siteUrl,market:row.market,language:row.language,seed:"",maximumPages:3,title:`${row.projectName} Research Agent 生产验收`,description:"生产 Worker、证据、报告与 Credits 完整链路验收"},locale:row.language.startsWith("en")?"en":"zh-CN",idempotencyKey:`research:acceptance:${release}`,correlationId,entitlements:[],creditCost:5,queue:"agents",jobType:"research.run",priority:100,maxAttempts:2,timeoutSeconds:900});
const deadline=Date.now()+15*60*1000;let task=executionRepository().task(row.organizationId,created.task.id);while(task&&!['completed','failed','cancelled','quarantined'].includes(task.state)&&Date.now()<deadline){await wait(2000);task=executionRepository().task(row.organizationId,created.task.id);}if(!task||task.state!=="completed"){const attempts=executionRepository().attempts(row.organizationId,created.job.id);throw new Error(`RESEARCH_ACCEPTANCE_FAILED:${task?.state||"missing"}:${attempts.at(-1)?.errorCode||"unknown"}`);}
const run=db.prepare("SELECT status,opportunities_found opportunitiesFound,evidence_count evidenceCount,source_count sourceCount,degraded_sources degradedSources FROM research_runs WHERE execution_task_id=?").bind(task.id).first<Record<string,unknown>>(),artifact=db.prepare("SELECT id,kind,object_key objectKey,sha256 FROM execution_artifacts WHERE organization_id=? AND task_id=? AND scan_state='clean'").bind(row.organizationId,task.id).first<Record<string,unknown>>(),terminal=db.prepare("SELECT entry_type entryType,quantity FROM commerce_credit_ledger WHERE organization_id=? AND task_id=? AND entry_type IN('commit','release') ORDER BY created_at DESC LIMIT 1").bind(row.organizationId,task.id).first<Record<string,unknown>>();if(!run||run.status!=="completed"||Number(run.evidenceCount)<1||!artifact||artifact.kind!=="research_report"||terminal?.entryType!=="commit"||Number(terminal.quantity)!==5)throw new Error("RESEARCH_ACCEPTANCE_INVARIANT_FAILED");console.log(JSON.stringify({release,taskId:task.id,state:task.state,projectId:row.projectId,run,artifact,credits:terminal,workerProgress:executionRepository().progress(row.organizationId,task.id,20).map(item=>({progress:item.progress,stage:item.stage,messageKey:item.messageKey}))},null,2));
