import { NextResponse } from "next/server";
import { getCurrentUser, writeAudit } from "../../../../lib/auth";
import { clearModelProvider,listModelProviders,modelEncryptionReady,modelProviderDefinitions,saveModelProvider,testModelProvider,type ModelProvider } from "../../../../lib/model-providers";
import { AuthorizationError,authorizePlatformAccount } from "../../../../platform/modules/identity/authorization";
async function admin(){const user=await getCurrentUser();if(!user)return null;try{authorizePlatformAccount(user.role);return user;}catch(error){if(error instanceof AuthorizationError)return null;throw error;}}
const valid=(value:unknown):value is ModelProvider=>typeof value==="string"&&value in modelProviderDefinitions;
export async function GET(){const user=await admin();if(!user)return NextResponse.json({error:"无权访问"},{status:403});return NextResponse.json({encryptionReady:modelEncryptionReady(),providers:await listModelProviders()},{headers:{"cache-control":"private, no-store"}});}
export async function PATCH(request:Request){const user=await admin();if(!user)return NextResponse.json({error:"无权访问"},{status:403});const body=await request.json().catch(()=>null) as Record<string,unknown>|null;if(!valid(body?.provider))return NextResponse.json({error:"模型供应商无效"},{status:400});try{await saveModelProvider({provider:body.provider,enabled:body.enabled===true,isDefault:body.isDefault===true,baseUrl:String(body.baseUrl||modelProviderDefinitions[body.provider].baseUrl),model:String(body.model||""),apiKey:typeof body.apiKey==="string"?body.apiKey:undefined,temperature:Number(body.temperature),maxOutputTokens:Number(body.maxOutputTokens)},user.id);}catch(error){const code=error instanceof Error?error.message:"SAVE_FAILED",messages:Record<string,string>={MODEL_CONFIG_ENCRYPTION_KEY_MISSING:"服务器尚未配置模型密钥加密能力",MODEL_API_KEY_REQUIRED:"启用模型前请填写 API Key",MODEL_NAME_REQUIRED:"请填写模型名称",MODEL_ENDPOINT_INVALID:"接口地址必须使用该供应商的官方 HTTPS 域名"};return NextResponse.json({error:messages[code]||"模型配置保存失败",code},{status:code==="MODEL_CONFIG_ENCRYPTION_KEY_MISSING"?503:400});}await writeAudit("admin_model_provider_update",user.id,request,JSON.stringify({provider:body.provider,enabled:body.enabled===true,isDefault:body.isDefault===true}));return NextResponse.json({ok:true});}
export async function POST(request:Request){const user=await admin();if(!user)return NextResponse.json({error:"无权访问"},{status:403});const body=await request.json().catch(()=>null) as Record<string,unknown>|null;if(!valid(body?.provider))return NextResponse.json({error:"模型供应商无效"},{status:400});const result=await testModelProvider(body.provider);await writeAudit("admin_model_provider_test",user.id,request,JSON.stringify({provider:body.provider,ok:result.ok}));return NextResponse.json(result,{status:result.ok?200:422});}
export async function DELETE(request:Request){const user=await admin();if(!user)return NextResponse.json({error:"无权访问"},{status:403});const body=await request.json().catch(()=>null) as Record<string,unknown>|null;if(!valid(body?.provider))return NextResponse.json({error:"模型供应商无效"},{status:400});await clearModelProvider(body.provider,user.id);await writeAudit("admin_model_provider_clear",user.id,request,JSON.stringify({provider:body.provider}));return NextResponse.json({ok:true});}
