import { getDatabase } from "./auth";
import { auditReportMarkdown, type AuditReportData } from "./audit-report";
import { publicRobotsPolicy, runSiteAudit } from "./site-audit";
import { SeoAuditAgent, type AuditAcquisition, type AuditAgentResult, type AuditSourceAcquirer } from "../platform/modules/agents/audit-agent";
import type { AgentExecutionEnvelope } from "../platform/modules/agents/contracts";
import { validateAgentExecutionEnvelope } from "../platform/modules/agents/contracts";
import { WorkerJobError } from "../platform/modules/execution/worker";

export type AuditExecutionInput={projectId:string;siteUrl:string;pageLimit:number};
export type AuditExecutionContext={organizationId:string;taskId:string;jobId:string;attemptId:string;accountId:string;correlationId:string;locale:"zh-CN"|"en"};
export type AuditExecutionResult={runId:string;score:number;pagesScanned:number;urlsDiscovered:number;findingCount:number;evidenceCount:number;partial:boolean;partialReasons:string[];degradedSources:string[];report:Uint8Array;reportTitle:string};

export class PublicCrawlAuditAcquirer implements AuditSourceAcquirer{
  constructor(private readonly signal?:AbortSignal){}
  async acquire(input:{siteUrl:string;maximumPages:number;integrationRefs:AgentExecutionEnvelope["integrationRefs"];signal?:AbortSignal}):Promise<AuditAcquisition>{
    const robots=await publicRobotsPolicy(input.siteUrl);if(!robots.allowed(input.siteUrl))throw new Error("ROBOTS_POLICY_DENIED");
    const result=await runSiteAudit(input.siteUrl,Math.min(input.maximumPages,1000),{allowed:robots.allowed,minimumDelayMs:robots.crawlDelaySeconds?robots.crawlDelaySeconds*1000:0,signal:input.signal??this.signal}),capturedAt=Math.floor(Date.now()/1000),providers=new Set(input.integrationRefs.map(item=>item.provider));
    const degradedSources=[!providers.has("google.search-console")?"google_search_console":"",!providers.has("google.analytics")?"google_analytics":"",!providers.has("rank.provider")?"rank_provider":"",!providers.has("backlink.provider")?"backlink_provider":""].filter(Boolean);
    return{capturedAt,freshUntil:capturedAt+86_400,result,degradedSources};
  }
}

function coverage(result:AuditAgentResult){if(!result.audit)return "";return `\n\n## 审计覆盖声明\n\n- 覆盖状态：${result.audit.partial?"部分覆盖":"完整覆盖"}\n- 已抓取 / 已发现：${result.audit.pages.length} / ${result.audit.urlsDiscovered}\n- robots.txt 排除：${result.audit.urlsBlockedByRobots}\n- 部分覆盖原因：${result.audit.partialReasons.length?result.audit.partialReasons.join("、"):"无"}\n- 未接入扩展数据源：${result.degradedSources.length?result.degradedSources.join("、"):"无"}\n\n> 未抓取或未授权的数据不会被外推为事实。所有修复项仅作为建议进入 Approval Center，不会直接修改网站。\n`}

export async function executeSiteAudit(input:AuditExecutionInput,context:AuditExecutionContext,signal?:AbortSignal,dependencies:{acquirer?:AuditSourceAcquirer}={}):Promise<AuditExecutionResult>{
  if(signal?.aborted)throw signal.reason;const db=getDatabase(),project=db.prepare("SELECT id,name,host,site_url AS siteUrl,market,language,status FROM projects WHERE id=? AND organization_id=?").bind(input.projectId,context.organizationId).first<{id:string;name:string;host:string;siteUrl:string;market:string;language:string;status:string}>();
  if(!project||project.status!=="active"||project.siteUrl!==input.siteUrl)throw new WorkerJobError("AUDIT_PROJECT_NOT_ACTIVE","Audit project is not active",false);
  const runId=context.taskId,started=Math.floor(Date.now()/1000);db.prepare(`INSERT INTO audit_runs(id,project_id,status,started_at,execution_task_id,agent_version) VALUES (?,?,'running',?,?, '1.0.0') ON CONFLICT(id) DO UPDATE SET status='running',started_at=excluded.started_at,completed_at=NULL,error=NULL`).bind(runId,input.projectId,started,context.taskId).run();
  try{
    const envelope=validateAgentExecutionEnvelope({schemaVersion:"1",kind:"execution",organizationId:context.organizationId,projectId:input.projectId,taskId:context.taskId,jobId:context.jobId,attemptId:context.attemptId,correlationId:context.correlationId,idempotencyKey:`audit:${context.taskId}`,agent:{key:"seo.audit",version:"1.0.0",capability:"audit.run"},actor:{type:"user",id:context.accountId},locale:context.locale,input:{siteUrl:input.siteUrl,maximumPages:input.pageLimit},artifactRefs:[],integrationRefs:[],memoryRefs:[],deadlineAt:Math.floor(Date.now()/1000)+900,cancellation:{tokenRef:`cancel:${context.taskId}`,pollAfterSeconds:2},limits:{maxRuntimeSeconds:900,maxOutputBytes:4_000_000,maxArtifacts:1,maxUsageUnits:Math.min(input.pageLimit,1000)}});
    const result=await new SeoAuditAgent(dependencies.acquirer??new PublicCrawlAuditAcquirer(signal)).runDetailed(envelope);if(signal?.aborted)throw signal.reason;const failure=result.events.find(event=>event.kind==="error");if(failure?.kind==="error")throw new WorkerJobError(failure.error.code,failure.error.messageKey,failure.error.retryable);if(!result.audit)throw new WorkerJobError("AUDIT_EMPTY_RESULT","Audit returned no result",true);
    const audit=result.audit,now=Math.floor(Date.now()/1000),priorFindingIds=db.prepare("SELECT id FROM findings WHERE run_id=?").bind(runId).all<{id:string}>().results.map(item=>item.id),statements=[];
    if(priorFindingIds.length)for(const id of priorFindingIds)statements.push(db.prepare("UPDATE seo_tasks SET status='dismissed',updated_at=? WHERE finding_id=? AND status='proposed'").bind(now,id));
    statements.push(db.prepare("DELETE FROM seo_tasks WHERE project_id=? AND id LIKE ?").bind(input.projectId,`${runId}:task:%`));
    statements.push(db.prepare("DELETE FROM audit_pages WHERE run_id=?").bind(runId),db.prepare("DELETE FROM audit_checks WHERE run_id=?").bind(runId),db.prepare("DELETE FROM audit_category_scores WHERE run_id=?").bind(runId),db.prepare("DELETE FROM audit_evidence WHERE run_id=?").bind(runId),db.prepare("DELETE FROM findings WHERE run_id=?").bind(runId),db.prepare("UPDATE findings SET status='resolved' WHERE project_id=? AND run_id<>? AND status='open'").bind(input.projectId,runId),db.prepare("UPDATE seo_tasks SET status='dismissed',updated_at=? WHERE project_id=? AND status='proposed' AND (finding_id IS NULL OR finding_id NOT IN (SELECT id FROM findings WHERE run_id=?))").bind(now,input.projectId,runId));
    for(const [index,page] of audit.pages.entries())statements.push(db.prepare(`INSERT INTO audit_pages(id,run_id,url,status_code,title,description,canonical,h1_count,images_without_alt) VALUES (?,?,?,?,?,?,?,?,?)`).bind(`${runId}:page:${index+1}`,runId,page.url,page.statusCode,page.title,page.description,page.canonical,page.h1Count,page.imagesWithoutAlt));
    for(const item of result.evidence)statements.push(db.prepare(`INSERT INTO audit_evidence(id,run_id,project_id,source_type,source_ref,summary,digest,confidence,captured_at,fresh_until,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)`).bind(`${runId}:${item.id}`,runId,input.projectId,item.sourceType,item.sourceRef,item.summary,item.digest,item.confidence,item.capturedAt,item.freshUntil,now));
    for(const [index,item] of audit.checks.entries())statements.push(db.prepare(`INSERT INTO audit_checks(id,run_id,project_id,category,check_key,status,severity,confidence,title,description,evidence,impact,recommendation,url,evidence_refs,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(`${runId}:check:${index+1}`,runId,input.projectId,item.category,item.key,item.status,item.severity,item.confidence,item.title,item.description,item.evidence||null,item.impact||null,item.recommendation||null,item.url||null,JSON.stringify([`${runId}:evidence-${index+1}`]),now));
    for(const [index,finding] of audit.findings.entries()){const checkIndex=audit.checks.findIndex(item=>item.title===finding.title&&item.url===finding.url),evidenceRef=`${runId}:evidence-${Math.max(0,checkIndex)+1}`,recommendation=result.recommendations.find(item=>item.checkIndex===checkIndex),findingId=`${runId}:finding:${index+1}`,priority={critical:100,high:80,medium:50,low:20}[finding.severity];statements.push(db.prepare(`INSERT INTO findings(id,run_id,project_id,category,severity,title,description,evidence,url,evidence_refs,confidence,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`).bind(findingId,runId,input.projectId,finding.category,finding.severity,finding.title,finding.description,finding.evidence||null,finding.url,JSON.stringify([evidenceRef]),recommendation?.confidence??.5,now),db.prepare(`INSERT INTO seo_tasks(id,project_id,finding_id,type,title,description,priority,status,requires_approval,created_at,updated_at) VALUES (?,?,?,?,?,?,?,'proposed',1,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,description=excluded.description,priority=excluded.priority,status='proposed',requires_approval=1,updated_at=excluded.updated_at`).bind(`${runId}:task:${index+1}`,input.projectId,findingId,"fix_"+finding.category,finding.title,finding.description,priority,now,now));}
    for(const category of audit.categoryScores)statements.push(db.prepare(`INSERT INTO audit_category_scores(run_id,category,score,confidence,checks_total,checks_known) VALUES (?,?,?,?,?,?)`).bind(runId,category.category,category.score,category.confidence,category.checksTotal,category.checksKnown));
    statements.push(db.prepare(`UPDATE audit_runs SET status='completed',score=?,pages_scanned=?,urls_discovered=?,checks_total=?,checks_passed=?,checks_warning=?,checks_failed=?,checks_unknown=?,checks_skipped=?,evidence_count=?,coverage_status=?,partial_reasons=?,degraded_sources=?,completed_at=?,error=NULL WHERE id=?`).bind(audit.score,audit.pages.length,audit.urlsDiscovered,audit.summary.total,audit.summary.passed,audit.summary.warning,audit.summary.failed,audit.summary.unknown,audit.summary.skipped,result.evidence.length,audit.partial?"partial":"complete",JSON.stringify(audit.partialReasons),JSON.stringify(result.degradedSources),now,runId),db.prepare("UPDATE projects SET updated_at=? WHERE id=?").bind(now,input.projectId));db.batch(statements);
    const reportData:AuditReportData={project,run:{id:runId,score:audit.score,pagesScanned:audit.pages.length,urlsDiscovered:audit.urlsDiscovered,checksTotal:audit.summary.total,checksPassed:audit.summary.passed,checksWarning:audit.summary.warning,checksFailed:audit.summary.failed,checksUnknown:audit.summary.unknown,checksSkipped:audit.summary.skipped,completedAt:now},checks:audit.checks,scores:audit.categoryScores,pages:audit.pages},reportText=auditReportMarkdown(reportData)+coverage(result);
    return{runId,score:audit.score,pagesScanned:audit.pages.length,urlsDiscovered:audit.urlsDiscovered,findingCount:audit.findings.length,evidenceCount:result.evidence.length,partial:audit.partial,partialReasons:audit.partialReasons,degradedSources:result.degradedSources,report:new TextEncoder().encode(reportText),reportTitle:`${project.name} SEO Audit Agent 审计报告`};
  }catch(error){db.prepare("UPDATE audit_runs SET status='failed',error=?,completed_at=? WHERE id=?").bind(error instanceof Error?error.message:"AUDIT_FAILED",Math.floor(Date.now()/1000),runId).run();throw error;}
}
