type ReportProject={name:string;host:string;siteUrl:string;market:string;language:string};
type ReportRun={id:string;score:number;pagesScanned:number;urlsDiscovered:number;checksTotal:number;checksPassed:number;checksWarning:number;checksFailed:number;checksUnknown:number;checksSkipped:number;completedAt:number};
type ReportCheck={category:string;status:string;severity:string;confidence:string;title:string;description:string;evidence?:string|null;impact?:string|null;recommendation?:string|null;url?:string|null};
type ReportScore={category:string;score:number|null;confidence:string;checksTotal:number;checksKnown:number};
type ReportPage={url:string;statusCode:number;title?:string|null;h1Count:number;imagesWithoutAlt:number};
export type AuditReportData={project:ReportProject;run:ReportRun;checks:ReportCheck[];scores:ReportScore[];pages:ReportPage[]};

const categoryNames:Record<string,string>={technical:"技术 SEO",content:"内容质量与 E-E-A-T",on_page:"页面 SEO",structured_data:"结构化数据",performance:"性能与 Core Web Vitals",images:"图片优化",ai_search:"GEO / AI 搜索"};
const statusNames:Record<string,string>={pass:"通过",warning:"警告",fail:"失败",unknown:"未知",skipped:"跳过"};
const confidenceNames:Record<string,string>={confirmed:"已确认",likely:"较可能",hypothesis:"待验证",high:"高",medium:"中",low:"低"};
const esc=(value:unknown)=>String(value??"").replace(/[&<>"']/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]!));
const md=(value:unknown)=>String(value??"").replace(/\|/g,"\\|").replace(/\r?\n/g," ");
const date=(timestamp:number)=>new Date(timestamp*1000).toLocaleString("zh-CN",{timeZone:"Asia/Shanghai"});

export function auditReportMarkdown(data:AuditReportData):string{
 const issues=data.checks.filter(item=>item.status==="fail"||item.status==="warning");
 const unknowns=data.checks.filter(item=>item.status==="unknown"||item.status==="skipped");
 const known=Math.max(0,data.run.checksTotal-data.run.checksUnknown-data.run.checksSkipped),coverage=data.run.checksTotal?Math.round(known/data.run.checksTotal*100):0;
 const lines=[`# ${data.project.name}｜公开网站证据审计报告`,``,`- 网站：${data.project.siteUrl}`,
 `- 范围：本次实际发现并抓取的公开页面；不把未取得的数据视为通过`,`- 完成时间：${date(data.run.completedAt)}`,
 `- 已验证健康分：${data.run.score}/100`,`- 证据覆盖率：${coverage}%（${known}/${data.run.checksTotal}）`,`- URL：发现 ${data.run.urlsDiscovered}，实际抓取 ${data.run.pagesScanned}`,
 `- 检查项：${data.run.checksTotal}（通过 ${data.run.checksPassed}、警告 ${data.run.checksWarning}、失败 ${data.run.checksFailed}、未知 ${data.run.checksUnknown}、跳过 ${data.run.checksSkipped}）`,``,
 `## 分类得分`,``,`| 分类 | 得分 | 覆盖率 | 置信度 |`,`|---|---:|---:|---|`,...data.scores.map(item=>`| ${categoryNames[item.category]||item.category} | ${item.score??"数据不足"} | ${item.checksKnown}/${item.checksTotal} | ${confidenceNames[item.confidence]||item.confidence} |`),``,
 `## 已确认问题与机会`,``,`| 分类 | 状态 | 严重度 | 置信度 | 发现 | 证据 | 修复建议 |`,`|---|---|---|---|---|---|---|`,...issues.map(item=>`| ${categoryNames[item.category]||item.category} | ${statusNames[item.status]||item.status} | ${md(item.severity)} | ${confidenceNames[item.confidence]||item.confidence} | ${md(item.title)} | ${md(item.evidence||"—")} | ${md(item.recommendation||item.description)} |`),``,
 `## 优先行动计划`,``,...issues.sort((a,b)=>({critical:0,high:1,medium:2,low:3,info:4}[a.severity]??5)-({critical:0,high:1,medium:2,low:3,info:4}[b.severity]??5)).slice(0,30).map((item,index)=>`${index+1}. **${item.title}** — ${item.recommendation||item.description}${item.url?`（${item.url}）`:""}`),``,
 `## 未知项与后续授权`,``,...(unknowns.length?unknowns.map(item=>`- **${item.title}**：${item.evidence||item.description}；下一步：${item.recommendation||"补充数据后复核"}`):["- 无"]),``,
 `## 页面抓取清单`,``,`| URL | HTTP | Title | H1 | 缺 Alt |`,`|---|---:|---|---:|---:|`,...data.pages.map(page=>`| ${md(page.url)} | ${page.statusCode} | ${md(page.title||"—")} | ${page.h1Count} | ${page.imagesWithoutAlt} |`),``,
 `> OneShowSEO 证据规则：无法取得的数据标记为 Unknown，不计为通过；扩展数据能力由平台统一管理。`];
 return lines.join("\n");
}

export function auditReportHtml(data:AuditReportData):string{
 const issues=data.checks.filter(item=>item.status==="fail"||item.status==="warning");
 const unknowns=data.checks.filter(item=>item.status==="unknown"||item.status==="skipped");
 const known=Math.max(0,data.run.checksTotal-data.run.checksUnknown-data.run.checksSkipped),coverage=data.run.checksTotal?Math.round(known/data.run.checksTotal*100):0;
 return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(data.project.name)}｜公开网站证据审计报告</title><style>
 :root{--ink:#14213d;--muted:#667085;--line:#e5e9f2;--blue:#5265f7;--green:#16a36a;--orange:#d97706;--red:#dc2626}*{box-sizing:border-box}body{margin:0;background:#f4f6fa;color:var(--ink);font:14px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC",sans-serif}.report{max-width:1180px;margin:30px auto;padding:0 20px}.hero{background:linear-gradient(135deg,#15254e,#5265f7);color:white;border-radius:18px;padding:34px;display:flex;justify-content:space-between;gap:30px}.hero h1{margin:5px 0 10px;font-size:28px}.hero p{margin:4px 0;opacity:.8}.score{min-width:130px;height:130px;border:10px solid rgba(255,255,255,.22);border-top-color:#62e6b4;border-radius:50%;display:grid;place-content:center;text-align:center}.score b{font-size:42px;line-height:1}.cards{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin:16px 0}.card,.section{background:white;border:1px solid var(--line);border-radius:12px}.card{padding:18px}.card b{font-size:24px;display:block}.card span{color:var(--muted)}.section{padding:22px;margin:16px 0}.section h2{margin:0 0 14px;font-size:18px}.scores{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.scores article{border:1px solid var(--line);border-radius:9px;padding:13px}.scores b{font-size:22px;float:right;color:var(--blue)}.scores small{display:block;color:var(--muted);margin-top:7px}.finding{border-top:1px solid var(--line);padding:15px 0}.finding:first-of-type{border-top:0}.finding header{display:flex;gap:8px;align-items:center}.pill{border-radius:99px;padding:3px 8px;font-size:11px}.fail{background:#fee2e2;color:var(--red)}.warning{background:#fff4d6;color:var(--orange)}.unknown{background:#eef0f4;color:#667085}.finding p{margin:7px 0;color:var(--muted)}.finding dl{display:grid;grid-template-columns:60px 1fr;margin:5px 0}.finding dt{font-weight:700}.finding dd{margin:0}.finding small{word-break:break-all;color:#8b95a7}table{width:100%;border-collapse:collapse;font-size:12px}th,td{text-align:left;padding:9px;border-top:1px solid var(--line);vertical-align:top}th{background:#f8f9fc}footer{color:var(--muted);text-align:center;padding:20px}@media print{body{background:white}.report{max-width:none;margin:0}.no-print{display:none}.section,.card{break-inside:avoid}}@media(max-width:800px){.cards,.scores{grid-template-columns:1fr 1fr}.hero{flex-direction:column}.score{min-width:100px;width:100px;height:100px}}
 </style></head><body><main class="report"><section class="hero"><div><small>ONSHOWSEO EVIDENCE AUDIT</small><h1>${esc(data.project.name)}</h1><p>${esc(data.project.siteUrl)} · ${esc(data.project.market)} / ${esc(data.project.language)}</p><p>${esc(date(data.run.completedAt))} · 发现 ${data.run.urlsDiscovered} 个 URL · 抓取 ${data.run.pagesScanned} 页 · 证据覆盖 ${coverage}%</p></div><div class="score"><b>${data.run.score}</b><span>/100 已验证</span></div></section>
 <div class="cards">${[["通过",data.run.checksPassed],["警告",data.run.checksWarning],["失败",data.run.checksFailed],["未知",data.run.checksUnknown],["跳过",data.run.checksSkipped]].map(([label,value])=>`<article class="card"><b>${value}</b><span>${label}</span></article>`).join("")}</div>
 <section class="section"><h2>分类得分与证据覆盖</h2><div class="scores">${data.scores.map(item=>`<article><b>${item.score??"—"}</b><strong>${esc(categoryNames[item.category]||item.category)}</strong><small>覆盖 ${item.checksKnown}/${item.checksTotal} · 置信度 ${esc(confidenceNames[item.confidence]||item.confidence)}</small></article>`).join("")}</div></section>
 <section class="section"><h2>已确认问题与机会（${issues.length}）</h2>${issues.map(item=>`<article class="finding"><header><span class="pill ${esc(item.status)}">${esc(statusNames[item.status]||item.status)}</span><strong>${esc(item.title)}</strong><small>${esc(confidenceNames[item.confidence]||item.confidence)}</small></header><p>${esc(item.description)}</p><dl><dt>证据</dt><dd>${esc(item.evidence||"—")}</dd><dt>影响</dt><dd>${esc(item.impact||"—")}</dd><dt>建议</dt><dd>${esc(item.recommendation||"—")}</dd></dl>${item.url?`<small>${esc(item.url)}</small>`:""}</article>`).join("")||"<p>未发现开放问题。</p>"}</section>
 <section class="section"><h2>未知项与后续授权（${unknowns.length}）</h2>${unknowns.map(item=>`<article class="finding"><header><span class="pill unknown">${esc(statusNames[item.status]||item.status)}</span><strong>${esc(item.title)}</strong></header><p>${esc(item.evidence||item.description)}</p><dl><dt>下一步</dt><dd>${esc(item.recommendation||"补充数据后复核")}</dd></dl></article>`).join("")||"<p>无未知项。</p>"}</section>
 <section class="section"><h2>页面抓取清单（${data.pages.length}）</h2><table><thead><tr><th>URL</th><th>HTTP</th><th>Title</th><th>H1</th><th>缺 Alt</th></tr></thead><tbody>${data.pages.map(page=>`<tr><td>${esc(page.url)}</td><td>${page.statusCode}</td><td>${esc(page.title||"—")}</td><td>${page.h1Count}</td><td>${page.imagesWithoutAlt}</td></tr>`).join("")}</tbody></table></section>
 <footer>OneShowSEO 证据优先报告 · 未取得的数据不会被计为通过</footer></main></body></html>`;
}
