import { getDatabase } from "./auth";
import { createHash } from "node:crypto";
import { ContentAgent, type ContentEvidence, type ContentQualityCheck } from "../platform/modules/agents/content-agent";
import { validateAgentExecutionEnvelope, type AgentExecutionEnvelope } from "../platform/modules/agents/contracts";
import { WorkerJobError } from "../platform/modules/execution/worker";

export type ContentExecutionInput={projectId:string;title:string;keyword:string;contentType:"blog_post"|"guide"|"landing_page"|"content_refresh";audience:string;intent:string;tone:string;goal:string;sourceRef:string;brief?:string};
export type ContentExecutionResult={runId:string;title:string;contentType:string;wordCount:number;qualityScore:number;checksPassed:number;checksTotal:number;evidenceCount:number;reviewRequired:true;report:Uint8Array;reportTitle:string;checks:ContentQualityCheck[]};

export async function executeContentAgent(input:ContentExecutionInput,context:{organizationId:string;taskId:string;jobId:string;attemptId:string;accountId:string;correlationId:string;locale:"zh-CN"|"en"},signal?:AbortSignal):Promise<ContentExecutionResult>{
  if(signal?.aborted)throw signal.reason;const db=getDatabase(),project=db.prepare("SELECT id,name,status FROM projects WHERE id=? AND organization_id=?").bind(input.projectId,context.organizationId).first<{id:string;name:string;status:string}>();
  if(!project||project.status!=="active")throw new WorkerJobError("CONTENT_PROJECT_NOT_ACTIVE","Content project is not active",false);
  const runId=context.taskId,started=Math.floor(Date.now()/1000);db.prepare(`INSERT INTO content_runs(id,project_id,execution_task_id,status,title,keyword,content_type,audience,intent,tone,goal,source_ref,brief,agent_version,started_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,'1.0.0',?) ON CONFLICT(id) DO UPDATE SET status='running',completed_at=NULL,error=NULL`).bind(runId,input.projectId,context.taskId,"running",input.title,input.keyword,input.contentType,input.audience,input.intent,input.tone,input.goal,input.sourceRef,input.brief||"",started).run();
  try{
    const evidenceRows=db.prepare(`SELECT id,source_ref AS sourceRef,summary,digest,captured_at AS capturedAt,confidence FROM research_evidence WHERE project_id=? AND (fresh_until>=? OR source_ref=?) ORDER BY CASE WHEN source_ref=? THEN 0 ELSE 1 END,confidence DESC,captured_at DESC LIMIT 12`).bind(input.projectId,started,input.sourceRef,input.sourceRef).all<ContentEvidence>().results;
    const evidence=evidenceRows.length?evidenceRows:[{id:`brief-source-${runId}`,sourceRef:input.sourceRef,summary:"由 Content Brief 明确指定的来源，等待编辑完成事实复核。",digest:createHash("sha256").update(`${input.sourceRef}:${input.title}`).digest("hex"),capturedAt:started,confidence:.65}];
    const envelope:AgentExecutionEnvelope=validateAgentExecutionEnvelope({schemaVersion:"1",kind:"execution",organizationId:context.organizationId,projectId:input.projectId,taskId:context.taskId,jobId:context.jobId,attemptId:context.attemptId,correlationId:context.correlationId,idempotencyKey:`content:${context.taskId}`,agent:{key:"content.agent",version:"1.0.0",capability:"content.generate"},actor:{type:"user",id:context.accountId},locale:context.locale,input,artifactRefs:[],integrationRefs:[],memoryRefs:[],deadlineAt:started+900,cancellation:{tokenRef:`cancel:${context.taskId}`,pollAfterSeconds:2},limits:{maxRuntimeSeconds:900,maxOutputBytes:2_000_000,maxArtifacts:1,maxUsageUnits:1}});
    const result=await new ContentAgent(evidence).runDetailed(envelope);if(signal?.aborted)throw signal.reason;const failure=result.events.find(event=>event.kind==="error");if(failure?.kind==="error")throw new WorkerJobError(failure.error.code,failure.error.messageKey,failure.error.retryable);
    const now=Math.floor(Date.now()/1000),passed=result.checks.filter(item=>item.status==="pass").length,statements=[db.prepare("DELETE FROM content_quality_checks WHERE run_id=?").bind(runId)];for(const check of result.checks)statements.push(db.prepare(`INSERT INTO content_quality_checks(id,run_id,project_id,check_key,label,status,detail,created_at) VALUES (?,?,?,?,?,?,?,?)`).bind(`${runId}:${check.key}`,runId,input.projectId,check.key,check.label,check.status,check.detail,now));statements.push(db.prepare(`UPDATE content_runs SET status='completed',word_count=?,quality_score=?,checks_passed=?,checks_total=?,evidence_count=?,review_status='pending',completed_at=?,error=NULL WHERE id=?`).bind(result.wordCount,result.qualityScore,passed,result.checks.length,result.evidence.length,now,runId));db.batch(statements);
    return{runId,title:input.title,contentType:input.contentType,wordCount:result.wordCount,qualityScore:result.qualityScore,checksPassed:passed,checksTotal:result.checks.length,evidenceCount:result.evidence.length,reviewRequired:true,report:new TextEncoder().encode(result.markdown),reportTitle:input.title,checks:result.checks};
  }catch(error){db.prepare("UPDATE content_runs SET status='failed',completed_at=?,error=? WHERE id=?").bind(Math.floor(Date.now()/1000),error instanceof Error?error.message.slice(0,500):"CONTENT_EXECUTION_FAILED",runId).run();throw error;}
}
