import{constants}from"node:fs";import{access}from"node:fs/promises";import pg from"pg";import{getDatabase}from"./auth";import{billingPaymentState}from"./billing";import{dependency,readiness,type DependencyHealth}from"../platform/modules/operations/health";
const now=()=>Math.floor(Date.now()/1000),elapsed=(start:number)=>Math.max(0,Date.now()-start),safe=async(name:DependencyHealth["name"],required:boolean,check:()=>Promise<Omit<DependencyHealth,"name"|"required"|"checkedAt">>):Promise<DependencyHealth>=>{try{return dependency({name,required,checkedAt:now(),...await check()});}catch{return dependency({name,required,checkedAt:now(),state:"unavailable",latencyMs:null,code:`${name.toUpperCase()}_UNAVAILABLE`});}};
async function sqlite(){return safe("sqlite",true,async()=>{const started=Date.now(),row=getDatabase().prepare("SELECT 1 ok").first<{ok:number}>();return{state:row?.ok===1?"ready"as const:"unavailable"as const,latencyMs:elapsed(started),code:row?.ok===1?"SQLITE_READY":"SQLITE_QUERY_FAILED"};});}
async function postgres(){const connectionString=process.env.DATABASE_URL;if(!connectionString)return dependency({name:"postgres",required:false,state:"not_configured",latencyMs:null,code:"POSTGRES_NOT_CONFIGURED",checkedAt:now()});return safe("postgres",true,async()=>{const started=Date.now(),client=new pg.Client({connectionString,connectionTimeoutMillis:1500,query_timeout:1500});try{await client.connect();await client.query("SELECT 1");return{state:"ready"as const,latencyMs:elapsed(started),code:"POSTGRES_READY"};}finally{await client.end().catch(()=>undefined);}});}
async function objectStorage(){const root=process.env.OBJECT_STORAGE_ROOT;if(!root)return dependency({name:"object_storage",required:false,state:"not_configured",latencyMs:null,code:"OBJECT_STORAGE_NOT_CONFIGURED",checkedAt:now()});return safe("object_storage",process.env.OBJECT_STORAGE_REQUIRED==="true",async()=>{const started=Date.now();await access(root,constants.R_OK|constants.W_OK);return{state:"ready"as const,latencyMs:elapsed(started),code:"OBJECT_STORAGE_READY"};});}
function workers(){const enabled=process.env.WORKER_RUNTIME_ENABLED==="true",required=process.env.WORKERS_REQUIRED==="true";if(!enabled)return dependency({name:"workers",required,state:"not_configured",latencyMs:null,code:"WORKERS_NOT_CONFIGURED",checkedAt:now()});try{const row=getDatabase().prepare("SELECT COUNT(*) queued,MIN(available_at) oldest FROM execution_jobs WHERE state IN('queued','retrying')").first<{queued:number;oldest:number|null}>(),stale=Boolean(row?.oldest&&row.oldest<now()-300);return dependency({name:"workers",required,state:stale?"degraded":"ready",latencyMs:null,code:stale?"WORKER_BACKLOG_STALE":"WORKERS_READY",checkedAt:now(),detail:{queued:Number(row?.queued??0),oldestAvailableAt:row?.oldest??null}});}catch{return dependency({name:"workers",required,state:"unavailable",latencyMs:null,code:"WORKER_STATE_UNAVAILABLE",checkedAt:now()});}}
function email(){const configured=Boolean(process.env.EMAIL_SMTP_HOST&&process.env.EMAIL_SMTP_USER&&process.env.EMAIL_SMTP_PASSWORD&&process.env.EMAIL_FROM);return dependency({name:"email",required:false,state:configured?"degraded":"not_configured",latencyMs:null,code:configured?"EMAIL_CONFIGURED_UNVERIFIED":"EMAIL_NOT_CONFIGURED",checkedAt:now()});}
function billing(){const state=billingPaymentState();return dependency({name:"billing",required:false,state:state.enabled?"ready":state.configured?"degraded":"not_configured",latencyMs:null,code:state.enabled?"BILLING_READY":state.configured?"BILLING_APPROVAL_PENDING":"BILLING_NOT_CONFIGURED",checkedAt:now()});}
function providers(){try{const rows=getDatabase().prepare("SELECT state,COUNT(*) count FROM integration_connections WHERE deleted_at IS NULL GROUP BY state").all<{state:string;count:number}>().results,total=rows.reduce((sum,row)=>sum+Number(row.count),0),unhealthy=rows.filter(row=>!["connected","syncing"].includes(row.state)).reduce((sum,row)=>sum+Number(row.count),0);return dependency({name:"providers",required:false,state:!total?"not_configured":unhealthy?"degraded":"ready",latencyMs:null,code:!total?"PROVIDERS_NOT_CONFIGURED":unhealthy?"PROVIDERS_DEGRADED":"PROVIDERS_READY",checkedAt:now(),detail:{connections:total,unhealthy}});}catch{return dependency({name:"providers",required:false,state:"not_configured",latencyMs:null,code:"PROVIDERS_SCHEMA_UNAVAILABLE",checkedAt:now()});}}
export function liveness(){return{state:"alive"as const,checkedAt:now(),version:process.env.APP_VERSION||"development",uptimeSeconds:Math.floor(process.uptime())};}
export async function platformReadiness(){const[sqliteHealth,postgresHealth,storageHealth]=await Promise.all([sqlite(),postgres(),objectStorage()]);return readiness([sqliteHealth,postgresHealth,workers(),storageHealth,email(),billing(),providers()]);}
