import { getDatabase } from "./auth";
import { ensureProductSchema } from "./product";
import { SqliteIntegrationConnectionRepository } from "../platform/adapters/sqlite/integration-connection-repository";
import { IntegrationConnectionService } from "../platform/modules/integrations/connections";
import { wordpressAdapter,type ProviderCredentialResolver,type ProviderHttpClient } from "../platform/modules/integrations/launch-adapters";
import { SafeProviderHttpClient,type SafeHttpRequest } from "../platform/modules/integrations/safe-http";
import { integrationSecretVault } from "../platform/modules/integrations/vault";

export async function integrationRepository(){await ensureProductSchema();const repository=new SqliteIntegrationConnectionRepository(getDatabase());repository.ensureSchema();return repository;}

async function runtimeDependencies(){const repository=await integrationRepository(),vault=integrationSecretVault();const credentials:ProviderCredentialResolver={async withAuthorization<T>(handle:string,operation:(authorization:string)=>Promise<T>){const record=repository.credentialContext(handle);if(!record)throw new Error("INTEGRATION_CREDENTIAL_UNAVAILABLE");return vault.withDecrypted(record.encryptedEnvelope,{organizationId:record.organizationId,projectId:record.projectId,connectionId:record.connectionId,recordId:record.id,recordVersion:record.recordVersion,purpose:"provider_credential"},secret=>operation(new TextDecoder().decode(secret)));}};const clients=new Map<string,SafeProviderHttpClient>();const http:ProviderHttpClient={async request(input:SafeHttpRequest){const url=new URL(input.url);let client=clients.get(url.hostname);if(!client){client=new SafeProviderHttpClient({allowedHosts:[url.hostname],credentialHosts:[url.hostname],timeoutMs:10_000,maxRedirects:2,maxRetries:2,maxResponseBytes:2_000_000,circuitFailureThreshold:3,circuitResetSeconds:60});clients.set(url.hostname,client);}return client.request(input);}};return{repository,vault,credentials,http};}

export async function integrationRuntime(){const{repository,vault,credentials,http}=await runtimeDependencies(),adapters=new Map([["wordpress",wordpressAdapter(http,credentials)]]);return{repository,service:new IntegrationConnectionService(repository,vault,adapters)};}

type WordpressPost=Record<string,unknown>&{id?:number;link?:string;status?:string;slug?:string;title?:{raw?:string;rendered?:string};content?:{raw?:string;rendered?:string}};
const json=(body:Uint8Array)=>JSON.parse(new TextDecoder().decode(body)) as unknown;
const post=(value:unknown):WordpressPost|null=>value&&typeof value==="object"&&!Array.isArray(value)?value as WordpressPost:null;

export async function publishWordpressPost(input:{organizationId:string;projectId:string;connectionId:string;title:string;slug:string;excerpt:string;html:string;contentHash:string;correlationId:string;signal?:AbortSignal}){
 const{repository,credentials,http}=await runtimeDependencies(),connection=repository.connection(input.organizationId,input.projectId,input.connectionId);if(!connection||connection.providerId!=="wordpress"||connection.state!=="connected")throw new Error("PUBLISH_CONNECTION_UNAVAILABLE");if(!connection.grantedScopes.includes("content.write"))throw new Error("PUBLISH_SCOPE_REQUIRED");const credential=repository.credential(connection.id);if(!credential||credential.revokedAt)throw new Error("PUBLISH_CREDENTIAL_UNAVAILABLE");if(input.signal?.aborted)throw input.signal.reason;
 const base=connection.metadata.baseUrl?.replace(/\/$/,"");if(!base)throw new Error("PUBLISH_BASE_URL_REQUIRED");const authorized=<T>(operation:(authorization:string)=>Promise<T>)=>credentials.withAuthorization(credential.id,operation),slug=input.slug.trim();let existing:WordpressPost|null=null;
 if(slug){const found=await authorized(authorization=>http.request({url:`${base}/wp-json/wp/v2/posts?context=edit&slug=${encodeURIComponent(slug)}&per_page=1`,method:"GET",credentialHeaders:{Authorization:authorization},correlationId:input.correlationId}));const values=json(found.body);existing=Array.isArray(values)?post(values[0]):null;}
 if(existing?.id){const sameTitle=String(existing.title?.raw||existing.title?.rendered||"").trim()===input.title.trim(),sameContent=String(existing.content?.raw||"").trim()===input.html.trim();if(!sameTitle||!sameContent)throw new Error("PUBLISH_TARGET_EXISTS");return{externalId:String(existing.id),url:String(existing.link||`${base}/?p=${existing.id}`),status:String(existing.status||"publish"),verified:true,attempts:1};}
 const payload={title:input.title,content:input.html,excerpt:input.excerpt,status:"publish",...(slug?{slug}:{})},created=await authorized(authorization=>http.request({url:`${base}/wp-json/wp/v2/posts`,method:"POST",headers:{"content-type":"application/json"},credentialHeaders:{Authorization:authorization},body:JSON.stringify(payload),idempotent:false,correlationId:input.correlationId})),createdPost=post(json(created.body));if(!createdPost?.id)throw new Error("PUBLISH_PROVIDER_RESPONSE_INVALID");if(input.signal?.aborted)throw input.signal.reason;
 const verifiedResponse=await authorized(authorization=>http.request({url:`${base}/wp-json/wp/v2/posts/${createdPost.id}?context=edit`,method:"GET",credentialHeaders:{Authorization:authorization},correlationId:input.correlationId})),verified=post(json(verifiedResponse.body)),verifiedOk=Boolean(verified?.id===createdPost.id&&String(verified.status)==="publish"&&String(verified.title?.raw||verified.title?.rendered||"").trim()===input.title.trim());if(!verifiedOk)throw new Error("PUBLISH_VERIFICATION_FAILED");return{externalId:String(createdPost.id),url:String(verified?.link||createdPost.link||`${base}/?p=${createdPost.id}`),status:String(verified?.status||createdPost.status||"publish"),verified:true,attempts:created.attempts+verifiedResponse.attempts};
}
