import { ensureAuthSchema, getDatabase } from "./auth";

export const modelProviderDefinitions = {
  openai: { name:"OpenAI", baseUrl:"https://api.openai.com/v1", model:"gpt-5-mini" },
  deepseek: { name:"DeepSeek", baseUrl:"https://api.deepseek.com", model:"deepseek-chat" },
  qwen: { name:"通义千问", baseUrl:"https://dashscope.aliyuncs.com/compatible-mode/v1", model:"qwen-plus" },
  zhipu: { name:"智谱 AI", baseUrl:"https://open.bigmodel.cn/api/paas/v4", model:"glm-4-flash" },
  moonshot: { name:"Moonshot", baseUrl:"https://api.moonshot.cn/v1", model:"moonshot-v1-8k" },
} as const;
export type ModelProvider=keyof typeof modelProviderDefinitions;
export type StoredModelProvider={provider:ModelProvider;name:string;enabled:boolean;isDefault:boolean;configured:boolean;baseUrl:string;model:string;temperature:number;maxOutputTokens:number;lastTestStatus:string|null;lastTestedAt:number|null;lastError:string|null;updatedAt:number|null};
export type RuntimeModelConfig={provider:ModelProvider;name:string;baseUrl:string;model:string;apiKey:string;temperature:number;maxOutputTokens:number};
const encoder=new TextEncoder(),decoder=new TextDecoder(),b64=(bytes:Uint8Array)=>Buffer.from(bytes).toString("base64url"),unb64=(value:string)=>new Uint8Array(Buffer.from(value,"base64url"));
export const modelEncryptionReady=()=>{const value=(process.env.MODEL_CONFIG_ENCRYPTION_KEY||process.env.DATA_SOURCE_ENCRYPTION_KEY)?.trim();return Boolean(value&&value.length>=24)};
async function key(){const secret=(process.env.MODEL_CONFIG_ENCRYPTION_KEY||process.env.DATA_SOURCE_ENCRYPTION_KEY)?.trim();if(!secret||secret.length<24)throw new Error("MODEL_CONFIG_ENCRYPTION_KEY_MISSING");const digest=await crypto.subtle.digest("SHA-256",encoder.encode(secret));return crypto.subtle.importKey("raw",digest,{name:"AES-GCM"},false,["encrypt","decrypt"]);}
async function encrypt(value:string){const iv=crypto.getRandomValues(new Uint8Array(12)),payload=await crypto.subtle.encrypt({name:"AES-GCM",iv},await key(),encoder.encode(value));return `v1.${b64(iv)}.${b64(new Uint8Array(payload))}`;}
async function decrypt(value:string){const [version,iv,payload]=value.split(".");if(version!=="v1"||!iv||!payload)throw new Error("MODEL_CONFIG_INVALID");return decoder.decode(await crypto.subtle.decrypt({name:"AES-GCM",iv:unb64(iv)},await key(),unb64(payload)));}
export async function ensureModelProviderSchema(){const db=getDatabase();await ensureAuthSchema(db);db.exec(`CREATE TABLE IF NOT EXISTS platform_model_providers(provider TEXT PRIMARY KEY,enabled INTEGER NOT NULL DEFAULT 0,is_default INTEGER NOT NULL DEFAULT 0,base_url TEXT NOT NULL,model_name TEXT NOT NULL,encrypted_api_key TEXT,temperature REAL NOT NULL DEFAULT 0.4,max_output_tokens INTEGER NOT NULL DEFAULT 4000,last_test_status TEXT,last_tested_at INTEGER,last_error TEXT,updated_by TEXT REFERENCES users(id) ON DELETE SET NULL,updated_at INTEGER NOT NULL);`);const now=Math.floor(Date.now()/1000);for(const [provider,definition] of Object.entries(modelProviderDefinitions))db.prepare("INSERT OR IGNORE INTO platform_model_providers(provider,base_url,model_name,updated_at) VALUES (?,?,?,?)").bind(provider,definition.baseUrl,definition.model,now).run();}
function validEndpoint(provider:ModelProvider,value:string){const expected=new URL(modelProviderDefinitions[provider].baseUrl),candidate=new URL(value);if(candidate.protocol!=="https:"||candidate.username||candidate.password||candidate.origin!==expected.origin)throw new Error("MODEL_ENDPOINT_INVALID");return candidate.href.replace(/\/$/,"");}
export async function listModelProviders():Promise<StoredModelProvider[]>{await ensureModelProviderSchema();const rows=getDatabase().prepare("SELECT provider,enabled,is_default AS isDefault,base_url AS baseUrl,model_name AS model,encrypted_api_key AS encryptedApiKey,temperature,max_output_tokens AS maxOutputTokens,last_test_status AS lastTestStatus,last_tested_at AS lastTestedAt,last_error AS lastError,updated_at AS updatedAt FROM platform_model_providers ORDER BY provider").all<Record<string,unknown>>().results;return rows.filter(row=>String(row.provider) in modelProviderDefinitions).map(row=>{const provider=String(row.provider) as ModelProvider;return{provider,name:modelProviderDefinitions[provider].name,enabled:Boolean(row.enabled),isDefault:Boolean(row.isDefault),configured:Boolean(row.encryptedApiKey),baseUrl:String(row.baseUrl),model:String(row.model),temperature:Number(row.temperature),maxOutputTokens:Number(row.maxOutputTokens),lastTestStatus:row.lastTestStatus?String(row.lastTestStatus):null,lastTestedAt:row.lastTestedAt?Number(row.lastTestedAt):null,lastError:row.lastError?String(row.lastError):null,updatedAt:row.updatedAt?Number(row.updatedAt):null}});}
export async function saveModelProvider(input:{provider:ModelProvider;enabled:boolean;isDefault:boolean;baseUrl:string;model:string;apiKey?:string;temperature:number;maxOutputTokens:number},adminId:string){await ensureModelProviderSchema();const db=getDatabase(),row=db.prepare("SELECT encrypted_api_key AS encryptedApiKey FROM platform_model_providers WHERE provider=?").bind(input.provider).first<{encryptedApiKey:string|null}>(),cipher=input.apiKey?.trim()?await encrypt(input.apiKey.trim()):row?.encryptedApiKey||null,baseUrl=validEndpoint(input.provider,input.baseUrl),model=input.model.trim().slice(0,120);if(!model)throw new Error("MODEL_NAME_REQUIRED");if(input.enabled&&!cipher)throw new Error("MODEL_API_KEY_REQUIRED");const temperature=Math.max(0,Math.min(2,Number(input.temperature)||0)),maxOutputTokens=Math.max(256,Math.min(32000,Math.round(Number(input.maxOutputTokens)||4000))),now=Math.floor(Date.now()/1000);if(input.isDefault)db.prepare("UPDATE platform_model_providers SET is_default=0").run();db.prepare("UPDATE platform_model_providers SET enabled=?,is_default=?,base_url=?,model_name=?,encrypted_api_key=?,temperature=?,max_output_tokens=?,last_test_status=?,last_error=NULL,updated_by=?,updated_at=? WHERE provider=?").bind(input.enabled?1:0,input.isDefault?1:0,baseUrl,model,cipher,temperature,maxOutputTokens,cipher?"configured":null,adminId,now,input.provider).run();}
export async function clearModelProvider(provider:ModelProvider,adminId:string){await ensureModelProviderSchema();const definition=modelProviderDefinitions[provider];getDatabase().prepare("UPDATE platform_model_providers SET enabled=0,is_default=0,base_url=?,model_name=?,encrypted_api_key=NULL,last_test_status=NULL,last_tested_at=NULL,last_error=NULL,updated_by=?,updated_at=? WHERE provider=?").bind(definition.baseUrl,definition.model,adminId,Math.floor(Date.now()/1000),provider).run();}
export async function getDefaultModelConfig():Promise<RuntimeModelConfig|null>{await ensureModelProviderSchema();const row=getDatabase().prepare("SELECT provider,base_url AS baseUrl,model_name AS model,encrypted_api_key AS encryptedApiKey,temperature,max_output_tokens AS maxOutputTokens FROM platform_model_providers WHERE enabled=1 AND encrypted_api_key IS NOT NULL ORDER BY is_default DESC,updated_at DESC LIMIT 1").first<{provider:string;baseUrl:string;model:string;encryptedApiKey:string;temperature:number;maxOutputTokens:number}>();if(!row||!(row.provider in modelProviderDefinitions))return null;const provider=row.provider as ModelProvider;return{provider,name:modelProviderDefinitions[provider].name,baseUrl:validEndpoint(provider,row.baseUrl),model:row.model,apiKey:await decrypt(row.encryptedApiKey),temperature:row.temperature,maxOutputTokens:row.maxOutputTokens};}
export async function modelRuntimeStatus(){const providers=await listModelProviders(),active=providers.find(item=>item.enabled&&item.configured&&item.isDefault)||providers.find(item=>item.enabled&&item.configured);return active?{ready:true,provider:active.name,model:active.model}:{ready:false,provider:null,model:null};}
export async function testModelProvider(provider:ModelProvider){const providers=await listModelProviders(),stored=providers.find(item=>item.provider===provider),db=getDatabase(),now=Math.floor(Date.now()/1000);try{if(!stored?.configured)throw new Error("MODEL_API_KEY_REQUIRED");const row=db.prepare("SELECT encrypted_api_key AS value FROM platform_model_providers WHERE provider=?").bind(provider).first<{value:string}>(),apiKey=await decrypt(row!.value),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);let response:Response;try{response=await fetch(`${validEndpoint(provider,stored.baseUrl)}/models`,{headers:{authorization:`Bearer ${apiKey}`},signal:controller.signal,redirect:"error"});}finally{clearTimeout(timer);}if(!response.ok)throw new Error(`HTTP_${response.status}`);db.prepare("UPDATE platform_model_providers SET last_test_status='passed',last_tested_at=?,last_error=NULL WHERE provider=?").bind(now,provider).run();return{ok:true};}catch(error){const message=error instanceof Error?error.message:"MODEL_TEST_FAILED";db.prepare("UPDATE platform_model_providers SET last_test_status='failed',last_tested_at=?,last_error=? WHERE provider=?").bind(now,message.slice(0,160),provider).run();return{ok:false,error:message};}}
export async function generateWithDefaultModel(input:{title:string;keyword:string;contentType:string;audience:string;intent:string;tone:string;goal:string;brief?:string;evidence:Array<{sourceRef:string;summary:string}>},signal?:AbortSignal):Promise<{markdown:string;provider:string;model:string}|null>{const config=await getDefaultModelConfig();if(!config)return null;const evidence=input.evidence.map((item,index)=>`${index+1}. ${item.summary}\n来源：${item.sourceRef}`).join("\n\n"),prompt=`请为 OneShowSEO 生成一份可供人工审核的中文内容草稿。严格使用 Markdown，只有一个 H1，包含摘要、清晰的 H2/H3、执行步骤、常见问题和行动建议。不得虚构数据、排名、客户案例或来源；证据不足时明确标记“待核验”。\n\n标题：${input.title}\n目标关键词：${input.keyword}\n内容类型：${input.contentType}\n目标受众：${input.audience}\n搜索意图：${input.intent}\n品牌语气：${input.tone}\n内容目标：${input.goal}\n补充要求：${input.brief||"无"}\n\n可用证据：\n${evidence}`,controller=new AbortController(),timer=setTimeout(()=>controller.abort(),90000),abort=()=>controller.abort(signal?.reason);signal?.addEventListener("abort",abort,{once:true});try{const response=await fetch(`${config.baseUrl}/chat/completions`,{method:"POST",headers:{authorization:`Bearer ${config.apiKey}`,"content-type":"application/json"},body:JSON.stringify({model:config.model,messages:[{role:"system",content:"你是专业的 SEO/GEO 内容编辑，所有结论必须可审核、可追溯。"},{role:"user",content:prompt}],temperature:config.temperature,max_tokens:config.maxOutputTokens}),signal:controller.signal,redirect:"error"});if(!response.ok)throw new Error(`MODEL_HTTP_${response.status}`);const data=await response.json() as {choices?:Array<{message?:{content?:unknown}}>};const markdown=typeof data.choices?.[0]?.message?.content==="string"?data.choices[0].message.content.trim():"";if(!markdown)throw new Error("MODEL_EMPTY_RESPONSE");return{markdown:markdown.slice(0,200000),provider:config.name,model:config.model};}finally{clearTimeout(timer);signal?.removeEventListener("abort",abort);}}
