import{redirect}from"next/navigation";import{getCurrentUser,getDatabase,type AppUser}from"./auth";import{ensureExecutionSchema}from"./execution";import{ensureBillingSchema}from"./billing";import{integrationRepository}from"./integrations";import{SqliteFeatureFlagRepository}from"../platform/adapters/sqlite/feature-flag-repository";import{SqliteOperatorAdministrationRepository}from"../platform/adapters/sqlite/operator-administration-repository";import{OperatorAdministrationService,type OperatorPermission}from"../platform/modules/operations/administration";
import{observabilityService}from"./observability";
let repository:SqliteOperatorAdministrationRepository|undefined,service:OperatorAdministrationService|undefined;
export async function operatorAdministration(){await ensureExecutionSchema();const db=getDatabase();repository??=new SqliteOperatorAdministrationRepository(db);repository.ensureSchema();db.exec("CREATE TABLE IF NOT EXISTS operations_incidents(id TEXT PRIMARY KEY,severity TEXT NOT NULL CHECK(severity IN('low','medium','high','critical')),state TEXT NOT NULL CHECK(state IN('open','investigating','monitoring','resolved')),title TEXT NOT NULL,organization_id TEXT,correlation_id TEXT NOT NULL,owner_account_id TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,resolved_at INTEGER);CREATE INDEX IF NOT EXISTS operations_incident_state_idx ON operations_incidents(state,severity,updated_at DESC);");return service??=new OperatorAdministrationService(repository);}
export async function authorizeOperator(user:AppUser,permission:OperatorPermission,input:Partial<{organizationId:string;projectId:string;reason:string;targetType:string;targetId:string;correlationId:string}>={}){return(await operatorAdministration()).authorize({actorAccountId:user.id,accountRole:user.role,permission,organizationId:input.organizationId,projectId:input.projectId,reason:input.reason,targetType:input.targetType??"admin_console",targetId:input.targetId,correlationId:input.correlationId??`operator:${crypto.randomUUID()}`});}
export async function requireOperatorConsole(){const user=await getCurrentUser();if(!user)redirect("/login?returnTo=%2Fadmin");try{const authorization=await authorizeOperator(user,"tenants.read");return{user,role:authorization.role};}catch{redirect("/workspace");}}
type Count={key:string;count:number};
const counts=(sql:string)=>getDatabase().prepare(sql).all<Count>().results;
export async function operatorDashboardSnapshot(query="",visible:ReadonlySet<string>=new Set(["*"])){
 await ensureBillingSchema();await ensureExecutionSchema();await integrationRepository();await operatorAdministration();new SqliteFeatureFlagRepository(getDatabase());const db=getDatabase(),term=`%${query.trim().slice(0,120)}%`,allowed=(permission:OperatorPermission)=>visible.has("*")||visible.has(permission),access={users:allowed("users.read"),ledger:allowed("ledger.read"),providers:allowed("providers.read"),jobs:allowed("jobs.read"),flags:allowed("flags.read"),incidents:allowed("incidents.read"),notifications:allowed("notifications.read"),audit:allowed("audit.read")};
 const tenants=db.prepare("SELECT o.id,o.name,o.slug,o.status,u.plan,u.status accountStatus FROM identity_organizations o JOIN users u ON u.id=o.owner_user_id ORDER BY o.created_at DESC LIMIT 100").all().results;
 const denied=[{key:"permission_required",count:0}],users=access.users?counts("SELECT status key,COUNT(*) count FROM users GROUP BY status ORDER BY status"):denied,providers=access.providers?counts("SELECT provider_id||':'||state key,COUNT(*) count FROM integration_connections WHERE deleted_at IS NULL GROUP BY provider_id,state ORDER BY key"):denied,jobs=access.jobs?counts("SELECT state key,COUNT(*) count FROM execution_jobs GROUP BY state ORDER BY state"):denied,notifications=access.notifications?counts("SELECT state key,COUNT(*) count FROM operations_notifications GROUP BY state ORDER BY state"):denied;
 const reconciliations=access.ledger?db.prepare("SELECT id,organization_id organizationId,status,stale_pending_count stalePendingCount,inconsistent_state_count inconsistentStateCount,over_limit_metric_count overLimitMetricCount,credit_imbalance creditImbalance,correlation_id correlationId,created_at createdAt FROM commerce_usage_reconciliations ORDER BY created_at DESC LIMIT 50").all().results:[];
 const featureFlags=access.flags?db.prepare("SELECT flag_key flagKey,enabled,scope,scope_value scopeValue,version,updated_at updatedAt FROM platform_feature_flags WHERE active=1 ORDER BY flag_key,scope LIMIT 100").all().results:[];
 const incidents=access.incidents?db.prepare("SELECT id,severity,state,title,organization_id organizationId,correlation_id correlationId,owner_account_id ownerAccountId,updated_at updatedAt FROM operations_incidents ORDER BY updated_at DESC LIMIT 100").all().results:[];
 const audit=access.audit?db.prepare("SELECT id,actor_role actorRole,permission,organization_id organizationId,target_type targetType,target_id targetId,reason,outcome,correlation_id correlationId,occurred_at occurredAt FROM operations_elevated_actions WHERE permission LIKE ? OR correlation_id LIKE ? OR COALESCE(target_id,'') LIKE ? ORDER BY occurred_at DESC LIMIT 100").bind(term,term,term).all().results:[];
 const observability=access.incidents?observabilityService().dashboard():null;
 return{capturedAt:Math.floor(Date.now()/1000),access,tenants,users,providers,jobs,quarantined:Number(jobs.find(item=>item.key==="quarantined")?.count??0),notifications,reconciliations,featureFlags,incidents,audit,observability,secretAccess:false};
}
