import os from "node:os";
import { getDatabase } from "./auth";
import { artifactObjectService, atomicTaskSettlementService, executionRepository, executionWorkerSupervisor } from "./execution";
import { commerceService, ensureBillingSchema } from "./billing";
import { executeSiteAudit, type AuditExecutionInput, type AuditExecutionResult } from "./audit-execution";
import { executeResearchAgent, type ResearchExecutionInput, type ResearchExecutionResult } from "./research-execution";
import { executeContentAgent, type ContentExecutionInput, type ContentExecutionResult } from "./content-execution";
import { executePublishAgent,markPublishFailed,type PublishExecutionInput,type PublishExecutionResult } from "./publish-execution";
import { executeGeoAgent,type GeoExecutionInput,type GeoExecutionResult } from "./geo-execution";
import { executeAnalyticsAgent,type AnalyticsExecutionInput,type AnalyticsExecutionResult } from "./analytics-execution";
import { can, permissions } from "../platform/modules/identity/authorization";
import { WorkerJobError, type WorkerHandler, type WorkerHandlers, type WorkerTerminalState } from "../platform/modules/execution/worker";
import type { ArtifactRecord, ExecutionTask, NotificationRecord } from "../platform/modules/execution";
import type { CommercialSubject } from "../platform/modules/commerce";

type WorkerAccount={accountId:string;organizationId:string;organizationStatus:CommercialSubject["organizationStatus"];planKey:CommercialSubject["planKey"];trialEndsAt:number|null;accountCreatedAt:number;accountStatus:string;membershipStatus:string;roleKey:string;projectStatus:string};
type AuditWorkerResult=AuditExecutionResult&{artifact:ArtifactRecord;subject:CommercialSubject};
type ResearchWorkerResult=ResearchExecutionResult&{artifact:ArtifactRecord;subject:CommercialSubject};
type ContentWorkerResult=ContentExecutionResult&{artifact:ArtifactRecord;subject:CommercialSubject};
type PublishWorkerResult=PublishExecutionResult&{artifact:ArtifactRecord;subject:CommercialSubject};
type GeoWorkerResult=GeoExecutionResult&{artifact:ArtifactRecord;subject:CommercialSubject};
type AnalyticsWorkerResult=AnalyticsExecutionResult&{artifact:ArtifactRecord;subject:CommercialSubject};

function account(task:ExecutionTask):WorkerAccount{
  const row=getDatabase().prepare(`SELECT u.id AS accountId,u.plan AS planKey,u.trial_ends_at AS trialEndsAt,u.created_at AS accountCreatedAt,u.status AS accountStatus,
    o.id AS organizationId,o.status AS organizationStatus,m.status AS membershipStatus,r.role_key AS roleKey,p.status AS projectStatus
    FROM users u JOIN identity_memberships m ON m.user_id=u.id AND m.organization_id=? JOIN identity_roles r ON r.id=m.role_id
    JOIN identity_organizations o ON o.id=m.organization_id JOIN projects p ON p.id=? AND p.organization_id=o.id WHERE u.id=? LIMIT 1`)
    .bind(task.organizationId,task.projectId,task.requestedByAccountId).first<WorkerAccount>();
  if(!row)throw new WorkerJobError("EXECUTION_SUBJECT_NOT_FOUND","Task owner is no longer available",false);return row;
}
function subject(row:WorkerAccount):CommercialSubject{return{accountId:row.accountId,organizationId:row.organizationId,organizationStatus:row.organizationStatus,planKey:row.planKey,trialEndsAt:row.trialEndsAt,accountCreatedAt:row.accountCreatedAt};}
function authorizeAudit(task:ExecutionTask){const row=account(task);if(row.accountStatus!=="active"||row.membershipStatus!=="active"||row.projectStatus!=="active"||!can(row.roleKey as Parameters<typeof can>[0],permissions.auditsRun))throw new WorkerJobError("EXECUTION_NOT_AUTHORIZED","Audit authorization is no longer valid",false);commerceService().authorizeAccess(subject(row));return row;}
function authorizeResearch(task:ExecutionTask){const row=account(task);if(row.accountStatus!=="active"||row.membershipStatus!=="active"||row.projectStatus!=="active"||!can(row.roleKey as Parameters<typeof can>[0],permissions.researchRun))throw new WorkerJobError("EXECUTION_NOT_AUTHORIZED","Research authorization is no longer valid",false);commerceService().authorizeAccess(subject(row));return row;}
function authorizeContent(task:ExecutionTask){const row=account(task);if(row.accountStatus!=="active"||row.membershipStatus!=="active"||row.projectStatus!=="active"||!can(row.roleKey as Parameters<typeof can>[0],permissions.contentCreate))throw new WorkerJobError("EXECUTION_NOT_AUTHORIZED","Content authorization is no longer valid",false);commerceService().authorizeAccess(subject(row));return row;}
function authorizePublish(task:ExecutionTask){const row=account(task);if(row.accountStatus!=="active"||row.membershipStatus!=="active"||row.projectStatus!=="active"||!can(row.roleKey as Parameters<typeof can>[0],permissions.contentPublish))throw new WorkerJobError("EXECUTION_NOT_AUTHORIZED","Publish authorization is no longer valid",false);commerceService().authorizeAccess(subject(row));return row;}
function authorizeGeo(task:ExecutionTask){const row=account(task);if(row.accountStatus!=="active"||row.membershipStatus!=="active"||row.projectStatus!=="active"||!can(row.roleKey as Parameters<typeof can>[0],permissions.auditsRun))throw new WorkerJobError("EXECUTION_NOT_AUTHORIZED","GEO authorization is no longer valid",false);commerceService().authorizeAccess(subject(row));return row;}
function authorizeAnalytics(task:ExecutionTask){const row=account(task);if(row.accountStatus!=="active"||row.membershipStatus!=="active"||row.projectStatus!=="active"||!can(row.roleKey as Parameters<typeof can>[0],permissions.auditsRun))throw new WorkerJobError("EXECUTION_NOT_AUTHORIZED","Analytics authorization is no longer valid",false);commerceService().authorizeAccess(subject(row));return row;}
function reservationId(task:ExecutionTask){return getDatabase().prepare("SELECT id FROM commerce_credit_ledger WHERE organization_id=? AND task_id=? AND entry_type='reservation' ORDER BY created_at LIMIT 1").bind(task.organizationId,task.id).first<{id:string}>()?.id??null;}
function notification(task:ExecutionTask,state:WorkerTerminalState,now:number):NotificationRecord[]{if(!task.requestedByAccountId)return[];return[{id:crypto.randomUUID(),organizationId:task.organizationId,accountId:task.requestedByAccountId,projectId:task.projectId,taskId:task.id,channel:"in_app",notificationType:"execution_terminal",locale:task.locale,titleKey:state==="completed"?"notification.audit.completed":"notification.audit.failed",bodyKey:state==="completed"?"notification.audit.report_ready":"notification.audit.not_completed",arguments:{taskId:task.id,state},state:"pending",idempotencyKey:`audit-terminal:${task.id}:${state}`,availableAt:now,sentAt:null,readAt:null,lastError:null,createdAt:now,updatedAt:now}];}
function researchNotification(task:ExecutionTask,state:WorkerTerminalState,now:number):NotificationRecord[]{if(!task.requestedByAccountId)return[];return[{id:crypto.randomUUID(),organizationId:task.organizationId,accountId:task.requestedByAccountId,projectId:task.projectId,taskId:task.id,channel:"in_app",notificationType:"execution_terminal",locale:task.locale,titleKey:state==="completed"?"notification.research.completed":"notification.research.failed",bodyKey:state==="completed"?"notification.research.report_ready":"notification.research.not_completed",arguments:{taskId:task.id,state},state:"pending",idempotencyKey:`research-terminal:${task.id}:${state}`,availableAt:now,sentAt:null,readAt:null,lastError:null,createdAt:now,updatedAt:now}];}
function researchProgress(task:ExecutionTask,attemptId:string,progress:number,stage:string,messageKey:string){const repository=executionRepository(),sequence=(repository.progress(task.organizationId,task.id,500)[0]?.sequence??0)+1;repository.appendProgress({id:crypto.randomUUID(),organizationId:task.organizationId,projectId:task.projectId,taskId:task.id,attemptId,sequence,progress,stage,messageKey,metadata:{agent:"research.agent",version:"1.0.0"},correlationId:task.correlationId,createdAt:Math.floor(Date.now()/1000)});}
function auditProgress(task:ExecutionTask,attemptId:string,progress:number,stage:string,messageKey:string){const repository=executionRepository(),sequence=(repository.progress(task.organizationId,task.id,500)[0]?.sequence??0)+1;repository.appendProgress({id:crypto.randomUUID(),organizationId:task.organizationId,projectId:task.projectId,taskId:task.id,attemptId,sequence,progress,stage,messageKey,metadata:{agent:"seo.audit",version:"1.0.0"},correlationId:task.correlationId,createdAt:Math.floor(Date.now()/1000)});}
function contentProgress(task:ExecutionTask,attemptId:string,progress:number,stage:string,messageKey:string){const repository=executionRepository(),sequence=(repository.progress(task.organizationId,task.id,500)[0]?.sequence??0)+1;repository.appendProgress({id:crypto.randomUUID(),organizationId:task.organizationId,projectId:task.projectId,taskId:task.id,attemptId,sequence,progress,stage,messageKey,metadata:{agent:"content.agent",version:"1.0.0"},correlationId:task.correlationId,createdAt:Math.floor(Date.now()/1000)});}
function contentNotification(task:ExecutionTask,state:WorkerTerminalState,now:number):NotificationRecord[]{if(!task.requestedByAccountId)return[];return[{id:crypto.randomUUID(),organizationId:task.organizationId,accountId:task.requestedByAccountId,projectId:task.projectId,taskId:task.id,channel:"in_app",notificationType:"execution_terminal",locale:task.locale,titleKey:state==="completed"?"notification.content.completed":"notification.content.failed",bodyKey:state==="completed"?"notification.content.draft_ready":"notification.content.not_completed",arguments:{taskId:task.id,state},state:"pending",idempotencyKey:`content-terminal:${task.id}:${state}`,availableAt:now,sentAt:null,readAt:null,lastError:null,createdAt:now,updatedAt:now}];}
function publishNotification(task:ExecutionTask,state:WorkerTerminalState,now:number):NotificationRecord[]{if(!task.requestedByAccountId)return[];return[{id:crypto.randomUUID(),organizationId:task.organizationId,accountId:task.requestedByAccountId,projectId:task.projectId,taskId:task.id,channel:"in_app",notificationType:"execution_terminal",locale:task.locale,titleKey:state==="completed"?"notification.publish.completed":"notification.publish.failed",bodyKey:state==="completed"?"notification.publish.verified":"notification.publish.not_completed",arguments:{taskId:task.id,state},state:"pending",idempotencyKey:`publish-terminal:${task.id}:${state}`,availableAt:now,sentAt:null,readAt:null,lastError:null,createdAt:now,updatedAt:now}];}
function geoNotification(task:ExecutionTask,state:WorkerTerminalState,now:number):NotificationRecord[]{if(!task.requestedByAccountId)return[];return[{id:crypto.randomUUID(),organizationId:task.organizationId,accountId:task.requestedByAccountId,projectId:task.projectId,taskId:task.id,channel:"in_app",notificationType:"execution_terminal",locale:task.locale,titleKey:state==="completed"?"notification.geo.completed":"notification.geo.failed",bodyKey:state==="completed"?"notification.geo.report_ready":"notification.geo.not_completed",arguments:{taskId:task.id,state},state:"pending",idempotencyKey:`geo-terminal:${task.id}:${state}`,availableAt:now,sentAt:null,readAt:null,lastError:null,createdAt:now,updatedAt:now}];}
function analyticsNotification(task:ExecutionTask,state:WorkerTerminalState,now:number):NotificationRecord[]{if(!task.requestedByAccountId)return[];return[{id:crypto.randomUUID(),organizationId:task.organizationId,accountId:task.requestedByAccountId,projectId:task.projectId,taskId:task.id,channel:"in_app",notificationType:"execution_terminal",locale:task.locale,titleKey:state==="completed"?"notification.analytics.completed":"notification.analytics.failed",bodyKey:state==="completed"?"notification.analytics.report_ready":"notification.analytics.not_completed",arguments:{taskId:task.id,state},state:"pending",idempotencyKey:`analytics-terminal:${task.id}:${state}`,availableAt:now,sentAt:null,readAt:null,lastError:null,createdAt:now,updatedAt:now}];}

export function auditWorkerHandler(dependencies:{executeAudit?:typeof executeSiteAudit}={}):WorkerHandler{const executeAudit=dependencies.executeAudit??executeSiteAudit;return{
  authorize:async({task})=>{await ensureBillingSchema();authorizeAudit(task);},
  execute:async(input,context)=>{
    const row=authorizeAudit(context.task),commercial=commerceService(),effective=commercial.resolve(subject(row)),auditInput=input as unknown as AuditExecutionInput;
    if(auditInput.projectId!==context.task.projectId||typeof auditInput.siteUrl!=="string"||!Number.isInteger(auditInput.pageLimit))throw new WorkerJobError("AUDIT_INPUT_INVALID","Audit task input is invalid",false);
    if(!context.task.requestedByAccountId)throw new WorkerJobError("AUDIT_ACCOUNT_REQUIRED","Audit task owner is required",false);auditProgress(context.task,context.attemptId,5,"crawl_policy","audit.crawl_policy.started");const result=await executeAudit(auditInput,{organizationId:context.task.organizationId,taskId:context.task.id,jobId:context.job.id,attemptId:context.attemptId,accountId:context.task.requestedByAccountId,correlationId:context.task.correlationId,locale:context.task.locale},context.signal),usageKey=`audit:${context.task.id}:pages_crawled`;auditProgress(context.task,context.attemptId,85,"report_generation","audit.report_generation.started");
    commercial.ingestUsage(subject(row),{metric:"pages_crawled",quantity:result.pagesScanned,state:"pending",idempotencyKey:usageKey,projectId:context.task.projectId,taskId:context.task.id});commercial.finalizeUsage(subject(row),usageKey);
    const artifact=await (await artifactObjectService()).store({organizationId:context.task.organizationId,projectId:context.task.projectId,taskId:context.task.id,attemptId:context.attemptId,artifactId:`audit-report-${context.task.id}`,kind:"seo_audit_report",filename:`audit-report-${context.task.id}.md`,mimeType:"text/markdown",body:result.report,provenance:{title:result.reportTitle,runId:result.runId,agent:"seo.audit",agentVersion:"1.0.0",score:result.score,pagesScanned:result.pagesScanned,evidenceCount:result.evidenceCount,coverage:result.partial?"partial":"complete",partialReasons:result.partialReasons,degradedSources:result.degradedSources,worker:"production"},idempotencyKey:`audit-report-${context.task.id}`,correlationId:`audit-${context.task.id}`,storageLimitBytes:effective.limits.storageBytes,retentionDays:effective.limits.retentionDays});
    return{...result,artifact,subject:subject(row)} satisfies AuditWorkerResult;
  },
  settle:async({state,result},context)=>{const now=Math.floor(Date.now()/1000),completed=result as AuditWorkerResult|null,row=completed?.subject??subject(account(context.task));await (await atomicTaskSettlementService()).settle({organizationId:context.task.organizationId,projectId:context.task.projectId,taskId:context.task.id,jobId:context.job.id,attemptId:context.attemptId,state,subject:row,reservationId:reservationId(context.task),artifacts:state==="completed"&&completed?[completed.artifact]:[],notifications:notification(context.task,state,now),externalEffects:[],idempotencyKey:`worker-settle:${context.task.id}`,correlationId:context.task.correlationId});}
};}

export function researchWorkerHandler(dependencies:{executeResearch?:typeof executeResearchAgent}={}):WorkerHandler{const executeResearch=dependencies.executeResearch??executeResearchAgent;return{
  authorize:async({task})=>{await ensureBillingSchema();authorizeResearch(task);},
  execute:async(input,context)=>{
    const row=authorizeResearch(context.task),commercial=commerceService(),effective=commercial.resolve(subject(row)),researchInput=input as unknown as ResearchExecutionInput;
    if(researchInput.projectId!==context.task.projectId||typeof researchInput.siteUrl!=="string"||!Number.isInteger(researchInput.maximumPages))throw new WorkerJobError("RESEARCH_INPUT_INVALID","Research task input is invalid",false);
    if(!context.task.requestedByAccountId)throw new WorkerJobError("RESEARCH_ACCOUNT_REQUIRED","Research task owner is required",false);researchProgress(context.task,context.attemptId,5,"source_acquisition","research.source_acquisition.started");const result=await executeResearch(researchInput,{organizationId:context.task.organizationId,taskId:context.task.id,jobId:context.job.id,attemptId:context.attemptId,accountId:context.task.requestedByAccountId,correlationId:context.task.correlationId,locale:context.task.locale},context.signal),usageKey=`research:${context.task.id}:sources`;researchProgress(context.task,context.attemptId,85,"report_generation","research.report_generation.started");
    commercial.ingestUsage(subject(row),{metric:"research_sources",quantity:result.evidenceCount,state:"pending",idempotencyKey:usageKey,projectId:context.task.projectId,taskId:context.task.id});commercial.finalizeUsage(subject(row),usageKey);
    const artifact=await (await artifactObjectService()).store({organizationId:context.task.organizationId,projectId:context.task.projectId,taskId:context.task.id,attemptId:context.attemptId,artifactId:`research-report-${context.task.id}`,kind:"research_report",filename:`research-report-${context.task.id}.md`,mimeType:"text/markdown",body:result.report,provenance:{title:result.reportTitle,runId:result.runId,agent:"research.agent",agentVersion:"1.0.0",opportunitiesFound:result.opportunitiesFound,evidenceCount:result.evidenceCount,degradedSources:result.degradedSources,worker:"production"},idempotencyKey:`research-report-${context.task.id}`,correlationId:`research-${context.task.id}`,storageLimitBytes:effective.limits.storageBytes,retentionDays:effective.limits.retentionDays});
    return{...result,artifact,subject:subject(row)} satisfies ResearchWorkerResult;
  },
  settle:async({state,result},context)=>{const now=Math.floor(Date.now()/1000),completed=result as ResearchWorkerResult|null,row=completed?.subject??subject(account(context.task));await (await atomicTaskSettlementService()).settle({organizationId:context.task.organizationId,projectId:context.task.projectId,taskId:context.task.id,jobId:context.job.id,attemptId:context.attemptId,state,subject:row,reservationId:reservationId(context.task),artifacts:state==="completed"&&completed?[completed.artifact]:[],notifications:researchNotification(context.task,state,now),externalEffects:[],idempotencyKey:`worker-settle:${context.task.id}`,correlationId:context.task.correlationId});}
};}

export function contentWorkerHandler(dependencies:{executeContent?:typeof executeContentAgent}={}):WorkerHandler{const executeContent=dependencies.executeContent??executeContentAgent;return{
  authorize:async({task})=>{await ensureBillingSchema();authorizeContent(task);},
  execute:async(input,context)=>{
    const row=authorizeContent(context.task),commercial=commerceService(),effective=commercial.resolve(subject(row)),contentInput=input as unknown as ContentExecutionInput;
    if(contentInput.projectId!==context.task.projectId||typeof contentInput.title!=="string"||typeof contentInput.keyword!=="string")throw new WorkerJobError("CONTENT_INPUT_INVALID","Content task input is invalid",false);
    if(!context.task.requestedByAccountId)throw new WorkerJobError("CONTENT_ACCOUNT_REQUIRED","Content task owner is required",false);contentProgress(context.task,context.attemptId,10,"brief_validation","content.brief.validating");const result=await executeContent(contentInput,{organizationId:context.task.organizationId,taskId:context.task.id,jobId:context.job.id,attemptId:context.attemptId,accountId:context.task.requestedByAccountId,correlationId:context.task.correlationId,locale:context.task.locale},context.signal),usageKey=`content:${context.task.id}:generated`;contentProgress(context.task,context.attemptId,85,"quality_gate","content.quality.checking");
    commercial.ingestUsage(subject(row),{metric:"content_generated",quantity:1,state:"pending",idempotencyKey:usageKey,projectId:context.task.projectId,taskId:context.task.id});commercial.finalizeUsage(subject(row),usageKey);
    const artifact=await (await artifactObjectService()).store({organizationId:context.task.organizationId,projectId:context.task.projectId,taskId:context.task.id,attemptId:context.attemptId,artifactId:`content-draft-${context.task.id}`,kind:"content_draft",filename:`content-draft-${context.task.id}.md`,mimeType:"text/markdown",body:result.report,provenance:{title:result.reportTitle,runId:result.runId,agent:"content.agent",agentVersion:"1.0.0",contentType:result.contentType,wordCount:result.wordCount,qualityScore:result.qualityScore,checksPassed:result.checksPassed,checksTotal:result.checksTotal,evidenceCount:result.evidenceCount,reviewRequired:true,worker:"production"},idempotencyKey:`content-draft-${context.task.id}`,correlationId:`content-${context.task.id}`,storageLimitBytes:effective.limits.storageBytes,retentionDays:effective.limits.retentionDays});return{...result,artifact,subject:subject(row)} satisfies ContentWorkerResult;
  },
  settle:async({state,result},context)=>{const now=Math.floor(Date.now()/1000),completed=result as ContentWorkerResult|null,row=completed?.subject??subject(account(context.task));await (await atomicTaskSettlementService()).settle({organizationId:context.task.organizationId,projectId:context.task.projectId,taskId:context.task.id,jobId:context.job.id,attemptId:context.attemptId,state,subject:row,reservationId:reservationId(context.task),artifacts:state==="completed"&&completed?[completed.artifact]:[],notifications:contentNotification(context.task,state,now),externalEffects:[],idempotencyKey:`worker-settle:${context.task.id}`,correlationId:context.task.correlationId});if(state==="completed"&&completed){const input=context.task.input as unknown as ContentExecutionInput&{description?:string};getDatabase().prepare(`INSERT INTO seo_tasks(id,project_id,type,title,description,priority,status,requires_approval,created_at,updated_at) VALUES (?,?,?,?,?,65,'proposed',1,?,?) ON CONFLICT(id) DO NOTHING`).bind(`content-review-${context.task.id}`,context.task.projectId,`content_review_${completed.contentType}`,completed.title,input.description||`Content Agent 草稿已生成；质量分 ${completed.qualityScore}；等待人工审核。`,now,now).run();}}
};}

export function publishWorkerHandler(dependencies:{executePublish?:typeof executePublishAgent}={}):WorkerHandler{const executePublish=dependencies.executePublish??executePublishAgent;return{
  authorize:async({task})=>{await ensureBillingSchema();authorizePublish(task);},
  execute:async(input,context)=>{const row=authorizePublish(context.task),commercial=commerceService(),effective=commercial.resolve(subject(row)),publishInput=input as unknown as PublishExecutionInput;if(publishInput.projectId!==context.task.projectId||publishInput.provider!=="wordpress"||!publishInput.artifactId||!publishInput.connectionId)throw new WorkerJobError("PUBLISH_INPUT_INVALID","Publish task input is invalid",false);contentProgress(context.task,context.attemptId,10,"publish_preflight","publish.preflight.started");const result=await executePublish(publishInput,{organizationId:context.task.organizationId,taskId:context.task.id,attemptId:context.attemptId,correlationId:context.task.correlationId},context.signal);contentProgress(context.task,context.attemptId,90,"publish_verification","publish.verification.completed");const artifact=await (await artifactObjectService()).store({organizationId:context.task.organizationId,projectId:context.task.projectId,taskId:context.task.id,attemptId:context.attemptId,artifactId:`publish-report-${context.task.id}`,kind:"publish_report",filename:`publish-report-${context.task.id}.md`,mimeType:"text/markdown",body:result.report,provenance:{title:publishInput.title,agent:"publish.agent",agentVersion:"1.0.0",provider:publishInput.provider,publishedUrl:result.publishedUrl,externalId:result.externalId,verified:result.verified,contentHash:result.contentHash,worker:"production"},idempotencyKey:`publish-report-${context.task.id}`,correlationId:`publish-${context.task.id}`,storageLimitBytes:effective.limits.storageBytes,retentionDays:effective.limits.retentionDays});return{...result,artifact,subject:subject(row)} satisfies PublishWorkerResult;},
  settle:async({state,result,error},context)=>{const now=Math.floor(Date.now()/1000),completed=result as PublishWorkerResult|null,row=completed?.subject??subject(account(context.task)),input=context.task.input as unknown as PublishExecutionInput;if(state!=="completed")markPublishFailed(input.requestId,error instanceof Error?error.message:"PUBLISH_EXECUTION_FAILED");await (await atomicTaskSettlementService()).settle({organizationId:context.task.organizationId,projectId:context.task.projectId,taskId:context.task.id,jobId:context.job.id,attemptId:context.attemptId,state,subject:row,reservationId:reservationId(context.task),artifacts:state==="completed"&&completed?[completed.artifact]:[],notifications:publishNotification(context.task,state,now),externalEffects:state==="completed"&&completed?[completed.effect]:[],idempotencyKey:`worker-settle:${context.task.id}`,correlationId:context.task.correlationId});}
};}

export function geoWorkerHandler(dependencies:{executeGeo?:typeof executeGeoAgent}={}):WorkerHandler{const executeGeo=dependencies.executeGeo??executeGeoAgent;return{
  authorize:async({task})=>{await ensureBillingSchema();authorizeGeo(task);},
  execute:async(input,context)=>{const row=authorizeGeo(context.task),commercial=commerceService(),effective=commercial.resolve(subject(row)),geoInput=input as unknown as GeoExecutionInput;if(geoInput.projectId!==context.task.projectId||typeof geoInput.siteUrl!=="string"||!Number.isInteger(geoInput.maximumPages))throw new WorkerJobError("GEO_INPUT_INVALID","GEO task input is invalid",false);if(!context.task.requestedByAccountId)throw new WorkerJobError("GEO_ACCOUNT_REQUIRED","GEO task owner is required",false);auditProgress(context.task,context.attemptId,5,"geo_crawl","geo.crawl.started");const result=await executeGeo(geoInput,{organizationId:context.task.organizationId,taskId:context.task.id,jobId:context.job.id,attemptId:context.attemptId,accountId:context.task.requestedByAccountId,correlationId:context.task.correlationId,locale:context.task.locale},context.signal),usageKey=`geo:${context.task.id}:pages`;auditProgress(context.task,context.attemptId,85,"geo_report","geo.report.generated");commercial.ingestUsage(subject(row),{metric:"geo_pages",quantity:result.pagesScanned,state:"pending",idempotencyKey:usageKey,projectId:context.task.projectId,taskId:context.task.id});commercial.finalizeUsage(subject(row),usageKey);const artifact=await (await artifactObjectService()).store({organizationId:context.task.organizationId,projectId:context.task.projectId,taskId:context.task.id,attemptId:context.attemptId,artifactId:`geo-report-${context.task.id}`,kind:"geo_readiness_report",filename:`geo-readiness-${context.task.id}.md`,mimeType:"text/markdown",body:result.report,provenance:{title:result.reportTitle,runId:result.runId,agent:"geo.agent",agentVersion:"1.0.0",score:result.score,pagesScanned:result.pagesScanned,checksTotal:result.checksTotal,recommendations:result.recommendations,degradedSources:result.degradedSources,worker:"production"},idempotencyKey:`geo-report-${context.task.id}`,correlationId:`geo-${context.task.id}`,storageLimitBytes:effective.limits.storageBytes,retentionDays:effective.limits.retentionDays});return{...result,artifact,subject:subject(row)} satisfies GeoWorkerResult;},
  settle:async({state,result},context)=>{const now=Math.floor(Date.now()/1000),completed=result as GeoWorkerResult|null,row=completed?.subject??subject(account(context.task));await (await atomicTaskSettlementService()).settle({organizationId:context.task.organizationId,projectId:context.task.projectId,taskId:context.task.id,jobId:context.job.id,attemptId:context.attemptId,state,subject:row,reservationId:reservationId(context.task),artifacts:state==="completed"&&completed?[completed.artifact]:[],notifications:geoNotification(context.task,state,now),externalEffects:[],idempotencyKey:`worker-settle:${context.task.id}`,correlationId:context.task.correlationId});}
};}

export function analyticsWorkerHandler(dependencies:{executeAnalytics?:typeof executeAnalyticsAgent}={}):WorkerHandler{const executeAnalytics=dependencies.executeAnalytics??executeAnalyticsAgent;return{
  authorize:async({task})=>{await ensureBillingSchema();authorizeAnalytics(task);},
  execute:async(input,context)=>{const row=authorizeAnalytics(context.task),commercial=commerceService(),effective=commercial.resolve(subject(row)),analyticsInput=input as unknown as AnalyticsExecutionInput;if(analyticsInput.projectId!==context.task.projectId||!Number.isInteger(analyticsInput.lookbackDays)||analyticsInput.lookbackDays<1||analyticsInput.lookbackDays>365)throw new WorkerJobError("ANALYTICS_INPUT_INVALID","Analytics task input is invalid",false);if(!context.task.requestedByAccountId)throw new WorkerJobError("ANALYTICS_ACCOUNT_REQUIRED","Analytics task owner is required",false);auditProgress(context.task,context.attemptId,10,"analytics_acquisition","analytics.acquisition.started");const result=await executeAnalytics(analyticsInput,{organizationId:context.task.organizationId,taskId:context.task.id,jobId:context.job.id,attemptId:context.attemptId,accountId:context.task.requestedByAccountId,correlationId:context.task.correlationId,locale:context.task.locale},context.signal),usageKey=`analytics:${context.task.id}:snapshots`;auditProgress(context.task,context.attemptId,85,"analytics_report","analytics.report.generated");const artifact=await (await artifactObjectService()).store({organizationId:context.task.organizationId,projectId:context.task.projectId,taskId:context.task.id,attemptId:context.attemptId,artifactId:`analytics-report-${context.task.id}`,kind:"analytics_report",filename:`analytics-report-${context.task.id}.md`,mimeType:"text/markdown",body:result.report,provenance:{title:result.reportTitle,runId:result.runId,agent:"analytics.agent",agentVersion:"1.0.0",evidenceSources:result.evidenceSources,insights:result.insights,recommendations:result.recommendations,degradedSources:result.degradedSources,worker:"production"},idempotencyKey:`analytics-report-${context.task.id}`,correlationId:`analytics-${context.task.id}`,storageLimitBytes:effective.limits.storageBytes,retentionDays:effective.limits.retentionDays});commercial.ingestUsage(subject(row),{metric:"analytics_snapshots",quantity:1,state:"pending",idempotencyKey:usageKey,projectId:context.task.projectId,taskId:context.task.id});commercial.finalizeUsage(subject(row),usageKey);return{...result,artifact,subject:subject(row)} satisfies AnalyticsWorkerResult;},
  settle:async({state,result},context)=>{const now=Math.floor(Date.now()/1000),completed=result as AnalyticsWorkerResult|null,row=completed?.subject??subject(account(context.task));await (await atomicTaskSettlementService()).settle({organizationId:context.task.organizationId,projectId:context.task.projectId,taskId:context.task.id,jobId:context.job.id,attemptId:context.attemptId,state,subject:row,reservationId:reservationId(context.task),artifacts:state==="completed"&&completed?[completed.artifact]:[],notifications:analyticsNotification(context.task,state,now),externalEffects:[],idempotencyKey:`worker-settle:${context.task.id}`,correlationId:context.task.correlationId});}
};}

export async function createProductionWorker(){
  const workerId=(process.env.WORKER_ID||`${os.hostname()}:${process.pid}`).slice(0,128),handlers:WorkerHandlers={"seo.audit":auditWorkerHandler(),"research.run":researchWorkerHandler(),"content.generate":contentWorkerHandler(),"content.publish":publishWorkerHandler(),"geo.audit":geoWorkerHandler(),"analytics.snapshot":analyticsWorkerHandler()};
  return executionWorkerSupervisor(handlers,{workerId,queue:"agents",concurrency:Number(process.env.WORKER_CONCURRENCY||2),pollIntervalMs:Number(process.env.WORKER_POLL_INTERVAL_MS||1000),leaseSeconds:Number(process.env.WORKER_LEASE_SECONDS||60),heartbeatIntervalMs:Number(process.env.WORKER_HEARTBEAT_INTERVAL_MS||15000),shutdownGraceMs:Number(process.env.WORKER_SHUTDOWN_GRACE_MS||30000),maintenanceLimit:100,baseBackoffSeconds:5,maxBackoffSeconds:300},{onError:error=>console.error("Worker execution error",error instanceof Error?{name:error.name,message:error.message}:String(error))});
}

export function startWorkerHeartbeat(workerId:string){const db=getDatabase(),write=()=>{const now=Math.floor(Date.now()/1000);db.exec("CREATE TABLE IF NOT EXISTS execution_worker_heartbeats(worker_id TEXT PRIMARY KEY,queue TEXT NOT NULL,process_id INTEGER NOT NULL,hostname TEXT NOT NULL,started_at INTEGER NOT NULL,last_seen_at INTEGER NOT NULL)");db.prepare("INSERT INTO execution_worker_heartbeats(worker_id,queue,process_id,hostname,started_at,last_seen_at) VALUES (?,?,?,?,?,?) ON CONFLICT(worker_id) DO UPDATE SET process_id=excluded.process_id,hostname=excluded.hostname,last_seen_at=excluded.last_seen_at").bind(workerId,"agents",process.pid,os.hostname(),now,now).run();};write();const timer=setInterval(write,15000);return()=>{clearInterval(timer);db.prepare("DELETE FROM execution_worker_heartbeats WHERE worker_id=?").bind(workerId).run();};}
