import { createHash } from "node:crypto";
import { getDatabase } from "./auth";
import { artifactObjectService, atomicTaskCreationService } from "./execution";
import { publishWordpressPost } from "./integrations";
import { permissions, type OrganizationRoleKey } from "../platform/modules/identity/authorization";
import { WorkerJobError } from "../platform/modules/execution/worker";
import type { CommercialSubject } from "../platform/modules/commerce";
import type { ExternalEffectRecord } from "../platform/modules/execution";

export const PUBLISH_CREDIT_COST=5;
export type PublishRequest={id:string;organizationId:string;projectId:string;contentTaskId:string;artifactId:string;connectionId:string;provider:"wordpress";title:string;slug:string;excerpt:string;scheduledFor:number|null;status:string;executionTaskId:string|null;externalId:string|null;publishedUrl:string|null;verificationStatus:string;error:string|null;createdAt:number;updatedAt:number};
export type PublishExecutionInput={projectId:string;requestId:string;contentTaskId:string;artifactId:string;connectionId:string;provider:"wordpress";title:string;slug:string;excerpt:string;legacyTaskId:string};
export type PublishExecutionResult={requestId:string;externalId:string;publishedUrl:string;verified:boolean;contentHash:string;effect:ExternalEffectRecord;report:Uint8Array};

export async function ensurePublishSchema(){const db=getDatabase();db.exec(`
 CREATE TABLE IF NOT EXISTS publish_requests(
  id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,project_id TEXT NOT NULL,content_task_id TEXT NOT NULL,artifact_id TEXT NOT NULL,connection_id TEXT NOT NULL,
  provider TEXT NOT NULL CHECK(provider IN('wordpress')),title TEXT NOT NULL,slug TEXT NOT NULL,excerpt TEXT NOT NULL DEFAULT '',scheduled_for INTEGER,
  status TEXT NOT NULL CHECK(status IN('awaiting_approval','queued','publishing','published','failed','cancelled')),execution_task_id TEXT,external_id TEXT,published_url TEXT,
  verification_status TEXT NOT NULL DEFAULT 'pending' CHECK(verification_status IN('pending','verified','failed')),error TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,
  UNIQUE(organization_id,project_id,id),UNIQUE(execution_task_id),FOREIGN KEY(organization_id,project_id) REFERENCES projects(organization_id,id),
  FOREIGN KEY(organization_id,project_id,content_task_id) REFERENCES execution_tasks(organization_id,project_id,id),FOREIGN KEY(organization_id,artifact_id) REFERENCES execution_artifacts(organization_id,id),
  FOREIGN KEY(organization_id,project_id,connection_id) REFERENCES integration_connections(organization_id,project_id,id));
 CREATE INDEX IF NOT EXISTS publish_requests_scope_idx ON publish_requests(organization_id,project_id,status,updated_at DESC,id);
 `);}

export function publishDashboard(organizationId:string,projectId:string){const db=getDatabase();const candidates=db.prepare(`
 SELECT cr.execution_task_id AS contentTaskId,cr.title,cr.keyword,cr.content_type AS contentType,cr.quality_score AS qualityScore,cr.checks_passed AS checksPassed,cr.checks_total AS checksTotal,
  cr.completed_at AS completedAt,a.id AS artifactId,r.status AS reviewStatus,
  CASE WHEN cr.status='completed' AND cr.checks_total>0 AND cr.checks_passed=cr.checks_total AND r.status='approved' AND a.scan_state='clean' THEN 1 ELSE 0 END AS ready
 FROM content_runs cr LEFT JOIN seo_tasks r ON r.id='content-review-'||cr.execution_task_id
 LEFT JOIN execution_artifacts a ON a.organization_id=? AND a.project_id=cr.project_id AND a.task_id=cr.execution_task_id AND a.kind='content_draft'
 WHERE cr.project_id=? ORDER BY cr.completed_at DESC LIMIT 50`).bind(organizationId,projectId).all().results;
 const requests=db.prepare(`SELECT pr.id,pr.content_task_id AS contentTaskId,pr.artifact_id AS artifactId,pr.connection_id AS connectionId,pr.provider,pr.title,pr.slug,pr.excerpt,pr.scheduled_for AS scheduledFor,pr.status,pr.execution_task_id AS executionTaskId,pr.external_id AS externalId,pr.published_url AS publishedUrl,pr.verification_status AS verificationStatus,pr.error,pr.created_at AS createdAt,pr.updated_at AS updatedAt,st.status AS approvalStatus,et.state AS executionState FROM publish_requests pr LEFT JOIN seo_tasks st ON st.id=pr.id LEFT JOIN execution_tasks et ON et.id=pr.execution_task_id WHERE pr.organization_id=? AND pr.project_id=? ORDER BY pr.updated_at DESC LIMIT 100`).bind(organizationId,projectId).all().results;
 return{candidates,requests};}

export async function queueApprovedPublish(input:{organizationId:string;projectId:string;requestId:string;accountId:string;role:OrganizationRoleKey;subject:CommercialSubject;locale:"zh-CN"|"en"}){
 await ensurePublishSchema();const db=getDatabase(),request=db.prepare("SELECT id,project_id AS projectId,content_task_id AS contentTaskId,artifact_id AS artifactId,connection_id AS connectionId,provider,title,slug,excerpt,scheduled_for AS scheduledFor,status,execution_task_id AS executionTaskId FROM publish_requests WHERE id=? AND organization_id=? AND project_id=?").bind(input.requestId,input.organizationId,input.projectId).first<PublishRequest>();
 if(!request)throw new Error("PUBLISH_REQUEST_NOT_FOUND");if(request.executionTaskId)return{taskId:request.executionTaskId,duplicate:true};if(request.status!=="awaiting_approval")throw new Error("PUBLISH_REQUEST_STATE_CONFLICT");
 const created=(await atomicTaskCreationService()).create({activeOrganizationId:input.organizationId,organizationId:input.organizationId,projectId:input.projectId,requestedByAccountId:input.accountId,role:input.role,permission:permissions.contentPublish,subject:input.subject,triggerType:"approval",taskType:"publish_agent",capability:"content.publish",input:{projectId:input.projectId,requestId:request.id,contentTaskId:request.contentTaskId,artifactId:request.artifactId,connectionId:request.connectionId,provider:request.provider,title:request.title,slug:request.slug,excerpt:request.excerpt,legacyTaskId:request.id,description:`发布到 WordPress；Slug：${request.slug||"由 CMS 生成"}`},locale:input.locale,idempotencyKey:`publish:${request.id}:approved`,correlationId:`publish:${crypto.randomUUID()}`,entitlements:[],creditCost:PUBLISH_CREDIT_COST,queue:"agents",jobType:"content.publish",priority:80,availableAt:request.scheduledFor??undefined,maxAttempts:3,timeoutSeconds:120});
 db.prepare("UPDATE publish_requests SET status='queued',execution_task_id=?,updated_at=? WHERE id=? AND status='awaiting_approval'").bind(created.task.id,Math.floor(Date.now()/1000),request.id).run();return{taskId:created.task.id,duplicate:created.duplicate};
}

function markdownToHtml(markdown:string){const escape=(value:string)=>value.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");const inline=(value:string)=>escape(value).replace(/\*\*([^*]+)\*\*/g,"<strong>$1</strong>").replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,'<a href="$2">$1</a>');const lines=markdown.replace(/\r/g,"").split("\n"),out:string[]=[];let list=false;for(const raw of lines){const line=raw.trim();if(/^[-*] /.test(line)){if(!list){out.push("<ul>");list=true;}out.push(`<li>${inline(line.slice(2))}</li>`);continue;}if(list){out.push("</ul>");list=false;}if(!line)continue;const heading=line.match(/^(#{1,4})\s+(.+)$/);if(heading)out.push(`<h${heading[1].length}>${inline(heading[2])}</h${heading[1].length}>`);else out.push(`<p>${inline(line)}</p>`);}if(list)out.push("</ul>");return out.join("\n");}

export async function executePublishAgent(input:PublishExecutionInput,context:{organizationId:string;taskId:string;attemptId:string;correlationId:string},signal?:AbortSignal):Promise<PublishExecutionResult>{
 if(signal?.aborted)throw signal.reason;await ensurePublishSchema();const db=getDatabase(),request=db.prepare("SELECT status FROM publish_requests WHERE id=? AND organization_id=? AND project_id=? AND execution_task_id=?").bind(input.requestId,context.organizationId,input.projectId,context.taskId).first<{status:string}>();if(!request||!["queued","publishing"].includes(request.status))throw new WorkerJobError("PUBLISH_REQUEST_INVALID","Publish request is unavailable",false);
 db.prepare("UPDATE publish_requests SET status='publishing',error=NULL,updated_at=? WHERE id=?").bind(Math.floor(Date.now()/1000),input.requestId).run();const artifact=executionArtifact(context.organizationId,input.projectId,input.contentTaskId,input.artifactId);const objects=await artifactObjectService(),access=objects.authorizeAccess({activeOrganizationId:context.organizationId,organizationId:context.organizationId,activeProjectId:input.projectId,artifactId:artifact.id}),token=new URL(access.url,"https://oneshowseo.local").searchParams.get("token");if(!token)throw new WorkerJobError("PUBLISH_ARTIFACT_ACCESS_FAILED","Content artifact access failed",false);const resolved=await objects.resolveAccess(token),markdown=new TextDecoder().decode(resolved.body),html=markdownToHtml(markdown),contentHash=createHash("sha256").update(html).digest("hex");
 const published=await publishWordpressPost({organizationId:context.organizationId,projectId:input.projectId,connectionId:input.connectionId,title:input.title,slug:input.slug,excerpt:input.excerpt,html,contentHash,correlationId:context.correlationId,signal});const now=Math.floor(Date.now()/1000),requestHash=createHash("sha256").update(JSON.stringify({connectionId:input.connectionId,title:input.title,slug:input.slug,contentHash})).digest("hex");const effect:ExternalEffectRecord={id:`publish-effect-${context.taskId}`,organizationId:context.organizationId,projectId:input.projectId,taskId:context.taskId,attemptId:context.attemptId,provider:"wordpress",operation:"content.publish",externalReference:published.externalId,requestHash,state:"succeeded",evidence:{url:published.url,status:published.status,verified:published.verified,contentHash,providerAttempts:published.attempts},errorCode:null,idempotencyKey:`wordpress:${context.taskId}:publish`,correlationId:context.correlationId,createdAt:now,updatedAt:now};
 db.prepare("UPDATE publish_requests SET status='published',external_id=?,published_url=?,verification_status=?,error=NULL,updated_at=? WHERE id=?").bind(published.externalId,published.url,published.verified?"verified":"failed",now,input.requestId).run();const report=`# 发布执行报告\n\n- 内容：${input.title}\n- 平台：WordPress\n- 状态：已发布并验证\n- 地址：${published.url}\n- 外部 ID：${published.externalId}\n- 内容哈希：${contentHash}\n- 执行关联：${context.correlationId}\n`;return{requestId:input.requestId,externalId:published.externalId,publishedUrl:published.url,verified:published.verified,contentHash,effect,report:new TextEncoder().encode(report)};
}

function executionArtifact(organizationId:string,projectId:string,taskId:string,artifactId:string){const value=getDatabase().prepare("SELECT id FROM execution_artifacts WHERE id=? AND organization_id=? AND project_id=? AND task_id=? AND kind='content_draft' AND scan_state='clean'").bind(artifactId,organizationId,projectId,taskId).first<{id:string}>();if(!value)throw new WorkerJobError("PUBLISH_ARTIFACT_INVALID","Approved content artifact is unavailable",false);return value;}

export function markPublishFailed(requestId:string,error:string){getDatabase().prepare("UPDATE publish_requests SET status='failed',verification_status='failed',error=?,updated_at=? WHERE id=?").bind(error.slice(0,500),Math.floor(Date.now()/1000),requestId).run();}
