import { NextResponse } from "next/server";
import { getCurrentUser, getDatabase, writeAudit } from "../../../../../lib/auth";
import { ensureProductSchema, ownedProject } from "../../../../../lib/product";
import { commerceService, commercialSubject, ensureBillingSchema } from "../../../../../lib/billing";
import { atomicTaskCreationService } from "../../../../../lib/execution";
import { permissions, type OrganizationRoleKey } from "../../../../../platform/modules/identity/authorization";
import { CommerceError } from "../../../../../platform/modules/commerce/service";
import { TaskCreationError } from "../../../../../platform/modules/execution/task-creation";

const CONTENT_CREDIT_COST=20,types=new Set(["blog_post","guide","landing_page","content_refresh"]);
const text=(value:unknown,max:number)=>typeof value==="string"?value.trim().slice(0,max):"";
function payload(projectId:string){const db=getDatabase(),runs=db.prepare(`SELECT id,execution_task_id AS taskId,status,title,keyword,content_type AS contentType,audience,intent,tone,goal,source_ref AS sourceRef,brief,word_count AS wordCount,quality_score AS qualityScore,checks_passed AS checksPassed,checks_total AS checksTotal,evidence_count AS evidenceCount,review_status AS reviewStatus,agent_version AS agentVersion,started_at AS startedAt,completed_at AS completedAt,error FROM content_runs WHERE project_id=? ORDER BY started_at DESC LIMIT 50`).bind(projectId).all().results,latest=runs[0] as {id:string}|undefined,checks=latest?db.prepare(`SELECT id,check_key AS checkKey,label,status,detail,created_at AS createdAt FROM content_quality_checks WHERE run_id=? ORDER BY created_at,id`).bind(latest.id).all().results:[];return{runs,latestRun:latest||null,checks};}

export async function GET(_:Request,context:{params:Promise<{id:string}>}){const user=await getCurrentUser();if(!user)return NextResponse.json({error:"请先登录"},{status:401});await ensureProductSchema();const{id}=await context.params;if(!await ownedProject(user.organization.organizationId,id))return NextResponse.json({error:"项目不存在"},{status:404});return NextResponse.json(payload(id),{headers:{"cache-control":"private, no-store"}});}

export async function POST(request:Request,context:{params:Promise<{id:string}>}){
  const user=await getCurrentUser();if(!user)return NextResponse.json({error:"请先登录"},{status:401});await ensureProductSchema();const{id}=await context.params,project=await ownedProject(user.organization.organizationId,id);if(!project)return NextResponse.json({error:"项目不存在"},{status:404});if(project.status!=="active")return NextResponse.json({error:"项目已归档或停用，不能生成内容"},{status:409});
  const raw=await request.json().catch(()=>({})) as Record<string,unknown>,input={projectId:id,title:text(raw.title,160),keyword:text(raw.keyword,160),contentType:text(raw.contentType,40),audience:text(raw.audience,300),intent:text(raw.intent,100),tone:text(raw.tone,200),goal:text(raw.goal,300),sourceRef:text(raw.sourceRef,1000),brief:text(raw.brief,5000)};
  if(!input.title||!input.keyword||!types.has(input.contentType)||!input.audience||!input.intent||!input.tone||!input.goal||!input.sourceRef)return NextResponse.json({error:"请完整填写标题、关键词、类型、受众、意图、语气、目标和证据来源",code:"CONTENT_BRIEF_INVALID"},{status:400});
  try{
    await ensureBillingSchema();const service=commerceService(),subject=commercialSubject(user);service.authorizeAccess(subject);const current=service.usageTotals(subject).find(item=>item.metric==="content_generated"),currentUsage=Number(current?.final??0)+Number(current?.pending??0),requested=request.headers.get("idempotency-key")?.trim(),idempotencyKey=requested&&/^[A-Za-z0-9][A-Za-z0-9._:-]{15,127}$/.test(requested)?requested:`content:${id}:${crypto.randomUUID()}`,correlationId=request.headers.get("traceparent")||`content:${crypto.randomUUID()}`;
    const created=(await atomicTaskCreationService()).create({activeOrganizationId:user.organization.organizationId,organizationId:user.organization.organizationId,projectId:id,requestedByAccountId:user.id,role:user.organization.roleKey as OrganizationRoleKey,permission:permissions.contentCreate,subject,triggerType:"manual",taskType:"content_agent",capability:"content.generate",input:{...input,description:`目标关键词：${input.keyword}；目标受众：${input.audience}；搜索意图：${input.intent}；品牌语气：${input.tone}；内容目标：${input.goal}；证据来源：${input.sourceRef}；补充要求：${input.brief||"无"}`},locale:project.language.startsWith("en")?"en":"zh-CN",idempotencyKey,correlationId,entitlements:[{key:"contentItems",quantity:1,currentUsage}],creditCost:CONTENT_CREDIT_COST,queue:"agents",jobType:"content.generate",priority:65,maxAttempts:2,timeoutSeconds:900});
    await writeAudit("content_generation_queued",user.id,request,JSON.stringify({projectId:id,taskId:created.task.id,jobId:created.job.id,creditsReserved:CONTENT_CREDIT_COST,agent:"content.agent@1.0.0",title:input.title}));return NextResponse.json({taskId:created.task.id,jobId:created.job.id,state:created.task.state,creditsReserved:CONTENT_CREDIT_COST,duplicate:created.duplicate,correlationId},{status:202});
  }catch(error){if(error instanceof CommerceError||error instanceof TaskCreationError)return NextResponse.json({error:error.message,code:error.code},{status:error.status});console.error("Failed to queue content generation",error);return NextResponse.json({error:"内容生成任务创建失败，请稍后重试"},{status:500});}
}
