import { NextResponse } from "next/server";
import { getCurrentUser, getDatabase, writeAudit } from "../../../../../lib/auth";
import { ensureProductSchema, ownedProject } from "../../../../../lib/product";
import { commerceService, commercialSubject, ensureBillingSchema } from "../../../../../lib/billing";
import { atomicTaskCreationService, ensureExecutionSchema } from "../../../../../lib/execution";
import { can, permissions, type OrganizationRoleKey } from "../../../../../platform/modules/identity/authorization";
import { CommerceError } from "../../../../../platform/modules/commerce/service";
import { TaskCreationError } from "../../../../../platform/modules/execution/task-creation";

const CONTENT_CREDIT_COST=20,types=new Set(["blog_post","guide","landing_page","content_refresh"]);
const text=(value:unknown,max:number)=>typeof value==="string"?value.trim().slice(0,max):"";
function ensureContentStudioSchema(){getDatabase().exec(`CREATE TABLE IF NOT EXISTS content_versions(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,run_id TEXT NOT NULL REFERENCES content_runs(id) ON DELETE CASCADE,version_number INTEGER NOT NULL,body TEXT NOT NULL,word_count INTEGER NOT NULL DEFAULT 0,created_by_account_id TEXT NOT NULL,created_at INTEGER NOT NULL,UNIQUE(project_id,run_id,version_number));CREATE INDEX IF NOT EXISTS content_versions_scope_idx ON content_versions(organization_id,project_id,run_id,version_number DESC);`)}
function payload(projectId:string){ensureContentStudioSchema();const db=getDatabase(),runs=db.prepare(`SELECT cr.id,cr.execution_task_id AS taskId,cr.status,cr.title,cr.keyword,cr.content_type AS contentType,cr.audience,cr.intent,cr.tone,cr.goal,cr.source_ref AS sourceRef,cr.brief,cr.word_count AS wordCount,cr.quality_score AS qualityScore,cr.checks_passed AS checksPassed,cr.checks_total AS checksTotal,cr.evidence_count AS evidenceCount,cr.review_status AS reviewStatus,cr.agent_version AS agentVersion,cr.started_at AS startedAt,cr.completed_at AS completedAt,cr.error,(SELECT a.id FROM execution_artifacts a WHERE a.project_id=cr.project_id AND a.task_id=cr.execution_task_id AND a.kind='content_draft' AND a.scan_state='clean' ORDER BY a.created_at DESC LIMIT 1) AS artifactId FROM content_runs cr WHERE cr.project_id=? ORDER BY cr.started_at DESC LIMIT 50`).bind(projectId).all().results,latest=runs[0] as {id:string}|undefined,checks=latest?db.prepare(`SELECT id,check_key AS checkKey,label,status,detail,created_at AS createdAt FROM content_quality_checks WHERE run_id=? ORDER BY created_at,id`).bind(latest.id).all().results:[],versions=db.prepare(`SELECT id,run_id AS runId,version_number AS versionNumber,body,word_count AS wordCount,created_at AS createdAt FROM content_versions WHERE project_id=? ORDER BY created_at DESC LIMIT 50`).bind(projectId).all().results;return{runs,latestRun:latest||null,checks,versions};}

export async function GET(_:Request,context:{params:Promise<{id:string}>}){const user=await getCurrentUser();if(!user)return NextResponse.json({error:"请先登录"},{status:401});await ensureExecutionSchema();const{id}=await context.params;if(!await ownedProject(user.organization.organizationId,id))return NextResponse.json({error:"项目不存在"},{status:404});return NextResponse.json(payload(id),{headers:{"cache-control":"private, no-store"}});}

export async function POST(request:Request,context:{params:Promise<{id:string}>}){
  const user=await getCurrentUser();if(!user)return NextResponse.json({error:"请先登录"},{status:401});await ensureProductSchema();const{id}=await context.params,project=await ownedProject(user.organization.organizationId,id);if(!project)return NextResponse.json({error:"项目不存在"},{status:404});if(project.status!=="active")return NextResponse.json({error:"项目已归档或停用，不能生成内容"},{status:409});
  const raw=await request.json().catch(()=>({})) as Record<string,unknown>,input={projectId:id,title:text(raw.title,160),keyword:text(raw.keyword,160),contentType:text(raw.contentType,40),audience:text(raw.audience,300),intent:text(raw.intent,100),tone:text(raw.tone,200),goal:text(raw.goal,300),sourceRef:text(raw.sourceRef,1000),brief:text(raw.brief,5000)};
  if(!input.title||!input.keyword||!types.has(input.contentType)||!input.audience||!input.intent||!input.tone||!input.goal||!input.sourceRef)return NextResponse.json({error:"请完整填写标题、关键词、类型、受众、意图、语气、目标和证据来源",code:"CONTENT_BRIEF_INVALID"},{status:400});
  try{
    await ensureBillingSchema();const service=commerceService(),subject=commercialSubject(user);service.authorizeAccess(subject);const current=service.usageTotals(subject).find(item=>item.metric==="content_generated"),currentUsage=Number(current?.final??0)+Number(current?.pending??0),requested=request.headers.get("idempotency-key")?.trim(),idempotencyKey=requested&&/^[A-Za-z0-9][A-Za-z0-9._:-]{15,127}$/.test(requested)?requested:`content:${id}:${crypto.randomUUID()}`,correlationId=request.headers.get("traceparent")||`content:${crypto.randomUUID()}`;
    const created=(await atomicTaskCreationService()).create({activeOrganizationId:user.organization.organizationId,organizationId:user.organization.organizationId,projectId:id,requestedByAccountId:user.id,role:user.organization.roleKey as OrganizationRoleKey,permission:permissions.contentCreate,subject,triggerType:"manual",taskType:"content_agent",capability:"content.generate",input:{...input,description:`目标关键词：${input.keyword}；目标受众：${input.audience}；搜索意图：${input.intent}；品牌语气：${input.tone}；内容目标：${input.goal}；证据来源：${input.sourceRef}；补充要求：${input.brief||"无"}`},locale:project.language.startsWith("en")?"en":"zh-CN",idempotencyKey,correlationId,entitlements:[{key:"contentItems",quantity:1,currentUsage}],creditCost:CONTENT_CREDIT_COST,queue:"agents",jobType:"content.generate",priority:65,maxAttempts:2,timeoutSeconds:900});
    await writeAudit("content_generation_queued",user.id,request,JSON.stringify({projectId:id,taskId:created.task.id,jobId:created.job.id,creditsReserved:CONTENT_CREDIT_COST,agent:"content.agent@1.0.0",title:input.title}));return NextResponse.json({taskId:created.task.id,jobId:created.job.id,state:created.task.state,creditsReserved:CONTENT_CREDIT_COST,duplicate:created.duplicate,correlationId},{status:202});
  }catch(error){if(error instanceof CommerceError||error instanceof TaskCreationError)return NextResponse.json({error:error.message,code:error.code},{status:error.status});console.error("Failed to queue content generation",error);return NextResponse.json({error:"内容生成任务创建失败，请稍后重试"},{status:500});}
}

export async function PATCH(request:Request,context:{params:Promise<{id:string}>}){
  const user=await getCurrentUser();if(!user)return NextResponse.json({error:"请先登录"},{status:401});await ensureProductSchema();ensureContentStudioSchema();const{id}=await context.params,project=await ownedProject(user.organization.organizationId,id);if(!project)return NextResponse.json({error:"项目不存在"},{status:404});if(!can(user.organization.roleKey as OrganizationRoleKey,permissions.contentCreate))return NextResponse.json({error:"没有编辑内容的权限"},{status:403});
  const raw=await request.json().catch(()=>({})) as Record<string,unknown>,runId=text(raw.runId,128),body=typeof raw.body==="string"?raw.body.slice(0,200000):"";if(!runId||!body.trim())return NextResponse.json({error:"请选择内容并填写正文",code:"CONTENT_VERSION_INVALID"},{status:400});const db=getDatabase(),run=db.prepare("SELECT id FROM content_runs WHERE id=? AND project_id=? AND status='completed'").bind(runId,id).first<{id:string}>();if(!run)return NextResponse.json({error:"内容草稿不存在或尚未生成完成"},{status:404});
  const latest=Number(db.prepare("SELECT COALESCE(MAX(version_number),0) AS value FROM content_versions WHERE project_id=? AND run_id=?").bind(id,runId).first<{value:number}>()?.value??0),versionNumber=latest+1,now=Math.floor(Date.now()/1000),wordCount=body.replace(/[#>*_`\[\]()\-]/g," ").trim().split(/\s+|(?=[\u4e00-\u9fff])/).filter(Boolean).length,version={id:crypto.randomUUID(),runId,versionNumber,body,wordCount,createdAt:now};db.prepare("INSERT INTO content_versions(id,organization_id,project_id,run_id,version_number,body,word_count,created_by_account_id,created_at) VALUES (?,?,?,?,?,?,?,?,?)").bind(version.id,user.organization.organizationId,id,runId,versionNumber,body,wordCount,user.id,now).run();await writeAudit("content_version_saved",user.id,request,JSON.stringify({projectId:id,runId,versionId:version.id,versionNumber,wordCount}));return NextResponse.json({version},{status:201});
}
