import { NextResponse } from "next/server";
import { getCurrentUser, writeAudit } from "../../../../lib/auth";
import { clearDataSource, dataSourceDefinitions, type DataSourceProvider, listDataSources, saveDataSource } from "../../../../lib/data-sources";
import {AuthorizationError,authorizePlatformAccount} from "../../../../platform/modules/identity/authorization";

async function admin(){const user=await getCurrentUser();if(!user)return null;try{authorizePlatformAccount(user.role);return user;}catch(error){if(error instanceof AuthorizationError)return null;throw error;}}
function validProvider(value:unknown):value is DataSourceProvider{return typeof value==="string"&&value in dataSourceDefinitions;}

export async function GET(){const user=await admin();if(!user)return NextResponse.json({error:"无权访问"},{status:403});const sources=await listDataSources();return NextResponse.json({encryptionReady:Boolean(process.env.DATA_SOURCE_ENCRYPTION_KEY&&process.env.DATA_SOURCE_ENCRYPTION_KEY.length>=24),sources:sources.map(source=>({...source,name:dataSourceDefinitions[source.provider].name,description:dataSourceDefinitions[source.provider].description,fields:dataSourceDefinitions[source.provider].fields.map(field=>({key:field.key,label:field.label,required:field.required,configured:source.configured}))}))});}

export async function PATCH(request:Request){const user=await admin();if(!user)return NextResponse.json({error:"无权访问"},{status:403});const body=await request.json().catch(()=>null) as Record<string,unknown>|null;if(!validProvider(body?.provider))return NextResponse.json({error:"数据源无效"},{status:400});const values=body?.values&&typeof body.values==="object"&&!Array.isArray(body.values)?Object.fromEntries(Object.entries(body.values).filter((entry):entry is [string,string]=>typeof entry[1]==="string")):{};try{await saveDataSource(body.provider,values,body.enabled===true,user.id);}catch(error){const message=error instanceof Error?error.message:"SAVE_FAILED";if(message==="DATA_SOURCE_ENCRYPTION_KEY_MISSING")return NextResponse.json({error:"服务器尚未配置数据源加密密钥"},{status:503});if(message==="DATA_SOURCE_REQUIRED_FIELDS_MISSING")return NextResponse.json({error:"启用前请补齐必填配置"},{status:400});return NextResponse.json({error:"保存失败"},{status:500});}await writeAudit("admin_data_source_update",user.id,request,JSON.stringify({provider:body.provider,enabled:body.enabled===true}));return NextResponse.json({ok:true});}

export async function DELETE(request:Request){const user=await admin();if(!user)return NextResponse.json({error:"无权访问"},{status:403});const body=await request.json().catch(()=>null) as Record<string,unknown>|null;if(!validProvider(body?.provider))return NextResponse.json({error:"数据源无效"},{status:400});await clearDataSource(body.provider,user.id);await writeAudit("admin_data_source_clear",user.id,request,JSON.stringify({provider:body.provider}));return NextResponse.json({ok:true});}
