import { NextResponse } from "next/server";
import { getCurrentUser,getDatabase,writeAudit } from "../../../../../lib/auth";
import { ensureProductSchema,ownedProject } from "../../../../../lib/product";
import { ensurePublishSchema,publishDashboard,PUBLISH_CREDIT_COST } from "../../../../../lib/publish-execution";
import { integrationRepository } from "../../../../../lib/integrations";
import { can,permissions,type OrganizationRoleKey } from "../../../../../platform/modules/identity/authorization";

const clean=(value:unknown,max:number)=>typeof value==="string"?value.trim().slice(0,max):"";
const slugPattern=/^[a-z0-9]+(?:-[a-z0-9]+)*$/;

export async function GET(_:Request,context:{params:Promise<{id:string}>}){const user=await getCurrentUser();if(!user)return NextResponse.json({error:"请先登录"},{status:401});const{id}=await context.params;await ensureProductSchema();if(!await ownedProject(user.organization.organizationId,id))return NextResponse.json({error:"项目不存在"},{status:404});await ensurePublishSchema();const state=publishDashboard(user.organization.organizationId,id),connections=(await integrationRepository()).listConnections(user.organization.organizationId,id).filter(item=>item.providerId==="wordpress").map(item=>({id:item.id,provider:item.providerId,state:item.state,writeEnabled:item.grantedScopes.includes("content.write"),baseUrl:item.metadata.baseUrl||"",maskedHint:item.maskedHint,health:item.health?.state||null,updatedAt:item.updatedAt}));return NextResponse.json({...state,connections,creditCost:PUBLISH_CREDIT_COST},{headers:{"cache-control":"private, no-store"}});}

export async function POST(request:Request,context:{params:Promise<{id:string}>}){
 const user=await getCurrentUser();if(!user)return NextResponse.json({error:"请先登录"},{status:401});const{id}=await context.params;await ensureProductSchema();const project=await ownedProject(user.organization.organizationId,id);if(!project)return NextResponse.json({error:"项目不存在"},{status:404});if(project.status!=="active")return NextResponse.json({error:"项目不可用"},{status:409});if(!can(user.organization.roleKey as OrganizationRoleKey,permissions.contentPublish))return NextResponse.json({error:"没有创建发布任务的权限"},{status:403});
 const body=await request.json().catch(()=>null)as Record<string,unknown>|null,contentTaskId=clean(body?.contentTaskId,128),artifactId=clean(body?.artifactId,128),connectionId=clean(body?.connectionId,128),title=clean(body?.title,160),slug=clean(body?.slug,180).toLowerCase(),excerpt=clean(body?.excerpt,500),scheduledRaw=clean(body?.scheduledAt,80),scheduledFor=scheduledRaw?Math.floor(new Date(scheduledRaw).getTime()/1000):null,now=Math.floor(Date.now()/1000);
 if(!contentTaskId||!artifactId||!connectionId||!title)return NextResponse.json({error:"请选择已审批内容和发布连接"},{status:400});if(slug&&!slugPattern.test(slug))return NextResponse.json({error:"Slug 只能包含小写字母、数字和连字符"},{status:400});if(scheduledFor!==null&&(!Number.isFinite(scheduledFor)||scheduledFor<=now))return NextResponse.json({error:"排期时间必须晚于当前时间"},{status:400});
 await ensurePublishSchema();const db=getDatabase(),candidate=db.prepare(`SELECT cr.execution_task_id AS taskId,cr.title,cr.checks_passed AS checksPassed,cr.checks_total AS checksTotal,r.status AS reviewStatus,a.id AS artifactId FROM content_runs cr JOIN seo_tasks r ON r.id='content-review-'||cr.execution_task_id JOIN execution_artifacts a ON a.organization_id=? AND a.project_id=cr.project_id AND a.task_id=cr.execution_task_id AND a.kind='content_draft' AND a.scan_state='clean' WHERE cr.project_id=? AND cr.execution_task_id=? AND a.id=? AND cr.status='completed'`).bind(user.organization.organizationId,id,contentTaskId,artifactId).first<{taskId:string;title:string;checksPassed:number;checksTotal:number;reviewStatus:string;artifactId:string}>();if(!candidate||candidate.reviewStatus!=="approved"||candidate.checksTotal<1||candidate.checksPassed!==candidate.checksTotal)return NextResponse.json({error:"内容尚未通过质量检查和人工审批"},{status:409});
 const connection=(await integrationRepository()).connection(user.organization.organizationId,id,connectionId);if(!connection||connection.providerId!=="wordpress"||connection.state!=="connected")return NextResponse.json({error:"请先连接可用的 WordPress 站点",code:"PUBLISH_CONNECTION_REQUIRED"},{status:409});if(!connection.grantedScopes.includes("content.write"))return NextResponse.json({error:"当前 WordPress 连接缺少发布权限，请重新连接",code:"PUBLISH_SCOPE_REQUIRED"},{status:409});
 const taskId=crypto.randomUUID(),description=`发布平台：wordpress；计划时间：${scheduledFor?new Date(scheduledFor*1000).toISOString():"审批后立即执行"}；Slug：${slug||"由 CMS 生成"}；内容任务：${contentTaskId}`;db.transaction(()=>{db.prepare(`INSERT INTO seo_tasks(id,project_id,type,title,description,priority,status,requires_approval,created_at,updated_at) VALUES (?,?,?,?,?,80,'proposed',1,?,?)`).bind(taskId,id,"publish_wordpress",title,description,now,now).run();db.prepare(`INSERT INTO publish_requests(id,organization_id,project_id,content_task_id,artifact_id,connection_id,provider,title,slug,excerpt,scheduled_for,status,verification_status,created_at,updated_at) VALUES (?,?,?,?,?,?,'wordpress',?,?,?,?, 'awaiting_approval','pending',?,?)`).bind(taskId,user.organization.organizationId,id,contentTaskId,artifactId,connectionId,title,slug,excerpt,scheduledFor,now,now).run();});await writeAudit("publish_approval_requested",user.id,request,JSON.stringify({projectId:id,taskId,contentTaskId,artifactId,connectionId,scheduledFor,creditsOnApproval:PUBLISH_CREDIT_COST}));return NextResponse.json({taskId,state:"awaiting_approval",creditsOnApproval:PUBLISH_CREDIT_COST},{status:202});
}
