-- description: Add versioned governed recommendations, evidence, changes, policy, decisions, execution, verification, and rollback
-- rollback: Export approval governance records before dropping additive approval schema tables
-- minimum-app-version: 0.1.0
CREATE SCHEMA IF NOT EXISTS approvals;
CREATE TABLE approvals.recommendations(id text PRIMARY KEY,organization_id text NOT NULL,project_id text NOT NULL,task_id text NOT NULL,agent_key text NOT NULL,agent_version text NOT NULL,capability text NOT NULL,state text NOT NULL CHECK(state IN('pending','approved','rejected','changes_requested','deferred','expired','executing','verified','failed','rolled_back')),current_version integer NOT NULL CHECK(current_version>0),risk text NOT NULL CHECK(risk IN('low','medium','high','critical')),confidence numeric NOT NULL CHECK(confidence BETWEEN 0 AND 1),estimated_cost numeric NOT NULL CHECK(estimated_cost>=0),expires_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(organization_id,project_id,id),FOREIGN KEY(organization_id,project_id)REFERENCES project_governance.projects(organization_id,id));
CREATE TABLE approvals.recommendation_versions(recommendation_id text NOT NULL REFERENCES approvals.recommendations(id),version integer NOT NULL CHECK(version>0),title text NOT NULL,impact_hypothesis text NOT NULL,payload jsonb NOT NULL CHECK(jsonb_typeof(payload)='object'),payload_hash text NOT NULL CHECK(payload_hash~'^[0-9a-f]{64}$'),created_by text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(recommendation_id,version));
CREATE TABLE approvals.evidence_refs(id text PRIMARY KEY,organization_id text NOT NULL,project_id text NOT NULL,recommendation_id text NOT NULL,kind text NOT NULL CHECK(kind IN('artifact','integration','public')),reference_id text NOT NULL,digest text NOT NULL CHECK(digest~'^[0-9a-f]{64}$'),captured_at timestamptz NOT NULL,expires_at timestamptz NOT NULL,provenance jsonb NOT NULL CHECK(jsonb_typeof(provenance)='object'),created_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(organization_id,project_id,recommendation_id)REFERENCES approvals.recommendations(organization_id,project_id,id));
CREATE TABLE approvals.change_sets(id text NOT NULL,recommendation_id text NOT NULL,version integer NOT NULL,target_type text NOT NULL,target_ref text NOT NULL,before_hash text NOT NULL,after_hash text NOT NULL,operations jsonb NOT NULL CHECK(jsonb_typeof(operations)='array'),rollback_required boolean NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id,version),FOREIGN KEY(recommendation_id,version)REFERENCES approvals.recommendation_versions(recommendation_id,version));
CREATE TABLE approvals.policies(id text NOT NULL,organization_id text NOT NULL,project_id text,capability text,environment text NOT NULL CHECK(environment IN('production','staging')),risk text NOT NULL CHECK(risk IN('low','medium','high','critical')),action text NOT NULL CHECK(action IN('allow','require_approval','deny')),version integer NOT NULL CHECK(version>0),active boolean NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id,version));
CREATE TABLE approvals.assignments(id text PRIMARY KEY,recommendation_id text NOT NULL REFERENCES approvals.recommendations(id),membership_id text NOT NULL,revision integer NOT NULL CHECK(revision>0),assigned_by text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE approvals.decisions(id text PRIMARY KEY,organization_id text NOT NULL,project_id text NOT NULL,recommendation_id text NOT NULL,recommendation_version integer NOT NULL,actor_id text NOT NULL,decision text NOT NULL CHECK(decision IN('approve','reject','request_changes','defer','expire')),reason text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(organization_id,project_id,id),FOREIGN KEY(organization_id,project_id,recommendation_id)REFERENCES approvals.recommendations(organization_id,project_id,id),FOREIGN KEY(recommendation_id,recommendation_version)REFERENCES approvals.recommendation_versions(recommendation_id,version));
CREATE TABLE approvals.executions(id text PRIMARY KEY,organization_id text NOT NULL,project_id text NOT NULL,recommendation_id text NOT NULL,decision_id text NOT NULL,task_id text NOT NULL,state text NOT NULL CHECK(state IN('queued','running','completed','failed')),idempotency_key text NOT NULL UNIQUE,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(organization_id,project_id,recommendation_id)REFERENCES approvals.recommendations(organization_id,project_id,id),FOREIGN KEY(organization_id,project_id,decision_id)REFERENCES approvals.decisions(organization_id,project_id,id));
CREATE TABLE approvals.verifications(id text PRIMARY KEY,execution_id text NOT NULL REFERENCES approvals.executions(id),state text NOT NULL CHECK(state IN('pending','passed','failed')),evidence_ref_id text REFERENCES approvals.evidence_refs(id),verified_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE approvals.rollbacks(id text PRIMARY KEY,execution_id text NOT NULL REFERENCES approvals.executions(id),state text NOT NULL CHECK(state IN('available','requested','running','completed','failed')),artifact_ref_id text,requested_by text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE FUNCTION approvals.reject_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'APPROVAL_RECORD_IMMUTABLE'; END $$;
CREATE TRIGGER approval_versions_no_mutation BEFORE UPDATE OR DELETE ON approvals.recommendation_versions FOR EACH ROW EXECUTE FUNCTION approvals.reject_immutable();
CREATE TRIGGER approval_evidence_no_mutation BEFORE UPDATE OR DELETE ON approvals.evidence_refs FOR EACH ROW EXECUTE FUNCTION approvals.reject_immutable();
CREATE TRIGGER approval_changes_no_mutation BEFORE UPDATE OR DELETE ON approvals.change_sets FOR EACH ROW EXECUTE FUNCTION approvals.reject_immutable();
CREATE TRIGGER approval_policies_no_mutation BEFORE UPDATE OR DELETE ON approvals.policies FOR EACH ROW EXECUTE FUNCTION approvals.reject_immutable();
CREATE TRIGGER approval_decisions_no_mutation BEFORE UPDATE OR DELETE ON approvals.decisions FOR EACH ROW EXECUTE FUNCTION approvals.reject_immutable();
CREATE INDEX approval_queue_idx ON approvals.recommendations(organization_id,project_id,state,risk,expires_at);
DO $p$ BEGIN
  IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname='oneshowseo_app') THEN
    GRANT USAGE ON SCHEMA approvals TO oneshowseo_app;
    GRANT SELECT,INSERT,UPDATE ON approvals.recommendations,approvals.assignments,approvals.executions,approvals.verifications,approvals.rollbacks TO oneshowseo_app;
    GRANT SELECT,INSERT ON approvals.recommendation_versions,approvals.evidence_refs,approvals.change_sets,approvals.policies,approvals.decisions TO oneshowseo_app;
  END IF;
  IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname='oneshowseo_worker') THEN
    GRANT USAGE ON SCHEMA approvals TO oneshowseo_worker;
    GRANT SELECT,INSERT,UPDATE ON approvals.executions,approvals.verifications,approvals.rollbacks TO oneshowseo_worker;
    GRANT SELECT ON approvals.recommendations,approvals.recommendation_versions,approvals.evidence_refs,approvals.change_sets,approvals.policies,approvals.assignments,approvals.decisions TO oneshowseo_worker;
  END IF;
END $p$;
