-- description: Add tenant-scoped provider connections, encrypted credential records, health, ownership, and immutable lifecycle audit
-- rollback: Export connection metadata and securely erase credential envelopes before dropping the additive integrations schema
-- minimum-app-version: 0.1.0
CREATE SCHEMA IF NOT EXISTS integrations;
CREATE TABLE integrations.connections(id text PRIMARY KEY,organization_id text NOT NULL,project_id text NOT NULL,provider_id text NOT NULL,auth_method text NOT NULL CHECK(auth_method IN('oauth2','api_key')),environment text NOT NULL CHECK(environment IN('production','staging')),state text NOT NULL CHECK(state IN('disconnected','connecting','connected','syncing','degraded','expired','permission_required','rate_limited','error')),granted_scopes jsonb NOT NULL CHECK(jsonb_typeof(granted_scopes)='array'),owner_account_id text NOT NULL,masked_hint text NOT NULL,health jsonb,last_synced_at timestamptz,revision bigint NOT NULL DEFAULT 1 CHECK(revision>0),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),disconnected_at timestamptz,deleted_at timestamptz,UNIQUE(organization_id,project_id,id),FOREIGN KEY(organization_id,project_id)REFERENCES project_governance.projects(organization_id,id));
CREATE TABLE integrations.credentials(id text PRIMARY KEY,connection_id text NOT NULL REFERENCES integrations.connections(id),record_version integer NOT NULL CHECK(record_version>0),encrypted_envelope text NOT NULL,key_version text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),revoked_at timestamptz,UNIQUE(connection_id,record_version));
CREATE TABLE integrations.oauth_states(id text PRIMARY KEY,organization_id text NOT NULL,project_id text NOT NULL,provider_id text NOT NULL,state_hash text NOT NULL UNIQUE,redirect_uri text NOT NULL,requested_scopes jsonb NOT NULL CHECK(jsonb_typeof(requested_scopes)='array'),expires_at timestamptz NOT NULL,consumed_at timestamptz,created_by text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(organization_id,project_id)REFERENCES project_governance.projects(organization_id,id));
CREATE TABLE integrations.audit_events(id text PRIMARY KEY,organization_id text NOT NULL,project_id text NOT NULL,actor_id text NOT NULL,action text NOT NULL,connection_id text NOT NULL,reason text NOT NULL,correlation_id text NOT NULL,metadata jsonb NOT NULL CHECK(jsonb_typeof(metadata)='object'),occurred_at timestamptz NOT NULL,FOREIGN KEY(organization_id,project_id,connection_id)REFERENCES integrations.connections(organization_id,project_id,id));
CREATE FUNCTION integrations.reject_audit_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'INTEGRATION_AUDIT_APPEND_ONLY';END $$;
CREATE TRIGGER integration_audit_no_mutation BEFORE UPDATE OR DELETE ON integrations.audit_events FOR EACH ROW EXECUTE FUNCTION integrations.reject_audit_mutation();
CREATE INDEX integration_connection_scope_idx ON integrations.connections(organization_id,project_id,state,provider_id);
CREATE INDEX integration_oauth_expiry_idx ON integrations.oauth_states(expires_at) WHERE consumed_at IS NULL;
DO $p$ BEGIN IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname='oneshowseo_app')THEN GRANT USAGE ON SCHEMA integrations TO oneshowseo_app;GRANT SELECT,INSERT,UPDATE ON integrations.connections,integrations.credentials,integrations.oauth_states TO oneshowseo_app;GRANT SELECT,INSERT ON integrations.audit_events TO oneshowseo_app;REVOKE DELETE ON ALL TABLES IN SCHEMA integrations FROM oneshowseo_app;END IF;IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname='oneshowseo_worker')THEN GRANT USAGE ON SCHEMA integrations TO oneshowseo_worker;GRANT SELECT,UPDATE ON integrations.connections TO oneshowseo_worker;GRANT SELECT ON integrations.credentials TO oneshowseo_worker;END IF;END $p$;
