-- description: Add signed event subscriptions, replay-safe inbox/outbox delivery, bounded attempts, quarantine, and inspection metadata
-- rollback: Pause subscriptions, drain or quarantine deliveries, export redacted evidence, then drop webhook delivery tables
-- minimum-app-version: 0.1.0
CREATE TABLE developer.webhook_subscriptions(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES identity.organizations(id) ON DELETE CASCADE,project_id text,endpoint_url text NOT NULL,event_types jsonb NOT NULL CHECK(jsonb_typeof(event_types)='array'),status text NOT NULL CHECK(status IN('paused','active','disabled')),signing_secret_envelope text NOT NULL,signing_key_version text NOT NULL,secret_prefix text NOT NULL,created_by_account_id text NOT NULL REFERENCES identity.accounts(id) ON DELETE RESTRICT,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz);
CREATE INDEX developer_webhook_subscription_org_idx ON developer.webhook_subscriptions(organization_id,status,created_at);
CREATE TABLE developer.webhook_outbox(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES identity.organizations(id) ON DELETE CASCADE,project_id text,event_id text NOT NULL,subscription_id text NOT NULL REFERENCES developer.webhook_subscriptions(id) ON DELETE RESTRICT,event_type text NOT NULL,payload jsonb NOT NULL CHECK(jsonb_typeof(payload)='object'),state text NOT NULL CHECK(state IN('pending','delivering','retrying','delivered','quarantined')),attempt_count integer NOT NULL DEFAULT 0 CHECK(attempt_count>=0),available_at timestamptz NOT NULL,delivered_at timestamptz,last_status integer,last_error_code text,correlation_id text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(subscription_id,event_id));
CREATE INDEX developer_webhook_outbox_due_idx ON developer.webhook_outbox(state,available_at,id);
CREATE TABLE developer.webhook_delivery_attempts(id text PRIMARY KEY,delivery_id text NOT NULL REFERENCES developer.webhook_outbox(id) ON DELETE RESTRICT,attempt_number integer NOT NULL CHECK(attempt_number>0),state text NOT NULL,status_code integer,error_code text,started_at timestamptz NOT NULL,finished_at timestamptz NOT NULL,correlation_id text NOT NULL,UNIQUE(delivery_id,attempt_number));
CREATE TABLE developer.webhook_inbox(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES identity.organizations(id) ON DELETE CASCADE,source text NOT NULL,event_id text NOT NULL,body_hash text NOT NULL CHECK(body_hash~'^[a-f0-9]{64}$'),received_at timestamptz NOT NULL DEFAULT now(),processed_at timestamptz,UNIQUE(source,event_id));
DO $p$ BEGIN IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname='oneshowseo_app')THEN GRANT SELECT,INSERT,UPDATE ON developer.webhook_subscriptions,developer.webhook_outbox,developer.webhook_inbox TO oneshowseo_app;GRANT SELECT,INSERT ON developer.webhook_delivery_attempts TO oneshowseo_app;REVOKE DELETE ON developer.webhook_subscriptions,developer.webhook_outbox,developer.webhook_delivery_attempts,developer.webhook_inbox FROM oneshowseo_app;END IF;IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname='oneshowseo_worker')THEN GRANT USAGE ON SCHEMA developer TO oneshowseo_worker;GRANT SELECT,UPDATE ON developer.webhook_subscriptions,developer.webhook_outbox TO oneshowseo_worker;GRANT SELECT,INSERT ON developer.webhook_delivery_attempts TO oneshowseo_worker;END IF;END $p$;
