-- description: Separate platform operator roles, scoped assignments, reason-required elevated actions, and immutable audit evidence
-- rollback: Disable elevated operator actions, export immutable audit evidence, revoke assignments, then drop the added tables
-- minimum-app-version: 0.1.0
CREATE TABLE operations.operator_assignments(id text PRIMARY KEY,account_id text NOT NULL REFERENCES identity.accounts(id) ON DELETE CASCADE,role text NOT NULL CHECK(role IN('platform_admin','support','finance','operations','security')),organization_scopes jsonb NOT NULL CHECK(jsonb_typeof(organization_scopes) IN('string','array')),project_scopes jsonb NOT NULL CHECK(jsonb_typeof(project_scopes) IN('string','array')),active boolean NOT NULL DEFAULT true,granted_by_account_id text NOT NULL REFERENCES identity.accounts(id) ON DELETE RESTRICT,granted_at timestamptz NOT NULL DEFAULT now(),revoked_at timestamptz);
CREATE INDEX operator_assignments_account_idx ON operations.operator_assignments(account_id,active,role);
CREATE TABLE operations.elevated_actions(id text PRIMARY KEY,actor_account_id text NOT NULL REFERENCES identity.accounts(id) ON DELETE RESTRICT,actor_role text NOT NULL,permission text NOT NULL,organization_id text REFERENCES identity.organizations(id) ON DELETE RESTRICT,project_id text,target_type text NOT NULL,target_id text,reason text,outcome text NOT NULL CHECK(outcome IN('success','denied','failed')),correlation_id text NOT NULL,metadata jsonb NOT NULL CHECK(jsonb_typeof(metadata)='object'),occurred_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX elevated_actions_scope_idx ON operations.elevated_actions(organization_id,occurred_at DESC,id);
CREATE INDEX elevated_actions_correlation_idx ON operations.elevated_actions(correlation_id,occurred_at,id);
CREATE OR REPLACE FUNCTION operations.reject_elevated_action_mutation()RETURNS trigger LANGUAGE plpgsql AS $$BEGIN RAISE EXCEPTION 'ELEVATED_ACTIONS_APPEND_ONLY';END$$;
CREATE TRIGGER elevated_actions_no_update BEFORE UPDATE OR DELETE ON operations.elevated_actions FOR EACH ROW EXECUTE FUNCTION operations.reject_elevated_action_mutation();
DO $p$ BEGIN IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname='oneshowseo_app')THEN GRANT SELECT ON operations.operator_assignments,operations.elevated_actions TO oneshowseo_app;GRANT INSERT ON operations.elevated_actions TO oneshowseo_app;REVOKE UPDATE,DELETE ON operations.elevated_actions FROM oneshowseo_app;END IF;END $p$;
