-- description: Add tenant retention, legal hold, export, credential erasure, artifact expiry, and staged deletion workflows
-- rollback: Disable privacy workers, preserve requests and audit evidence, export active holds, then drop added tables only after policy approval
-- minimum-app-version: 0.1.0
CREATE TABLE operations.retention_policies(organization_id text PRIMARY KEY REFERENCES identity.organizations(id) ON DELETE RESTRICT,default_days integer NOT NULL CHECK(default_days BETWEEN 1 AND 3650),artifact_days integer NOT NULL CHECK(artifact_days BETWEEN 1 AND 3650),audit_days integer NOT NULL CHECK(audit_days BETWEEN 1 AND 3650),legal_hold boolean NOT NULL DEFAULT false,legal_hold_reason text,updated_by_account_id text NOT NULL REFERENCES identity.accounts(id) ON DELETE RESTRICT,updated_at timestamptz NOT NULL DEFAULT now(),CHECK(NOT legal_hold OR length(legal_hold_reason)>=8));
CREATE TABLE operations.privacy_requests(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES identity.organizations(id) ON DELETE RESTRICT,account_id text NOT NULL REFERENCES identity.accounts(id) ON DELETE RESTRICT,project_id text,type text NOT NULL CHECK(type IN('organization_export','credential_erasure','project_deletion','account_deletion')),state text NOT NULL CHECK(state IN('requested','awaiting_approval','processing','completed','denied','failed')),reason text NOT NULL,approval_reference text,artifact_id text,correlation_id text NOT NULL,requested_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz);CREATE INDEX privacy_request_scope_idx ON operations.privacy_requests(organization_id,state,requested_at DESC);
CREATE TABLE operations.privacy_exports(id text PRIMARY KEY,request_id text NOT NULL UNIQUE REFERENCES operations.privacy_requests(id) ON DELETE RESTRICT,organization_id text NOT NULL REFERENCES identity.organizations(id) ON DELETE RESTRICT,object_key text NOT NULL UNIQUE,sha256 text NOT NULL CHECK(sha256~'^[a-f0-9]{64}$'),size_bytes bigint NOT NULL CHECK(size_bytes>=0),expires_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE operations.artifact_expirations(artifact_id text PRIMARY KEY,organization_id text NOT NULL REFERENCES identity.organizations(id) ON DELETE RESTRICT,expired_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE operations.privacy_audit(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES identity.organizations(id) ON DELETE RESTRICT,action text NOT NULL,target_id text,correlation_id text NOT NULL,occurred_at timestamptz NOT NULL DEFAULT now());CREATE TRIGGER privacy_audit_no_mutation BEFORE UPDATE OR DELETE ON operations.privacy_audit FOR EACH ROW EXECUTE FUNCTION operations.reject_elevated_action_mutation();
DO $p$ BEGIN IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname='oneshowseo_app')THEN GRANT SELECT,INSERT,UPDATE ON operations.retention_policies,operations.privacy_requests TO oneshowseo_app;GRANT SELECT,INSERT ON operations.privacy_exports,operations.artifact_expirations,operations.privacy_audit TO oneshowseo_app;REVOKE DELETE ON operations.retention_policies,operations.privacy_requests,operations.privacy_exports,operations.artifact_expirations,operations.privacy_audit FROM oneshowseo_app;REVOKE UPDATE ON operations.privacy_exports,operations.artifact_expirations,operations.privacy_audit FROM oneshowseo_app;END IF;END $p$;
