-- description: Add durable content opportunities, briefs, and scheduling plans without triggering content generation
-- rollback: Stop new planning writes, retain briefs and schedules for export, then remove tables after product-owner approval
-- minimum-app-version: 0.1.0

SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';

CREATE TABLE agents.content_opportunity_states (project_id text NOT NULL REFERENCES project_governance.projects(id) ON DELETE CASCADE,opportunity_id text NOT NULL,organization_id text NOT NULL REFERENCES identity.organizations(id) ON DELETE CASCADE,status text NOT NULL DEFAULT 'NEW' CHECK(status IN('NEW','PLANNED','IGNORED','CONVERTED')),updated_by_account_id text NOT NULL REFERENCES identity.accounts(id) ON DELETE RESTRICT,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(project_id,opportunity_id));
CREATE INDEX content_opportunity_states_scope_idx ON agents.content_opportunity_states(organization_id,project_id,status,updated_at DESC);
CREATE TABLE agents.content_briefs (id text PRIMARY KEY,organization_id text NOT NULL REFERENCES identity.organizations(id) ON DELETE CASCADE,project_id text NOT NULL REFERENCES project_governance.projects(id) ON DELETE CASCADE,opportunity_id text,topic text NOT NULL,primary_keyword text NOT NULL,secondary_keywords jsonb NOT NULL DEFAULT '[]',audience text NOT NULL,search_intent text NOT NULL,content_goal text NOT NULL,content_type text NOT NULL,suggested_word_count integer NOT NULL CHECK(suggested_word_count BETWEEN 100 AND 20000),outline jsonb NOT NULL DEFAULT '[]',target_platforms jsonb NOT NULL DEFAULT '[]',status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','READY','GENERATING','REVIEW','APPROVED')),created_by_account_id text NOT NULL REFERENCES identity.accounts(id) ON DELETE RESTRICT,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX content_briefs_scope_idx ON agents.content_briefs(organization_id,project_id,status,updated_at DESC);
CREATE TABLE agents.content_plans (id text PRIMARY KEY,organization_id text NOT NULL REFERENCES identity.organizations(id) ON DELETE CASCADE,project_id text NOT NULL REFERENCES project_governance.projects(id) ON DELETE CASCADE,brief_id text NOT NULL REFERENCES agents.content_briefs(id) ON DELETE CASCADE,scheduled_at timestamptz,priority integer NOT NULL DEFAULT 50 CHECK(priority BETWEEN 0 AND 100),status text NOT NULL DEFAULT 'UNSCHEDULED' CHECK(status IN('UNSCHEDULED','SCHEDULED','IN_PROGRESS','PUBLISHED','FAILED')),owner_id text NOT NULL REFERENCES identity.accounts(id) ON DELETE RESTRICT,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(project_id,brief_id));
CREATE INDEX content_plans_calendar_idx ON agents.content_plans(organization_id,project_id,scheduled_at,status);

DO $permissions$ BEGIN IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='oneshowseo_app') THEN GRANT SELECT,INSERT,UPDATE ON agents.content_opportunity_states,agents.content_briefs,agents.content_plans TO oneshowseo_app; REVOKE DELETE ON agents.content_opportunity_states,agents.content_briefs,agents.content_plans FROM oneshowseo_app; END IF; END $permissions$;
