import { NextResponse } from "next/server";
import { getCurrentUser,writeAudit } from "../../../../../lib/auth";
import { ensureProductSchema,ownedProject,pageLimit } from "../../../../../lib/product";
import { commerceService,commercialSubject,ensureBillingSchema } from "../../../../../lib/billing";
import { atomicTaskCreationService } from "../../../../../lib/execution";
import { ensureGeoSchema,geoDashboard,GEO_CREDIT_COST } from "../../../../../lib/geo-execution";
import { permissions,type OrganizationRoleKey } from "../../../../../platform/modules/identity/authorization";
import { CommerceError } from "../../../../../platform/modules/commerce/service";
import { TaskCreationError } from "../../../../../platform/modules/execution/task-creation";

export async function GET(_:Request,context:{params:Promise<{id:string}>}){const user=await getCurrentUser();if(!user)return NextResponse.json({error:"请先登录"},{status:401});await ensureProductSchema();const{id}=await context.params;if(!await ownedProject(user.organization.organizationId,id))return NextResponse.json({error:"项目不存在"},{status:404});await ensureGeoSchema();return NextResponse.json({...geoDashboard(user.organization.organizationId,id),creditCost:GEO_CREDIT_COST,capabilities:{onsiteEvidence:true,externalVisibilityMonitoring:false}},{headers:{"cache-control":"private, no-store"}})}
export async function POST(request:Request,context:{params:Promise<{id:string}>}){const user=await getCurrentUser();if(!user)return NextResponse.json({error:"请先登录"},{status:401});await ensureProductSchema();const{id}=await context.params,project=await ownedProject(user.organization.organizationId,id);if(!project)return NextResponse.json({error:"项目不存在"},{status:404});if(project.status!=="active")return NextResponse.json({error:"项目不可用"},{status:409});try{await ensureBillingSchema();commerceService().authorizeAccess(commercialSubject(user));const requested=request.headers.get("idempotency-key")?.trim(),idempotencyKey=requested&&/^[A-Za-z0-9][A-Za-z0-9._:-]{15,127}$/.test(requested)?requested:`geo:${id}:${crypto.randomUUID()}`,correlationId=`geo:${crypto.randomUUID()}`,maximumPages=Math.min(pageLimit(user),30),created=(await atomicTaskCreationService()).create({activeOrganizationId:user.organization.organizationId,organizationId:user.organization.organizationId,projectId:id,requestedByAccountId:user.id,role:user.organization.roleKey as OrganizationRoleKey,permission:permissions.auditsRun,subject:commercialSubject(user),triggerType:"manual",taskType:"geo_agent",capability:"geo.audit",input:{projectId:id,siteUrl:project.siteUrl,maximumPages,title:`${project.name} GEO 就绪度扫描`,description:`检查 ${project.host} 的机器可读性、答案结构、权威信号与 AI 爬虫策略`},locale:project.language.startsWith("en")?"en":"zh-CN",idempotencyKey,correlationId,entitlements:[],creditCost:GEO_CREDIT_COST,queue:"agents",jobType:"geo.audit",priority:70,maxAttempts:3,timeoutSeconds:900});await writeAudit("geo_run_queued",user.id,request,JSON.stringify({projectId:id,taskId:created.task.id,creditsReserved:GEO_CREDIT_COST,agent:"geo.agent@1.0.0"}));return NextResponse.json({taskId:created.task.id,state:created.task.state,creditsReserved:GEO_CREDIT_COST,duplicate:created.duplicate},{status:202})}catch(error){if(error instanceof CommerceError||error instanceof TaskCreationError)return NextResponse.json({error:error.message,code:error.code},{status:error.status});console.error("Failed to queue GEO Agent",error);return NextResponse.json({error:"GEO 扫描创建失败，请稍后重试"},{status:500})}}
