import { NextResponse } from "next/server";
import { getCurrentUser, writeAudit } from "../../../../lib/auth";
import { notificationService } from "../../../../lib/notifications";
import { notificationTemplates, NotificationError, type NotificationLocale } from "../../../../platform/modules/notifications";

const noStore={"cache-control":"private, no-store"};
function failure(error:unknown){if(error instanceof NotificationError)return NextResponse.json({error:error.message,code:error.code},{status:error.status,headers:noStore});if(error instanceof Error&&error.message==="NOTIFICATION_RECOVERY_NOT_CONFIGURED")return NextResponse.json({error:"通知恢复服务暂不可用",code:error.message},{status:503,headers:noStore});throw error;}
export async function GET(){const user=await getCurrentUser();if(!user)return NextResponse.json({error:"请先登录"},{status:401,headers:noStore});try{const service=await notificationService();return NextResponse.json({preferences:Object.keys(notificationTemplates).map(notificationType=>service.preference({organizationId:user.organization.organizationId,accountId:user.id,notificationType}))},{headers:noStore});}catch(error){return failure(error);}}
export async function PATCH(request:Request){const user=await getCurrentUser();if(!user)return NextResponse.json({error:"请先登录"},{status:401,headers:noStore});try{const body=await request.json().catch(()=>null) as Record<string,unknown>|null;if(!body||typeof body.notificationType!=="string"||typeof body.inAppEnabled!=="boolean"||typeof body.emailEnabled!=="boolean"||(body.locale!=="zh-CN"&&body.locale!=="en")||!Number.isInteger(body.version))throw new NotificationError("INVALID_REQUEST","通知偏好参数无效");const preference=(await notificationService()).updatePreference({organizationId:user.organization.organizationId,accountId:user.id,notificationType:body.notificationType,inAppEnabled:body.inAppEnabled,emailEnabled:body.emailEnabled,locale:body.locale as NotificationLocale,expectedVersion:Number(body.version)});await writeAudit("notification_preference_updated",user.id,request,JSON.stringify({organizationId:user.organization.organizationId,notificationType:body.notificationType,inAppEnabled:body.inAppEnabled,emailEnabled:body.emailEnabled,locale:body.locale,version:preference.version}));return NextResponse.json({preference},{headers:noStore});}catch(error){return failure(error);}}
