"use client";
import { useCallback,useEffect,useState } from "react";
import { ArrowRight,Brain,CaretRight,ChartLineUp,CheckCircle,ClockCountdown,Database,FileText,Info,MagnifyingGlass,Play,PlugsConnected,SealCheck,Sparkle,Target,TrendDown,TrendUp,WarningCircle } from "@phosphor-icons/react";
import { Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis } from "recharts";

type Metrics={healthScore:number|null;healthDelta:number|null;openIssues:number|null;issueDelta:number|null;opportunities:number;contentDrafts:number;published:number;geoScore:number|null;openTasks:number};
type Coverage={audit:boolean;research:boolean;content:boolean;publish:boolean;geo:boolean;searchConsole:boolean;ga4:boolean;aiVisibility:boolean};
type Insight={id:string;kind:"growth"|"risk"|"coverage"|"workflow";title:string;summary:string;action:string;priority:number;confidence:number;delta:number|null;sourceRefs:string[];digest:string;createdAt:number};
export type AnalyticsData={creditCost:number;capabilities:{internalEvidence:boolean;searchPerformanceSnapshot:boolean;analyticsSnapshot:boolean;aiVisibilitySnapshot:boolean};latestRun:null|{id:string;taskId:string;status:string;lookbackDays:number;evidenceSources:number;insights:number;recommendations:number;metrics:Metrics;coverage:Coverage;auditHistory:Array<{capturedAt:number;score:number;issues:number}>;degradedSources:string[];agentVersion:string;startedAt:number;completedAt:number|null;error:string|null};insights:Insight[];history:Array<{id:string;status:string;metrics:Metrics;coverage:Coverage;completedAt:number}>;external:{searchConsole:boolean;ga4:boolean;searchConsoleSnapshot:boolean;ga4Snapshot:boolean;aiVisibilitySnapshot:boolean}};
async function waitForTask(taskId:string){const started=Date.now();while(Date.now()-started<8*60*1000){const response=await fetch(`/api/tasks?taskId=${encodeURIComponent(taskId)}`,{cache:"no-store"}),payload=await response.json();if(!response.ok)throw new Error(payload.error||"任务状态读取失败");if(["completed","failed","cancelled","quarantined"].includes(payload.task.state))return payload.task;await new Promise(resolve=>setTimeout(resolve,1200))}throw new Error("分析仍在后台运行，请稍后查看")}
const coverageLabels:Record<keyof Coverage,string>={audit:"SEO 审计",research:"研究机会",content:"内容生产",publish:"发布验证",geo:"GEO 就绪度",searchConsole:"GSC 表现快照",ga4:"GA4 行为快照",aiVisibility:"AI 可见性快照"};

export default function AnalyticsAgentControl({project,navigate,refresh}:{project:{id:string;host:string};navigate:(value:string)=>void;refresh:()=>Promise<void>}){
 const [data,setData]=useState<AnalyticsData|null>(null),[running,setRunning]=useState(false),[error,setError]=useState(""),[tab,setTab]=useState<"all"|"action"|"growth">("action");
 const load=useCallback(async()=>{const response=await fetch(`/api/projects/${project.id}/analytics`,{cache:"no-store"}),payload=await response.json();if(!response.ok)throw new Error(payload.error||"分析数据读取失败");setData(payload)},[project.id]);useEffect(()=>{const timer=setTimeout(()=>load().catch(caught=>setError(caught instanceof Error?caught.message:"分析数据读取失败")),0);return()=>clearTimeout(timer)},[load]);
 const run=async()=>{setRunning(true);setError("");try{const response=await fetch(`/api/projects/${project.id}/analytics`,{method:"POST"}),payload=await response.json();if(!response.ok)throw new Error(payload.error||"分析任务创建失败");const task=await waitForTask(payload.taskId);await Promise.all([load(),refresh()]);if(task.state!=="completed")throw new Error("分析未完成，预留 Credits 已释放")}catch(caught){setError(caught instanceof Error?caught.message:"分析失败")}finally{setRunning(false)}};
 const runData=data?.latestRun,m=runData?.metrics,coverage=runData?.coverage,insights=data?.insights||[],visible=insights.filter(item=>tab==="all"||tab==="growth"&&item.kind==="growth"||tab==="action"&&item.kind!=="growth"),priority=insights.find(item=>item.kind!=="growth"),last=runData?.completedAt?new Date(runData.completedAt*1000).toLocaleString("zh-CN"):"尚未生成";const delta=(value:number|null|undefined)=>value===null||value===undefined?"—":`${value>0?"+":""}${value}`;
 const cards=[[SealCheck,"SEO 健康分",m?.healthScore??"—",m?.healthDelta,coverage?.audit,"audit"],[WarningCircle,"开放问题",m?.openIssues??"—",m?.issueDelta,coverage?.audit,"issues"],[MagnifyingGlass,"研究机会",m?.opportunities??0,null,coverage?.research,"research"],[FileText,"内容记录",m?.contentDrafts??0,null,coverage?.content,"content"],[CheckCircle,"已验证发布",m?.published??0,null,coverage?.publish,"publish"],[Sparkle,"GEO 就绪分",m?.geoScore??"—",null,coverage?.geo,"geo"]] as const;
 return <div className="analytics-v2-page" key={runData?.id||"analytics-empty"}><header className="analytics-v2-header"><div><p><Brain/> AI Agents <CaretRight/> <strong>Analytics Agent</strong></p><div><h1>Analytics Agent</h1><span className={running?"running":runData?"ready":"not-run"}>{running?<ClockCountdown/>:runData?<CheckCircle weight="fill"/>:<Info/>}{running?"分析中":runData?"快照已生成":"等待首次分析"}</span></div><small>汇总可追溯证据、识别变化并把结果转化为下一步行动。</small></div><aside><span>最近分析：{last}</span><button onClick={()=>navigate("数据连接")}><PlugsConnected/>数据覆盖</button><button className="primary" onClick={run} disabled={running}><Play weight="fill"/>{running?"正在生成…":"生成分析报告"}</button></aside></header>
 {error&&<div className="analytics-v2-alert" role="alert"><WarningCircle/>{error}</div>}
 <section className="analytics-v2-truth"><Info weight="fill"/><div><strong>站内执行结果 ≠ 流量与收入增长</strong><p>当前可验证审计、研究、内容、发布、GEO 和任务结果。只有取得 GSC、GA4 或 AI 可见性快照后，才会展示点击、会话、转化、收入和 AI 引荐趋势。</p></div><button onClick={()=>navigate("数据连接")}>管理数据源 <ArrowRight/></button></section>
 <section className="analytics-v2-hero"><article><small>DECISION SUMMARY</small><h2>{!runData?"建立第一份可追溯的增长分析基线":priority?.title||"当前证据范围内未发现新的高优先级风险"}</h2><p>{!runData?"Analytics Agent 会读取现有 Agent 与任务记录，生成变化判断、建议和报告，不会编造尚未接入的商业指标。":priority?.summary||`${runData.evidenceSources} 类证据已纳入本次分析。`}</p><div><span><strong>{runData?.evidenceSources||0}</strong> 个证据来源</span><span><strong>{runData?.insights||0}</strong> 条分析洞察</span><span><strong>{runData?.recommendations||0}</strong> 项建议行动</span></div></article><aside><small>分析成本</small><strong>{data?.creditCost||3} Credits</strong><p>只读分析，不会自动修改网站。</p><button onClick={run} disabled={running}>{runData?"更新分析快照":"建立分析基线"}<ArrowRight/></button></aside></section>
 <section className="analytics-v2-metrics">{cards.map(([Icon,label,value,change,ready,key])=><article key={key} className={ready?"ready":"empty"}><span><Icon weight="duotone"/></span><div><small>{label}</small><strong>{value}{typeof value==="number"&&key==="geo"&&<em>/100</em>}</strong><p>{ready?change===null?"真实持久化记录":<>{Number(change)>=0?<TrendUp/>:<TrendDown/>}{delta(change)} 较上一快照</>:"暂无可验证快照"}</p></div></article>)}</section>
 <div className="analytics-v2-layout"><main><section className="analytics-v2-panel analytics-v2-workflow"><header><div><span>EVIDENCE WORKFLOW</span><h2>分析闭环</h2></div><small>每个结论都保留来源</small></header><div>{[[Database,"读取证据",Boolean(runData)],[ChartLineUp,"检测变化",Boolean(runData)],[Sparkle,"形成洞察",Boolean(runData)],[Target,"生成行动",Boolean(runData)],[FileText,"报告归档",Boolean(runData)]].map(([Icon,label,done],index)=><article className={done?"done":""} key={label as string}><span><Icon/></span><strong>{label as string}</strong><small>{done?"已完成":"等待运行"}</small>{index<4&&<CaretRight/>}</article>)}</div></section>
 <section className="analytics-v2-panel analytics-v2-trend"><header><div><span>VERIFIED CHANGE</span><h2>SEO 健康与问题趋势</h2><p>仅使用真实审计快照；没有历史时只建立基线。</p></div></header>{runData?.auditHistory?.length?<div><ResponsiveContainer><LineChart data={runData.auditHistory.map(item=>({...item,date:new Date(item.capturedAt*1000).toLocaleDateString("zh-CN",{month:"numeric",day:"numeric"})}))}><XAxis dataKey="date"/><YAxis yAxisId="score" domain={[0,100]}/><YAxis yAxisId="issues" orientation="right"/><Tooltip/><Line yAxisId="score" type="monotone" dataKey="score" name="健康分" stroke="#5c50ee" strokeWidth={3}/><Line yAxisId="issues" type="monotone" dataKey="issues" name="开放问题" stroke="#f29a38" strokeWidth={2}/></LineChart></ResponsiveContainer></div>:<div className="analytics-v2-empty"><ChartLineUp/><strong>尚无可比较的审计快照</strong><p>先运行 SEO Audit Agent，再生成分析报告。</p><button onClick={()=>navigate("网站诊断")}>前往 SEO 审计</button></div>}</section>
 <section className="analytics-v2-panel analytics-v2-insights"><header><div><span>ATTRIBUTABLE INSIGHTS</span><h2>洞察与下一步行动</h2><p>增长、风险、覆盖缺口和工作流阻塞分开呈现。</p></div><nav>{[["action","待行动"],["growth","正向变化"],["all","全部"]].map(([value,label])=><button className={tab===value?"active":""} onClick={()=>setTab(value as typeof tab)} key={value}>{label}</button>)}</nav></header>{visible.length?<div>{visible.map(item=><article key={item.id}><span className={item.kind}>{item.kind==="growth"?<TrendUp/>:item.kind==="risk"?<WarningCircle/>:item.kind==="workflow"?<Target/>:<Database/>}</span><div><strong>{item.title}</strong><p>{item.summary}</p><small>证据：{item.sourceRefs.join(" · ")} · 置信度 {Math.round(item.confidence*100)}%</small></div><em>{item.priority} 优先级</em><button onClick={()=>item.kind==="coverage"?navigate("数据连接"):navigate("任务中心")}>{item.action}<ArrowRight/></button></article>)}</div>:<div className="analytics-v2-empty"><MagnifyingGlass/><strong>{runData?"当前筛选没有洞察":"尚无分析洞察"}</strong><p>{runData?"切换筛选查看其他判断。":"生成首次分析报告后展示。"}</p></div>}</section></main>
 <aside><section className="analytics-v2-next"><small>AI-RECOMMENDED NEXT STEP</small><span><Sparkle weight="fill"/></span><h2>{priority?.title||"建立分析基线"}</h2><p>{priority?.action||"汇总当前项目的站内 Agent 结果，形成第一份可复查报告。"}</p><dl><div><dt>网站修改</dt><dd>不会自动执行</dd></div><div><dt>建议状态</dt><dd>进入任务中心</dd></div><div><dt>外部指标</dt><dd>缺失时不估算</dd></div></dl><button onClick={priority?()=>priority.kind==="coverage"?navigate("数据连接"):navigate("任务中心"):run}>{priority?"处理建议":"生成分析报告"}<ArrowRight/></button></section>
 <section className="analytics-v2-panel analytics-v2-coverage"><header><h2>数据覆盖</h2><p>“已连接”与“已有快照”分别判断</p></header>{(Object.keys(coverageLabels) as Array<keyof Coverage>).map(key=>{const ready=Boolean(coverage?.[key]),configured=key==="searchConsole"?data?.external.searchConsole:key==="ga4"?data?.external.ga4:false;return <article key={key}><span className={ready?"ready":configured?"configured":"missing"}>{ready?<CheckCircle weight="fill"/>:configured?<ClockCountdown/>:<WarningCircle/>}</span><div><strong>{coverageLabels[key]}</strong><small>{ready?"已有可追溯快照":configured?"已配置，等待数据快照":"尚未接入或暂无记录"}</small></div></article>})}<button onClick={()=>navigate("数据连接")}>管理数据连接 <ArrowRight/></button></section>
 <section className="analytics-v2-panel analytics-v2-report"><FileText/><div><strong>可追溯分析报告</strong><p>{runData?"最新报告已由 Worker 生成并归档。":"运行后生成 Markdown 报告资产。"}</p></div><button onClick={()=>navigate("报告")}>查看报告</button></section></aside></div></div>
}
