"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { ArrowRight,ArrowsClockwise,BracketsCurly,CheckCircle,ClipboardText,Code,Copy,Eye,EyeSlash,Gauge,Globe,Key,Lightning,LockKey,Plus,ShieldCheck,Trash,WarningCircle,WebhooksLogo,X } from "@phosphor-icons/react";

type ApiKey={id:string;name:string;keyPrefix:string;status:"active"|"revoked";scopes:string[];projectIds:"*"|string[];expiresAt:number|null;lastUsedAt:number|null;createdAt:number;revokedAt:number|null;createdByAccountId:string;rateLimitPolicy:{requestsPerMinute:number;monthlyRequests:number;costUnitsPerMinute:number}};
type Webhook={id:string;url:string;eventTypes:string[];status:string;projectId:string|null;secretPrefix:string;createdAt:number;updatedAt:number};
type Delivery={id:string;subscriptionId:string;eventId:string;eventType:string;state:string;attemptCount:number;availableAt:number;deliveredAt:number|null;lastStatus:number|null;lastErrorCode:string|null;createdAt:number};
type ApiData={access:boolean;plan:{id:string;name:string};limits:{requests:number;activeKeys:number};usage:{used:number;periodStart:number;periodEnd:number};keys:ApiKey[];webhooks:Webhook[];deliveries:Delivery[];recent:Array<{route:string;method:string;statusCode:number;createdAt:number}>;capabilities:{restApi:boolean;webhookDelivery:boolean;mcpServer:boolean}};
const tabs=["总览","API 参考","API Keys","Webhooks","MCP Server","速率限制"];
const endpoints=[
 {method:"GET",path:"/projects",description:"列出当前账户的全部项目",live:true},
 {method:"GET",path:"/projects/{id}",description:"读取一个项目的基本信息",live:true},
 {method:"POST",path:"/projects/{id}/audit",description:"启动项目 SEO 审计",live:false},
 {method:"GET",path:"/keywords",description:"读取项目关键词与机会池",live:false},
 {method:"POST",path:"/content/generate",description:"创建 AI 内容草稿",live:false},
 {method:"GET",path:"/rank-tracking",description:"读取排名跟踪数据",live:false},
];

export default function ApiMcpCenter({navigate}:{navigate:(value:string)=>void}){
 const [data,setData]=useState<ApiData|null>(null),[tab,setTab]=useState("总览"),[language,setLanguage]=useState("cURL"),[creating,setCreating]=useState(false),[name,setName]=useState("Production"),[revealed,setRevealed]=useState(""),[showKey,setShowKey]=useState(false),[notice,setNotice]=useState(""),[error,setError]=useState(""),[webhookUrl,setWebhookUrl]=useState(""),[webhookSecret,setWebhookSecret]=useState("");
 const [now]=useState(()=>Math.floor(Date.now()/1000));
 const load=useCallback(async()=>{const response=await fetch("/api/api-access",{cache:"no-store"});const json=await response.json();if(!response.ok)throw new Error(json.error);setData(json)},[]);
 useEffect(()=>{const timer=setTimeout(()=>load().catch(error=>setError(error.message)),0);return()=>clearTimeout(timer)},[load]);
 const origin=typeof window==="undefined"?"https://oneshowseo.com":window.location.origin;
 const example=useMemo(()=>({
  cURL:`curl --request GET \\\n+  --url ${origin}/api/v1/projects \\\n+  --header 'Authorization: Bearer YOUR_API_KEY' \\\n+  --header 'Accept: application/json'`,
  JavaScript:`const response = await fetch("${origin}/api/v1/projects", {\n  headers: { Authorization: "Bearer YOUR_API_KEY" }\n});\nconst { data } = await response.json();`,
  Python:`import requests\n\nresponse = requests.get(\n    "${origin}/api/v1/projects",\n    headers={"Authorization": "Bearer YOUR_API_KEY"}\n)\nprint(response.json())`,
  PHP:`$response = file_get_contents(\n  "${origin}/api/v1/projects",\n  false,\n  stream_context_create(["http" => ["header" => "Authorization: Bearer YOUR_API_KEY"]])\n);`
 })[language as "cURL"], [language,origin]);
 const activeKeys=data?.keys.filter(key=>key.status==="active"&&(!key.expiresAt||key.expiresAt>now))||[];
 const copy=async(value:string,message="已复制")=>{await navigator.clipboard.writeText(value);setNotice(message);setTimeout(()=>setNotice(""),1800)};
 const createKey=async(event:React.FormEvent)=>{event.preventDefault();setError("");const response=await fetch("/api/api-access",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"create_key",name})});const json=await response.json();if(!response.ok)return setError(json.error);setCreating(false);setRevealed(json.plainTextKey);setShowKey(true);await load()};
 const revoke=async(id:string)=>{if(!confirm("撤销后将立即失效且无法恢复，确认继续？"))return;const response=await fetch("/api/api-access",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"revoke_key",id})});const json=await response.json();if(!response.ok)return setError(json.error);setNotice("API Key 已撤销");await load()};
 const rotate=async(id:string)=>{if(!confirm("轮换会立即撤销旧密钥，确认已准备更新调用方？"))return;const response=await fetch("/api/api-access",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"rotate_key",id})}),json=await response.json();if(!response.ok)return setError(json.error);setRevealed(json.plainTextKey);setShowKey(true);setNotice("API Key 已轮换");await load()};
 const createWebhook=async(event:React.FormEvent)=>{event.preventDefault();const response=await fetch("/api/api-access",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"create_webhook",url:webhookUrl,events:["task.completed","task.failed","approval.required"]})}),json=await response.json();if(!response.ok)return setError(json.error);setWebhookUrl("");setWebhookSecret(json.signingSecret);setNotice("Webhook 订阅已创建");await load()};
 const webhookAction=async(action:"delete_webhook"|"retry_webhook",id:string)=>{const response=await fetch("/api/api-access",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,id})}),json=await response.json();if(!response.ok)return setError(json.error);setNotice(action==="delete_webhook"?"Webhook 已停用":"投递已重新排队");await load()};
 if(!data)return <div className="api-center api-loading"><ArrowsClockwise className="spin"/>{error||"正在读取 API 配置…"}</div>;
 const pct=data.limits.requests?Math.min(100,Math.round(data.usage.used/data.limits.requests*100)):0;
 return <div className="api-center">
  <header className="api-header"><div><h1>API & MCP</h1><p>将 OneShowSEO 接入你的工作流，安全访问真实 SEO 数据与自动化能力。</p></div><aside><button>快捷操作</button><i>Y</i></aside></header>
  <nav className="api-tabs">{tabs.map(item=><button key={item} className={tab===item?"active":""} onClick={()=>setTab(item)}>{item}</button>)}</nav>
  {error&&<div className="api-alert" role="alert"><WarningCircle/>{error}<button aria-label="关闭错误提示" onClick={()=>setError("")}><X/></button></div>}
  {tab==="总览"&&<div className="api-layout"><main>
   <section className="panel api-connect"><header><div><h2>将 OneShowSEO 连接到你的工具</h2><p>构建自定义集成、自动化工作流，并访问可验证的 SEO 数据。</p></div><em>API v1</em></header><div>{[
    [Globe,"RESTful API","JSON 响应与标准 HTTP 状态码"],[Gauge,"速率限制",data.access?`${data.limits.requests.toLocaleString()} 次请求 / 月`:"升级后开放"],[ShieldCheck,"安全", "API Key 仅展示一次并以哈希保存"],[Lightning,"实时数据","项目与网站数据实时读取"],[BracketsCurly,"MCP 支持",data.capabilities.mcpServer?"已启用":"服务端尚未启用"]
   ].map(([Icon,title,text])=><article key={title as string}><span><Icon weight="duotone"/></span><strong>{title as string}</strong><small>{text as string}</small></article>)}</div></section>
   <QuickStart language={language} setLanguage={setLanguage} example={example} origin={origin} copy={copy}/>
   <EndpointTable onAll={()=>setTab("API 参考")}/>
  </main><aside className="api-side">
   <ApiKeyCard data={data} activeKeys={activeKeys} showKey={showKey} setShowKey={setShowKey} setCreating={setCreating} navigate={navigate} copy={copy}/>
   <UsageCard data={data} pct={pct} onOpen={()=>setTab("速率限制")}/>
   <section className="panel api-sdk"><header><h2>SDK 与客户端</h2></header><div className="api-empty-mini"><Code/><strong>官方 SDK 正在准备</strong><p>当前请使用标准 REST API；不会展示尚未发布的 npm、pip 或 Composer 包。</p></div></section>
   <section className="panel api-resources"><h2>帮助资源</h2>{[[ClipboardText,"API 参考","查看已开放端点与响应约定",()=>setTab("API 参考")],[Key,"密钥管理","生成、查看状态或撤销密钥",()=>setTab("API Keys")],[WebhooksLogo,"Webhook 状态","查看事件投递开放进度",()=>setTab("Webhooks")],[BracketsCurly,"MCP Server","查看 MCP 接入状态",()=>setTab("MCP Server")]].map(([Icon,title,text,action])=><button key={title as string} onClick={action as ()=>void}><Icon/><span><strong>{title as string}</strong><small>{text as string}</small></span><ArrowRight/></button>)}</section>
  </aside></div>}
  {tab==="API 参考"&&<ApiReference origin={origin}/>}
  {tab==="API Keys"&&<KeysPage data={data} activeKeys={activeKeys} setCreating={setCreating} revoke={revoke} rotate={rotate} navigate={navigate}/>}
  {tab==="Webhooks"&&<WebhooksPage data={data} url={webhookUrl} setUrl={setWebhookUrl} secret={webhookSecret} clearSecret={()=>setWebhookSecret("")} create={createWebhook} action={webhookAction}/>}
  {tab==="MCP Server"&&<McpPage origin={origin}/>}
  {tab==="速率限制"&&<RateLimits data={data} pct={pct} navigate={navigate}/>}
  {creating&&<div className="api-modal-backdrop" onMouseDown={event=>event.target===event.currentTarget&&setCreating(false)}><form className="api-modal" onSubmit={createKey}><header><div><span><Key/></span><div><h2>生成新的 API Key</h2><p>密钥只会完整展示一次，请保存到安全的服务端环境。</p></div></div><button type="button" onClick={()=>setCreating(false)}><X/></button></header><label>密钥名称<input autoFocus value={name} onChange={event=>setName(event.target.value)} maxLength={60} required/></label><div className="api-modal-note"><LockKey/><p>默认采用最小权限 projects:read、组织内项目范围和当前套餐限速；创建后可安全轮换或撤销。</p></div><footer><button type="button" onClick={()=>setCreating(false)}>取消</button><button className="primary">生成密钥</button></footer></form></div>}
  {revealed&&<div className="api-modal-backdrop"><section className="api-modal api-key-reveal"><header><div><span><CheckCircle/></span><div><h2>API Key 已生成</h2><p>关闭此窗口后将无法再次查看完整密钥。</p></div></div></header><label>新密钥<div><code>{showKey?revealed:revealed.replace(/_.{20,}$/,"_••••••••••••••••")}</code><button onClick={()=>setShowKey(!showKey)}>{showKey?<EyeSlash/>:<Eye/>}</button><button onClick={()=>copy(revealed,"完整 API Key 已复制")}><Copy/></button></div></label><footer><button className="primary" onClick={()=>{setRevealed("");setShowKey(false)}}>我已安全保存</button></footer></section></div>}
  {notice&&<div className="api-toast" role="status" aria-live="polite"><CheckCircle weight="fill"/>{notice}</div>}
 </div>
}

function QuickStart({language,setLanguage,example,origin,copy}:{language:string;setLanguage:(v:string)=>void;example:string;origin:string;copy:(v:string,m?:string)=>void}){return <section className="panel api-quick"><header><div><h2>快速开始</h2><p>几分钟内调用 OneShowSEO API。</p></div><nav>{["cURL","JavaScript","Python","PHP"].map(item=><button key={item} className={language===item?"active":""} onClick={()=>setLanguage(item)}>{item}</button>)}</nav></header><div className="api-code"><button onClick={()=>copy(example,"代码已复制")}><Copy/>复制</button><pre>{example}</pre></div><footer><span>Base URL:</span><code>{origin}/api/v1</code><button onClick={()=>copy(`${origin}/api/v1`)}>复制地址 <ArrowRight/></button></footer></section>}
function EndpointTable({onAll}:{onAll:()=>void}){return <section className="panel api-endpoints"><header><div><h2>API 端点</h2><p>只把已实际开放的端点标记为可用。</p></div><button onClick={onAll}>查看完整参考 <ArrowRight/></button></header><div className="api-endpoint-table"><div className="head"><span>端点</span><span>方法</span><span>说明</span><span>状态</span></div>{endpoints.slice(0,6).map(row=><article key={`${row.method}${row.path}`}><code>{row.path}</code><em className={row.method.toLowerCase()}>{row.method}</em><span>{row.description}</span><b className={row.live?"live":"planned"}>{row.live?"已开放":"规划中"}</b></article>)}</div></section>}
function ApiKeyCard({data,activeKeys,showKey,setShowKey,setCreating,navigate,copy}:{data:ApiData;activeKeys:ApiKey[];showKey:boolean;setShowKey:(v:boolean)=>void;setCreating:(v:boolean)=>void;navigate:(v:string)=>void;copy:(v:string,m?:string)=>void}){const key=activeKeys[0];return <section className="panel api-key-card"><header><h2>你的 API Key</h2>{data.access?<button onClick={()=>setCreating(true)}><Plus/>生成新密钥</button>:<em>套餐受限</em>}</header>{!data.access?<div className="api-gated"><LockKey/><strong>当前套餐不包含 API 访问</strong><p>升级到 Pro 或 Business 后可生成安全密钥并调用真实 API。</p><button onClick={()=>navigate("套餐升级")}>查看升级方案</button></div>:key?<><small>Live Key <i/></small><div className="api-masked"><code>{showKey?`osseo_live_${key.keyPrefix}_已隐藏`:`osseo_live_${key.keyPrefix}_••••••••••••`}</code><button onClick={()=>setShowKey(!showKey)}>{showKey?<EyeSlash/>:<Eye/>}</button><button onClick={()=>copy(`osseo_live_${key.keyPrefix}_••••••••••••`,"已复制密钥标识；完整密钥不会再次显示")}><Copy/></button></div><p>创建于 {new Date(key.createdAt*1000).toLocaleDateString("zh-CN")}<span>{key.lastUsedAt?`最近使用 ${new Date(key.lastUsedAt*1000).toLocaleString("zh-CN")}`:"尚未使用"}</span></p><div className="api-warning"><WarningCircle/><span>完整密钥仅在创建时展示。请勿分享或写入客户端代码。</span></div></>:<div className="api-gated"><Key/><strong>还没有 API Key</strong><p>创建第一把密钥后即可调用已开放端点。</p><button onClick={()=>setCreating(true)}>生成第一把密钥</button></div>}</section>}
function UsageCard({data,pct,onOpen}:{data:ApiData;pct:number;onOpen:()=>void}){return <section className="panel api-usage"><header><h2>API 用量</h2><button onClick={onOpen}>查看分析 <ArrowRight/></button></header><div><small>当前套餐</small><em>{data.plan.name} Plan</em></div><p><span>已用请求</span><strong>{data.usage.used.toLocaleString()} / {data.limits.requests?data.limits.requests.toLocaleString():"—"}</strong></p><i><b style={{width:`${pct}%`}}/></i><small>重置日期：{new Date(data.usage.periodEnd*1000).toLocaleDateString("zh-CN")}</small><footer><span><strong>{data.usage.used}</strong>本月</span><span><strong>{data.recent.length}</strong>最近记录</span><span><strong>{pct}%</strong>额度</span></footer></section>}
function ApiReference({origin}:{origin:string}){return <div className="api-page-grid"><main><section className="panel api-reference-hero"><span><Code/></span><div><h2>REST API v1</h2><p>使用 Bearer API Key 读取你的 OneShowSEO 项目。所有响应均为 JSON，错误包含稳定的 code 与 message。</p><code>{origin}/api/v1</code></div></section><EndpointTable onAll={()=>undefined}/></main><aside><section className="panel api-policy"><h2>认证方式</h2><p>在服务端请求中发送：</p><code>Authorization: Bearer osseo_live_...</code><div><ShieldCheck/><span>密钥按账户隔离，并受套餐额度约束。</span></div></section><section className="panel api-policy"><h2>响应约定</h2><p><b>200</b> 请求成功</p><p><b>401</b> 密钥无效、已撤销或额度已耗尽</p><p><b>404</b> 资源不存在或无权访问</p></section></aside></div>}
function KeysPage({data,activeKeys,setCreating,revoke,rotate,navigate}:{data:ApiData;activeKeys:ApiKey[];setCreating:(v:boolean)=>void;revoke:(id:string)=>void;rotate:(id:string)=>void;navigate:(v:string)=>void}){return <section className="panel api-keys-page"><header><div><h2>API Keys</h2><p>密钥归组织所有，支持操作范围、项目范围、到期、轮换和即时撤销。</p></div>{data.access?<button className="primary" onClick={()=>setCreating(true)}><Plus/>生成新密钥</button>:<button className="primary" onClick={()=>navigate("套餐升级")}>升级套餐</button>}</header><div className="api-key-summary"><article><small>活跃密钥</small><strong>{activeKeys.length}</strong><span>上限 {data.limits.activeKeys||"—"}</span></article><article><small>已撤销</small><strong>{data.keys.filter(key=>key.status==="revoked").length}</strong><span>不可恢复</span></article><article><small>本月请求</small><strong>{data.usage.used}</strong><span>真实调用记录</span></article></div><div className="api-key-table"><div className="head"><span>名称 / 范围</span><span>密钥标识</span><span>到期时间</span><span>最近使用</span><span>状态</span><span>操作</span></div>{data.keys.map(key=><article key={key.id}><strong>{key.name}<small>{key.scopes.join(" · ")}</small></strong><code>osseo_live_{key.keyPrefix}_••••</code><span>{key.expiresAt?new Date(key.expiresAt*1000).toLocaleDateString("zh-CN"):"永不过期"}</span><span>{key.lastUsedAt?new Date(key.lastUsedAt*1000).toLocaleString("zh-CN"):"从未使用"}</span><em className={key.status}>{key.status==="active"?"活跃":"已撤销"}</em><span><button disabled={key.status!=="active"} onClick={()=>rotate(key.id)}><ArrowsClockwise/>轮换</button><button disabled={key.status!=="active"} onClick={()=>revoke(key.id)}><Trash/>撤销</button></span></article>)}{!data.keys.length&&<div className="api-empty"><Key/><strong>还没有 API Key</strong><p>{data.access?"生成第一把密钥开始接入。":"当前套餐不包含 API 访问。"}</p></div>}</div></section>}
function WebhooksPage({data,url,setUrl,secret,clearSecret,create,action}:{data:ApiData;url:string;setUrl:(v:string)=>void;secret:string;clearSecret:()=>void;create:(event:React.FormEvent)=>void;action:(action:"delete_webhook"|"retry_webhook",id:string)=>void}){return <div className="api-page-grid"><main><section className="panel api-keys-page"><header><div><h2>Webhook 订阅</h2><p>事件使用独立密钥签名，失败会自动退避并在耗尽后隔离。</p></div></header>{secret&&<div className="api-warning"><ShieldCheck/><span>签名密钥仅展示一次：<code>{secret}</code></span><button onClick={clearSecret}>我已保存</button></div>}<form className="api-modal" onSubmit={create}><label>HTTPS 接收地址<input value={url} onChange={event=>setUrl(event.target.value)} placeholder="https://example.com/webhooks/oneshowseo" required/></label><p>默认订阅：任务完成、任务失败、需要审批。</p><button className="primary">创建订阅</button></form><div className="api-key-table">{data.webhooks.map(item=><article key={item.id}><strong>{new URL(item.url).host}</strong><code>{item.secretPrefix}••••</code><span>{item.eventTypes.join(" · ")}</span><span>{new Date(item.updatedAt*1000).toLocaleString("zh-CN")}</span><em className={item.status}>{item.status}</em><button onClick={()=>action("delete_webhook",item.id)}><Trash/>停用</button></article>)}{!data.webhooks.length&&<div className="api-empty"><WebhooksLogo/><strong>还没有订阅</strong><p>添加一个安全的 HTTPS 接收地址。</p></div>}</div></section></main><aside><section className="panel api-policy"><h2>最近投递</h2>{data.deliveries.map(item=><p key={item.id}><b>{item.eventType}</b> {item.state} · {item.attemptCount} 次 {(["retrying","quarantined"].includes(item.state))&&<button onClick={()=>action("retry_webhook",item.id)}>安全重试</button>}</p>)}{!data.deliveries.length&&<p>暂无投递记录。</p>}</section><section className="panel api-policy"><h2>验证规则</h2><p>校验 X-OneShow-Signature 与时间戳，保存 Event ID 防止重复处理。</p></section></aside></div>}
function McpPage({origin}:{origin:string}){return <div className="api-page-grid"><main><section className="panel api-reference-hero"><span><BracketsCurly/></span><div><h2>MCP Server 已启用</h2><p>无状态 Streamable HTTP，复用组织 API Key、项目范围、权益、Credits 与审计。</p><code>{origin}/api/mcp</code></div></section><section className="panel api-endpoints"><header><div><h2>已开放工具</h2><p>工具目录会根据密钥范围自动过滤。</p></div><em>协议 2026-07-28</em></header><div className="api-endpoint-table">{[["list_projects","projects:read"],["get_project","projects:read"],["start_agent_task","tasks:write"]].map(([name,scope])=><article key={name}><code>{name}</code><em className="get">TOOL</em><span>{scope}</span><b className="live">已开放</b></article>)}</div></section></main><aside><section className="panel api-policy"><h2>连接方式</h2><p>Authorization: Bearer osseo_live_...</p><p>MCP-Protocol-Version: 2026-07-28</p><p>每次请求携带 Mcp-Method；工具调用同时携带 Mcp-Name。</p></section></aside></div>}
function RateLimits({data,pct,navigate}:{data:ApiData;pct:number;navigate:(v:string)=>void}){const policy=data.keys.find(key=>key.status==="active")?.rateLimitPolicy;return <div className="api-rate-page"><section className="panel"><header><div><h2>速率与额度</h2><p>按密钥、组织、项目、端点和成本联合限制，超限不会联系下游服务。</p></div><em>{data.plan.name} Plan</em></header><div className="api-rate-meter"><strong>{data.usage.used.toLocaleString()}</strong><span>/ {data.limits.requests?data.limits.requests.toLocaleString():"未开放"} requests</span><i><b style={{width:`${pct}%`}}/></i><small>{pct}% 已使用 · {new Date(data.usage.periodEnd*1000).toLocaleDateString("zh-CN")} 重置</small></div><div className="api-rate-rules"><article><Gauge/><strong>每分钟请求</strong><span>{policy?.requestsPerMinute??"—"}</span></article><article><Key/><strong>每分钟成本单位</strong><span>{policy?.costUnitsPerMinute??"—"}</span></article><article><ArrowsClockwise/><strong>超额策略</strong><span>返回 429 与稳定重试时间</span></article></div>{!data.access&&<button className="primary" onClick={()=>navigate("套餐升级")}>升级以开启 API</button>}</section><section className="panel api-rate-note"><ShieldCheck/><div><h3>公平使用与安全保护</h3><p>每次已认证请求都会形成用量记录。密钥无效返回 401，速率超限返回 429，不会自动收费。</p></div></section></div>}
