"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { ArrowRight,ArrowsClockwise,BracketsCurly,CheckCircle,ClipboardText,Code,Copy,Eye,EyeSlash,Gauge,Globe,Key,Lightning,LockKey,Plus,ShieldCheck,Trash,WarningCircle,WebhooksLogo,X } from "@phosphor-icons/react";

type ApiKey={id:string;name:string;keyPrefix:string;status:"active"|"revoked";lastUsedAt:number|null;createdAt:number;revokedAt:number|null};
type Webhook={id:string;url:string;eventTypes:string[];status:string;createdAt:number};
type ApiData={access:boolean;plan:{id:string;name:string};limits:{requests:number;activeKeys:number};usage:{used:number;periodStart:number;periodEnd:number};keys:ApiKey[];webhooks:Webhook[];recent:Array<{route:string;method:string;statusCode:number;createdAt:number}>;capabilities:{restApi:boolean;webhookDelivery:boolean;mcpServer:boolean}};
const tabs=["总览","API 参考","API Keys","Webhooks","MCP Server","速率限制"];
const endpoints=[
 {method:"GET",path:"/projects",description:"列出当前账户的全部项目",live:true},
 {method:"GET",path:"/projects/{id}",description:"读取一个项目的基本信息",live:true},
 {method:"POST",path:"/projects/{id}/audit",description:"启动项目 SEO 审计",live:false},
 {method:"GET",path:"/keywords",description:"读取项目关键词与机会池",live:false},
 {method:"POST",path:"/content/generate",description:"创建 AI 内容草稿",live:false},
 {method:"GET",path:"/rank-tracking",description:"读取排名跟踪数据",live:false},
];

export default function ApiMcpCenter({navigate}:{navigate:(value:string)=>void}){
 const [data,setData]=useState<ApiData|null>(null),[tab,setTab]=useState("总览"),[language,setLanguage]=useState("cURL"),[creating,setCreating]=useState(false),[name,setName]=useState("Production"),[revealed,setRevealed]=useState(""),[showKey,setShowKey]=useState(false),[notice,setNotice]=useState(""),[error,setError]=useState("");
 const load=useCallback(async()=>{const response=await fetch("/api/api-access",{cache:"no-store"});const json=await response.json();if(!response.ok)throw new Error(json.error);setData(json)},[]);
 useEffect(()=>{const timer=setTimeout(()=>load().catch(error=>setError(error.message)),0);return()=>clearTimeout(timer)},[load]);
 const origin=typeof window==="undefined"?"https://oneshowseo.com":window.location.origin;
 const example=useMemo(()=>({
  cURL:`curl --request GET \\\n+  --url ${origin}/api/v1/projects \\\n+  --header 'Authorization: Bearer YOUR_API_KEY' \\\n+  --header 'Accept: application/json'`,
  JavaScript:`const response = await fetch("${origin}/api/v1/projects", {\n  headers: { Authorization: "Bearer YOUR_API_KEY" }\n});\nconst { data } = await response.json();`,
  Python:`import requests\n\nresponse = requests.get(\n    "${origin}/api/v1/projects",\n    headers={"Authorization": "Bearer YOUR_API_KEY"}\n)\nprint(response.json())`,
  PHP:`$response = file_get_contents(\n  "${origin}/api/v1/projects",\n  false,\n  stream_context_create(["http" => ["header" => "Authorization: Bearer YOUR_API_KEY"]])\n);`
 })[language as "cURL"], [language,origin]);
 const activeKeys=data?.keys.filter(key=>key.status==="active")||[];
 const copy=async(value:string,message="已复制")=>{await navigator.clipboard.writeText(value);setNotice(message);setTimeout(()=>setNotice(""),1800)};
 const createKey=async(event:React.FormEvent)=>{event.preventDefault();setError("");const response=await fetch("/api/api-access",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"create_key",name})});const json=await response.json();if(!response.ok)return setError(json.error);setCreating(false);setRevealed(json.plainTextKey);setShowKey(true);await load()};
 const revoke=async(id:string)=>{if(!confirm("撤销后将立即失效且无法恢复，确认继续？"))return;const response=await fetch("/api/api-access",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"revoke_key",id})});const json=await response.json();if(!response.ok)return setError(json.error);setNotice("API Key 已撤销");await load()};
 if(!data)return <div className="api-center api-loading"><ArrowsClockwise className="spin"/>{error||"正在读取 API 配置…"}</div>;
 const pct=data.limits.requests?Math.min(100,Math.round(data.usage.used/data.limits.requests*100)):0;
 return <div className="api-center">
  <header className="api-header"><div><h1>API & MCP</h1><p>将 OneShowSEO 接入你的工作流，安全访问真实 SEO 数据与自动化能力。</p></div><aside><button>快捷操作</button><i>Y</i></aside></header>
  <nav className="api-tabs">{tabs.map(item=><button key={item} className={tab===item?"active":""} onClick={()=>setTab(item)}>{item}</button>)}</nav>
  {error&&<div className="api-alert"><WarningCircle/>{error}<button onClick={()=>setError("")}><X/></button></div>}
  {tab==="总览"&&<div className="api-layout"><main>
   <section className="panel api-connect"><header><div><h2>将 OneShowSEO 连接到你的工具</h2><p>构建自定义集成、自动化工作流，并访问可验证的 SEO 数据。</p></div><em>API v1</em></header><div>{[
    [Globe,"RESTful API","JSON 响应与标准 HTTP 状态码"],[Gauge,"速率限制",data.access?`${data.limits.requests.toLocaleString()} 次请求 / 月`:"升级后开放"],[ShieldCheck,"安全", "API Key 仅展示一次并以哈希保存"],[Lightning,"实时数据","项目与网站数据实时读取"],[BracketsCurly,"MCP 支持",data.capabilities.mcpServer?"已启用":"服务端尚未启用"]
   ].map(([Icon,title,text])=><article key={title as string}><span><Icon weight="duotone"/></span><strong>{title as string}</strong><small>{text as string}</small></article>)}</div></section>
   <QuickStart language={language} setLanguage={setLanguage} example={example} origin={origin} copy={copy}/>
   <EndpointTable onAll={()=>setTab("API 参考")}/>
  </main><aside className="api-side">
   <ApiKeyCard data={data} activeKeys={activeKeys} showKey={showKey} setShowKey={setShowKey} setCreating={setCreating} navigate={navigate} copy={copy}/>
   <UsageCard data={data} pct={pct} onOpen={()=>setTab("速率限制")}/>
   <section className="panel api-sdk"><header><h2>SDK 与客户端</h2></header><div className="api-empty-mini"><Code/><strong>官方 SDK 正在准备</strong><p>当前请使用标准 REST API；不会展示尚未发布的 npm、pip 或 Composer 包。</p></div></section>
   <section className="panel api-resources"><h2>帮助资源</h2>{[[ClipboardText,"API 参考","查看已开放端点与响应约定",()=>setTab("API 参考")],[Key,"密钥管理","生成、查看状态或撤销密钥",()=>setTab("API Keys")],[WebhooksLogo,"Webhook 状态","查看事件投递开放进度",()=>setTab("Webhooks")],[BracketsCurly,"MCP Server","查看 MCP 接入状态",()=>setTab("MCP Server")]].map(([Icon,title,text,action])=><button key={title as string} onClick={action as ()=>void}><Icon/><span><strong>{title as string}</strong><small>{text as string}</small></span><ArrowRight/></button>)}</section>
  </aside></div>}
  {tab==="API 参考"&&<ApiReference origin={origin}/>} {tab==="API Keys"&&<KeysPage data={data} activeKeys={activeKeys} setCreating={setCreating} revoke={revoke} navigate={navigate}/>} {tab==="Webhooks"&&<UnavailablePage icon={WebhooksLogo} title="Webhooks" text="Webhook 配置模型已经就绪，但安全签名与出站投递服务尚未启用，因此当前不会把事件发送到外部地址。" points={["HTTPS 端点验证","签名重放保护","失败重试与投递日志"]}/>} {tab==="MCP Server"&&<UnavailablePage icon={BracketsCurly} title="MCP Server" text="MCP 服务端尚未上线。正式开放后会复用 OneShowSEO API Key，并提供项目、审计和内容工具。" points={["Streamable HTTP 传输","按项目隔离权限","每次工具调用可审计"]}/>} {tab==="速率限制"&&<RateLimits data={data} pct={pct} navigate={navigate}/>} 
  {creating&&<div className="api-modal-backdrop" onMouseDown={event=>event.target===event.currentTarget&&setCreating(false)}><form className="api-modal" onSubmit={createKey}><header><div><span><Key/></span><div><h2>生成新的 API Key</h2><p>密钥只会完整展示一次，请保存到安全的服务端环境。</p></div></div><button type="button" onClick={()=>setCreating(false)}><X/></button></header><label>密钥名称<input autoFocus value={name} onChange={event=>setName(event.target.value)} maxLength={60} required/></label><div className="api-modal-note"><LockKey/><p>不要把 API Key 写入浏览器代码、公开仓库或客户端应用。</p></div><footer><button type="button" onClick={()=>setCreating(false)}>取消</button><button className="primary">生成密钥</button></footer></form></div>}
  {revealed&&<div className="api-modal-backdrop"><section className="api-modal api-key-reveal"><header><div><span><CheckCircle/></span><div><h2>API Key 已生成</h2><p>关闭此窗口后将无法再次查看完整密钥。</p></div></div></header><label>新密钥<div><code>{showKey?revealed:revealed.replace(/_.{20,}$/,"_••••••••••••••••")}</code><button onClick={()=>setShowKey(!showKey)}>{showKey?<EyeSlash/>:<Eye/>}</button><button onClick={()=>copy(revealed,"完整 API Key 已复制")}><Copy/></button></div></label><footer><button className="primary" onClick={()=>{setRevealed("");setShowKey(false)}}>我已安全保存</button></footer></section></div>}
  {notice&&<div className="api-toast"><CheckCircle weight="fill"/>{notice}</div>}
 </div>
}

function QuickStart({language,setLanguage,example,origin,copy}:{language:string;setLanguage:(v:string)=>void;example:string;origin:string;copy:(v:string,m?:string)=>void}){return <section className="panel api-quick"><header><div><h2>快速开始</h2><p>几分钟内调用 OneShowSEO API。</p></div><nav>{["cURL","JavaScript","Python","PHP"].map(item=><button key={item} className={language===item?"active":""} onClick={()=>setLanguage(item)}>{item}</button>)}</nav></header><div className="api-code"><button onClick={()=>copy(example,"代码已复制")}><Copy/>复制</button><pre>{example}</pre></div><footer><span>Base URL:</span><code>{origin}/api/v1</code><button onClick={()=>copy(`${origin}/api/v1`)}>复制地址 <ArrowRight/></button></footer></section>}
function EndpointTable({onAll}:{onAll:()=>void}){return <section className="panel api-endpoints"><header><div><h2>API 端点</h2><p>只把已实际开放的端点标记为可用。</p></div><button onClick={onAll}>查看完整参考 <ArrowRight/></button></header><div className="api-endpoint-table"><div className="head"><span>端点</span><span>方法</span><span>说明</span><span>状态</span></div>{endpoints.slice(0,6).map(row=><article key={`${row.method}${row.path}`}><code>{row.path}</code><em className={row.method.toLowerCase()}>{row.method}</em><span>{row.description}</span><b className={row.live?"live":"planned"}>{row.live?"已开放":"规划中"}</b></article>)}</div></section>}
function ApiKeyCard({data,activeKeys,showKey,setShowKey,setCreating,navigate,copy}:{data:ApiData;activeKeys:ApiKey[];showKey:boolean;setShowKey:(v:boolean)=>void;setCreating:(v:boolean)=>void;navigate:(v:string)=>void;copy:(v:string,m?:string)=>void}){const key=activeKeys[0];return <section className="panel api-key-card"><header><h2>你的 API Key</h2>{data.access?<button onClick={()=>setCreating(true)}><Plus/>生成新密钥</button>:<em>套餐受限</em>}</header>{!data.access?<div className="api-gated"><LockKey/><strong>当前套餐不包含 API 访问</strong><p>升级到 Pro 或 Business 后可生成安全密钥并调用真实 API。</p><button onClick={()=>navigate("套餐升级")}>查看升级方案</button></div>:key?<><small>Live Key <i/></small><div className="api-masked"><code>{showKey?`osseo_live_${key.keyPrefix}_已隐藏`:`osseo_live_${key.keyPrefix}_••••••••••••`}</code><button onClick={()=>setShowKey(!showKey)}>{showKey?<EyeSlash/>:<Eye/>}</button><button onClick={()=>copy(`osseo_live_${key.keyPrefix}_••••••••••••`,"已复制密钥标识；完整密钥不会再次显示")}><Copy/></button></div><p>创建于 {new Date(key.createdAt*1000).toLocaleDateString("zh-CN")}<span>{key.lastUsedAt?`最近使用 ${new Date(key.lastUsedAt*1000).toLocaleString("zh-CN")}`:"尚未使用"}</span></p><div className="api-warning"><WarningCircle/><span>完整密钥仅在创建时展示。请勿分享或写入客户端代码。</span></div></>:<div className="api-gated"><Key/><strong>还没有 API Key</strong><p>创建第一把密钥后即可调用已开放端点。</p><button onClick={()=>setCreating(true)}>生成第一把密钥</button></div>}</section>}
function UsageCard({data,pct,onOpen}:{data:ApiData;pct:number;onOpen:()=>void}){return <section className="panel api-usage"><header><h2>API 用量</h2><button onClick={onOpen}>查看分析 <ArrowRight/></button></header><div><small>当前套餐</small><em>{data.plan.name} Plan</em></div><p><span>已用请求</span><strong>{data.usage.used.toLocaleString()} / {data.limits.requests?data.limits.requests.toLocaleString():"—"}</strong></p><i><b style={{width:`${pct}%`}}/></i><small>重置日期：{new Date(data.usage.periodEnd*1000).toLocaleDateString("zh-CN")}</small><footer><span><strong>{data.usage.used}</strong>本月</span><span><strong>{data.recent.length}</strong>最近记录</span><span><strong>{pct}%</strong>额度</span></footer></section>}
function ApiReference({origin}:{origin:string}){return <div className="api-page-grid"><main><section className="panel api-reference-hero"><span><Code/></span><div><h2>REST API v1</h2><p>使用 Bearer API Key 读取你的 OneShowSEO 项目。所有响应均为 JSON，错误包含稳定的 code 与 message。</p><code>{origin}/api/v1</code></div></section><EndpointTable onAll={()=>undefined}/></main><aside><section className="panel api-policy"><h2>认证方式</h2><p>在服务端请求中发送：</p><code>Authorization: Bearer osseo_live_...</code><div><ShieldCheck/><span>密钥按账户隔离，并受套餐额度约束。</span></div></section><section className="panel api-policy"><h2>响应约定</h2><p><b>200</b> 请求成功</p><p><b>401</b> 密钥无效、已撤销或额度已耗尽</p><p><b>404</b> 资源不存在或无权访问</p></section></aside></div>}
function KeysPage({data,activeKeys,setCreating,revoke,navigate}:{data:ApiData;activeKeys:ApiKey[];setCreating:(v:boolean)=>void;revoke:(id:string)=>void;navigate:(v:string)=>void}){return <section className="panel api-keys-page"><header><div><h2>API Keys</h2><p>为服务端集成创建独立密钥，并在不再使用时立即撤销。</p></div>{data.access?<button className="primary" onClick={()=>setCreating(true)}><Plus/>生成新密钥</button>:<button className="primary" onClick={()=>navigate("套餐升级")}>升级套餐</button>}</header><div className="api-key-summary"><article><small>活跃密钥</small><strong>{activeKeys.length}</strong><span>上限 {data.limits.activeKeys||"—"}</span></article><article><small>已撤销</small><strong>{data.keys.filter(key=>key.status==="revoked").length}</strong><span>不可恢复</span></article><article><small>本月请求</small><strong>{data.usage.used}</strong><span>真实调用记录</span></article></div><div className="api-key-table"><div className="head"><span>名称</span><span>密钥标识</span><span>创建时间</span><span>最近使用</span><span>状态</span><span>操作</span></div>{data.keys.map(key=><article key={key.id}><strong>{key.name}</strong><code>osseo_live_{key.keyPrefix}_••••</code><span>{new Date(key.createdAt*1000).toLocaleDateString("zh-CN")}</span><span>{key.lastUsedAt?new Date(key.lastUsedAt*1000).toLocaleString("zh-CN"):"从未使用"}</span><em className={key.status}>{key.status==="active"?"活跃":"已撤销"}</em><button disabled={key.status!=="active"} onClick={()=>revoke(key.id)}><Trash/>撤销</button></article>)}{!data.keys.length&&<div className="api-empty"><Key/><strong>还没有 API Key</strong><p>{data.access?"生成第一把密钥开始接入。":"当前套餐不包含 API 访问。"}</p></div>}</div></section>}
function UnavailablePage({icon:Icon,title,text,points}:{icon:typeof WebhooksLogo;title:string;text:string;points:string[]}){return <div className="api-unavailable"><section className="panel"><span><Icon weight="duotone"/></span><em>尚未启用</em><h2>{title}</h2><p>{text}</p><div>{points.map(point=><article key={point}><CheckCircle/><span>{point}</span><b>上线前校验</b></article>)}</div><button disabled>等待平台服务开放</button></section><aside className="panel"><LockKey/><h3>为什么暂不可用？</h3><p>商业化功能只有在鉴权、配额、日志和安全边界完整后才会开放，避免页面显示与真实能力不一致。</p></aside></div>}
function RateLimits({data,pct,navigate}:{data:ApiData;pct:number;navigate:(v:string)=>void}){return <div className="api-rate-page"><section className="panel"><header><div><h2>速率与额度</h2><p>额度按账户和自然月计算；超过限制后不会产生额外扣费。</p></div><em>{data.plan.name} Plan</em></header><div className="api-rate-meter"><strong>{data.usage.used.toLocaleString()}</strong><span>/ {data.limits.requests?data.limits.requests.toLocaleString():"未开放"} requests</span><i><b style={{width:`${pct}%`}}/></i><small>{pct}% 已使用 · {new Date(data.usage.periodEnd*1000).toLocaleDateString("zh-CN")} 重置</small></div><div className="api-rate-rules"><article><Gauge/><strong>月度请求</strong><span>{data.limits.requests?data.limits.requests.toLocaleString():"未包含"}</span></article><article><Key/><strong>活跃密钥</strong><span>{data.limits.activeKeys||"未包含"}</span></article><article><ArrowsClockwise/><strong>超额策略</strong><span>停止新请求</span></article></div>{!data.access&&<button className="primary" onClick={()=>navigate("套餐升级")}>升级以开启 API</button>}</section><section className="panel api-rate-note"><ShieldCheck/><div><h3>公平使用与安全保护</h3><p>每次成功或失败的已认证请求都会形成审计记录。密钥无效或套餐额度耗尽时返回 401，不会自动收费。</p></div></section></div>}
