"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { ArrowRight,ArrowsClockwise,CalendarBlank,Check,CheckCircle,ClockCountdown,Code,FileText,FunnelSimple,Gauge,LinkSimple,MagnifyingGlass,NotePencil,PaperPlaneTilt,Robot,SealCheck,ShieldCheck,Sparkle,Target,TrendUp,WarningCircle,X } from "@phosphor-icons/react";

type Decision="approve"|"reject"|"request_changes"|"defer"|"schedule";
type Approval={id:string;source:"governed"|"legacy";projectId:string;projectName:string;projectHost:string;type:string;title:string;description:string;priority:number;status:string;createdAt:number;updatedAt:number;category:string|null;severity:string|null;evidence:string|null;url:string|null;lastAction:Decision|null;lastNote:string|null;scheduledFor:number|null;decisionAt:number|null;risk:"critical"|"high"|"medium"|"low";deadline:number;confidence:number|null;estimatedCost:number|null;impactHypothesis:string;evidenceRefs:Array<{id:string;kind:string;referenceId:string;digest:string;capturedAt:number;expiresAt:number;provenance:Record<string,unknown>}>;changeSets:Array<{id:string;targetType:string;targetRef:string;beforeHash:string;afterHash:string;operations:unknown[];rollbackRequired:boolean}>;assignee:string|null;stateRevision:number|null;currentVersion:number|null;agentKey:string|null;agentVersion:string|null};
type ApprovalData={items:Approval[];summary:{pending:number;highRisk:number;expiringSoon:number;approvedToday:number;scheduled:number};capabilities:{directPublish:boolean;automationRules:boolean}};
const tabLabels:{[key:string]:string}={pending:"待审批",approved:"已批准",rejected:"已驳回",scheduled:"已排期",all:"全部"};
const riskLabel={critical:"严重风险",high:"高风险",medium:"中风险",low:"低风险"};
const pendingState=(status:string)=>["proposed","pending","deferred","changes_requested"].includes(status);
const localizedState=(status:string)=>{const en=typeof document!=="undefined"&&document.documentElement.lang.startsWith("en");const labels:Record<string,[string,string]>={proposed:["待审批","Pending"],pending:["待审批","Pending"],deferred:["已延期","Deferred"],changes_requested:["待修改","Changes requested"],approved:["已批准","Approved"],executing:["执行中","Executing"],verified:["已验证","Verified"],rejected:["已驳回","Rejected"],dismissed:["已忽略","Dismissed"],expired:["已过期","Expired"],failed:["失败","Failed"],rolled_back:["已回滚","Rolled back"]};return(labels[status]?.[en?1:0])||status};
const agentName=(type:string)=>type.startsWith("content_")?"Content Agent":type.startsWith("publish_")?"Publish Agent":type.startsWith("research_")?"Research Agent":type.startsWith("knowledge_")?"Knowledge Agent":type.startsWith("fix_")?"SEO Audit Agent":"SEO Agent";
const typeName=(type:string)=>type.startsWith("publish_")?"发布任务":type.startsWith("content_")?"内容变更":type.startsWith("knowledge_")?"知识资产":type.startsWith("fix_")?"页面修复":type==="rank_keyword"?"排名监控":"SEO 任务";
const ago=(time:number)=>{const seconds=Math.max(0,Math.floor(Date.now()/1000)-time);if(seconds<60)return"刚刚";if(seconds<3600)return`${Math.floor(seconds/60)} 分钟前`;if(seconds<86400)return`${Math.floor(seconds/3600)} 小时前`;return`${Math.floor(seconds/86400)} 天前`};

export default function ApprovalCenter(){
 const [data,setData]=useState<ApprovalData|null>(null),[selectedId,setSelectedId]=useState(""),[tab,setTab]=useState("pending"),[risk,setRisk]=useState("all"),[type,setType]=useState("all"),[query,setQuery]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState(""),[dialog,setDialog]=useState<"reject"|"changes"|"schedule"|null>(null),[note,setNote]=useState(""),[scheduleAt,setScheduleAt]=useState("");
 const load=useCallback(async()=>{const response=await fetch("/api/approvals",{cache:"no-store"}),json=await response.json();if(!response.ok)throw new Error(json.error);setData(json);setSelectedId(current=>current&&json.items.some((item:Approval)=>item.id===current)?current:(json.items.find((item:Approval)=>item.status==="proposed")||json.items[0])?.id||"")},[]);
 useEffect(()=>{const timer=setTimeout(()=>load().catch(error=>setError(error.message)),0);return()=>clearTimeout(timer)},[load]);
 const filtered=useMemo(()=>{if(!data)return[];return data.items.filter(item=>{const tabMatch=tab==="all"||(tab==="pending"&&pendingState(item.status))||(tab==="approved"&&["approved","executing","verified"].includes(item.status)&&item.lastAction!=="schedule")||(tab==="rejected"&&["dismissed","rejected","expired","failed","rolled_back"].includes(item.status))||(tab==="scheduled"&&item.status==="approved"&&item.lastAction==="schedule");return tabMatch&&(risk==="all"||item.risk===risk)&&(type==="all"||item.type.startsWith(type))&&`${item.title} ${item.description} ${item.projectHost}`.toLowerCase().includes(query.toLowerCase())})},[data,tab,risk,type,query]);
 const selected=data?.items.find(item=>item.id===selectedId)||filtered[0]||null;
 const decide=async(action:Decision,options:{note?:string;scheduledFor?:number}={})=>{if(!selected)return;setBusy(true);setError("");const response=await fetch("/api/approvals",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({taskId:selected.id,source:selected.source,expectedStateRevision:selected.stateRevision,action,...options})}),json=await response.json();setBusy(false);if(!response.ok)return setError(json.error);setDialog(null);setNote("");setScheduleAt("");setSuccess(action==="approve"?(json.publishQueued?"已批准并进入发布队列":"审批已通过"):action==="reject"?"审批项已驳回":action==="request_changes"?"修改请求已发送":action==="schedule"?"审批项已排期":"已推迟处理");setTimeout(()=>setSuccess(""),2200);await load()};
 if(!data)return <div className="approval-center approval-loading"><ArrowsClockwise className="spin"/>{error||"正在读取审批队列…"}</div>;
 return <div className="approval-center">
  <header className="approval-header"><div><h1>Approval Center</h1><p>在 AI 建议进入执行或发布流程前完成审核与批准。</p></div><aside><button>快捷操作</button><i>Y</i></aside></header>
  <div className="approval-top-actions"><button disabled={!data.capabilities.automationRules}><Robot/>自动化规则 <small>{data.capabilities.automationRules?"":"待开放"}</small></button><button><ShieldCheck/>审批设置</button></div>
  <section className="approval-metrics">{[
   [FileText,"待审批",data.summary.pending,"需要审核","purple"],[WarningCircle,"高风险",data.summary.highRisk,"高优先级","red"],[ClockCountdown,"即将到期",data.summary.expiringSoon,"24 小时内","orange"],[SealCheck,"今日批准",data.summary.approvedToday,"已完成","green"],[CalendarBlank,"已排期",data.summary.scheduled,"等待执行","blue"]
  ].map(([Icon,label,value,sub,tone])=><article className={tone as string} key={label as string}><span><Icon weight="duotone"/></span><div><small>{label as string}</small><strong>{value as number}</strong><em>{sub as string}</em></div></article>)}</section>
  <nav className="approval-tabs">{Object.entries(tabLabels).map(([key,label])=><button className={tab===key?"active":""} key={key} onClick={()=>setTab(key)}>{label}{key==="pending"&&<small>{data.summary.pending}</small>}</button>)}</nav>
  <div className="approval-filters"><select value={type} onChange={event=>setType(event.target.value)} aria-label="类型筛选"><option value="all">全部类型</option><option value="fix_">页面修复</option><option value="content_">内容变更</option><option value="publish_">发布任务</option><option value="knowledge_">知识资产</option></select><select disabled aria-label="Agent 筛选"><option>全部 Agents</option></select><select disabled aria-label="项目筛选"><option>全部项目</option></select><select value={risk} onChange={event=>setRisk(event.target.value)} aria-label="风险筛选"><option value="all">全部风险</option><option value="critical">严重风险</option><option value="high">高风险</option><option value="medium">中风险</option><option value="low">低风险</option></select><span><CalendarBlank/>最近 30 天</span><label><MagnifyingGlass/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="搜索审批项…"/></label><button aria-label="更多筛选"><FunnelSimple/></button></div>
  {error&&<div className="approval-alert error"><WarningCircle/>{error}<button onClick={()=>setError("")}><X/></button></div>}{success&&<div className="approval-alert success"><CheckCircle/>{success}</div>}
  <div className="approval-workspace"><section className="panel approval-queue"><header><h2>审批队列 <small>{filtered.length}</small></h2></header><div>{filtered.map(item=><button key={item.id} className={selected?.id===item.id?"active":""} onClick={()=>setSelectedId(item.id)}><span className={`queue-icon ${item.risk}`}><TaskIcon type={item.type}/></span><div><strong>{item.title}</strong><small>{item.description}</small><em>{agentName(item.type)}　·　{item.projectHost}</em></div><aside><time>{ago(item.updatedAt)}</time><b className={item.risk}>{riskLabel[item.risk]}</b></aside></button>)}{!filtered.length&&<div className="approval-empty"><SealCheck/><strong>当前筛选下没有审批项</strong><p>切换状态或清除筛选条件查看其他记录。</p></div>}</div><footer>显示 {filtered.length} / {data.items.length} 条审批记录</footer></section>
   <main className="approval-detail">{selected?<ApprovalDetail item={selected} data={data} busy={busy} decide={decide} setDialog={setDialog}/>:<section className="panel approval-no-selection"><FileText/><h2>选择一条审批项</h2><p>在左侧队列中选择任务以查看证据和变更预览。</p></section>}</main>
   <aside className="approval-side">{selected&&<ApprovalSide item={selected}/>}</aside>
  </div>
  {dialog&&selected&&<div className="approval-modal-backdrop" onMouseDown={event=>event.target===event.currentTarget&&setDialog(null)}><form className="approval-modal" onSubmit={event=>{event.preventDefault();if(dialog==="reject")decide("reject",{note});if(dialog==="changes")decide("request_changes",{note});if(dialog==="schedule")decide("schedule",{note,scheduledFor:Math.floor(new Date(scheduleAt).getTime()/1000)})}}><header><div><span>{dialog==="reject"?<X/>:dialog==="schedule"?<CalendarBlank/>:<NotePencil/>}</span><div><h2>{dialog==="reject"?"驳回审批项":dialog==="schedule"?"安排执行时间":"请求修改"}</h2><p>{selected.title}</p></div></div><button type="button" onClick={()=>setDialog(null)}><X/></button></header>{dialog==="schedule"&&<label>执行时间<input required type="datetime-local" value={scheduleAt} onChange={event=>setScheduleAt(event.target.value)}/></label>}<label>{dialog==="schedule"?"备注（可选）":"说明"}<textarea required={dialog!=="schedule"} value={note} onChange={event=>setNote(event.target.value)} placeholder={dialog==="reject"?"说明驳回原因…":dialog==="changes"?"说明需要修改的内容…":"添加执行备注…"}/></label><footer><button type="button" onClick={()=>setDialog(null)}>取消</button><button className={dialog==="reject"?"danger":"primary"} disabled={busy}>{busy?"正在处理…":dialog==="reject"?"确认驳回":dialog==="schedule"?"确认排期":"发送修改请求"}</button></footer></form></div>}
 </div>
}

function TaskIcon({type}:{type:string}){if(type.startsWith("publish_"))return <PaperPlaneTilt/>;if(type.startsWith("content_"))return <FileText/>;if(type.startsWith("fix_"))return <Code/>;if(type.startsWith("knowledge_"))return <Sparkle/>;return <Target/>}
function ApprovalDetail({item,data,busy,decide,setDialog}:{item:Approval;data:ApprovalData;busy:boolean;decide:(action:Decision,options?:{note?:string;scheduledFor?:number})=>void;setDialog:(value:"reject"|"changes"|"schedule")=>void}){const pending=pendingState(item.status);return <><section className="panel approval-detail-head"><div><em>{typeName(item.type)}</em><h2>{item.title} <small className={item.risk}>{riskLabel[item.risk]}</small></h2><p>{item.description}</p><span>{item.agentKey?`${item.agentKey} v${item.agentVersion}`:agentName(item.type)}　·　{item.projectName}　·　创建于 {ago(item.createdAt)}</span></div><aside><small>AI 置信度</small><strong>{item.confidence!==null?`${Math.round(item.confidence*100)}%`:item.evidence?"有证据":"待补充"}</strong><i><b style={{width:item.confidence!==null?`${item.confidence*100}%`:item.evidence?"88%":"35%"}}/></i></aside></section>
 <section className="panel approval-recommendation"><header><h3>AI 建议</h3></header><p>{item.impactHypothesis||item.description}</p><button>建议版本 v{item.currentVersion||1} <ArrowRight/></button></section>
 <section className="approval-impact-cards"><article className="panel"><small>潜在影响</small><strong>{item.severity==="critical"?"严重问题":item.severity==="high"?"高影响":"待验证"}</strong><em>基于审计证据</em></article><article className="panel"><small>风险等级</small><strong className={item.risk}>{riskLabel[item.risk]}</strong><em>优先级 {item.priority}/100</em></article><article className="panel"><small>预计成本</small><strong>{item.estimatedCost!==null?`${item.estimatedCost} Credits`:"待核算"}</strong><em>执行时重新校验余额</em></article><article className="panel"><small>审批时限</small><strong>{new Date(item.deadline*1000).toLocaleDateString("zh-CN")}</strong><em>到期后禁止执行</em></article></section>
 <section className="panel approval-preview"><header><h3>变更预览</h3><nav><button className="active">内容预览</button><button>技术变更</button></nav></header><div><article><em>当前状态</em><h4>现有页面或任务</h4><p>{item.url||"尚未绑定具体页面"}</p><strong>当前摘要</strong><p>{item.changeSets[0]?.beforeHash||item.evidence||"当前没有可展示的页面级证据。"}</p></article><ArrowRight/><article className="proposed"><em>建议状态</em><h4>{item.title}</h4><p>{item.description}</p><strong>变更后摘要</strong><p>{item.changeSets[0]?.afterHash||"执行前将再次生成目标摘要"}</p><ul><li>保留人工审批与操作记录</li><li>仅修改当前项目授权范围</li><li>执行后重新验证结果</li></ul></article></div><footer><span>操作类型：{typeName(item.type)}</span><span>目标：{item.url||item.projectHost}</span></footer></section>
 <section className="panel approval-actions">{pending?<><button className="primary" disabled={busy} onClick={()=>decide("approve")}><Check/> {item.type.startsWith("publish_")&&!data.capabilities.directPublish?"批准并进入发布队列":"批准"}</button><button disabled={busy} onClick={()=>decide("defer")}><CalendarBlank/>稍后处理</button><button className="reject" disabled={busy} onClick={()=>setDialog("reject")}><X/>驳回</button><button disabled={busy} onClick={()=>setDialog("changes")}><NotePencil/>请求修改</button>{item.source==="legacy"&&<button disabled={busy} onClick={()=>setDialog("schedule")}><ClockCountdown/>排期</button>}</>:<><span className={`decision ${item.status}`}><CheckCircle/>{localizedState(item.status)}</span>{item.lastNote&&<p>{item.lastNote}</p>}</>}</section></>}
function ApprovalSide({item}:{item:Approval}){const evidence=item.evidenceRefs.length?item.evidenceRefs.map(ref=>({icon:Gauge,title:`${ref.kind} 证据`,text:`${ref.referenceId} · ${ref.digest.slice(0,12)}… · ${JSON.stringify(ref.provenance)}`})):[{icon:Gauge,title:"网站诊断",text:item.evidence||"当前证据来自 SEO 任务"},{icon:LinkSimple,title:"目标页面",text:item.url||"尚未绑定具体 URL"}];return <><section className="panel approval-forecast"><h2>影响预测</h2><p>仅展示可验证的影响方向</p>{[[TrendUp,"自然搜索流量","待连接 GSC"],[Target,"排名改善","待连接排名源"],[Sparkle,"AI 可见性","待连接监控源"],[Gauge,"问题风险",riskLabel[item.risk]]].map(([Icon,label,value])=><article key={label as string}><span><Icon/></span><strong>{label as string}</strong><em>{value as string}</em></article>)}</section><section className="panel approval-evidence"><header><h2>证据与来源</h2></header>{evidence.map(({icon:Icon,title,text})=><article key={`${title}${text}`}><span><Icon/></span><div><strong>{title}</strong><p>{text}</p></div><CheckCircle/></article>)}</section><section className="panel approval-timeline"><h2>活动时间线</h2>{[{time:ago(item.createdAt),title:item.agentKey||agentName(item.type),text:`创建建议 v${item.currentVersion||1}`},{time:ago(item.updatedAt),title:"Approval Center",text:item.lastNote||localizedState(item.status)}].map(row=><article key={`${row.time}${row.title}`}><time>{row.time}</time><i/><div><strong>{row.title}</strong><p>{row.text}</p></div></article>)}</section><section className="panel approval-rules"><h2>负责人和规则</h2><p><span>负责人</span><strong>{item.assignee||"当前项目所有者"}</strong></p><p><span>审批规则</span><strong>{item.risk==="high"||item.risk==="critical"?"高风险必须人工审批":"按项目审批策略处理"}</strong></p></section></>}
