"use client";
import { useCallback,useEffect,useState } from "react";
import { ArrowRight,Brain,CaretRight,ChartLineUp,CheckCircle,ClockCountdown,Code,Database,FileText,Globe,Info,LinkSimple,MagnifyingGlass,Play,Robot,ShieldCheck,Sparkle,WarningCircle } from "@phosphor-icons/react";

type GeoDimension="machine_readability"|"answerability"|"authority"|"crawler_access";
type GeoCheck={id:string;dimension:GeoDimension;category:string;checkKey:string;status:"pass"|"warning"|"fail"|"unknown"|"skipped";severity:string;confidence:string;title:string;description:string;evidence:string|null;recommendation:string|null;url:string|null;digest:string;createdAt:number};
export type GeoData={creditCost:number;capabilities:{onsiteEvidence:boolean;externalVisibilityMonitoring:boolean};latestRun:null|{id:string;taskId:string;status:string;score:number;pagesScanned:number;checksTotal:number;checksPassed:number;checksWarning:number;checksFailed:number;recommendations:number;dimensions:Record<GeoDimension,number|null>;degradedSources:string[];agentVersion:string;startedAt:number;completedAt:number|null;error:string|null};checks:GeoCheck[]};
const names:Record<GeoDimension,string>={machine_readability:"机器可读性",answerability:"答案可提取性",authority:"实体与权威",crawler_access:"AI 爬虫访问"};
const icons:Record<GeoDimension,typeof Code>={machine_readability:Code,answerability:Sparkle,authority:ShieldCheck,crawler_access:Robot};
async function waitForTask(taskId:string){const started=Date.now();while(Date.now()-started<16*60*1000){const response=await fetch(`/api/tasks?taskId=${encodeURIComponent(taskId)}`,{cache:"no-store"}),payload=await response.json();if(!response.ok)throw new Error(payload.error||"任务状态读取失败");if(["completed","failed","cancelled","quarantined"].includes(payload.task.state))return payload.task;await new Promise(resolve=>setTimeout(resolve,1500))}throw new Error("GEO 扫描仍在后台运行，请稍后查看")}

export default function GeoAgentControl({project,navigate,refresh}:{project:{id:string;host:string};navigate:(value:string)=>void;refresh:()=>Promise<void>}){
 const [data,setData]=useState<GeoData|null>(null),[running,setRunning]=useState(false),[error,setError]=useState(""),[tab,setTab]=useState<"all"|"open"|"passed">("open");
 const load=useCallback(async()=>{const response=await fetch(`/api/projects/${project.id}/geo`,{cache:"no-store"}),payload=await response.json();if(!response.ok)throw new Error(payload.error||"GEO 数据读取失败");setData(payload)},[project.id,setData]);useEffect(()=>{const timer=setTimeout(()=>load().catch(caught=>setError(caught instanceof Error?caught.message:"GEO 数据读取失败")),0);return()=>clearTimeout(timer)},[load]);
 const run=async()=>{setRunning(true);setError("");try{const response=await fetch(`/api/projects/${project.id}/geo`,{method:"POST"}),payload=await response.json();if(!response.ok)throw new Error(payload.error||"GEO 扫描创建失败");const task=await waitForTask(payload.taskId);await Promise.all([load(),refresh()]);if(task.state!=="completed")throw new Error("GEO 扫描未完成，预留 Credits 已释放")}catch(caught){setError(caught instanceof Error?caught.message:"GEO 扫描失败")}finally{setRunning(false)}};
 const runData=data?.latestRun,checks=data?.checks||[],visible=checks.filter(item=>tab==="all"||tab==="open"&&["warning","fail"].includes(item.status)||tab==="passed"&&item.status==="pass"),last=runData?.completedAt?new Date(runData.completedAt*1000).toLocaleString("zh-CN"):"尚未运行",priority=checks.find(item=>["fail","warning"].includes(item.status));
 return <div className="geo-v2-page"><header className="geo-v2-header"><div><p><Brain/> AI Agents <CaretRight/> <strong>GEO Agent</strong></p><div><h1>GEO Agent</h1><span className={running?"running":runData?"ready":"not-run"}>{running?<ClockCountdown/>:runData?<CheckCircle weight="fill"/>:<Info/>}{running?"扫描中":runData?"证据已更新":"等待首次扫描"}</span></div><small>用可验证页面证据提升品牌被生成式搜索理解、提取和引用的准备度。</small></div><aside><span>最近运行：{last}</span><button onClick={()=>navigate("AI 可见性")}><ChartLineUp/>AI 可见性</button><button className="primary" onClick={run} disabled={running}><Play weight="fill"/>{running?"正在扫描…":"运行 GEO 扫描"}</button></aside></header>
 {error&&<div className="geo-v2-alert"><WarningCircle/>{error}</div>}
 <section className="geo-v2-truth"><Info weight="fill"/><div><strong>GEO 就绪度 ≠ 外部 AI 提及量</strong><p>本页结论来自网站公开页面、结构化数据、robots.txt 与 llms.txt。ChatGPT、Perplexity、Claude、Gemini 的真实提及和引用需要独立监控数据源，当前不会估算。</p></div><button onClick={()=>navigate("数据连接")}>查看数据源 <ArrowRight/></button></section>
 <section className="geo-v2-summary"><article className="geo-v2-score"><div style={{"--score":`${runData?.score||0}%`} as React.CSSProperties}><strong>{runData?.score??"—"}</strong><small>/100</small></div><section><span>GEO READINESS</span><h2>{!runData?"建立第一个可验证的 GEO 基线":runData.score>=80?"站内 GEO 基础较完整，继续强化权威来源。":runData.score>=60?"基础可用，但仍有影响机器理解的缺口。":"优先修复机器可读性、权威和答案结构。"}</h2><p>{runData?`${runData.pagesScanned} 个页面 · ${runData.checksTotal} 项检查 · ${runData.recommendations} 项建议`:"运行后会生成证据、建议、报告并结算 5 Credits。"}</p></section></article><div className="geo-v2-dimensions">{(Object.keys(names) as GeoDimension[]).map(key=>{const Icon=icons[key],value=runData?.dimensions?.[key];return <article key={key}><span><Icon weight="duotone"/></span><div><small>{names[key]}</small><strong>{value??"—"}{value!==null&&value!==undefined&&<em>/100</em>}</strong><i><b style={{width:`${value||0}%`}}/></i></div></article>})}</div></section>
 <section className="geo-v2-metrics"><article><span><Database/></span><div><small>证据检查</small><strong>{runData?.checksTotal||0}</strong><p>全部来自公开页面</p></div></article><article><span><CheckCircle/></span><div><small>已通过</small><strong>{runData?.checksPassed||0}</strong><p>当前证据范围</p></div></article><article><span><WarningCircle/></span><div><small>待优化</small><strong>{(runData?.checksWarning||0)+(runData?.checksFailed||0)}</strong><p>已进入建议队列</p></div></article><article><span><FileText/></span><div><small>报告状态</small><strong>{runData?.status==="completed"?"已生成":"待生成"}</strong><p>可追溯 Markdown 资产</p></div></article></section>
 <div className="geo-v2-layout"><main><section className="geo-v2-panel geo-v2-workflow"><header><div><span>EVIDENCE WORKFLOW</span><h2>GEO 分析链路</h2></div><small>每一步都有持久化证据</small></header><div>{[[Globe,"安全抓取",Boolean(runData)],[Code,"结构化理解",Boolean(runData)],[Sparkle,"答案提取",Boolean(runData)],[ShieldCheck,"权威核验",Boolean(runData)],[FileText,"报告与任务",Boolean(runData)]].map(([Icon,label,done],index)=><article className={done?"done":""} key={label as string}><span><Icon/></span><strong>{label as string}</strong><small>{done?"已完成":"等待运行"}</small>{index<4&&<CaretRight/>}</article>)}</div></section>
 <section className="geo-v2-panel geo-v2-checks"><header><div><span>VERIFIED FINDINGS</span><h2>证据与优化建议</h2><p>未知和未接入的数据不会被视为通过。</p></div><nav>{[["open","待优化"],["passed","已通过"],["all","全部"]].map(([value,label])=><button className={tab===value?"active":""} key={value} onClick={()=>setTab(value as typeof tab)}>{label}</button>)}</nav></header>{visible.length?<div className="geo-v2-table"><div className="head"><span>检查项</span><span>维度</span><span>证据</span><span>置信度</span><span>状态</span></div>{visible.slice(0,20).map(item=><article key={item.id}><div><span className={item.status}>{item.status==="pass"?<CheckCircle weight="fill"/>:<WarningCircle weight="fill"/>}</span><p><strong>{item.title}</strong><small>{item.recommendation||item.description}</small></p></div><em>{names[item.dimension]}</em><p>{item.evidence||"证据记录已保存"}{item.url&&<a href={item.url} target="_blank" rel="noreferrer">查看来源</a>}</p><code>{item.confidence}</code><b className={item.status}>{item.status==="pass"?"通过":item.status==="fail"?"需修复":item.status==="warning"?"需优化":"证据不足"}</b></article>)}</div>:<div className="geo-v2-empty"><MagnifyingGlass/><strong>{runData?"当前筛选没有检查项":"尚无 GEO 证据"}</strong><p>{runData?"切换筛选查看其他检查结果。":"运行 GEO Agent 建立站内就绪度基线。"}</p><button onClick={run} disabled={running}>运行首次扫描</button></div>}</section></main><aside><section className="geo-v2-next"><small>AI-RECOMMENDED NEXT STEP</small><span><Sparkle weight="fill"/></span><h2>{priority?.title||(!runData?"建立 GEO 基线":"保持证据更新")}</h2><p>{priority?.recommendation||priority?.description||(!runData?"从公开站点抓取开始，检查机器可读性、答案结构、主体权威和 AI 爬虫策略。":"当前没有开放建议，建议按周期复查。")}</p><dl><div><dt>执行成本</dt><dd>{data?.creditCost||5} Credits</dd></div><div><dt>网站修改</dt><dd>不会自动执行</dd></div><div><dt>建议审批</dt><dd>进入任务中心</dd></div></dl><button onClick={priority?()=>navigate("任务中心"):run}>{priority?"审阅优化任务":"运行 GEO 扫描"}<ArrowRight/></button></section><section className="geo-v2-panel geo-v2-boundary"><header><h2>数据边界</h2></header>{[[CheckCircle,"已接通","页面、Schema、作者、来源、robots.txt、llms.txt"],[WarningCircle,"尚未接通","AI 平台提及、引用份额、答案位置和 AI 引荐流量"],[LinkSimple,"下一步","接入监控提供方后进入 AI 可见性趋势"]].map(([Icon,title,text])=><article key={title as string}><span><Icon/></span><p><strong>{title as string}</strong><small>{text as string}</small></p></article>)}</section></aside></div></div>
}
