"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import Link from "next/link"; import Image from "next/image";
import { House,FirstAidKit,CheckSquare,MagnifyingGlass,UsersThree,FileText,Robot,Plug,Gear,UserCircle,ArrowClockwise,CheckCircle,Globe,LockKey,ArrowRight,SignOut } from "@phosphor-icons/react";

type Project={id:string;name:string;siteUrl:string;host:string;market:string;language:string};
type Finding={id:string;severity:string;category:string;title:string;description:string;evidence?:string;url:string};
type Task={id:string;title:string;description:string;priority:number;status:string};
type Dashboard={user:{name:string;email:string;plan:string;role:string};projects:Project[];project?:Project;latestRun?:{status:string;score:number;pagesScanned:number;completedAt:number};findings?:Finding[];tasks?:Task[];connections?:{provider:string;status:string}[];usage?:{pagesCrawled:number};limits:{projects:number;pagesPerAudit:number}};
type ProjectForm={name:string;siteUrl:string;market:string;language:string;businessGoal:string;approvalMode:string};
const modules=[[House,"总览"],[FirstAidKit,"网站诊断"],[CheckSquare,"任务中心"],[MagnifyingGlass,"关键词研究"],[UsersThree,"竞争对手"],[FileText,"内容规划"],[Robot,"AI 内容生产"],[Plug,"数据连接"],[Gear,"项目设置"]] as const;
const providers:{[key:string]:string}={public_crawl:"公开网站抓取",google_search_console:"Google Search Console",google_analytics_4:"Google Analytics 4",rank_provider:"关键词排名数据",cms:"CMS 发布"};

export default function WorkspacePage(){
 const [data,setData]=useState<Dashboard|null>(null),[active,setActive]=useState("总览"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[toast,setToast]=useState("");
 const [form,setForm]=useState({name:"",siteUrl:"",market:"CN",language:"zh-CN",businessGoal:"organic_growth",approvalMode:"required"});
 const load=useCallback(async(id?:string)=>{const r=await fetch(`/api/dashboard${id?`?projectId=${id}`:""}`,{cache:"no-store"});if(r.status===401){location.href="/login?returnTo=%2Fworkspace";return}const j=await r.json();if(!r.ok)throw new Error(j.error);setData(j)},[]);
 useEffect(()=>{const timer=setTimeout(()=>load().catch(e=>setError(e.message)),0);return()=>clearTimeout(timer)},[load]);
 const notice=(x:string)=>{setToast(x);setTimeout(()=>setToast(""),2200)};
 const create=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError("");const r=await fetch("/api/projects",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const j=await r.json();setBusy(false);if(!r.ok)return setError(j.error);await load(j.project.id);notice("项目已创建，可以开始首次诊断")};
 const audit=async()=>{if(!data?.project)return;setBusy(true);setError("");const r=await fetch(`/api/projects/${data.project.id}/audit`,{method:"POST"});const j=await r.json();setBusy(false);if(!r.ok)return setError(j.error);await load(data.project.id);notice(`诊断完成：扫描 ${j.pagesScanned} 个页面`) };
 const decide=async(id:string,status:string)=>{const r=await fetch("/api/tasks",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,status})});const j=await r.json();if(!r.ok)return setError(j.error);await load(data?.project?.id);notice(status==="approved"?"任务已批准":"任务已忽略")};
 const logout=async()=>{await fetch("/api/auth/logout",{method:"POST"});location.href="/login"};
 const counts=useMemo(()=>Object.fromEntries(["critical","high","medium","low"].map(s=>[s,(data?.findings||[]).filter(f=>f.severity===s).length])),[data]);
 if(!data)return <main className="product-loading"><ArrowClockwise className="spin"/>正在读取项目数据…{error&&<p>{error}</p>}</main>;
 return <main className="app-shell commercial-workspace"><aside className="workspace-sidebar"><Link href="/"><Image src="/brand/oneshowseo.png" alt="OneShowSEO" width={162} height={41} unoptimized/></Link>
  <select className="project-select" value={data.project?.id||""} onChange={e=>load(e.target.value)} disabled={!data.projects.length}><option value="">{data.projects.length?"选择项目":"尚未创建项目"}</option>{data.projects.map(p=><option key={p.id} value={p.id}>{p.host}</option>)}</select>
  <nav>{modules.map(([Icon,label])=><button key={label} className={active===label?"active":""} onClick={()=>setActive(label)}><Icon/>{label}</button>)}</nav>
  <div className="plan-card"><span>当前套餐 · {data.user.plan}</span><p>项目 <b>{data.projects.length} / {data.limits.projects}</b></p><i><em style={{width:`${Math.min(100,data.projects.length/data.limits.projects*100)}%`}}/></i><p>本月抓取 <b>{data.usage?.pagesCrawled||0} 页</b></p><p>单次上限 <b>{data.limits.pagesPerAudit} 页</b></p><Link href="/pricing">查看套餐</Link></div>
 </aside><section className="workspace-content"><header className="app-topbar"><span/><div><UserCircle weight="fill"/><strong>{data.user.name}</strong>{data.user.role==="admin"&&<Link href="/admin">管理后台</Link>}<button onClick={logout}><SignOut/>退出</button></div></header><div className="workspace-inner">
 {!data.project?<Onboarding form={form} setForm={setForm} create={create} busy={busy} error={error}/>:<>
  <div className="workspace-heading"><div><span className="eyebrow">{active}</span><h1>{data.project.name}</h1><p>{data.project.siteUrl} · {data.project.market} / {data.project.language}</p></div><button className="primary-action" onClick={audit} disabled={busy}><ArrowClockwise className={busy?"spin":""}/>{busy?"正在诊断…":"运行网站诊断"}</button></div>{error&&<p className="product-error">{error}</p>}
  {active==="总览"&&<Overview data={data} counts={counts} audit={audit}/>} {active==="网站诊断"&&<AuditView data={data}/>} {active==="任务中心"&&<TaskView tasks={data.tasks||[]} decide={decide}/>} {active==="数据连接"&&<Connections items={data.connections||[]}/>} {!["总览","网站诊断","任务中心","数据连接"].includes(active)&&<ProviderModule title={active}/>} </>}
 </div></section>{toast&&<div className="toast"><CheckCircle weight="fill"/>{toast}</div>}</main>
}

function Onboarding({form,setForm,create,busy,error}:{form:ProjectForm;setForm:React.Dispatch<React.SetStateAction<ProjectForm>>;create:(e:React.FormEvent)=>void;busy:boolean;error:string}){return <section className="onboarding"><span className="eyebrow">新项目</span><h1>建立你的 SEO 增长基线</h1><p>添加网站后，OneShowSEO 会先执行公开网页诊断。外部搜索与流量数据需要单独授权。</p><form onSubmit={create}><label>项目名称<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="例如：OneShowSEO 官网" required/></label><label>网站地址<input value={form.siteUrl} onChange={e=>setForm({...form,siteUrl:e.target.value})} placeholder="https://example.com" required/></label><label>目标市场<select value={form.market} onChange={e=>setForm({...form,market:e.target.value})}><option value="CN">中国</option><option value="US">美国</option><option value="GLOBAL">全球</option></select></label><label>主要语言<select value={form.language} onChange={e=>setForm({...form,language:e.target.value})}><option value="zh-CN">简体中文</option><option value="en-US">English</option></select></label><label>变更审批<select value={form.approvalMode} onChange={e=>setForm({...form,approvalMode:e.target.value})}><option value="required">全部需要人工审批</option><option value="low_risk_auto">低风险任务可自动执行</option></select></label>{error&&<p className="product-error">{error}</p>}<button disabled={busy}>{busy?"正在创建…":"创建项目"}<ArrowRight/></button></form></section>}
function Overview({data,counts}:{data:Dashboard;counts:Record<string,number>;audit:()=>void}){const run=data.latestRun;return <><div className="real-metrics"><article><span>SEO 健康分</span><strong>{run?.score??"—"}</strong><small>{run?"最近一次公开网页诊断":"等待首次诊断"}</small></article><article><span>已扫描页面</span><strong>{run?.pagesScanned||0}</strong><small>仅展示真实抓取结果</small></article><article><span>开放问题</span><strong>{data.findings?.length||0}</strong><small>{counts.critical||0} 个严重 · {counts.high||0} 个高优先级</small></article><article><span>待决策任务</span><strong>{(data.tasks||[]).filter(t=>t.status==="proposed").length}</strong><small>执行前需要审批</small></article></div><div className="commercial-grid"><section className="panel"><div className="panel-title"><h2>优先处理的问题</h2><Link href="#" onClick={e=>e.preventDefault()}>基于影响排序</Link></div><FindingRows items={(data.findings||[]).slice(0,6)}/></section><section className="panel"><div className="panel-title"><h2>执行边界</h2></div><div className="trust-list"><p><CheckCircle/>公开网站抓取：已启用</p><p><LockKey/>搜索表现：等待 GSC 授权</p><p><LockKey/>流量与转化：等待 GA4 授权</p><p><LockKey/>自动发布：等待 CMS 授权</p></div></section></div></>}
function AuditView({data}:{data:Dashboard}){return <section className="panel full-panel"><div className="panel-title"><div><h2>最近一次诊断</h2><p>{data.latestRun?`${new Date((data.latestRun.completedAt||0)*1000).toLocaleString()} · ${data.latestRun.pagesScanned} 页 · 健康分 ${data.latestRun.score}`:"尚未运行"}</p></div></div><FindingRows items={data.findings||[]}/></section>}
function FindingRows({items}:{items:Finding[]}){const labels:Record<string,string>={critical:"严重",high:"高",medium:"中",low:"低"};if(!items.length)return <div className="honest-empty"><CheckCircle/>当前没有开放问题。首次诊断后会在这里生成证据和修复建议。</div>;return <div className="finding-list">{items.map(f=><article key={f.id}><em className={`severity ${f.severity}`}>{labels[f.severity]||f.severity}</em><div><strong>{f.title}</strong><p>{f.description}</p><small>{f.url}{f.evidence?` · 证据：${f.evidence}`:""}</small></div></article>)}</div>}
function TaskView({tasks,decide}:{tasks:Task[];decide:(id:string,status:string)=>void}){if(!tasks.length)return <div className="honest-empty"><CheckSquare/>没有待处理任务。运行网站诊断后，问题会转化为可审批任务。</div>;return <section className="panel full-panel"><div className="panel-title"><h2>任务决策队列</h2></div><div className="task-decision-list">{tasks.map(t=><article key={t.id}><span className="priority">P{t.priority}</span><div><strong>{t.title}</strong><p>{t.description}</p><small>状态：{t.status}</small></div>{t.status==="proposed"&&<aside><button onClick={()=>decide(t.id,"dismissed")}>忽略</button><button className="approve" onClick={()=>decide(t.id,"approved")}>批准</button></aside>}</article>)}</div></section>}
function Connections({items}:{items:{provider:string;status:string}[]}){return <div className="connection-grid">{items.map(x=><article key={x.provider}><Globe/><div><strong>{providers[x.provider]||x.provider}</strong><p>{x.provider==="public_crawl"?"无需账户授权，按套餐页面上限抓取公开 HTML。":"连接后才会采集并展示真实数据。"}</p></div><em className={x.status}>{x.status==="connected"?"已连接":"未连接"}</em></article>)}</div>}
function ProviderModule({title}:{title:string}){const copy:{[k:string]:string}={关键词研究:"连接 Google Search Console 与排名数据服务后，系统会生成真实关键词机会池。",竞争对手:"添加竞品并连接 SERP 数据服务后，系统会分析内容与排名缺口。",内容规划:"关键词机会通过审批后，可生成主题集群、页面映射与 Content Brief。","AI 内容生产":"Content Brief 审批后进入内容草稿流程；发布前始终保留人工审核。",项目设置:"项目目标、调度、审批策略和通知规则将在这里管理。"};return <section className="provider-module"><LockKey/><span className="eyebrow">能力边界清晰</span><h2>{title}</h2><p>{copy[title]}</p><button onClick={()=>{}}>前往数据连接</button></section>}
