"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowRight, CalendarBlank, CaretDown, CaretLeft, CaretRight, ChartBar, CheckCircle, ClockCountdown, Eye, FileText, FunnelSimple, Globe, ListBullets, MagnifyingGlass, PaperPlaneTilt, PlugsConnected, Plus, ShieldCheck, Stack, WarningCircle, X } from "@phosphor-icons/react";
import type { Icon as PhosphorIcon } from "@phosphor-icons/react";

export type PublishData = {
  creditCost: number;
  connections: Array<{ id: string; provider: string; state: string; writeEnabled: boolean; baseUrl: string; maskedHint: string; health: string | null; updatedAt: number }>;
  candidates: Array<{ contentTaskId: string; title: string; keyword: string; contentType: string; qualityScore: number; checksPassed: number; checksTotal: number; completedAt: number; artifactId: string | null; reviewStatus: string | null; ready: number }>;
  requests: Array<{ id: string; contentTaskId: string; artifactId: string; connectionId: string; provider: string; title: string; slug: string; excerpt: string; scheduledFor: number | null; status: string; executionTaskId: string | null; externalId: string | null; publishedUrl: string | null; verificationStatus: string; error: string | null; createdAt: number; updatedAt: number; approvalStatus: string | null; executionState: string | null }>;
};

type RequestItem = PublishData["requests"][number];
type Row = { id: string; contentTaskId: string; title: string; keyword: string; contentType: string; qualityScore: number; platform: string; scheduledFor: number | null; status: "draft" | "approval" | "running" | "published" | "failed"; statusLabel: string; publishedUrl: string | null; updatedAt: number; request?: RequestItem };
const emptyData: PublishData = { creditCost: 0, connections: [], candidates: [], requests: [] };
const tabs = ["发布计划", "发布中", "已发布", "失败记录", "草稿箱"] as const;
const typeLabels: Record<string, string> = { blog_post: "博客文章", guide: "指南", landing_page: "落地页", content_refresh: "内容更新" };
const formatDateTime = (value: number | null) => value ? new Date(value * 1000).toLocaleString("zh-CN", { month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" }) : "审批后发布";
const dayKey = (value: Date) => `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, "0")}-${String(value.getDate()).padStart(2, "0")}`;

export default function PublishAgentControl({ projectId, project, data, user, navigate, refresh }: { projectId?: string; project?: { id: string; host?: string }; data?: PublishData; user?: { name: string; email: string }; tasks?: unknown; research?: unknown; navigate: (value: string) => void; refresh: () => Promise<void> }) {
  const projectKey = projectId || project?.id || "";
  const [remote, setRemote] = useState<PublishData | undefined>(data), [loading, setLoading] = useState(true), [error, setError] = useState(""), [success, setSuccess] = useState("");
  const [tab, setTab] = useState<(typeof tabs)[number]>("发布计划"), [query, setQuery] = useState(""), [statusFilter, setStatusFilter] = useState("all"), [typeFilter, setTypeFilter] = useState("all");
  const [calendarMode, setCalendarMode] = useState(false), [calendarCursor, setCalendarCursor] = useState(() => new Date()), [creating, setCreating] = useState(false), [saving, setSaving] = useState(false), [page, setPage] = useState(1);
  const [now] = useState(() => Math.floor(Date.now() / 1000));
  const [form, setForm] = useState({ contentTaskId: "", title: "", slug: "", excerpt: "", scheduledAt: "" });

  const loadPublish = useCallback(async () => { if (!projectKey) return; setLoading(true); try { const response = await fetch(`/api/projects/${projectKey}/publish`, { cache: "no-store" }), result = await response.json(); if (!response.ok) throw new Error(result.error || "发布状态读取失败"); setRemote(result); setError(""); } catch (caught) { setError(caught instanceof Error ? caught.message : "发布状态读取失败"); } finally { setLoading(false); } }, [projectKey]);
  useEffect(() => { const timer = setTimeout(() => void loadPublish(), 0); return () => clearTimeout(timer); }, [loadPublish]);

  const publish = remote || data || emptyData;
  const connection = publish.connections.find((item) => item.state === "connected" && item.writeEnabled);
  const ready = publish.candidates.filter((item) => Boolean(item.ready));
  const requestMap = useMemo(() => new Map(publish.requests.map((item) => [item.contentTaskId, item])), [publish.requests]);
  const rows = useMemo<Row[]>(() => {
    const candidateRows = publish.candidates.map((candidate) => {
      const request = requestMap.get(candidate.contentTaskId); let status: Row["status"] = "draft", statusLabel = candidate.ready ? "待发布" : candidate.reviewStatus === "approved" ? "质量检查中" : "待审核";
      if (request) { if (request.status === "published" && request.verificationStatus === "verified") { status = "published"; statusLabel = "已发布"; } else if (request.status === "failed" || request.verificationStatus === "failed") { status = "failed"; statusLabel = "发布失败"; } else if (["queued", "publishing", "running", "retrying"].includes(request.executionState || request.status)) { status = "running"; statusLabel = "发布中"; } else { status = "approval"; statusLabel = "待审批"; } }
      return { id: request?.id || candidate.contentTaskId, contentTaskId: candidate.contentTaskId, title: candidate.title, keyword: candidate.keyword, contentType: candidate.contentType, qualityScore: candidate.qualityScore, platform: request?.provider === "wordpress" || connection ? "WordPress" : "未选择", scheduledFor: request?.scheduledFor || null, status, statusLabel, publishedUrl: request?.publishedUrl || null, updatedAt: request?.updatedAt || candidate.completedAt, request } as Row;
    });
    const candidateIds = new Set(candidateRows.map((item) => item.contentTaskId));
    const orphans = publish.requests.filter((item) => !candidateIds.has(item.contentTaskId)).map((request) => ({ id: request.id, contentTaskId: request.contentTaskId, title: request.title, keyword: request.slug, contentType: "blog_post", qualityScore: 0, platform: request.provider === "wordpress" ? "WordPress" : request.provider, scheduledFor: request.scheduledFor, status: request.status === "published" ? "published" : request.status === "failed" ? "failed" : ["queued", "publishing"].includes(request.status) ? "running" : "approval", statusLabel: request.status === "published" ? "已发布" : request.status === "failed" ? "发布失败" : ["queued", "publishing"].includes(request.status) ? "发布中" : "待审批", publishedUrl: request.publishedUrl, updatedAt: request.updatedAt, request } as Row));
    return [...candidateRows, ...orphans].sort((a, b) => b.updatedAt - a.updatedAt);
  }, [publish, requestMap, connection]);

  const counts = useMemo(() => ({ pending: rows.filter((row) => row.status === "draft").length, today: rows.filter((row) => row.scheduledFor && dayKey(new Date(row.scheduledFor * 1000)) === dayKey(new Date(now * 1000))).length, weekPublished: rows.filter((row) => row.status === "published" && row.updatedAt >= now - 7 * 86400).length, published: rows.filter((row) => row.status === "published").length, approval: rows.filter((row) => row.status === "approval").length, running: rows.filter((row) => row.status === "running").length, failed: rows.filter((row) => row.status === "failed").length }), [rows, now]);
  const completed = counts.published + counts.failed, successRate = completed ? Math.round((counts.published / completed) * 1000) / 10 : null;
  const filtered = useMemo(() => rows.filter((row) => { const tabMatch = tab === "发布计划" || (tab === "发布中" && row.status === "running") || (tab === "已发布" && row.status === "published") || (tab === "失败记录" && row.status === "failed") || (tab === "草稿箱" && row.status === "draft"), search = query.trim().toLowerCase(); return tabMatch && (statusFilter === "all" || row.status === statusFilter) && (typeFilter === "all" || row.contentType === typeFilter) && (!search || `${row.title} ${row.keyword}`.toLowerCase().includes(search)); }), [rows, tab, statusFilter, typeFilter, query]);
  const pageCount = Math.max(1, Math.ceil(filtered.length / 8)), safePage = Math.min(page, pageCount), visibleRows = filtered.slice((safePage - 1) * 8, safePage * 8);

  const open = () => { if (!connection) { navigate("数据连接"); return; } const item = ready[0]; setForm({ contentTaskId: item?.contentTaskId || "", title: item?.title || "", slug: "", excerpt: "", scheduledAt: "" }); setError(""); setCreating(true); };
  const choose = (contentTaskId: string) => { const item = ready.find((value) => value.contentTaskId === contentTaskId); setForm((current) => ({ ...current, contentTaskId, title: item?.title || "" })); };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const selected = ready.find((item) => item.contentTaskId === form.contentTaskId); if (!connection || !selected?.artifactId) return; setSaving(true); setError(""); try { const response = await fetch(`/api/projects/${projectKey}/publish`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...form, artifactId: selected.artifactId, connectionId: connection.id }) }), result = await response.json(); if (!response.ok) throw new Error(result.error || "发布任务创建失败"); setCreating(false); setSuccess(`发布计划已进入人工审批；批准时预留 ${result.creditsOnApproval} Credits`); await Promise.all([refresh(), loadPublish()]); } catch (caught) { setError(caught instanceof Error ? caught.message : "发布任务创建失败"); } finally { setSaving(false); } };

  const metrics: Array<[PhosphorIcon, string, string | number, string]> = [[ClockCountdown, "待发布内容", counts.pending, "来自 Content Agent"], [CalendarBlank, "今日待发布", counts.today, "按真实排期统计"], [PaperPlaneTilt, "本周已发布", counts.weekPublished, "发布并验证成功"], [CheckCircle, "发布成功率", successRate === null ? "待产生" : `${successRate}%`, "基于已完成任务"], [Eye, "总曝光（近30天）", "待接入", "需要 GSC / GA4"], [ChartBar, "总点击（近30天）", "待接入", "需要 GSC / GA4"]];
  const calendar = useMemo(() => buildCalendar(calendarCursor, rows), [calendarCursor, rows]);
  const upcoming = rows.filter((row) => row.scheduledFor && row.scheduledFor >= now).sort((a, b) => (a.scheduledFor || 0) - (b.scheduledFor || 0)).slice(0, 5);
  const statusBars = [["已发布", counts.published, "#5e50eb"], ["待审批", counts.approval, "#7767ef"], ["发布中", counts.running, "#3d8bed"], ["草稿", counts.pending, "#a0a9bd"], ["失败", counts.failed, "#ed6257"]] as const, totalForBars = Math.max(1, rows.length);

  return <div className="publish-management">
    <header className="publish-management-header"><div><h1>发布管理</h1><p>统一管理内容发布与定时计划；所有外部变更强制人工审批，发布后回读验证。</p></div><aside><button onClick={() => navigate("内容库")}><FileText />内容库</button><button disabled={!ready.length || !connection}><Stack />批量发布 <CaretDown /></button><button className="primary" onClick={open}><Plus />{connection ? "创建发布计划" : "连接发布平台"}<CaretDown /></button></aside></header>
    <div className="publish-management-tabs"><nav>{tabs.map((name) => <button className={tab === name ? "active" : ""} key={name} onClick={() => { setTab(name); setPage(1); }}>{name}</button>)}</nav></div>
    {error && <div className="publish-management-alert"><WarningCircle weight="fill" />{error}<button onClick={() => void loadPublish()}>重试</button></div>}{success && <div className="publish-management-alert success"><CheckCircle weight="fill" />{success}<button aria-label="关闭" onClick={() => setSuccess("")}><X /></button></div>}
    {!connection && <div className="publish-management-setup"><PlugsConnected /><span><strong>发布通道尚未连接</strong><small>连接具有内容写入权限的 WordPress 后，才可以创建真实发布计划。</small></span><button onClick={() => navigate("数据连接")}>连接 WordPress <ArrowRight /></button></div>}
    <section className="publish-management-metrics">{metrics.map(([Icon, label, value, hint]) => <article key={label}><div><small>{label}</small><strong>{loading ? "—" : value}</strong><p>{hint}</p></div><span><Icon weight="duotone" /></span></article>)}</section>
    <section className="publish-management-filters"><select aria-label="筛选平台" disabled={!connection}><option>全部平台</option>{connection && <option>WordPress</option>}</select><select aria-label="筛选状态" value={statusFilter} onChange={(event) => { setStatusFilter(event.target.value); setPage(1); }}><option value="all">全部状态</option><option value="draft">草稿</option><option value="approval">待审批</option><option value="running">发布中</option><option value="published">已发布</option><option value="failed">失败</option></select><select aria-label="筛选内容类型" value={typeFilter} onChange={(event) => { setTypeFilter(event.target.value); setPage(1); }}><option value="all">全部内容类型</option>{Object.entries(typeLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><button disabled>全部负责人 <CaretDown /></button><button disabled><CalendarBlank />日期范围 <CaretDown /></button><label><MagnifyingGlass /><input value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} placeholder="搜索标题或关键词" /></label><button className="clear" onClick={() => { setStatusFilter("all"); setTypeFilter("all"); setQuery(""); }}><FunnelSimple />清空</button><button className={calendarMode ? "active" : ""} onClick={() => setCalendarMode((value) => !value)}><CalendarBlank />{calendarMode ? "列表视图" : "日历视图"}</button></section>
    <div className={`publish-management-layout ${calendarMode ? "calendar-only" : ""}`}>
      {!calendarMode && <main className="publish-plan-list"><header><h2>发布计划列表</h2><span>{filtered.length} 条真实记录</span></header><div className="publish-plan-table"><div className="head"><span>内容</span><span>平台</span><span>计划发布时间</span><span>状态</span><span>负责人</span><span>操作</span></div>{visibleRows.map((row) => <article key={row.id}><div className="content"><span><FileText weight="duotone" /></span><p><strong>{row.title}</strong><small>{row.keyword || typeLabels[row.contentType] || "内容资产"} · 质量分 {row.qualityScore || "待记录"}</small></p></div><span className="platform"><Globe />{row.platform}</span><time>{formatDateTime(row.scheduledFor)}</time><em className={row.status}>{row.statusLabel}</em><span className="owner"><i>{(user?.name || user?.email || "U").slice(0, 1).toUpperCase()}</i>{user?.name || user?.email || "当前成员"}</span><div className="actions">{row.publishedUrl ? <a href={row.publishedUrl} target="_blank" rel="noreferrer" aria-label={`打开 ${row.title}`}><Eye /></a> : <button onClick={() => row.status === "draft" ? open() : navigate("审批中心")} aria-label={`查看 ${row.title}`}><Eye /></button>}<button onClick={() => navigate("任务中心")} aria-label={`查看任务 ${row.title}`}><ListBullets /></button></div></article>)}</div>{!loading && !visibleRows.length && <div className="publish-plan-empty"><PaperPlaneTilt weight="duotone" /><strong>暂无发布计划</strong><p>{!connection ? "先连接 WordPress，再把通过审核的内容加入发布计划。" : !ready.length ? "Content Agent 的内容通过质量检查和人工审核后会出现在这里。" : "选择已批准内容，创建第一条发布计划。"}</p><button onClick={open}>{!connection ? "连接 WordPress" : !ready.length ? "查看内容库" : "创建发布计划"}</button></div>}<footer><span>共 {filtered.length} 条</span><nav><button disabled={safePage <= 1} onClick={() => setPage((value) => Math.max(1, value - 1))}><CaretLeft /></button>{Array.from({ length: Math.min(pageCount, 5) }, (_, index) => index + 1).map((value) => <button key={value} className={safePage === value ? "active" : ""} onClick={() => setPage(value)}>{value}</button>)}<button disabled={safePage >= pageCount} onClick={() => setPage((value) => Math.min(pageCount, value + 1))}><CaretRight /></button></nav></footer></main>}
      <section className="publish-calendar"><header><h2>发布日历</h2><div><button onClick={() => setCalendarCursor(new Date())}>今天</button><button aria-label="上个月" onClick={() => setCalendarCursor((value) => new Date(value.getFullYear(), value.getMonth() - 1, 1))}><CaretLeft /></button><button aria-label="下个月" onClick={() => setCalendarCursor((value) => new Date(value.getFullYear(), value.getMonth() + 1, 1))}><CaretRight /></button><strong>{calendarCursor.getFullYear()}年 {calendarCursor.getMonth() + 1}月</strong></div></header><div className="calendar-week"><span>一</span><span>二</span><span>三</span><span>四</span><span>五</span><span>六</span><span>日</span></div><div className="calendar-grid">{calendar.map((item) => <article key={item.key} className={`${item.current ? "" : "muted"} ${item.today ? "today" : ""}`}><b>{item.date.getDate()}</b>{item.items.length > 0 && <span className={item.items.some((row) => row.status === "published") ? "published" : "pending"}>{item.items.length} 项</span>}</article>)}</div><footer><span><i className="published" />已发布</span><span><i className="pending" />待发布</span><button>查看完整日历 <ArrowRight /></button></footer></section>
      <aside className="publish-management-side"><section className="platforms"><header><h2>平台分布</h2></header>{connection ? <div className="publish-platform-donut"><div><span><strong>{rows.length}</strong><small>计划总数</small></span></div><ul><li><i /><span>WordPress</span><b>{rows.length}</b><small>100%</small></li></ul></div> : <SideEmpty icon={Globe} text="连接发布平台后展示分布" />}</section><section className="status"><header><h2>发布状态分布</h2></header><div>{statusBars.map(([label, value, color]) => <article key={label}><span>{label}</span><i><b style={{ width: `${Math.max(value ? 8 : 0, (value / totalForBars) * 100)}%`, background: color }} /></i><em>{value}</em></article>)}</div></section><section className="results"><header><h2>最近发布效果（近7天）</h2></header><SideEmpty icon={ChartBar} text="连接 GSC / GA4 后展示曝光、点击和转化" /><button onClick={() => navigate("数据连接")}>连接效果数据 <ArrowRight /></button></section></aside>
    </div>
    <section className="publish-upcoming"><header><h2>即将发布（接下来 24 小时）</h2></header>{upcoming.length ? upcoming.map((row) => <article key={row.id}><time>{new Date((row.scheduledFor || 0) * 1000).toLocaleTimeString("zh-CN", { hour: "2-digit", minute: "2-digit" })}</time><strong>{row.title}</strong><span><Globe />{row.platform}</span></article>) : <div><ClockCountdown weight="duotone" /><p>未来 24 小时没有已批准的发布计划。</p></div>}</section>
    {creating && <div className="publish-create-backdrop" onMouseDown={(event) => event.target === event.currentTarget && setCreating(false)}><section className="publish-create-modal" role="dialog" aria-modal="true" aria-labelledby="publish-create-title"><header><div><span><PaperPlaneTilt /></span><div><h2 id="publish-create-title">创建发布计划</h2><p>提交后进入人工审批，不会立即修改外部网站。</p></div></div><button aria-label="关闭" onClick={() => setCreating(false)}><X /></button></header><form onSubmit={submit}><label>已批准内容<select value={form.contentTaskId} onChange={(event) => choose(event.target.value)} required><option value="">选择 Content Agent 草稿</option>{ready.map((item) => <option value={item.contentTaskId} key={item.contentTaskId}>{item.title} · 质量分 {item.qualityScore}</option>)}</select></label><label>发布标题<input value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} required maxLength={160} /></label><div><label>URL Slug（可选）<input value={form.slug} onChange={(event) => setForm({ ...form, slug: event.target.value.toLowerCase().replace(/[^a-z0-9-]/g, "") })} placeholder="seo-content-guide" /></label><label>发布时间（可选）<input type="datetime-local" value={form.scheduledAt} onChange={(event) => setForm({ ...form, scheduledAt: event.target.value })} /></label></div><label>摘要（可选）<textarea value={form.excerpt} onChange={(event) => setForm({ ...form, excerpt: event.target.value })} maxLength={500} /></label><aside><ShieldCheck />执行前需要人工审批；批准时预留 {publish.creditCost} Credits，失败后自动释放。</aside>{error && <p className="form-error"><WarningCircle />{error}</p>}<footer><button type="button" onClick={() => setCreating(false)}>取消</button><button className="primary" disabled={saving || !form.contentTaskId}>{saving ? "正在提交…" : "提交发布审批"}</button></footer></form></section></div>}
  </div>;
}

function buildCalendar(cursor: Date, rows: Row[]) { const first = new Date(cursor.getFullYear(), cursor.getMonth(), 1), mondayOffset = (first.getDay() + 6) % 7, start = new Date(cursor.getFullYear(), cursor.getMonth(), 1 - mondayOffset); return Array.from({ length: 42 }, (_, index) => { const date = new Date(start.getFullYear(), start.getMonth(), start.getDate() + index), key = dayKey(date); return { key, date, current: date.getMonth() === cursor.getMonth(), today: key === dayKey(new Date()), items: rows.filter((row) => row.scheduledFor && dayKey(new Date(row.scheduledFor * 1000)) === key) }; }); }
function SideEmpty({ icon: Icon, text }: { icon: PhosphorIcon; text: string }) { return <div className="publish-side-empty"><Icon weight="duotone" /><span>{text}</span></div>; }
