"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { ArrowRight,Bell,CalendarBlank,CaretRight,CheckCircle,ClockCountdown,FileText,Gear,Globe,Info,LinkSimple,LockKey,PaperPlaneTilt,PlugsConnected,Plus,ShieldCheck,WarningCircle,X } from "@phosphor-icons/react";
import type { Icon as PhosphorIcon } from "@phosphor-icons/react";

export type PublishData={creditCost:number;connections:Array<{id:string;provider:string;state:string;writeEnabled:boolean;baseUrl:string;maskedHint:string;health:string|null;updatedAt:number}>;candidates:Array<{contentTaskId:string;title:string;keyword:string;contentType:string;qualityScore:number;checksPassed:number;checksTotal:number;completedAt:number;artifactId:string|null;reviewStatus:string|null;ready:number}>;requests:Array<{id:string;contentTaskId:string;artifactId:string;connectionId:string;provider:string;title:string;slug:string;excerpt:string;scheduledFor:number|null;status:string;executionTaskId:string|null;externalId:string|null;publishedUrl:string|null;verificationStatus:string;error:string|null;createdAt:number;updatedAt:number;approvalStatus:string|null;executionState:string|null}>};

const labels:Record<string,string>={awaiting_approval:"待审批",queued:"等待执行",publishing:"发布中",published:"已发布",failed:"失败",cancelled:"已取消",completed:"已完成",running:"执行中",retrying:"重试中",quarantined:"人工处理"};
const formatTime=(value:number|null)=>value?new Date(value*1000).toLocaleString("zh-CN",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}):"审批后立即执行";

export default function PublishAgentControl({projectId,project,data,navigate,refresh}:{projectId?:string;project?:{id:string};data?:PublishData;tasks?:unknown;research?:unknown;navigate:(value:string)=>void;refresh:()=>Promise<void>}){
 const projectKey=projectId||project?.id||"",[remote,setRemote]=useState<PublishData|undefined>(data),loadPublish=useCallback(async()=>{if(!projectKey)return;const response=await fetch(`/api/projects/${projectKey}/publish`,{cache:"no-store"}),result=await response.json();if(!response.ok)throw new Error(result.error||"发布状态读取失败");setRemote(result)},[projectKey,setRemote]);useEffect(()=>{const timer=setTimeout(()=>loadPublish().catch(()=>{}),0);return()=>clearTimeout(timer)},[loadPublish]);const publish=remote||data||{creditCost:5,connections:[],candidates:[],requests:[]},ready=publish.candidates.filter(item=>Boolean(item.ready)),connection=publish.connections.find(item=>item.state==="connected"&&item.writeEnabled),[creating,setCreating]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState(""),[form,setForm]=useState({contentTaskId:"",title:"",slug:"",excerpt:"",scheduledAt:""});
 const selected=publish.candidates.find(item=>item.contentTaskId===form.contentTaskId),counts=useMemo(()=>({approval:publish.requests.filter(item=>item.status==="awaiting_approval").length,execution:publish.requests.filter(item=>["queued","publishing"].includes(item.status)).length,published:publish.requests.filter(item=>item.status==="published"&&item.verificationStatus==="verified").length,failed:publish.requests.filter(item=>item.status==="failed").length}),[publish.requests]);
 const open=()=>{if(!connection){navigate("数据连接");return;}const item=ready[0];setForm({contentTaskId:item?.contentTaskId||"",title:item?.title||"",slug:"",excerpt:"",scheduledAt:""});setError("");setCreating(true)};
 const submit=async(event:React.FormEvent)=>{event.preventDefault();if(!connection||!selected?.artifactId)return;setSaving(true);setError("");try{const response=await fetch(`/api/projects/${projectKey}/publish`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,artifactId:selected.artifactId,connectionId:connection.id})}),result=await response.json();if(!response.ok)throw new Error(result.error||"发布任务创建失败");setCreating(false);setSuccess(`已提交人工审批；批准时预留 ${result.creditsOnApproval} Credits`);await Promise.all([refresh(),loadPublish()]);setTimeout(()=>setSuccess(""),3500);}catch(caught){setError(caught instanceof Error?caught.message:"发布任务创建失败");}finally{setSaving(false)}};
 const choose=(contentTaskId:string)=>{const item=ready.find(value=>value.contentTaskId===contentTaskId);setForm(current=>({...current,contentTaskId,title:item?.title||""}))};
 const last=publish.requests[0]?.updatedAt||Math.max(0,...publish.candidates.map(item=>item.completedAt||0));
 return <div className="publish-v2-page">
  <header className="publish-v2-header"><div><p>AI Agents <CaretRight/> <strong>Publish Agent</strong></p><div><h1>Publish Agent</h1><span className={connection?"ready":"needs-setup"}>{connection?<CheckCircle weight="fill"/>:<WarningCircle weight="fill"/>}{connection?"发布通道就绪":"需要连接 CMS"}</span></div><small>审批后安全发布、验证外部结果，并为每一次变更保留证据。</small></div><aside><button aria-label="通知"><Bell/></button><span>{last?`最近活动：${new Date(last*1000).toLocaleString("zh-CN")}`:"尚无发布活动"}</span><button onClick={()=>navigate("项目设置")}><Gear/>发布设置</button><button className="primary" onClick={open}>{connection?<><Plus/>创建发布任务</>:<><PlugsConnected/>连接 WordPress</>}</button></aside></header>
  {success&&<div className="publish-v2-alert success"><CheckCircle weight="fill"/>{success}<button onClick={()=>setSuccess("")}><X/></button></div>}
  <section className="publish-v2-overview">
   <article className="publish-v2-score"><div className={connection&&ready.length?"complete":"partial"}><strong>{[Boolean(connection),ready.length>0,counts.approval===0].filter(Boolean).length}</strong><small>/3</small></div><div><span>发布准备度</span><h2>{!connection?"先连接 WordPress，发布动作才会开放。":!ready.length?"等待 Content Agent 草稿通过质量检查与人工审核。":"发布条件已具备，可以提交新的发布审批。"}</h2><p>系统只接受已生成、质量检查全部通过并经过人工审核的内容，不会把研究机会直接发布。</p></div></article>
   <article className="publish-v2-gates"><h3>发布前闸门</h3><div className={connection?"pass":"blocked"}><span>{connection?<CheckCircle/>:<PlugsConnected/>}</span><p><strong>CMS 写入权限</strong><small>{connection?`${connection.baseUrl} · ${connection.maskedHint}`:"尚未连接支持写入的 WordPress"}</small></p><em>{connection?"通过":"需配置"}</em></div><div className={ready.length?"pass":"blocked"}><span>{ready.length?<CheckCircle/>:<FileText/>}</span><p><strong>已批准内容</strong><small>{ready.length?`${ready.length} 个草稿可以进入发布审批`:"等待内容质量闸门与人工审核"}</small></p><em>{ready.length?"通过":"等待"}</em></div><div className="pass"><span><ShieldCheck/></span><p><strong>强制人工审批</strong><small>平台、URL、排期与 Credits 都会在执行前确认</small></p><em>已启用</em></div></article>
  </section>
  <section className="publish-v2-metrics">{([[FileText,"可发布内容",ready.length,"来自 Content Agent"],[ClockCountdown,"待人工审批",counts.approval,"执行前必须确认"],[PaperPlaneTilt,"执行队列",counts.execution,"Worker 实时状态"],[CheckCircle,"已发布并验证",counts.published,"具有外部发布证据"]] as Array<[PhosphorIcon,string,number,string]>).map(([Icon,label,value,hint])=><article key={label}><span><Icon weight="duotone"/></span><div><small>{label}</small><strong>{value}</strong><p>{hint}</p></div></article>)}</section>
  <div className="publish-v2-layout"><main>
   <section className="publish-v2-panel publish-v2-flow"><header><div><span>CONTROLLED WORKFLOW</span><h2>安全发布流程</h2></div><button onClick={()=>navigate("任务中心")}>打开 Approval Center <ArrowRight/></button></header><div>{([[FileText,"内容已批准",ready.length?"已具备":"等待内容"],[ShieldCheck,"发布审批",counts.approval?`${counts.approval} 项待处理`:"强制人工确认"],[CalendarBlank,"排期与执行",counts.execution?`${counts.execution} 项处理中`:"批准后进入 Worker"],[Globe,"CMS 发布",counts.published?`${counts.published} 次成功`:"等待执行"],[CheckCircle,"结果验证",counts.published?"已保存证据":"发布后自动验证"]] as Array<[PhosphorIcon,string,string]>).map(([Icon,title,status],index)=><article key={title} className={(index===0&&ready.length>0)||(index>0&&counts.published>0)?"done":""}><span><Icon/></span><strong>{title}</strong><small>{status}</small>{index<4&&<CaretRight/>}</article>)}</div></section>
   <section className="publish-v2-panel publish-v2-queue"><header><div><span>EXECUTION QUEUE</span><h2>发布任务</h2><p>状态来自审批记录、持久化任务、Worker 与外部验证结果。</p></div><button onClick={open} disabled={!connection||!ready.length}><Plus/>新建发布审批</button></header>{publish.requests.length?<div className="publish-v2-table"><div className="head"><span>内容</span><span>平台</span><span>执行时间</span><span>审批 / 执行</span><span>验证</span><span>结果</span></div>{publish.requests.slice(0,8).map(item=><article key={item.id}><div><FileText/><p><strong>{item.title}</strong><small>/{item.slug||"CMS 自动生成"}</small></p></div><span><Globe/>WordPress</span><time>{formatTime(item.scheduledFor)}</time><em className={item.status}>{labels[item.executionState||item.status]||labels[item.status]||item.status}</em><em className={item.verificationStatus}>{item.verificationStatus==="verified"?"已验证":item.verificationStatus==="failed"?"验证失败":"待验证"}</em>{item.publishedUrl?<a href={item.publishedUrl} target="_blank" rel="noreferrer">查看页面 <ArrowRight/></a>:<button onClick={()=>navigate("任务中心")}>{item.status==="awaiting_approval"?"去审批":"查看任务"}</button>}</article>)}</div>:<div className="publish-v2-empty"><PaperPlaneTilt weight="duotone"/><strong>还没有发布任务</strong><p>{!connection?"连接 WordPress 后，才能创建真实发布任务。":!ready.length?"内容通过质量检查和人工审核后会出现在这里。":"从已批准内容创建第一个发布审批。"}</p><button onClick={open}>{!connection?"连接 WordPress":!ready.length?"查看内容流程":"创建发布任务"}</button></div>}</section>
  </main><aside>
   <section className="publish-v2-panel publish-v2-ready"><header><span><LockKey/></span><div><small>AI-RECOMMENDED NEXT STEP</small><h2>{!connection?"连接安全发布通道":!ready.length?"完成内容审批":"提交发布审批"}</h2></div></header><p>{!connection?"使用 WordPress 应用密码建立最小权限连接；密钥只保存在加密凭据库中。":!ready.length?"只有 Content Agent 的最终草稿通过全部检查和人工审核后，才会进入这里。":"选择目标内容、URL Slug 和发布时间，再由 Approval Center 完成最终确认。"}</p><dl><div><dt>单次执行</dt><dd>{publish.creditCost} Credits</dd></div><div><dt>外部修改</dt><dd>必须审批</dd></div><div><dt>验证方式</dt><dd>发布后回读</dd></div></dl><button onClick={!connection?()=>navigate("数据连接"):!ready.length?()=>navigate("内容规划"):open}>{!connection?"连接 WordPress":!ready.length?"返回 Content Agent":"创建发布审批"}<ArrowRight/></button></section>
   <section className="publish-v2-panel publish-v2-evidence"><header><h2>执行保障</h2></header>{([[ShieldCheck,"权限复核","执行时再次确认成员和项目权限"],[LinkSimple,"防止重复发布","Slug 与内容摘要用于幂等校验"],[ClockCountdown,"失败恢复","超时自动重试，最终失败释放 Credits"],[CheckCircle,"结果证据","保存外部 ID、页面 URL 和内容哈希"]] as Array<[PhosphorIcon,string,string]>).map(([Icon,title,detail])=><article key={title}><span><Icon/></span><p><strong>{title}</strong><small>{detail}</small></p></article>)}</section>
  </aside></div>
  {creating&&<div className="publish-v2-modal-backdrop" onMouseDown={event=>event.target===event.currentTarget&&setCreating(false)}><section className="publish-v2-modal" role="dialog" aria-modal="true" aria-labelledby="publish-create-title"><header><div><span><PaperPlaneTilt/></span><div><h2 id="publish-create-title">创建发布审批</h2><p>提交后不会立即改动网站，需要在 Approval Center 明确批准。</p></div></div><button aria-label="关闭" onClick={()=>setCreating(false)}><X/></button></header><form onSubmit={submit}><label>已批准内容<select value={form.contentTaskId} onChange={event=>choose(event.target.value)} required><option value="">选择 Content Agent 草稿</option>{ready.map(item=><option value={item.contentTaskId} key={item.contentTaskId}>{item.title} · 质量分 {item.qualityScore}</option>)}</select></label><label>发布标题<input value={form.title} onChange={event=>setForm({...form,title:event.target.value})} required maxLength={160}/></label><div><label>URL Slug（可选）<input value={form.slug} onChange={event=>setForm({...form,slug:event.target.value.toLowerCase().replace(/[^a-z0-9-]/g,"")})} placeholder="ai-seo-guide"/><small>留空时由 WordPress 自动生成</small></label><label>发布时间（可选）<input type="datetime-local" value={form.scheduledAt} onChange={event=>setForm({...form,scheduledAt:event.target.value})}/><small>留空表示审批后立即执行</small></label></div><label>摘要（可选）<textarea value={form.excerpt} onChange={event=>setForm({...form,excerpt:event.target.value})} maxLength={500} placeholder="用于 WordPress 摘要和审批预览"/></label><aside><Info/>批准时将预留 {publish.creditCost} Credits；发布失败会自动释放。</aside>{error&&<p className="publish-v2-form-error"><WarningCircle/>{error}</p>}<footer><button type="button" onClick={()=>setCreating(false)}>取消</button><button className="primary" disabled={saving||!form.contentTaskId}>{saving?"正在提交…":"提交人工审批"}</button></footer></form></section></div>}
 </div>;
}
