import{createHash}from"node:crypto";
export type TelemetryKind="http"|"job"|"provider"|"billing"|"webhook"|"notification";
export type TelemetryOutcome="success"|"failure"|"degraded";
export type TelemetryEvent={id:string;kind:TelemetryKind;service:string;operation:string;outcome:TelemetryOutcome;durationMs:number|null;errorCode:string|null;organizationId:string|null;projectId:string|null;correlationId:string;traceId:string;spanId:string;parentSpanId:string|null;attributes:Record<string,unknown>;occurredAt:number};
export type SloDefinition={key:string;kind:TelemetryKind;targetPercent:number;windowSeconds:number;minimumSamples:number};
export type SliResult={key:string;state:"healthy"|"breached"|"insufficient_data";targetPercent:number;actualPercent:number|null;samples:number;failures:number;windowStart:number;windowEnd:number};
export interface ObservabilityRepository{append(event:TelemetryEvent):void;eventsSince(since:number):TelemetryEvent[];timeline(correlationId:string,limit:number):TelemetryEvent[];putAlert(input:{id:string;sloKey:string;state:"open"|"resolved";summary:string;correlationId:string;createdAt:number;resolvedAt:number|null}):void;}
export const platformSlos:SloDefinition[]=[{key:"web_availability",kind:"http",targetPercent:99.9,windowSeconds:30*86400,minimumSamples:20},{key:"job_success",kind:"job",targetPercent:99,windowSeconds:7*86400,minimumSamples:20},{key:"provider_success",kind:"provider",targetPercent:98,windowSeconds:86400,minimumSamples:20},{key:"webhook_delivery",kind:"webhook",targetPercent:99,windowSeconds:7*86400,minimumSamples:20}];
const sensitive=/secret|token|password|authorization|cookie|content|prompt|credential/i,secretValue=/(bearer\s+\S+|osseo_live_[a-z0-9_]+|whsec_[a-z0-9_-]+)/i;
export function redactTelemetry(value:unknown,depth=0):unknown{if(depth>5)return"[TRUNCATED]";if(Array.isArray(value))return value.slice(0,50).map(item=>redactTelemetry(item,depth+1));if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value as Record<string,unknown>).map(([key,item])=>[key,sensitive.test(key)?"[REDACTED]":redactTelemetry(item,depth+1)]));if(typeof value==="string")return secretValue.test(value)?"[REDACTED]":value.slice(0,500);return value;}
export function errorFingerprint(service:string,operation:string,errorCode:string){return createHash("sha256").update(`${service}:${operation}:${errorCode}`).digest("hex").slice(0,24);}
export class ObservabilityService{
 constructor(private readonly repository:ObservabilityRepository,private readonly now=()=>Math.floor(Date.now()/1000)){}
 record(input:Omit<TelemetryEvent,"id"|"traceId"|"spanId"|"attributes"|"occurredAt">&Partial<Pick<TelemetryEvent,"traceId"|"spanId"|"attributes"|"occurredAt">>){if(!/^[A-Za-z0-9][A-Za-z0-9._:-]{7,127}$/.test(input.correlationId))throw new Error("INVALID_CORRELATION_ID");const event:TelemetryEvent={...input,id:crypto.randomUUID(),traceId:input.traceId??input.correlationId,spanId:input.spanId??crypto.randomUUID(),attributes:redactTelemetry(input.attributes??{})as Record<string,unknown>,occurredAt:input.occurredAt??this.now()};this.repository.append(event);return event;}
 dashboard(at=this.now()){const oldest=Math.min(...platformSlos.map(slo=>at-slo.windowSeconds)),events=this.repository.eventsSince(oldest),slis=platformSlos.map(slo=>{const windowStart=at-slo.windowSeconds,matched=events.filter(event=>event.kind===slo.kind&&event.occurredAt>=windowStart&&event.occurredAt<=at),failures=matched.filter(event=>event.outcome==="failure").length,actualPercent=matched.length?Number((((matched.length-failures)/matched.length)*100).toFixed(3)):null,state=matched.length<slo.minimumSamples?"insufficient_data"as const:actualPercent!>=slo.targetPercent?"healthy"as const:"breached"as const;const result:SliResult={key:slo.key,state,targetPercent:slo.targetPercent,actualPercent,samples:matched.length,failures,windowStart,windowEnd:at};if(state==="breached")this.repository.putAlert({id:`slo:${slo.key}:${windowStart}`,sloKey:slo.key,state:"open",summary:`${slo.key} ${actualPercent}% < ${slo.targetPercent}%`,correlationId:`slo:${slo.key}:${at}`,createdAt:at,resolvedAt:null});return result;});return{capturedAt:at,slis};}
 timeline(correlationId:string,limit=100){return this.repository.timeline(correlationId,Math.max(1,Math.min(500,limit)));}
}
