import{createHash}from"node:crypto";
export type PrivacyRequestType="organization_export"|"credential_erasure"|"project_deletion"|"account_deletion";
export type PrivacyRequest={id:string;organizationId:string;accountId:string;projectId:string|null;type:PrivacyRequestType;state:"requested"|"awaiting_approval"|"processing"|"completed"|"denied"|"failed";reason:string;approvalReference:string|null;artifactId:string|null;correlationId:string;requestedAt:number;completedAt:number|null};
export type RetentionPolicy={organizationId:string;defaultDays:number;artifactDays:number;auditDays:number;legalHold:boolean;legalHoldReason:string|null;updatedByAccountId:string;updatedAt:number};
export interface PrivacyRepository{policy(organizationId:string):RetentionPolicy|null;putPolicy(value:RetentionPolicy):void;request(value:PrivacyRequest):void;requestById(organizationId:string,id:string):PrivacyRequest|null;updateRequest(value:PrivacyRequest):void;exportBundle(organizationId:string):Record<string,unknown>;putExport(input:{id:string;requestId:string;organizationId:string;objectKey:string;sha256:string;sizeBytes:number;expiresAt:number;createdAt:number}):void;eraseCredentials(organizationId:string,now:number):number;tombstoneProject(organizationId:string,projectId:string,now:number):boolean;tombstoneAccount(organizationId:string,accountId:string,now:number):boolean;expiredArtifacts(now:number,limit:number):Array<{id:string;organizationId:string;objectKey:string}>;recordArtifactExpiry(id:string,organizationId:string,now:number):void;}
export interface PrivacyArtifactWriter{write(objectKey:string,body:Uint8Array):Promise<void>;remove(objectKey:string):Promise<void>;}
export type PrivacyReleaseGates={exportsEnabled:boolean;credentialErasureEnabled:boolean;destructiveDeletionEnabled:boolean};
export class PrivacyError extends Error{constructor(readonly code:"OWNER_REQUIRED"|"CONFIRMATION_MISMATCH"|"REASON_REQUIRED"|"LEGAL_HOLD"|"RELEASE_DISABLED"|"REQUEST_NOT_FOUND"|"APPROVAL_REQUIRED",message:string){super(message);}}
const safe=(value:unknown,depth=0):unknown=>{if(depth>8)return"[TRUNCATED]";if(Array.isArray(value))return value.map(item=>safe(item,depth+1));if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value as Record<string,unknown>).filter(([key])=>!/secret|hash|token|password|authorization|cookie|envelope|security/i.test(key)).map(([key,item])=>[key,safe(item,depth+1)]));return typeof value==="string"?value.slice(0,20_000):value;};
export class PrivacyOperationsService{
 constructor(private readonly repository:PrivacyRepository,private readonly writer:PrivacyArtifactWriter,private readonly gates:PrivacyReleaseGates,private readonly now=()=>Math.floor(Date.now()/1000)){}
 updatePolicy(actor:{accountId:string;role:string;organizationId:string},input:{defaultDays:number;artifactDays:number;auditDays:number;legalHold:boolean;legalHoldReason?:string|null}){if(!["owner","security"].includes(actor.role))throw new PrivacyError("OWNER_REQUIRED","需要所有者或安全角色");if(![input.defaultDays,input.artifactDays,input.auditDays].every(value=>Number.isInteger(value)&&value>=1&&value<=3650))throw new Error("INVALID_RETENTION");if(input.legalHold&&!(input.legalHoldReason?.trim()&&input.legalHoldReason.trim().length>=8))throw new PrivacyError("REASON_REQUIRED","法律保留必须填写理由");const value:RetentionPolicy={organizationId:actor.organizationId,...input,legalHoldReason:input.legalHold?input.legalHoldReason!.trim():null,updatedByAccountId:actor.accountId,updatedAt:this.now()};this.repository.putPolicy(value);return value;}
 private authorize(actor:{accountId:string;role:string;organizationId:string},reason:string,confirmation:string,target:string){if(actor.role!=="owner")throw new PrivacyError("OWNER_REQUIRED","仅组织所有者可以申请");if(reason.trim().length<8||reason.trim().length>500)throw new PrivacyError("REASON_REQUIRED","必须填写 8–500 字理由");if(confirmation!==target)throw new PrivacyError("CONFIRMATION_MISMATCH","确认内容不匹配");}
 async exportOrganization(actor:{accountId:string;role:string;organizationId:string},input:{reason:string;confirmation:string;correlationId:string}){this.authorize(actor,input.reason,input.confirmation,actor.organizationId);if(!this.gates.exportsEnabled)throw new PrivacyError("RELEASE_DISABLED","组织导出尚未通过发布门禁");const now=this.now(),id=crypto.randomUUID(),body=new TextEncoder().encode(JSON.stringify({schemaVersion:"1",organizationId:actor.organizationId,exportedAt:now,data:safe(this.repository.exportBundle(actor.organizationId))})),hash=createHash("sha256").update(body).digest("hex"),objectKey=`oneshowseo/${actor.organizationId}/exports/${id}.json`,request:PrivacyRequest={id,organizationId:actor.organizationId,accountId:actor.accountId,projectId:null,type:"organization_export",state:"processing",reason:input.reason.trim(),approvalReference:null,artifactId:null,correlationId:input.correlationId,requestedAt:now,completedAt:null};this.repository.request(request);await this.writer.write(objectKey,body);const artifactId=crypto.randomUUID();this.repository.putExport({id:artifactId,requestId:id,organizationId:actor.organizationId,objectKey,sha256:hash,sizeBytes:body.byteLength,expiresAt:now+7*86400,createdAt:now});const completed={...request,state:"completed"as const,artifactId,completedAt:now};this.repository.updateRequest(completed);return{request:completed,artifact:{id:artifactId,sha256:hash,sizeBytes:body.byteLength,expiresAt:now+7*86400}};}
 requestDestructive(actor:{accountId:string;role:string;organizationId:string},input:{type:Exclude<PrivacyRequestType,"organization_export">;projectId?:string|null;reason:string;confirmation:string;correlationId:string}){const target=input.type==="project_deletion"?input.projectId||"":actor.organizationId;this.authorize(actor,input.reason,input.confirmation,target);const request:PrivacyRequest={id:crypto.randomUUID(),organizationId:actor.organizationId,accountId:actor.accountId,projectId:input.projectId??null,type:input.type,state:"awaiting_approval",reason:input.reason.trim(),approvalReference:null,artifactId:null,correlationId:input.correlationId,requestedAt:this.now(),completedAt:null};this.repository.request(request);return request;}
 execute(requestId:string,organizationId:string,approvalReference:string){const request=this.repository.requestById(organizationId,requestId);if(!request)throw new PrivacyError("REQUEST_NOT_FOUND","请求不存在");if(!approvalReference.trim())throw new PrivacyError("APPROVAL_REQUIRED","缺少审批凭据");if(this.repository.policy(organizationId)?.legalHold)throw new PrivacyError("LEGAL_HOLD","法律保留期间禁止擦除或删除");const credential=request.type==="credential_erasure";if(credential?!this.gates.credentialErasureEnabled:!this.gates.destructiveDeletionEnabled)throw new PrivacyError("RELEASE_DISABLED","该不可逆操作尚未通过发布门禁");const now=this.now();if(credential)this.repository.eraseCredentials(organizationId,now);else if(request.type==="project_deletion"&&request.projectId)this.repository.tombstoneProject(organizationId,request.projectId,now);else if(request.type==="account_deletion")this.repository.tombstoneAccount(organizationId,request.accountId,now);const completed={...request,state:"completed"as const,approvalReference,completedAt:now};this.repository.updateRequest(completed);return completed;}
 async expireArtifacts(limit=100){const now=this.now(),items=this.repository.expiredArtifacts(now,limit),expired:string[]=[];for(const item of items){if(this.repository.policy(item.organizationId)?.legalHold)continue;await this.writer.remove(item.objectKey);this.repository.recordArtifactExpiry(item.id,item.organizationId,now);expired.push(item.id);}return expired;}
}
