import { NextResponse } from "next/server";
import { getCurrentUser, getDatabase, writeAudit } from "../../../../lib/auth";
import { authorizeOperator, operatorAdministration } from "../../../../lib/operator-administration";
import { OperatorAuthorizationError, type OperatorRole } from "../../../../platform/modules/operations/administration";

const roles = new Set<OperatorRole>(["platform_admin","support","finance","operations","security"]);
async function administrator(){const user=await getCurrentUser();if(!user)return null;try{const result=await authorizeOperator(user,"flags.manage",{reason:"Manage operator access",targetType:"operator_assignment"});return result.role==="platform_admin"?user:null;}catch(error){if(error instanceof OperatorAuthorizationError)return null;throw error;}}
async function ready(){await operatorAdministration();return getDatabase();}

export async function GET(){const admin=await administrator();if(!admin)return NextResponse.json({error:"无权访问"},{status:403});const db=await ready();const assignments=db.prepare(`SELECT a.id,a.account_id accountId,u.name,u.email,a.role,a.organization_scopes organizationScopes,a.project_scopes projectScopes,a.granted_at grantedAt FROM operations_operator_assignments a JOIN users u ON u.id=a.account_id WHERE a.active=1 AND a.revoked_at IS NULL ORDER BY a.granted_at DESC`).all().results;const users=db.prepare(`SELECT id,name,email,role FROM users WHERE status='active' ORDER BY lower(name),lower(email) LIMIT 300`).all().results;return NextResponse.json({assignments,users},{headers:{"cache-control":"private, no-store"}});}

export async function POST(request:Request){const admin=await administrator();if(!admin)return NextResponse.json({error:"无权访问"},{status:403});const body=await request.json().catch(()=>null) as {accountId?:string;role?:OperatorRole}|null;if(!body?.accountId||!body.role||!roles.has(body.role))return NextResponse.json({error:"请选择有效用户和后台角色"},{status:400});const db=await ready(),target=db.prepare("SELECT id FROM users WHERE id=? AND status='active'").bind(body.accountId).first();if(!target)return NextResponse.json({error:"用户不存在或已停用"},{status:404});const now=Math.floor(Date.now()/1000),id=crypto.randomUUID();db.transaction(()=>{db.prepare("UPDATE operations_operator_assignments SET active=0,revoked_at=? WHERE account_id=? AND active=1 AND revoked_at IS NULL").bind(now,body.accountId).run();db.prepare("INSERT INTO operations_operator_assignments(id,account_id,role,organization_scopes,project_scopes,active,granted_by_account_id,granted_at,revoked_at) VALUES(?,?,?,?,?,1,?,?,NULL)").bind(id,body.accountId,body.role,JSON.stringify("*"),JSON.stringify("*"),admin.id,now).run();});await writeAudit("admin_operator_assignment",admin.id,request,JSON.stringify({assignmentId:id,accountId:body.accountId,role:body.role}));return NextResponse.json({ok:true,id},{status:201});}

export async function DELETE(request:Request){const admin=await administrator();if(!admin)return NextResponse.json({error:"无权访问"},{status:403});const body=await request.json().catch(()=>null) as {id?:string}|null;if(!body?.id)return NextResponse.json({error:"缺少授权 ID"},{status:400});const db=await ready(),assignment=db.prepare("SELECT account_id accountId FROM operations_operator_assignments WHERE id=? AND active=1 AND revoked_at IS NULL").bind(body.id).first<{accountId:string}>();if(!assignment)return NextResponse.json({error:"授权不存在"},{status:404});if(assignment.accountId===admin.id&&admin.role!=="admin")return NextResponse.json({error:"不能撤销当前会话唯一的平台授权"},{status:400});const now=Math.floor(Date.now()/1000);db.prepare("UPDATE operations_operator_assignments SET active=0,revoked_at=? WHERE id=?").bind(now,body.id).run();await writeAudit("admin_operator_revocation",admin.id,request,JSON.stringify({assignmentId:body.id,accountId:assignment.accountId}));return NextResponse.json({ok:true});}
